export const ESTRUTURA_CATEGORIAS = [
  { id: "cat_0", nome: "Vida Pessoal", icone: "👤", subcategorias: [{ id: "sub_0_0", nome: "Rotinas Diárias" }, { id: "sub_0_1", nome: "Hábitos e Manias" }] },
  { id: "cat_1", nome: "Comida & Bebida", icone: "🍔", subcategorias: [{ id: "sub_1_0", nome: "Restaurantes e Fast Food" }, { id: "sub_1_1", nome: "Gostos Peculiares" }] },
  { id: "cat_2", nome: "Relacionamentos", icone: "❤️", subcategorias: [{ id: "sub_2_0", nome: "Amizades e Grupos" }, { id: "sub_2_1", nome: "Vida Amorosa e Dates" }] },
  { id: "cat_3", nome: "Cultura & Lazer", icone: "🍿", subcategorias: [{ id: "sub_3_0", nome: "Filmes e Séries" }, { id: "sub_3_1", nome: "Hobbies e Tempos Livres" }] },
  { id: "cat_4", nome: "Viagens & Férias", icone: "✈️", subcategorias: [{ id: "sub_4_0", nome: "Destinos de Sonho" }, { id: "sub_4_1", nome: "Peripécias de Viagem" }] },
  { id: "cat_5", nome: "Trabalho & Carreira", icone: "💼", subcategorias: [{ id: "sub_5_0", nome: "Vida no Escritório" }, { id: "sub_5_1", nome: "Ambições Profissionais" }] },
  { id: "cat_6", nome: "Passado & Infância", icone: "🧸", subcategorias: [{ id: "sub_6_0", nome: "Memórias de Escola" }, { id: "sub_6_1", nome: "Traquinices de Criança" }] },
  { id: "cat_7", nome: "Personalidade", icone: "🧠", subcategorias: [{ id: "sub_7_0", nome: "Defeitos e Qualidades" }, { id: "sub_7_1", nome: "Medos e Fobias" }] },
  { id: "cat_8", nome: "Desporto & Fitness", icone: "⚽", subcategorias: [{ id: "sub_8_0", nome: "Idas ao Ginásio" }, { id: "sub_8_1", nome: "Futebol e Competição" }] },
  { id: "cat_9", nome: "Tecnologia", icone: "📱", subcategorias: [{ id: "sub_9_0", nome: "Vício em Redes Sociais" }, { id: "sub_9_1", nome: "Gadgets e Ecrãs" }] },
  { id: "cat_10", nome: "Dinheiro & Compras", icone: "💸", subcategorias: [{ id: "sub_10_0", nome: "Hábitos de Consumo" }, { id: "sub_10_1", nome: "Gestão de Poupanças" }] },
  { id: "cat_11", nome: "Casa & Decoração", icone: "🏠", subcategorias: [{ id: "sub_11_0", nome: "Limpeza e Arrumação" }, { id: "sub_11_1", nome: "Dias de Preguiça" }] },
  { id: "cat_12", nome: "Festa & Noite", icone: "🪩", subcategorias: [{ id: "sub_12_0", nome: "Saídas à Noite" }, { id: "sub_12_1", nome: "Ressacas e Arrependimentos" }] },
  { id: "cat_13", nome: "Animais de Estimação", icone: "🐶", subcategorias: [{ id: "sub_13_0", nome: "Cães vs Gatos" }, { id: "sub_13_1", nome: "Aventuras com Bichos" }] },
  { id: "cat_14", nome: "Dilemas & Cenários", icone: "🤔", subcategorias: [{ id: "sub_14_0", nome: "Escolhas Difíceis" }, { id: "sub_14_1", nome: "Cenários Improváveis" }] },
  { id: "cat_15", nome: "Moda & Estilo", icone: "👗", subcategorias: [{ id: "sub_15_0", nome: "Gostos de Roupa" }, { id: "sub_15_1", nome: "Compras Impulsivas" }] },
  { id: "cat_16", nome: "Carros & Condução", icone: "🚗", subcategorias: [{ id: "sub_16_0", nome: "Stress no Trânsito" }, { id: "sub_16_1", nome: "Roadtrips e Viagens" }] },
  { id: "cat_17", nome: "Saúde & Bem-Estar", icone: "🧘", subcategorias: [{ id: "sub_17_0", nome: "Hábitos de Sono" }, { id: "sub_17_1", nome: "Dietas e Alimentação" }] },
  { id: "cat_18", nome: "Natureza & Ar Livre", icone: "🌲", subcategorias: [{ id: "sub_18_0", nome: "Praia ou Campo" }, { id: "sub_18_1", nome: "Atividades Radicais" }] },
  { id: "cat_19", nome: "Artes & Criatividade", icone: "🎨", subcategorias: [{ id: "sub_19_0", nome: "Dotes Artísticos" }, { id: "sub_19_1", nome: "Projetos DIY" }] },
  { id: "cat_20", nome: "Superstições & Crenças", icone: "🔮", subcategorias: [{ id: "sub_20_0", nome: "Astrologia e Signos" }, { id: "sub_20_1", nome: "Sorte e Azar" }] },
  { id: "cat_21", nome: "Cozinha & Culinária", icone: "🍳", subcategorias: [{ id: "sub_21_0", nome: "Desastres na Cozinha" }, { id: "sub_21_1", nome: "Pratos de Assinatura" }] },
  { id: "cat_22", nome: "Jogos & Videojogos", icone: "🎮", subcategorias: [{ id: "sub_22_0", nome: "Vício nas Consolas" }, { id: "sub_22_1", nome: "Jogos de Tabuleiro" }] },
  { id: "cat_23", nome: "Livros & Leitura", icone: "📚", subcategorias: [{ id: "sub_23_0", nome: "Hábitos de Leitura" }, { id: "sub_23_1", nome: "Livros Favoritos" }] },
  { id: "cat_24", nome: "Beleza & Cuidados", icone: "💅", subcategorias: [{ id: "sub_24_0", nome: "Rotinas de Skincare" }, { id: "sub_24_1", nome: "Cabelo e Maquilhagem" }] },
  { id: "cat_25", nome: "Música & Concertos", icone: "🎸", subcategorias: [{ id: "sub_25_0", nome: "Gostos Musicais" }, { id: "sub_25_1", nome: "Loucuras em Festivais" }] },
  { id: "cat_26", nome: "Desastres & Gafes", icone: "🤦", subcategorias: [{ id: "sub_26_0", nome: "Momentos Embaraçosos" }, { id: "sub_26_1", nome: "Erros a Falar" }] },
  { id: "cat_27", nome: "Sonhos & Futuro", icone: "✨", subcategorias: [{ id: "sub_27_0", nome: "Objetivos de Vida" }, { id: "sub_27_1", nome: "Sonhos por Realizar" }] },
  { id: "cat_28", nome: "Televisão & Reality Shows", icone: "📺", subcategorias: [{ id: "sub_28_0", nome: "Vício em Reality Shows" }, { id: "sub_28_1", nome: "Novelas Antigas" }] },
  { id: "cat_29", nome: "Estudos & Escola", icone: "🎒", subcategorias: [{ id: "sub_29_0", nome: "Cábulas e Truques" }, { id: "sub_29_1", nome: "Testes e Exames" }] },
  { id: "cat_30", nome: "Humor & Comédia", icone: "😂", subcategorias: [{ id: "sub_30_0", nome: "Consumo de Memes" }, { id: "sub_30_1", nome: "Ataques de Riso" }] }
];