import { PerguntaTop3 } from "@/types/catalogo";

export const top3_carros_conducao: Record<string, PerguntaTop3[]> = {
  "sub_16_0": [ // Hábitos ao Volante
    { id: "t3_cc_h_01", texto: "As 3 coisas que mais me irritam profundamente nos outros condutores na estrada", opcoes: ["Não fazerem os piscas nas rotundas", "Andarem colados à traseira do meu carro", "Irem devagar na faixa da esquerda"] },
    { id: "t3_cc_h_02", texto: "Os 3 barulhos suspeitos no carro que eu finjo ativamente não estar a ouvir", opcoes: ["As pastilhas dos travões a chiar", "Um chocalhar a passar em buracos", "O motor a fazer um som agudo"] },
    { id: "t3_cc_h_03", texto: "As 3 músicas de karaoke absolutas que ponho a dar aos berros em viagens longas", opcoes: ["'Bohemian Rhapsody' dos Queen", "'A Minha Casinha' do Quim Barreiros", "Qualquer uma dos Xutos & Pontapés"] },
    { id: "t3_cc_h_04", texto: "Os 3 hábitos mais perigosos ou errados que ganhei ao volante com o tempo", opcoes: ["Segurar no volante só com uma mão em baixo", "Ver notificações no telemóvel no semáforo", "Passar em amarelos-quase-vermelhos"] },
    { id: "t3_cc_h_05", texto: "As 3 coisas indispensáveis que andam sempre perdidas no porta-luvas do meu carro", opcoes: ["Os óculos de sol riscados", "Toalhitas ou lenços secos velhos", "Canetas que já não escrevem"] },
    { id: "t3_cc_h_06", texto: "Os 3 insultos ou nomes feios que grito mais vezes dentro do carro com os vidros fechados", opcoes: ["'Passa-me por cima, anormal!'", "'Vai tirar a carta a um pacote de cereais'", "'Piscas é opção na tua terra?'"] },
    { id: "t3_cc_h_07", texto: "As 3 desculpas monumentais que arranjo para não lavar o carro durante meses", opcoes: ["'Para a semana vai chover de certeza'", "'O pó protege a pintura'", "'Não tenho moedas para a máquina'"] },
    { id: "t3_cc_h_08", texto: "As 3 atitudes nos passageiros que dou boleia que me fazem arrepender logo a seguir", opcoes: ["Bater com a porta com muita força", "Mexerem no ar condicionado sem perguntar", "Darem indicações do GPS quando eu sei o caminho"] },
    { id: "t3_cc_h_09", texto: "Os 3 momentos de maior pânico cego enquanto conduzo no dia a dia", opcoes: ["Quando acende a luz amarela do motor", "Ver a polícia a mandar parar à frente", "Fugir de um carro em sentido contrário"] },
    { id: "t3_cc_h_10", texto: "As 3 'manobras de Mestre' que sei fazer muito bem a conduzir (ou acho que sei)", opcoes: ["Estacionar à paralela à primeira e sem olhar", "Ponto de embraiagem perfeito nas subidas", "Entrar na autoestrada a prego a fundo"] },
    { id: "t3_cc_h_11", texto: "As 3 coisas parvas e irracionais que faço quando me perco do caminho com o GPS ligado", opcoes: ["Baixo o volume do rádio para 'ver' melhor", "Grito com a voz da senhora do Google Maps", "Desligo o GPS e tento ir por instinto e pioro"] },
    { id: "t3_cc_h_12", texto: "As 3 conversas chatas que tenho de gramar sempre na oficina do mecânico", opcoes: ["'Isto de certeza que já estava assim'", "'Vai ter de levar uma peça nova da Alemanha'", "'Vai ficar um pouco mais caro do que pensámos'"] },
    { id: "t3_cc_h_13", texto: "As 3 manias muito portuguesas que vejo na autoestrada e me deixam doente", opcoes: ["Malta na faixa do meio a 80 km/h sem ninguém à direita", "Carros gigantes da empresa a fazerem luzes atrás", "Pessoas a atirarem beatas pela janela fora"] },
    { id: "t3_cc_h_14", texto: "Os 3 acessórios foleiros ou azeiteiros de carro que nunca colocaria no meu", opcoes: ["Dados de peluche pendurados no espelho", "Autocolantes da família de pauzinhos no vidro", "Luzes néon azuis por baixo dos pedais"] },
    { id: "t3_cc_h_15", texto: "As 3 coisas em que confio demasiado no meu carro moderno e devia desconfiar", opcoes: ["Os sensores apitarem no estacionamento", "O travão de mão elétrico", "O sistema de mudança de faixa automática"] },
    { id: "t3_cc_h_16", texto: "As 3 razões pelas quais sinto que o meu carro se transformou num caixote do lixo rolante", opcoes: ["Garrafas de água vazias no banco de trás", "Talões de parquímetro espalhados nas portas", "Areia da praia desde o verão de 2021"] },
    { id: "t3_cc_h_17", texto: "Os 3 petiscos ou snacks que abro sempre a conduzir em viagens para o Algarve/Norte", opcoes: ["Um pacote de batatas fritas (e espalho tudo)", "Gomas ou rebuçados ácidos", "Sandes moles feitas em casa de alumínio"] },
    { id: "t3_cc_h_18", texto: "As 3 reações exageradas quando vou atestar o carro de combustível hoje em dia", opcoes: ["Deitar uma lágrima a olhar para o preço", "Encher até ao limite e abanar o carro", "Meter sempre 20€ para não pensar no problema"] },
    { id: "t3_cc_h_19", texto: "Os 3 perigos absolutos de circular por ruas ou ruelas em aldeias e vilas antigas", opcoes: ["Encontrar um trator de frente numa rua apertada", "As pedras da calçada todas soltas", "Bater com o espelho retrovisor nas paredes"] },
    { id: "t3_cc_h_20", texto: "As 3 frases de pânico que atiro para quem está ao meu lado quando falho a saída", opcoes: ["'Não vi a placa!'", "'O GPS disse tarde demais!'", "'Pronto, agora só damos a volta daqui a 30 quilómetros'"] }
  ],
  "sub_16_1": [ // Peripécias na Estrada
    { id: "t3_cc_p_01", texto: "Os 3 maiores sustos ou acidentes em que estive quase envolvido(a) na estrada", opcoes: ["Aquaplanagem na autoestrada à chuva", "Um cão atirar-se do nada para a frente do carro", "Alguém adormecer e passar para a minha faixa"] },
    { id: "t3_cc_p_02", texto: "As 3 desculpas clássicas que dou ou daria à polícia numa Operação STOP", opcoes: ["'Não sabia que não podia virar aqui, senhor guarda'", "'Esqueci-me mesmo da carteira em casa'", "'Bebi só um copinho de vinho ao jantar'"] },
    { id: "t3_cc_p_03", texto: "As 3 vezes em que passei as maiores vergonhas e calores a tentar estacionar", opcoes: ["Tentar estacionar à paralela 5 vezes com carros a apitar atrás", "Raspar com a jante no passeio enorme", "Ficar encravado e não conseguir sair do lugar"] },
    { id: "t3_cc_p_04", texto: "Os 3 piores azares mecânicos que me deixaram apeado no meio da rua", opcoes: ["Furar o pneu a caminho do trabalho", "A bateria morrer no parque de estacionamento escuro", "O motor sobreaquecer a deitar fumo a subir a serra"] },
    { id: "t3_cc_p_05", texto: "As 3 multas mais idiotas ou parvas que apanhei na vida e pelas quais jurei vingança", opcoes: ["Passar 5 minutos do talão no parquímetro EMEL", "Multa de velocidade por ir a 55 km/h", "Pisar um traço contínuo que já estava apagado"] },
    { id: "t3_cc_p_06", texto: "As 3 mentiras piedosas que contei aos meus pais quando lhes bati ou risquei o carro", opcoes: ["'Já estava assim quando cheguei ao carro'", "'Um gajo no parque raspou e fugiu'", "'Foi um carrinho do supermercado desgovernado'"] },
    { id: "t3_cc_p_07", texto: "Os 3 locais de terror onde passei mais tempo num engarrafamento completamente parado", opcoes: ["Ponte 25 de Abril às 18h", "Ponte da Arrábida (VCI) à chuva", "Na IC19 depois de um acidente"] },
    { id: "t3_cc_p_08", texto: "As 3 conversas mais épicas ou surreais que já ouvi de um motorista de TVDE ou Táxi", opcoes: ["Teorias da conspiração sobre políticos reptilianos", "As histórias dos engates que eles fazem de madrugada", "Dicas infalíveis de investimento em bolsa furadas"] },
    { id: "t3_cc_p_09", texto: "As 3 reações idiotas que tive ao cruzar-me com outro condutor agressivo e violento", opcoes: ["Trancar as portas todas rapidamente", "Fingir que estava a cantar e ignorar os gestos", "Gesticular de volta e depois fugir a prego a fundo"] },
    { id: "t3_cc_p_10", texto: "As 3 coisas que falharam e me fizeram chumbar (ou quase) no exame de condução", opcoes: ["Fazer a rotunda por fora a abrir", "Deixar o carro ir abaixo 3 vezes num STOP", "Não parar na passadeira para um peão"] },
    { id: "t3_cc_p_11", texto: "Os 3 rituais doentios de quem viaja no banco do pendura com muito medo de acidentes", opcoes: ["Travar no chão imaginário com os pés", "Agarrar a pega de cima com os nós dos dedos brancos", "Gritar 'CUIDADO!' a cada 5 minutos"] },
    { id: "t3_cc_p_12", texto: "As 3 situações onde pedi socorro divino por não conseguir encontrar o carro no parque", opcoes: ["No parque do IKEA e das grandes superfícies", "Nas ruas de um bairro parecido onde jantei", "No parque do aeroporto (onde paguei balúrdios)"] },
    { id: "t3_cc_p_13", texto: "As 3 desgraças épicas que envolviam tentar comer dentro do carro em andamento", opcoes: ["O Ketchup do hambúrguer cair na camisa nova", "O café quente entornar pelo porta-copos", "As batatas caírem por debaixo do banco para sempre"] },
    { id: "t3_cc_p_14", texto: "Os 3 momentos em que me esqueci de regras de trânsito básicas só por distração", opcoes: ["Passar num vermelho por achar que era verde", "Entrar em contramão numa rua de sentido único", "Esquecer de acender as luzes à noite na cidade"] },
    { id: "t3_cc_p_15", texto: "As 3 piores armadilhas para raspar a frente ou o fundo do carro (o tal barulho CRASH)", opcoes: ["Lombas invisíveis gigantescentes nas aldeias", "Descidas de garagem a pique", "Passeios altos escondidos nos shoppings"] },
    { id: "t3_cc_p_16", texto: "As 3 coisas em que fui apanhado a fazer na fila do trânsito por carros ao lado", opcoes: ["A tirar ranho do nariz relaxadamente", "A cantar e gesticular aos berros", "A chorar Baba e Ranho por uma desilusão amorosa"] },
    { id: "t3_cc_p_17", texto: "As 3 avarias manhosas dos carros velhos (charutos) que eu já conduzi na juventude", opcoes: ["O vidro não abrir ou cair para baixo sozinho", "Bater no rádio para ele apanhar a estação", "Cheiro constante a gasolina na cabine"] },
    { id: "t3_cc_p_18", texto: "As 3 manobras mais perigosas de chico-esperto que eu faço para fugir do trânsito", opcoes: ["Sair na saída errada e voltar a entrar depois", "Ir pela berma se ninguém estiver a ver (eu não faço, mas...) ", "Atalhar por bombas de gasolina"] },
    { id: "t3_cc_p_19", texto: "Os 3 maiores perigos naturais em estradas rurais e sinuosas à noite", opcoes: ["Javalis ou raposas no meio do escuro", "Falta de faixas brancas e sinalização", "Nevoeiro serrado que nem se vê o capot"] },
    { id: "t3_cc_p_20", texto: "As 3 vezes em que fui atrás do GPS para sítios manhosos e achei que ia morrer", opcoes: ["Meteu-me num caminho de terra batida suspeito", "Mandou-me por uma escadaria de trator", "Mandou-me virar à direita... para o mar"] }
  ]
};
