import { PerguntaTop3 } from "@/types/catalogo";

export const top3_casa_decoracao: Record<string, PerguntaTop3[]> = {
  "sub_11_0": [ // Tarefas Domésticas
    { id: "t3_cd_t_01", texto: "As 3 tarefas domésticas que atiro para o fundo da lista e evito fazer até ao último minuto", opcoes: ["Passar a ferro", "Lavar os vidros das janelas", "Limpar o pó às prateleiras altas"] },
    { id: "t3_cd_t_02", texto: "Os 3 eletrodomésticos que eu declaro como os verdadeiros salva-vidas lá de casa", opcoes: ["Aspirador robô", "Máquina de lavar loiça", "Micro-ondas"] },
    { id: "t3_cd_t_03", texto: "As 3 regras de limpeza sagradas que não suporto que quebrem na minha casa", opcoes: ["Andar com os sapatos da rua lá dentro", "Deixar loiça suja a acumular no lava-loiça", "Comer no sofá e deixar migalhas"] },
    { id: "t3_cd_t_04", texto: "As 3 piores desculpas de preguiça que invento para adiar a limpeza semanal de sábado", opcoes: ["'Vou só ver este episódio e depois limpo'", "'Nem está assim tão sujo, passo a vassoura rápida'", "'Amanhã de manhã tenho mais energia'"] },
    { id: "t3_cd_t_05", texto: "Os 3 produtos de limpeza química que fazem a casa cheirar a 'lavado' num instante", opcoes: ["Sonasol verde", "Cif com lixívia", "Esfregona mágica com cheiro a lavanda"] },
    { id: "t3_cd_t_06", texto: "As 3 tarefas da cozinha em que empurro as culpas para os outros fazerem", opcoes: ["Lavar tachos grandes com comida agarrada", "Limpar a gordura do fogão e forno", "Deitar o lixo orgânico fedorento lá fora"] },
    { id: "t3_cd_t_07", texto: "As 3 zonas de casa onde a desarrumação surge como por magia num único dia", opcoes: ["A cadeira do quarto (cheia de roupa)", "A bancada da entrada/hall (cheia de chaves e correio)", "O chão da casa de banho"] },
    { id: "t3_cd_t_08", texto: "As 3 coisas que me dão arrepios de nojo quando limpo a casa de banho", opcoes: ["Limpar o cabelo que fica no ralo do chuveiro", "Lavar o fundo da sanita", "Tirar as manchas de pasta de dentes do espelho"] },
    { id: "t3_cd_t_09", texto: "Os 3 grandes debates (guerras) sobre como fazer as coisas bem feitas em casa", opcoes: ["Pendurar o rolo higiénico para fora ou para dentro", "Meter a loiça na máquina sem passar água antes", "Estender roupa pelos lados ou pelo meio"] },
    { id: "t3_cd_t_10", texto: "As 3 coisas estúpidas em que perco muito tempo a dobrar e a guardar", opcoes: ["Lençóis com elástico que ficam sempre tortos", "Meias que ficam sem par", "T-shirts pelo método Marie Kondo"] },
    { id: "t3_cd_t_11", texto: "Os 3 barulhos ou enguiços domésticos que teimam em não se resolver sozinhos", opcoes: ["A torneira a pingar de noite", "A porta do quarto a ranger", "A máquina da roupa a saltar no chão ao centrifugar"] },
    { id: "t3_cd_t_12", texto: "As 3 técnicas de 'limpeza visual' que uso quando as visitas tocam à campainha de surpresa", opcoes: ["Atirar a roupa e tralha para dentro de um armário", "Fechar as portas dos quartos à chave", "Passar um pano rápido na mesa com as mãos"] },
    { id: "t3_cd_t_13", texto: "As 3 piores alturas e tarefas de manutenção sazonais na casa", opcoes: ["Descongelar e limpar o congelador por dentro", "Mudar os cortinados ou lavá-los", "Aspirar por baixo do sofá pesado"] },
    { id: "t3_cd_t_14", texto: "As 3 ferramentas ou produtos essenciais do 'kit de sobrevivência tuga' de arranjos", opcoes: ["Um rolo de fita cola prateada forte", "Um spray de WD-40", "Uma chave de fendas super velha"] },
    { id: "t3_cd_t_15", texto: "Os 3 cantinhos manhosos do chão onde juro que o meu aspirador não chega", opcoes: ["Por trás e de lado do frigorífico", "Nos rodapés do corredor", "Debaixo das cómodas de arrumação"] },
    { id: "t3_cd_t_16", texto: "As 3 recompensas emocionais de ter o quarto bem arrumado e de limpo no domingo", opcoes: ["Dormir com lençóis lavados a cheirar a amaciador", "A sensação mental de dever cumprido", "Poder andar descalço sem pisar lixo"] },
    { id: "t3_cd_t_17", texto: "As 3 peças da loiça ou talheres que lavo sempre mal porque odeio fazê-lo", opcoes: ["Colheres cheias de papa grossa seca", "Raladores de queijo cheios de pontas", "Tupperwares de plástico cheios de molho de tomate"] },
    { id: "t3_cd_t_18", texto: "As 3 desculpas parvas para não reciclar os lixos domésticos devidamente", opcoes: ["'Não tenho ecoponto perto de casa'", "'O meu caixote é muito pequeno para separar'", "'É sujo lavar as latas de atum'"] },
    { id: "t3_cd_t_19", texto: "Os 3 hábitos doentios de arejamento da casa que herdei dos meus pais", opcoes: ["Abrir todas as janelas às 8h da manhã no inverno", "Meter a roupa de cama a apanhar sol de castigo", "Espalhar purificador de ar a cada 10 minutos"] },
    { id: "t3_cd_t_20", texto: "As 3 coisas que costumo pedir ajuda à mãe ou ao pai quando a tarefa me ultrapassa", opcoes: ["Como tirar nódoas de vinho de camisas brancas", "Arranjar estores que encravaram no topo", "Cozer as bainhas que se descoseram"] }
  ],
  "sub_11_1": [ // Estilo e Conforto
    { id: "t3_cd_e_01", texto: "Os 3 estilos de decoração de interiores que eu usaria numa casa sem limite de orçamento", opcoes: ["Minimalista com madeiras e muito branco", "Industrial com metais negros e tijolo", "Boho Chic com muitas plantas e macramé"] },
    { id: "t3_cd_e_02", texto: "As 3 lojas de decoração ou móveis onde eu perco facilmente a cabeça e os trocos", opcoes: ["IKEA", "Zara Home", "Espaço Casa ou Gato Preto"] },
    { id: "t3_cd_e_03", texto: "As 3 divisões da casa às quais dou prioridade máxima na decoração e conforto", opcoes: ["A minha cama / o meu quarto", "A sala de estar / zona da TV", "A casa de banho"] },
    { id: "t3_cd_e_04", texto: "As 3 peças de decoração pirosas de que eu gosto imenso secretamente", opcoes: ["Letreiros de madeira com frases (ex: 'Love')", "Almofadas felpudas com pêlo sintético", "Luzes LED neon pelo teto inteiro"] },
    { id: "t3_cd_e_05", texto: "Os 3 requisitos absolutamente vitais para considerar que um sofá é espetacular", opcoes: ["Ter aquela chaise longue grande para esticar as pernas", "O tecido ser super macio", "Cabermos 3 pessoas sem estarmos colados"] },
    { id: "t3_cd_e_06", texto: "As 3 cores, ou tons de cor, com as quais pintaria as paredes do meu quarto de sonho", opcoes: ["Tons de terra ou bege claros", "Verde seco ou esmeralda", "Azul escuro e elegante"] },
    { id: "t3_cd_e_07", texto: "Os 3 objetos de adulto que comprei e que me fizeram sentir super orgulhoso da casa", opcoes: ["Uma planta verdadeira que ainda não morreu", "Uma mesa de centro em vidro e metal", "Um faqueiro dourado a combinar"] },
    { id: "t3_cd_e_08", texto: "As 3 peças ou móveis antigos e feios que me recuso a deitar fora por sentimentalismo", opcoes: ["Aquela cómoda de mogno grossa da avó", "Um sofá roto que é mega confortável", "Os tapetes orientais antigos da sala"] },
    { id: "t3_cd_e_09", texto: "As 3 caraterísticas ideais que eu teria de exigir de um vizinho no meu prédio", opcoes: ["Não fazer obras aos domingos de manhã", "Receber as minhas encomendas do correio na boa", "Gostar de silêncio após as 22h"] },
    { id: "t3_cd_e_10", texto: "As 3 fragrâncias ou velas aromáticas que adorava ter a perfumar a minha sala agora", opcoes: ["Cheiro a baunilha e caramelo", "Cheiro a canela e especiarias (vibes de outono)", "Cheiro a mar e brisa do oceano"] },
    { id: "t3_cd_e_11", texto: "As 3 razões pelas quais sinto que os meus quadros nas paredes nunca ficam direitos", opcoes: ["Fazer furos a olho sem medir a parede toda", "Usar fita-cola de dupla face barata", "Os móveis estarem todos tortos debaixo"] },
    { id: "t3_cd_e_12", texto: "As 3 plantas decorativas (reais ou falsas) clássicas que toda a gente compra e eu também", opcoes: ["As Costelas-de-Adão (Monstera) gigantes", "Os Catos pequeninos em cima da mesa", "Eucaliptos secos no quarto de banho"] },
    { id: "t3_cd_e_13", texto: "As 3 peças essenciais no meu canto de leitura ou canto do café no inverno", opcoes: ["Um cadeirão de orelhas super fofo", "Um tapete gigante onde o pé afunda", "Um candeeiro de pé com luz amarela quente"] },
    { id: "t3_cd_e_14", texto: "Os 3 erros clássicos e parvos que já cometi quando fui comprar móveis numa loja física", opcoes: ["Não tirar as medidas às portas da casa", "Trazer coisas e não saber montar", "Acreditar na foto do catálogo sem ver ao vivo"] },
    { id: "t3_cd_e_15", texto: "As 3 funções ou pequenos luxos de que eu não abdicava num roupeiro walk-in (closet)", opcoes: ["Gavetas só para óculos e joias/acessórios", "Muito espelho em todas as portas", "Uma prateleira iluminada a LED para os sapatos"] },
    { id: "t3_cd_e_16", texto: "As 3 decorações de Natal sem as quais a minha casa não tem a magia típica de dezembro", opcoes: ["A árvore grande a piscar em dois tons", "Mantas vermelhas e verdes nos sofás", "Bolas de neve em todo o lado"] },
    { id: "t3_cd_e_17", texto: "Os 3 materiais, revestimentos e texturas mais agradáveis de usar no chão da casa inteira", opcoes: ["Chão de madeira ou soalho flutuante", "Tapetes de fibras naturais espessas", "Mosaico super liso e fosco de casa de banho"] },
    { id: "t3_cd_e_18", texto: "As 3 piores ideias de decoração que existiam na casa dos meus pais nos anos 90", opcoes: ["Sofás de napa que colavam nas pernas", "Papel de parede com texturas ou padrão berrante", "Carpetes que iam de ponta a ponta na casa toda"] },
    { id: "t3_cd_e_19", texto: "Os 3 pequenos toques e truques decorativos que fazem um quarto parecer um hotel caro", opcoes: ["Almofadas empilhadas por tamanhos na cama", "Iluminação oculta muito baixa atrás da cabeceira", "Cortinas enormes a arrastar pelo chão"] },
    { id: "t3_cd_e_20", texto: "As 3 sensações perfeitas que me dão a certeza de que a minha casa é 'o meu porto seguro'", opcoes: ["Largar as chaves e descalçar-me assim que entro", "Ouvir a máquina do café e não ouvir carros", "Aconchegar-me de manta e apagar a luz principal"] }
  ]
};
