import { PerguntaTop3 } from "@/types/catalogo";

export const top3_desastres_gafes: Record<string, PerguntaTop3[]> = {
  "sub_26_0": [ // Em Público
    { id: "t3_dg_p_01", texto: "Os 3 desastres que me dão vontade de cavar um buraco e esconder-me lá dentro", opcoes: ["Tropeçar num passeio invisível e fingir que estou a correr", "Acenar de volta para alguém que estava a acenar à pessoa atrás de mim", "Fazer de conta que atendo uma chamada de vergonha"] },
    { id: "t3_dg_p_02", texto: "As 3 gafes épicas de mensagens de telemóvel que enviei para a pessoa errada", opcoes: ["Mandar um 'print' de uma conversa à própria pessoa da conversa", "Enviar uma mensagem amorosa no grupo do trabalho", "Mandar áudios a reclamar de alguém e falhar no chat"] },
    { id: "t3_dg_p_03", texto: "Os 3 piores momentos para me dar um ataque de riso incontrolável", opcoes: ["Numa reunião muito séria do chefe", "Num funeral (riso nervoso)", "Quando alguém me conta um acidente grave que teve"] },
    { id: "t3_dg_p_04", texto: "As 3 formas que utilizo para disfarçar o facto de me ter esquecido do nome da pessoa", opcoes: ["Dizer 'Ei! Olá, tudo bem contigo?' sem usar o nome", "Apresentá-la a um amigo para ela dizer o nome", "Dizer palavras genéricas como 'Amigo' ou 'Chefe'"] },
    { id: "t3_dg_p_05", texto: "As 3 situações onde empurrei as portas de vidro das lojas que diziam claramente 'Puxe'", opcoes: ["Na entrada do centro comercial cheio", "Na farmácia com toda a gente a olhar", "Ficar com a cara esmagada contra o vidro"] },
    { id: "t3_dg_p_06", texto: "As 3 desculpas parvas que dou quando bato com o ombro num móvel em casa dos outros", opcoes: ["'Quem é que meteu aqui esta cadeira?'", "'Estava só a testar a resistência da madeira'", "Fingir que não me doeu, com os olhos rasos d'água"] },
    { id: "t3_dg_p_07", texto: "Os 3 desastres de comunicação em que digo 'Tu também!' quando não devia", opcoes: ["No cinema ('Bom filme' -> 'Tu também')", "Na bilheteira ('Boa viagem' -> 'Para si também')", "Ao empregado do restaurante ('Bom apetite' -> 'Obrigado, para si também')"] },
    { id: "t3_dg_p_08", texto: "As 3 piores coisas de ter a barriga a fazer barulhos e roncos altíssimos", opcoes: ["Na sala de espera silenciosa do médico", "Numa biblioteca ou sala de estudo", "Durante um Date romântico sem barulho de fundo"] },
    { id: "t3_dg_p_09", texto: "Os 3 momentos em que percebi tarde demais que tinha a braguilha (fecho) das calças aberta", opcoes: ["Depois de uma reunião ou apresentação importante", "Ao sair de uma casa de banho pública num shopping", "Quando um estranho na rua fez gestos a avisar"] },
    { id: "t3_dg_p_10", texto: "As 3 gafes alimentares super embaraçosas que me acontecem em almoços de negócios", opcoes: ["Ficar com um bocado de espinafres nos dentes", "Sujar a camisa branca com molho vermelho do nada", "Deixar cair a garfada de massa na toalha da mesa"] },
    { id: "t3_dg_p_11", texto: "As 3 coisas bizarras que saem da minha boca quando não ouço bem a pessoa pela 3ª vez", opcoes: ["Sorrir, acenar com a cabeça e dizer 'Pois é...'", "Mandar uma gargalhada e rezar para que tenha sido uma piada", "Responder um simples 'Hum-hum' com ar de sábio"] },
    { id: "t3_dg_p_12", texto: "Os 3 piores acidentes de tecnologia no trabalho (falhas no Zoom/Teams)", opcoes: ["Esquecer o microfone ligado a mastigar batatas fritas", "Levantar-me e revelar que estou de cuecas/calções por baixo", "Partilhar o ecrã com conversas privadas no WhatsApp Web"] },
    { id: "t3_dg_p_13", texto: "As 3 reações horríveis que tenho ao cruzar-me com um ex-parceiro ou ex-chefe na rua", opcoes: ["Esconder-me atrás dos pacotes no corredor do supermercado", "Virar a cara rapidamente e fingir fascínio por uma parede", "Meter os olhos no telemóvel e apertar o passo"] },
    { id: "t3_dg_p_14", texto: "As 3 situações onde cedi o lugar nos transportes a quem afinal não precisava", opcoes: ["Oferecer a uma mulher achando que estava grávida e estava só forte", "Oferecer a alguém achando que era idoso e ficou ofendido", "Oferecer e a pessoa responder agressiva 'Eu aguento em pé'"] },
    { id: "t3_dg_p_15", texto: "Os 3 momentos de pânico silencioso no multibanco ou supermercado", opcoes: ["A máquina dizer 'Operação Rejeitada' com saldo na conta", "Deixar as moedas todas caírem ao chão a guardar o troco", "Não ter espaço para enfiar as compras nos sacos a tempo"] },
    { id: "t3_dg_p_16", texto: "As 3 formas que as lojas têm de me fazer cometer micos desnecessários", opcoes: ["Os alarmes apitarem à saída sem eu roubar nada", "Bater contra os manequins de roupa mal colocados", "Trocar um cliente com um empregado da loja"] },
    { id: "t3_dg_p_17", texto: "Os 3 maiores papéis de 'nabo' que fiz a entrar em carros errados", opcoes: ["Abrir a porta a um Uber que afinal era um carro normal", "Tentar abrir a chave num carro da mesma cor e marca no parque", "Ficar colado ao vidro de um carro a ver o dono lá dentro"] },
    { id: "t3_dg_p_18", texto: "As 3 perguntas muito intrometidas e constrangedoras de tias em jantares de Natal", opcoes: ["'E os namoradinhos/namoradas? Nada?'", "'Ainda não acabaste o curso porquê?'", "'Estás mais fortinho, não estás?'"] },
    { id: "t3_dg_p_19", texto: "As 3 palavras que me saem mal trocadas em discursos para mais de 10 pessoas", opcoes: ["Dizer 'Muito obrigado' com voz a falhar", "Engasgar-me nas consoantes ('pro... pro... poplema')", "Chamar a pessoa pelo nome do irmão dela"] },
    { id: "t3_dg_p_20", texto: "As 3 desculpas péssimas para justificar um esquecimento muito grosseiro do aniversário de alguém", opcoes: ["'Eu lembrei-me de manhã e juro que te ia ligar depois!'", "'O meu Facebook não me avisou'", "'Fiquei à espera da festa para te dar os parabéns pessoalmente'"] }
  ],
  "sub_26_1": [ // Acidentes Pessoais
    { id: "t3_dg_a_01", texto: "As 3 desgraças de coordenação motora que me acontecem a caminhar normalmente", opcoes: ["Dar um chuto na quina da cama e ficar a gemer", "Prender a maçaneta da porta no bolso das calças/casaco", "Bater com a testa no armário da cozinha superior"] },
    { id: "t3_dg_a_02", texto: "Os 3 acidentes que me acontecem invariavelmente com líquidos e canecas", opcoes: ["Dar um trago num chá e queimar a língua 3 dias", "Entornar meio copo de vinho porque falo com as mãos", "A última pinguinha de café cair nos sapatos"] },
    { id: "t3_dg_a_03", texto: "As 3 peripécias desastrosas com os fechos-éclair (zippers) da minha roupa", opcoes: ["Prender um bocado da camisola no fecho do casaco e entalar", "O fecho das calças rebentar depois do almoço gordo", "Não conseguir puxar o fecho do vestido nas costas sozinho(a)"] },
    { id: "t3_dg_a_04", texto: "Os 3 momentos de pânico e dor relacionados com pequenos objetos em casa", opcoes: ["Pisar um bloco de Lego descalço(a) no escuro", "Entalar o dedo na gaveta da cómoda", "O frasco de champô cair em cima dos dedos do pé no banho"] },
    { id: "t3_dg_a_05", texto: "As 3 vezes em que fui atraiçoado pelas intempéries (vento/chuva) nas piores alturas", opcoes: ["O vento virar o meu guarda-chuva do avesso e eu lutar com ele", "Passar um carro e atirar água de uma poça contra mim", "O vento levantar a minha saia/vestido à Marilyn Monroe na passadeira"] },
    { id: "t3_dg_a_06", texto: "Os 3 acidentes de percurso a tentar fazer tarefas de cabeleireiro no banho", opcoes: ["Deixar o sabonete escorregar 5 vezes seguidas", "Ouvir a campainha a tocar de champô nos olhos e cego(a)", "Cortar-me na canela a passar a lâmina depressa"] },
    { id: "t3_dg_a_07", texto: "As 3 perdas financeiras parvas devido a quedas acidentais das minhas mãos", opcoes: ["O telemóvel cair da sanita abaixo no pior segundo", "Deixar cair as chaves nos buracos dos elevadores", "Os óculos de sol voarem num barco para o mar"] },
    { id: "t3_dg_a_08", texto: "As 3 feridas ridículas nas quais me arrependo das minhas decisões na hora", opcoes: ["Cortar os lábios num envelope ou papel afiado", "Queimar os dedos a tentar ver se o tacho está quente", "Morder com muita força a minha própria bochecha/língua"] },
    { id: "t3_dg_a_09", texto: "As 3 dores repentinas de envelhecer (falso desporto) que apanho por movimentos básicos", opcoes: ["Ficar com um torcicolo horrível a dormir torto", "Dar um jeito nas costas a apanhar a caneta do chão", "Puxar um músculo a espirrar com demasiada força"] },
    { id: "t3_dg_a_10", texto: "Os 3 acidentes de moda em que percebi tarde demais a desgraça", opcoes: ["Usar calças com um buraco na zona traseira sem saber", "Andar com a etiqueta com o preço pendurada no casaco o dia todo", "Meias rotas com o dedo grande de fora na casa de alguém"] },
    { id: "t3_dg_a_11", texto: "As 3 vezes em que objetos me atacaram em minha casa sem eu estar à espera", opcoes: ["O cabo dos auscultadores prender e arrancar-me o ouvido", "A porta do frigorífico bater-me na cara a abrir rápido", "A vassoura atirar-me com cabo na testa ao ser pisada"] },
    { id: "t3_dg_a_12", texto: "As 3 peripécias desportivas onde a minha condição física causou humilhação", opcoes: ["Correr para o autocarro, tropeçar na calçada e perdê-lo na mesma", "Mandar a bola por cima de um muro impossível de saltar", "Fazer um pontapé de bicicleta falso e cair de rabo"] },
    { id: "t3_dg_a_13", texto: "Os 3 momentos em que parti coisas frágeis num local que não devia", opcoes: ["Partir copos chiques em casamentos na mesa de jantar", "Atirar jarras de vizinhos com os braços", "Deixar cair a loiça fina das lojas de decoração na prateleira"] },
    { id: "t3_dg_a_14", texto: "As 3 vezes em que fui atingido por coisas que vinham de cima sem eu ver", opcoes: ["As pinhas ou bolotas das árvores num piquenique", "Cacaca de pombos ou andorinhas nas praças", "A tampa do porta-bagagens descer e bater na minha cabeça"] },
    { id: "t3_dg_a_15", texto: "Os 3 piores objetos da rotina diária a pregar rasteiras perigosas", opcoes: ["Escorregar em tapetes lavados (corredores lisos)", "Pisar um charco de água à beira da piscina e quase fazer as aberturas", "O fio do carregador do PC enrodilhar nas pernas da cadeira"] },
    { id: "t3_dg_a_16", texto: "As 3 situações onde criei um caos aquático sem intenção", opcoes: ["Esquecer a água do banho aberta até inundar a casa", "Ligar a mangueira do quintal apontada à minha cara", "Mexer num aspersor (rega) e ele ligar em automático"] },
    { id: "t3_dg_a_17", texto: "Os 3 problemas muito estúpidos e embaraçosos com roupa no meio de ventos ou desportos", opcoes: ["A mola do soutien rebentar e não ter substituto na rua", "Os calções de banho caírem na piscina à frente de amigos", "O vento levantar as saias e toda a gente ver o espetáculo"] },
    { id: "t3_dg_a_18", texto: "As 3 vezes em que testei a durabilidade dos meus dentes", opcoes: ["A tentar abrir pacotes de plástico rijos com os dentes", "A morder o garfo de metal por engano em vez da comida", "A tentar desatar o nó apertado das sapatilhas velhas"] },
    { id: "t3_dg_a_19", texto: "As 3 acidentes em festas e aniversários provocados por demasiada euforia", opcoes: ["Pisar o calcanhar da pessoa à frente na passadeira lenta", "Rebentar o balão cedo demais e levar com restos no olho", "Soprar a vela com força e salivar em cima do bolo do amigo"] },
    { id: "t3_dg_a_20", texto: "As 3 vezes em que o meu corpo me traiu no momento da conquista (ou sedução)", opcoes: ["Ter um ataque de soluços imparável durante um jantar a dois", "Arrotar silenciosamente, mas sentir o cheiro das batatas de alho", "Tropeçar no tapete na aproximação final e perder a pose heroica"] }
  ]
};
