import { PerguntaTop3 } from "@/types/catalogo";

export const top3_dilemas_cenarios: Record<string, PerguntaTop3[]> = {
  "sub_14_0": [ // Decisões Difíceis
    { id: "t3_dc_d_01", texto: "Os 3 objetos que eu levaria indubitavelmente para uma ilha deserta", opcoes: ["Um canivete suíço gigante", "Fósforos / pederneira", "Um livro de 1000 páginas"] },
    { id: "t3_dc_d_02", texto: "Os 3 superpoderes que escolheria se pudesse criar o meu próprio super-herói", opcoes: ["Teletransporte (para não apanhar trânsito)", "Invisibilidade", "Ler a mente das pessoas"] },
    { id: "t3_dc_d_03", texto: "As 3 pessoas (amigos ou famosos) que escolhia para lutar ao meu lado num apocalipse zombie", opcoes: ["O The Rock (Dwayne Johnson)", "Um amigo meu que foi ao exército", "O Bear Grylls da sobrevivência"] },
    { id: "t3_dc_d_04", texto: "As 3 coisas que eu salvaria primeiro se a minha casa estivesse a arder (depois da família e pets)", opcoes: ["O telemóvel", "O disco rígido com as fotos todas", "O meu casaco/sapato mais caro"] },
    { id: "t3_dc_d_05", texto: "Os 3 primeiros luxos ridículos que comprava se me saíssem 50 milhões no Euromilhões", opcoes: ["Uma ilha privada só para mim", "Um avião particular ou jato", "Um cozinheiro pessoal 24h por dia"] },
    { id: "t3_dc_d_06", texto: "As 3 partes do meu passado para as quais viajaria no tempo para poder alterar uma decisão", opcoes: ["A escolha do curso na faculdade", "O dia em que perdoei aquele 'ex'", "Um investimento estúpido de dinheiro"] },
    { id: "t3_dc_d_07", texto: "Os 3 piores castigos ou torturas numa prisão moderna de 2024", opcoes: ["Não ter Wi-Fi durante 1 ano", "Comer o mesmo prato ao almoço e jantar", "Estar numa sala com música do Tik Tok em loop"] },
    { id: "t3_dc_d_08", texto: "Os 3 trabalhos mais exaustivos que eu recusaria fazer por 10.000€ ao mês", opcoes: ["Limpador de fossas / esgotos", "Testador de cobras venenosas", "Segurança numa discoteca super violenta"] },
    { id: "t3_dc_d_09", texto: "Os 3 sentidos sem os quais eu teria muita dificuldade em continuar a viver com alegria", opcoes: ["A Visão (ver filmes)", "A Audição (ouvir música)", "O Paladar (comer bem)"] },
    { id: "t3_dc_d_10", texto: "As 3 refeições que eu escolheria comer como 'Última Ceia' antes de morrer", opcoes: ["A comida da minha mãe", "Bife do lombo com muito molho e batatas", "Sushi à discrição sem parar"] },
    { id: "t3_dc_d_11", texto: "As 3 pessoas famosas e falecidas com quem jantava e conversava se a magia existisse", opcoes: ["Albert Einstein", "Michael Jackson", "Princesa Diana"] },
    { id: "t3_dc_d_12", texto: "As 3 opções estúpidas entre as quais hesitaria se me oferecessem um bilhete só de ida", opcoes: ["Marte no primeiro foguetão", "O fundo da Fossa das Marianas", "O topo do Evereste de helicóptero"] },
    { id: "t3_dc_d_13", texto: "As 3 verdades absolutas do Universo que eu perguntaria a um Deus omnisciente", opcoes: ["'Os extraterrestres andam aí escondidos?'", "'Existe vida depois da morte?'", "'Como é que as pirâmides foram feitas?'"] },
    { id: "t3_dc_d_14", texto: "Os 3 membros do meu grupo de amigos que deixaria no barco a naufragar para me salvar", opcoes: ["Aquele amigo que deve dinheiro a toda a gente", "Aquele que ressona como um trator", "O mais azedo e pessimista"] },
    { id: "t3_dc_d_15", texto: "As 3 regras ou leis imutáveis que eu aplicaria na Constituição se fosse Presidente do Mundo", opcoes: ["Trabalhar 4 dias e folgar 3", "Férias ilimitadas pagas", "Proibido andar devagar na faixa da esquerda"] },
    { id: "t3_dc_d_16", texto: "As 3 partes da minha vida em que eu carregaria num botão 'Skip' (Saltar para a frente) se pudesse", opcoes: ["A fase de fazer exames na faculdade", "Recuperar o coração de um desgosto amoroso", "Estar no meio do trânsito na ponte"] },
    { id: "t3_dc_d_17", texto: "Os 3 super-vilões da ficção dos quais eu aceitaria ser o ajudante nº 2", opcoes: ["O Joker (porque o gajo tem piada)", "Darth Vader", "Loki (Marvel)"] },
    { id: "t3_dc_d_18", texto: "Os 3 crimes ou infrações leves que eu cometeria com orgulho se não houvesse polícia 1 dia (A Purga)", opcoes: ["Saquear o El Corte Inglés", "Roubar os carros todos de um stand da Porsche", "Estacionar em frente à minha casa à lei da bala"] },
    { id: "t3_dc_d_19", texto: "As 3 escolhas de vestuário eternas se eu fosse obrigado a usar a mesma roupa para sempre", opcoes: ["Calças de fato de treino cinzentas", "T-shirt preta básica", "Ténis super confortáveis de corrida"] },
    { id: "t3_dc_d_20", texto: "Os 3 pactos loucos que faria com o Diabo para garantir sucesso financeiro na vida", opcoes: ["Vender um bocado do meu fígado", "Perder o dedo mindinho do pé", "Vender a alma das pessoas que não gosto"] }
  ],
  "sub_14_1": [ // Situações Absurdas
    { id: "t3_dc_s_01", texto: "As 3 formas mais caricatas e parvas de morrer que eu acho que me poderiam acontecer", opcoes: ["Tropeçar e cair num buraco aberto na rua", "Engasgar-me a rir com um copo de água", "Cair no banho a tentar cantar alto"] },
    { id: "t3_dc_s_02", texto: "As 3 desculpas monumentais que daria aos polícias se me apanhassem a correr nu na rua", opcoes: ["'Foi um desafio do TikTok, sr. guarda'", "'Assaltaram-me e levaram as cuecas'", "'Achei que era invisível hoje'"] },
    { id: "t3_dc_s_03", texto: "Os 3 crimes mesquinhos pelos quais eu provavelmente acabaria preso algum dia", opcoes: ["Dar uma estalada numa 'Karen' na fila do pão", "Pirataria na internet por ver filmes grátis", "Tirar uma camisola sem pagar do supermercado"] },
    { id: "t3_dc_s_04", texto: "Os 3 locais de primeira escolha para onde fugiria se fosse perseguido pelo FBI", opcoes: ["Para uma cabana na Amazónia", "Para o fundo da Serra da Estrela", "Para uma cave na Rússia"] },
    { id: "t3_dc_s_05", texto: "As 3 regras de trânsito estúpidas que eu criaria se comandasse o código da estrada", opcoes: ["Andar a 50 km/h na esquerda dá perda de carta", "Piscas obrigatórios com choque elétrico no volante", "As rotundas serem todas a direito"] },
    { id: "t3_dc_s_06", texto: "Os 3 factos inaceitáveis sobre a minha higiene se estivesse preso num bunker durante 1 ano", opcoes: ["Andar com a mesma roupa suja de mês a mês", "Não lavar os dentes nunca", "Usar musgo como papel higiénico"] },
    { id: "t3_dc_s_07", texto: "As 3 conspirações alienígenas em que eu acreditaria piamente se visse um disco voador", opcoes: ["Eles governam os políticos e o governo americano", "Os gatos são câmaras disfarçadas deles", "A Terra é plana e nós somos a jaula deles"] },
    { id: "t3_dc_s_08", texto: "As 3 razões pelas quais eu não sobreviveria a Jogos da Fome (Hunger Games)", opcoes: ["Sou bué medricas ao ver sangue", "A minha resistência a correr é zero", "Confio demasiado nas outras pessoas"] },
    { id: "t3_dc_s_09", texto: "As 3 frases absurdas que escolheria colocar no meu próprio testamento", opcoes: ["'Eu escondi 1 milhão de euros debaixo da... *morre*'", "'Espero que o Benfica não me desaponte no céu'", "'Apaguem o histórico do meu computador!'"] },
    { id: "t3_dc_s_10", texto: "Os 3 locais onde recuso terminantemente largar um poio se estiver super apertado(a)", opcoes: ["Casa de banho de posto de combustível suja", "No mato no meio de moitas", "Na casa de banho dos pais do meu namorado/a novo/a"] },
    { id: "t3_dc_s_11", texto: "As 3 mentiras históricas pelas quais fui enganado a vida inteira e sinto-me burro(a)", opcoes: ["'De noite os teus olhos estragam-se a ver TV'", "'Deixa ficar o dente que a fada vem'", "'A cegonha traz os bebés'"] },
    { id: "t3_dc_s_12", texto: "As 3 desculpas parvas que a internet ou os Youtubers dão quando são apanhados a fazer algo ilegal", opcoes: ["'Foi um mal-entendido e está fora de contexto'", "'Estava a sofrer problemas mentais'", "'Cortei relações com essa pessoa'"] },
    { id: "t3_dc_s_13", texto: "As 3 maiores conspirações da humanidade que acho que fazem 10% de sentido", opcoes: ["O Homem não foi à Lua em 1969", "A Área 51 esconde aliens e naves reais", "A Família Real Britânica são lagartos disfarçados"] },
    { id: "t3_dc_s_14", texto: "As 3 ideias milionárias e absurdas que eu levaria ao programa 'Shark Tank'", opcoes: ["Um capacete que lê os pensamentos dos cães", "Ténis com motores a jato", "Uma pastilha elástica que sacia a fome de uma francesinha"] },
    { id: "t3_dc_s_15", texto: "Os 3 piores azares ou feitiços que alguém me poderia rogar num ritual de vodu", opcoes: ["Ter soluços de 5 em 5 minutos para sempre", "Cada vez que minto, dar um estrondo de traque", "Cair sempre que passar por uma pessoa atraente"] },
    { id: "t3_dc_s_16", texto: "As 3 reações exageradas se visse o fantasma da minha trisavó no corredor", opcoes: ["Mijava-me de terror na hora", "Dava um salto mortal de 5 metros para a rua", "Dizia-lhe 'Vai dormir, mulher!' e desmaiava"] },
    { id: "t3_dc_s_17", texto: "Os 3 cenários de novela dramáticos em que acabaria metido(a) sem querer na vida real", opcoes: ["Descobrir que o meu irmão é o meu marido", "Ser sequestrado(a) por um barão rico na fazenda", "Perder a memória num acidente de barco"] },
    { id: "t3_dc_s_18", texto: "As 3 piores formas de descobrir que sou adotado(a)", opcoes: ["Numa discussão de Natal aos berros", "Num programa sensacionalista da tarde na TV", "Ao fazer um teste de DNA de farmácia a brincar"] },
    { id: "t3_dc_s_19", texto: "Os 3 talentos absolutos que aplicaria se fosse agente disfarçado numa máfia de traficantes", opcoes: ["A minha Poker Face (fingir que não sei de nada)", "A minha facilidade em mentir com confiança", "O dom de me misturar na parede como uma planta"] },
    { id: "t3_dc_s_20", texto: "Os 3 disfarces infalíveis que usaria para invadir e roubar um banco central", opcoes: ["Vestir de arrumador das limpezas com o balde e vassoura", "Ir com o fato do Super Mario a fingir ser animação", "Meter um bigode farfalhudo e óculos grossos de sol"] }
  ]
};
