import { PerguntaTop3 } from "@/types/catalogo";

export const top3_estudos_escola: Record<string, PerguntaTop3[]> = {
  "sub_29_0": [ // Aulas e Professores
    { id: "t3_ee_a_01", texto: "As 3 desculpas infalíveis (ou não) que dava aos professores por chegar atrasado", opcoes: ["'O autocarro avariou a meio do caminho'", "'Não ouvi o despertador tocar'", "'Estive a falar com o diretor de turma'"] },
    { id: "t3_ee_a_02", texto: "Os 3 piores lugares para ficar sentado na sala de aula", opcoes: ["Na primeira fila mesmo debaixo do nariz do stor", "Ao lado do lixo / caixote e da porta", "Ao lado daquele colega que não se cala um segundo"] },
    { id: "t3_ee_a_03", texto: "As 3 táticas milagrosas para tentar não adormecer nas aulas teóricas aborrecidas", opcoes: ["Apoiar a cabeça na mão e fingir que estou a pensar", "Pedir para ir à casa de banho só para lavar a cara", "Escrever os apontamentos com muita força"] },
    { id: "t3_ee_a_04", texto: "Os 3 tipos de professores que marcaram o meu percurso escolar", opcoes: ["O 'ditador' que metia a turma a tremer", "O que dava bué notas altas sem ver", "O descontraído que falava da própria vida 45 minutos"] },
    { id: "t3_ee_a_05", texto: "As 3 coisas que fazíamos às escondidas na última fila da sala", opcoes: ["Jogar ao Galo ou Batalha Naval", "Mandar bilhetinhos em papel", "Comer sandes aos bochechos rápidos"] },
    { id: "t3_ee_a_06", texto: "As 3 matérias ou disciplinas que eu achava que nunca iriam servir para nada (e estava certo)", opcoes: ["Bhaskara e Álgebra avançada", "Saber os rios afluentes do Douro de cor", "Aprender a tocar a flauta de bisel"] },
    { id: "t3_ee_a_07", texto: "Os 3 momentos de maior pânico ao ser chamado ao quadro negro/branco", opcoes: ["Não saber absolutamente nada do exercício", "A caneta não escrever e o stor ficar a olhar", "Fazer um barulho agudo de arranhar o quadro"] },
    { id: "t3_ee_a_08", texto: "As 3 artimanhas para fugir das aulas de Educação Física quando havia ginástica/atletismo", opcoes: ["'Esqueci-me do equipamento em casa'", "'Dói-me muito a barriga/perna'", "Falsificar a assinatura dos pais num papel"] },
    { id: "t3_ee_a_09", texto: "As 3 sensações gloriosas que só quem andou na escola nos anos 90/2000 entende", opcoes: ["Ouvir a campainha para o recreio grande", "O professor faltar e irmos para o bar", "O cheiro das folhas dos testes acabadas de imprimir (álcool)"] },
    { id: "t3_ee_a_10", texto: "As 3 vezes em que fui 'expulso' ou levei um aviso grave do professor", opcoes: ["Por não parar de me rir histericamente de uma parvoíce", "Por atirar aviões de papel ao colega da frente", "Por responder torto e dar uma de chico-esperto"] },
    { id: "t3_ee_a_11", texto: "Os 3 piores castigos coletivos que a turma inteira teve de sofrer por causa de um 'engraçadinho'", opcoes: ["Ficar sem intervalo", "Teste surpresa na hora", "Trabalho de casa com 50 páginas"] },
    { id: "t3_ee_a_12", texto: "As 3 atitudes dos 'betos' e populares da escola que metiam nojo", opcoes: ["Furarem as filas do bar porque conheciam as funcionárias", "Andarem sempre em bandos a rir alto", "Terem as mochilas caras atiradas para o chão"] },
    { id: "t3_ee_a_13", texto: "As 3 lendas urbanas que sopravam de ano para ano sobre os professores", opcoes: ["'O stor de História foi das forças especiais'", "'Aquela stora chumbou o próprio filho'", "'O diretor namora com a contínua'"] },
    { id: "t3_ee_a_14", texto: "Os 3 trabalhos de grupo onde percebi que ia ter de fazer tudo sozinho", opcoes: ["O colega que diz 'eu formato e imprimo no fim'", "Aquele que falta nos dias todos de combinar", "O que faz a capa com letras coloridas do WordArt e não faz mais nada"] },
    { id: "t3_ee_a_15", texto: "As 3 mentiras para não mostrar os trabalhos de casa que não estavam feitos", opcoes: ["'Esqueci-me do caderno em cima da mesa'", "'O meu cão comeu a folha'", "'Fiz no outro livro e enganei-me a trazer'"] },
    { id: "t3_ee_a_16", texto: "Os 3 melhores cheiros e recordações da papelaria / reprografia da escola", opcoes: ["As borrachas com cheiro a morango", "O cheiro do marcador branco (corretor)", "O afia-lápis cheio de aparas de madeira"] },
    { id: "t3_ee_a_17", texto: "As 3 frases com que os professores terminavam a aula mal tocava a campainha", opcoes: ["'A campainha é para mim, não é para vocês!'", "'A aula só acaba quando eu disser'", "'Limpem a sala antes de sair'"] },
    { id: "t3_ee_a_18", texto: "Os 3 perigos de ser apanhado com o telemóvel debaixo da carteira a teclar", opcoes: ["O stor apreender e só devolver no fim da semana", "Ser obrigado a ler a mensagem em voz alta para a turma", "O telemóvel tocar alto um toque piroso"] },
    { id: "t3_ee_a_19", texto: "As 3 mentiras piedosas que os meus pais diziam nas reuniões de encarregados de educação", opcoes: ["'Ele em casa estuda imenso'", "'Não percebo estas notas, ele sabia tudo'", "'Ele é muito distraído, mas é bom menino'"] },
    { id: "t3_ee_a_20", texto: "As 3 regras estúpidas do regulamento interno da escola que a malta contornava", opcoes: ["Proibido usar bonés ou chapéus dentro das salas", "Não poder sair do portão da escola nos furos", "A proibição de calções curtos no verão"] }
  ],
  "sub_29_1": [ // Testes e Exames
    { id: "t3_ee_t_01", texto: "As 3 técnicas de copianço mais arrojadas que utilizei (ou vi utilizar) nos testes", opcoes: ["Cábulas escritas na parte de trás da régua", "Apontamentos no interior do estojo e borracha", "Fórmulas escritas nas pernas por baixo da saia/calções"] },
    { id: "t3_ee_t_02", texto: "As 3 reações horríveis quando o professor entrega o teste e não percebo a Pergunta 1", opcoes: ["Suores frios e calafrios na espinha", "Olhar em volta para ver se mais alguém está em pânico", "Saltar para a 2 e não perceber essa também"] },
    { id: "t3_ee_t_03", texto: "Os 3 rituais maníacos da noite anterior ao grande Exame Nacional", opcoes: ["Dormir com os livros debaixo da almofada (por osmose)", "Beber 4 Red Bulls e estudar até às 5h da manhã", "Desistir e ir ver Netflix e que 'seja o que Deus quiser'"] },
    { id: "t3_ee_t_04", texto: "As 3 piores mentiras que conto a mim mesmo(a) na época de exames", opcoes: ["'Acordo amanhã às 6h da manhã e revejo tudo fresco'", "'Basta ler os resumos 2 vezes'", "'Não devem perguntar esta matéria difícil'"] },
    { id: "t3_ee_t_05", texto: "Os 3 métodos de estudo ineficazes que eu insistia em usar teimosamente", opcoes: ["Sublinhar a página toda de amarelo fosforescente", "Ler a matéria em voz alta e não decorar nada", "Copiar o livro todo para um caderno igualzinho"] },
    { id: "t3_ee_t_06", texto: "As 3 formas desesperadas de tentar 'encher chouriços' numa pergunta de desenvolvimento", opcoes: ["Escrever com a letra muito grande para ocupar espaço", "Repetir o enunciado da pergunta de 3 formas diferentes", "Usar palavras caras e difíceis sem nexo"] },
    { id: "t3_ee_t_07", texto: "As 3 atitudes irritantes do 'cromo' da turma depois de sair do teste", opcoes: ["Dizer 'Correu-me super mal!' e tira um 19", "Ficar à porta a confirmar as respostas todas", "Chorar porque achava que a 4.B estava incompleta"] },
    { id: "t3_ee_t_08", texto: "Os 3 pensamentos tóxicos quando saem as pautas com as notas dos testes afixadas no vidro", opcoes: ["Procurar a nota do meu rival para ver se tive mais", "Rezar para não ter a vermelha vergonhosa (negativa)", "Achar que o professor se enganou a somar as notas"] },
    { id: "t3_ee_t_09", texto: "As 3 coisas cruciais para pedir emprestadas num teste porque me esqueci de trazer", opcoes: ["Calculadora científica e rezar que tenha bateria", "Uma caneta que não falhe nos últimos 5 minutos", "Tipp-ex em fita (ou corretor)"] },
    { id: "t3_ee_t_10", texto: "As 3 desgraças de apagar algo no teste e ter a pior borracha do mundo", opcoes: ["Rasgar a folha de teste oficial", "Ficar uma mancha preta horrível e não apagar nada", "A borracha esfarelar-se toda em pó"] },
    { id: "t3_ee_t_11", texto: "Os 3 truques sujos para saber qual é a matéria que vai sair no teste surpresa", opcoes: ["Perguntar subtilmente à outra turma que já teve a aula", "Rever a última coisa que o professor meteu no quadro", "Rezar muito aos deuses da sorte"] },
    { id: "t3_ee_t_12", texto: "As 3 frases de pânico que assaltam o cérebro quando o tempo está a acabar", opcoes: ["'Faltam 5 minutos, entreguem!'", "'Ainda vou na metade da segunda página!'", "'Não consigo pensar, bloqueei!'"] },
    { id: "t3_ee_t_13", texto: "As 3 disciplinas onde tirei a pior negativa da minha vida com orgulho ferido", opcoes: ["Físico-Química", "Matemática", "História"] },
    { id: "t3_ee_t_14", texto: "As 3 reações quando o professor diz 'Este teste era super fácil'", opcoes: ["Vontade de atirar a caneta à cabeça dele", "Rir ironicamente com os colegas", "Duvidar da minha própria inteligência"] },
    { id: "t3_ee_t_15", texto: "Os 3 lugares onde estudei na Faculdade quando a biblioteca estava completamente cheia", opcoes: ["Nas escadas do edifício sentada no chão frio", "No café barulhento ao lado da faculdade", "Em casa na cama, e adormeci passada meia hora"] },
    { id: "t3_ee_t_16", texto: "As 3 técnicas de 'chico-esperto' nos testes de escolha múltipla (cruzes)", opcoes: ["Meter B em todas se não souber a resposta", "Fazer a lengalenga do 'Pim-pam-pum, cada bola mata um'", "Escolher a resposta mais comprida de todas"] },
    { id: "t3_ee_t_17", texto: "Os 3 momentos de maior nervosismo nas avaliações orais", opcoes: ["Quando o professor folheia a lista de chamada e para no meu nome", "Gaguejar e o silêncio da turma a ouvir a minha gafe", "Esquecer a palavra-chave e não conseguir desenrolar"] },
    { id: "t3_ee_t_18", texto: "As 3 coisas estúpidas que os professores implicavam durante os testes", opcoes: ["'Quem não trouxe folha de rascunho com o carimbo leva zero'", "'Se eu apanho um telemóvel a tocar na mochila, anulo o teste'", "'Arrumem as mochilas lá à frente na sala'"] },
    { id: "t3_ee_t_19", texto: "As 3 superstições e amuletos que levava para a mesa no dia do Exame Nacional", opcoes: ["A minha caneta da sorte que não me deixa falhar", "Um chocolate pequeno escondido para o fim", "Vestir a mesma roupa com que tive boa nota antes"] },
    { id: "t3_ee_t_20", texto: "As 3 mentiras para não mostrar aos pais a nota do teste que foi miserável", opcoes: ["'O professor ainda não entregou, demorou imenso'", "'A nota não conta para a média final do período'", "'A turma inteira tirou negativa, foi muito difícil'"] }
  ]
};
