import { PerguntaTop3 } from "@/types/catalogo";

export const top3_humor_comedia: Record<string, PerguntaTop3[]> = {
  "sub_30_0": [ // Piadas e Risos
    { id: "t3_hc_p_01", texto: "As 3 piadas mais secas e horríveis de que eu me rio com muita vergonha", opcoes: ["O que é um pontinho amarelo no mar? Um amarelo do ovo.", "Porque é que as gaivotas voam sobre o mar? Porque se voassem sobre a baía eram baionetas.", "Qual é o animal mais antigo do mundo? A zebra, porque ainda é a preto e branco."] },
    { id: "t3_hc_p_02", texto: "Os 3 momentos em que me rio histericamente na altura mais imprópria", opcoes: ["Numa sala de espera em absoluto silêncio", "Quando tropeço e caio à frente de desconhecidos", "Enquanto oiço uma bronca séria"] },
    { id: "t3_hc_p_03", texto: "As 3 coisas mais estúpidas que me fazem chorar a rir a qualquer hora da noite", opcoes: ["Vídeos de animais a assustarem-se com pepinos", "Quedas estúpidas em câmaras de segurança", "Memes sem nexo nenhum mandados às 3 da manhã"] },
    { id: "t3_hc_p_04", texto: "Os 3 comediantes (portugueses ou internacionais) que eu acho absolutamente hilariantes", opcoes: ["Ricardo Araújo Pereira", "Bruno Nogueira", "Joana Marques"] },
    { id: "t3_hc_p_05", texto: "As 3 r檀ações mais embaraçosas que tenho quando conto uma piada e ninguém se ri", opcoes: ["Continuar a rir-me sozinho da minha própria piada", "Explicar a piada a ver se alguém percebe", "Fazer silêncio absoluto e fingir que nada aconteceu"] },
    { id: "t3_hc_p_06", texto: "As 3 bocas ou piadas internas do grupo de amigos que já duram há mais de 10 anos", opcoes: ["Lembrar aquela vez em que alguém se perdeu num sítio óbvio", "Uma alcunha estúpida que nunca mais desapetece", "Imitar a voz esquisita de um conhecido"] },
    { id: "t3_hc_p_07", texto: "Os 3 estilos de humor negro que me fazem sentir mal por me estar a rir", opcoes: ["Piadas sobre desastres históricos", "Humor sobre dramas familiares alheios", "Gags visuais com acidentes leves"] },
    { id: "t3_hc_p_08", texto: "As 3 coisas que considero 'comédia involuntária' no dia a dia", opcoes: ["Pessoas a tentarem estacionar de forma trágica", "Discussões parvas de casal no supermercado", "Notícias bizarras de jornais locais"] },
    { id: "t3_hc_p_09", texto: "As 3 reações quando alguém faz uma piada seca que eu já conhecia de cor", opcoes: ["Dar um sorriso amarelo fingido", "Dizer 'Essa piada já tem barbas'", "Completar a piada antes da pessoa acabar"] },
    { id: "t3_hc_p_10", texto: "Os 3 sítios públicos onde é estritamente proibido rir, mas eu rio-me sempre", opcoes: ["Dentro de uma igreja a meio da missa", "Num elevador cheio de gente apertada", "Durante uma reunião de trabalho importante"] },
    { id: "t3_hc_p_11", texto: "As 3 razões pelas quais o meu sentido de humor é considerado esquisito", opcoes: ["Acho graça a coisas totalmente sem contexto", "Rio-me do azar dos outros (Schadenfreude)", "Uso ironia constante que ninguém percebe"] },
    { id: "t3_hc_p_12", texto: "Os 3 memes ou formatos de comédia da internet que já me fartaram", opcoes: ["Vídeos de pegas de malta a assustar os outros", "Trends de dança repetitivas no TikTok", "Frases cortadas com efeitos sonoros altos"] },
    { id: "t3_hc_p_13", texto: "As 3 coisas parvas que digo a rir-me quando não aguento mais as cólicas do riso", opcoes: ["'Chega, por favor, não consigo respirar!'", "'Estou a ficar sem ar nas costelas'", "'Socorro, mijei-me a rir'"] },
    { id: "t3_hc_p_14", texto: "Os 3 filmes de comédia clássicos que vejo sempre que preciso de animar o dia", opcoes: ["The Hangover (A Ressaca)", "As Branquelas (White Chicks)", "Mr. Bean / Monty Python"] },
    { id: "t3_hc_p_15", texto: "As 3 reações exageradas quando alguém me cospe a rir para cima enquanto fala", opcoes: ["Limpar a saliva disfarçadamente com a mão", "Fazer uma cara de nojo inesquecível", "Afastar-me meio metro para trás"] },
    { id: "t3_hc_p_16", texto: "Os 3 amigos que são incapazes de contar uma piada sem se rirem a meio", opcoes: ["O que se engasga com a própria saliva", "O que começa a rir antes da parte engraçada", "O que estraga o punchline todo"] },
    { id: "t3_hc_p_17", texto: "As 3 piadas de trabalho ou de escritório que ouço todos os dias e já enjoam", opcoes: ["'Ainda bem que já é sexta-feira!'", "'Estou a trabalhar tanto que já nem sei o meu nome'", "'Quem me dera estar a dormir na praia'"] },
    { id: "t3_hc_p_18", texto: "As 3 vezes em que fiz uma careta tão feia a rir que alguém tirou foto", opcoes: ["A rir de boca aberta debaixo de flash", "Com os olhos completamente espremidos", "A babar-me ligeiramente de rir"] },
    { id: "t3_hc_p_19", texto: "Os 3 programas de comédia de improviso ou sketches que adoro ver", opcoes: ["Gato Fedorento", "Isto é Gozar com Quem Trabalha", "Taskmaster Portugal"] },
    { id: "t3_hc_p_20", texto: "As 3 coisas mais irónicas de que me rio porque o meu dia foi uma desgraça", opcoes: ["O meu próprio azar monumental", "O trânsito infernal em que estou metido", "Ficar sem bateria no pior segundo"] }
  ],
  "sub_30_1": [ // Memes e Tangas
    { id: "t3_hc_m_01", texto: "Os 3 tipos de memes que passo a vida a enviar aos grupos do WhatsApp", opcoes: ["Memes sobre ansiedade e cansaço de adulto", "Gatos com caras estranhas e legendas parvas", "Indiretas sobre não ter dinheiro"] },
    { id: "t3_hc_m_02", texto: "As 3 tangas ou mentiras na brincadeira que invento só para ver se alguém acredita", opcoes: ["Inventar uma notícia falsa sobre uma celebridade", "Dizer que um prato esquisito é uma iguaria cara", "Fingir que sei falar uma língua inventada"] },
    { id: "t3_hc_m_03", texto: "Os 3 grupos de amigos onde partilho os stickers mais descabidos e proibidos", opcoes: ["O grupo principal de infância", "O grupo secreto dos melhores amigos", "O grupo do futebol/gaming"] },
    { id: "t3_hc_m_04", texto: "As 3 parvoíces que faço quando estou sozinho em casa a falar com o espelho", opcoes: ["Fazer discursos de vitória a receber um prémio", "Imitar personagens de filmes dramáticos", "Comentar as minhas próprias ações em voz alta"] },
    { id: "t3_hc_m_05", texto: "Os 3 maiores clássicos da internet e trolls de que me lembro com nostalgia", opcoes: ["O Rickrolling (mandar o link da música do Rick Astley)", "O meme do caixão (Coffin Dance)", "O doge clássico com cores"] },
    { id: "t3_hc_m_06", texto: "As 3 reações quando alguém me manda um meme que já tem 5 anos na internet", opcoes: ["Responder com 'A internet de 2018 mandou saudades'", "Dar um 'Haha' seco por compaixão", "Fingir que nunca tinha visto na vida"] },
    { id: "t3_hc_m_07", texto: "As 3 pegas ou partidas inofensivas que adoro pregar a amigos distraídos", opcoes: ["Mudar a linguagem do telemóvel para um idioma estranho", "Ligar o Bluetooth do meu telemóvel à coluna dele e meter som parvo", "Esconder as chaves de casa a fingir que não sei"] },
    { id: "t3_hc_m_08", texto: "Os 3 filtros de câmara mais ridículos que uso para mandar fotos estúpidas", opcoes: ["O filtro de bebé chorão", "O cãozinho fofinho com língua de fora", "A cara esticada em modo deformado"] },
    { id: "t3_hc_m_09", texto: "As 3 frases irónicas que uso quando alguém diz uma obviedade total", opcoes: ["'Não me digas, Sherlock Holmes!'", "'Uau, descobriste a pólvora!'", "'Nossa, que perspicaz!'"] },
    { id: "t3_hc_m_10", texto: "Os 3 stickers do WhatsApp que definem 100% a minha personalidade atual", opcoes: ["Um animal com ar de traumatizado", "Uma cara conhecida a chorar a rir", "Um texto gigante irónico"] },
    { id: "t3_hc_m_11", texto: "As 3 teorias da conspiração mais parvas que invento a brincar só para picar", opcoes: ["'Os pombos são robôs do governo a espionar-nos'", "'O meu frigorífico julga as minhas escolhas à noite'", "'A sério que o sol de hoje está muito falso'"] },
    { id: "t3_hc_m_12", texto: "Os 3 momentos em que fui vítima de uma tanga e caí que nem um patinho", opcoes: ["Acreditar numa mentira de 1 de Abril de um amigo", "Achar que um artigo satírico do Inimigo Público era real", "Cair numa piada de corvos/animais inventados"] },
    { id: "t3_hc_m_13", texto: "As 3 respostas mais sarcásticas que dou quando me perguntam 'O que estás a fazer?'", opcoes: ["'Estou a fazer croché com os pés'", "'Nada de especial, a planear a dominação mundial'", "'Respirar oxigénio, e tu?'"] },
    { id: "t3_hc_m_14", texto: "Os 3 desafios parvas da internet (Trends) em que a malta perdeu a cabeça", opcoes: ["O desafio do balde de gelo (Ice Bucket Challenge)", "Comer colheres de canela em pó seca", "Danificar coisas na escola (Devious Licks)"] },
    { id: "t3_hc_m_15", texto: "As 3 piores piadas secas que o meu pai ou tio contam em almoços de família", opcoes: ["Piadas sobre o preço do café e do gasóleo", "Trocadilhos com nomes de cidades e países", "A piada do 'E o camião? Tombou.'"] },
    { id: "t3_hc_m_16", texto: "As 3 coisas que acho piada só porque o meu cérebro está cansadíssimo à noite", opcoes: ["Ler comentários de Facebook de velhinhos indignados", "Ver vídeos de cozinhas a explodir em óleo", "Rir de erros ortográficos graves em tabuletas"] },
    { id: "t3_hc_m_17", texto: "Os 3 apelidos ou nomes falsos que dou quando me pedem o nome num café/restaurante", opcoes: ["'Napoleão'", "'Batman'", "'Senhor Doutor'"] },
    { id: "t3_hc_m_18", texto: "As 3 reações quando alguém estraga uma boa tanga com muita seriedade", opcoes: ["Ficar com pena de estragar a magia", "Dizer logo 'Estava a brincar, criatura!'", "Continuar a mentir só para ver até onde a pessoa vai"] },
    { id: "t3_hc_m_19", texto: "Os 3 vídeos virais portugueses clássicos que nunca morrem na memória coletiva", opcoes: ["O Toni dos teclados / Música pimba viral", "O incêndio na serra ('Olha o fogareu!')", "O senhor do 'Guedes, põe a carne no lume'"] },
    { id: "t3_hc_m_20", texto: "As 3 desculpas hilariantes que uso quando me apanham a fazer uma parvoíce total", opcoes: ["'Estava cientificamente a testar a gravidade'", "'O meu alter-ego assumiu o controlo por um segundo'", "'Culpa a energia dos planetas, não a minha'"] }
  ]
};
