import { PerguntaTop3 } from "@/types/catalogo";

export const top3_livros_leitura: Record<string, PerguntaTop3[]> = {
  "sub_23_0": [ // Hábitos de Leitor
    { id: "t3_ll_h_01", texto: "As 3 desculpas mais usadas para comprar livros novos tendo 10 por ler em casa", opcoes: ["'Esta capa é muito bonita e estava em promoção'", "'É para apoiar o autor'", "'Assim já fica na estante para quando me apetecer'"] },
    { id: "t3_ll_h_02", texto: "Os 3 objetos mais ridículos que já utilizei como marcador de páginas", opcoes: ["Um talão amachucado do Pingo Doce", "O embrulho de uma pastilha elástica", "Um bilhete de comboio velho"] },
    { id: "t3_ll_h_03", texto: "As 3 posições incrivelmente desconfortáveis onde teimo em ler na cama", opcoes: ["De barriga para baixo até o pescoço doer", "De lado a segurar o livro só com uma mão a tremer", "De costas com o livro por cima da cara (e cai no nariz)"] },
    { id: "t3_ll_h_04", texto: "Os 3 piores crimes literários que alguém pode cometer contra um livro", opcoes: ["Dobrar os cantos das páginas (Orelhas de cão)", "Escrever e sublinhar com caneta que trespassa a folha", "Ler no banho e molhar as páginas todas"] },
    { id: "t3_ll_h_05", texto: "As 3 mentiras que já disse numa conversa com pessoas mais 'intelectuais' sobre leitura", opcoes: ["'Sim, já li os clássicos do Eça de Queiroz todos'", "'Leio para aí 3 livros por mês'", "'Achei a metáfora do final do livro muito profunda'"] },
    { id: "t3_ll_h_06", texto: "As 3 coisas que me fazem abandonar um livro pela metade (sem remorsos)", opcoes: ["Os capítulos terem 50 páginas sem pausas", "Personagens aborrecidas e irritantes", "A escrita ser muito confusa e poética em excesso"] },
    { id: "t3_ll_h_07", texto: "Os 3 sítios onde a leitura é para mim um ato sagrado e intocável", opcoes: ["Nas viagens de autocarro ou comboio longo", "Sentado no sofá num dia de muita chuva", "Numa cadeira na praia ao final do dia"] },
    { id: "t3_ll_h_08", texto: "As 3 emoções que sinto quando cheiro um livro novo acabado de comprar", opcoes: ["Tranquilidade de papel impresso e cola", "Vontade gigante de começar a ler", "Sentimento de riqueza cultural momentânea"] },
    { id: "t3_ll_h_09", texto: "As 3 reações quando termino uma saga ou livro espetacular e fico com 'Ressaca Literária'", opcoes: ["Ficar a olhar para o teto durante meia hora a absorver", "Procurar fanfics e o final na internet", "Não conseguir começar a ler mais nada durante um mês"] },
    { id: "t3_ll_h_10", texto: "Os 3 maiores perigos ou stresses de ler livros num formato digital (Kindle/Kobo)", opcoes: ["Ficar sem bateria no clímax do capítulo", "Não poder cheirar o papel", "As pessoas acharem que estou só no telemóvel a jogar"] },
    { id: "t3_ll_h_11", texto: "As 3 coisas que investigo antes de sequer considerar comprar um livro na livraria", opcoes: ["A sinopse e o resumo na contracapa", "A grossura do livro (se for enorme desisto)", "As avaliações no Goodreads ou TikTok"] },
    { id: "t3_ll_h_12", texto: "Os 3 motivos pelos quais me recuso peremptoriamente a emprestar livros", opcoes: ["Vêm com as lombadas todas partidas", "As pessoas demoram meses a devolver (ou esquecem)", "Ficam com cheiro a casa dos outros"] },
    { id: "t3_ll_h_13", texto: "As 3 rotinas ou tiques que tenho de satisfazer para entrar em 'Modo Leitura'", opcoes: ["Fazer uma caneca de chá ou café quente", "Meter o telemóvel no Modo Silêncio longe", "Ajeitar os óculos ou ligar o candeeiro certo"] },
    { id: "t3_ll_h_14", texto: "As 3 razões pelas quais as lombadas da minha estante não estão perfeitamente alinhadas", opcoes: ["Falta de espaço para tantos livros diferentes", "Misturar livros grossos com finos", "Separar por cor em vez de ser pelo autor"] },
    { id: "t3_ll_h_15", texto: "Os 3 sinais inegáveis de que adormeci enquanto lia à noite", opcoes: ["O livro cai com estrondo no chão e acorda-me", "A baba escorre ligeiramente no travesseiro", "Acordo com as luzes ligadas e na mesma página de ontem"] },
    { id: "t3_ll_h_16", texto: "As 3 atitudes dos vendedores nas Feiras do Livro que me metem medo", opcoes: ["Aspirarem as carteiras das pessoas com saldos", "Empurrarem-me o 1º volume de uma saga de 10", "Dizerem 'Não pode perder isto!' a tudo"] },
    { id: "t3_ll_h_17", texto: "As 3 desilusões clássicas ao ver o 'BookTok' ou os Youtubers de Livros", opcoes: ["Eles comprarem dezenas de livros caros que eu não posso", "Terem estantes imaculadas que parecem do IKEA", "Chorarem muito para a câmara a fingir emoção"] },
    { id: "t3_ll_h_18", texto: "Os 3 tipos de organização de estante de livros que eu defendo ou ataco ferozmente", opcoes: ["Por ordem alfabética de autor", "Por cor da lombada (a mais polémica)", "Em pilhas confusas como num alfarrabista"] },
    { id: "t3_ll_h_19", texto: "As 3 frases irritantes que ouço quando as pessoas me veem sempre a ler", opcoes: ["'Não tens vida para além disso?'", "'Estás a estudar para quê?'", "'Eu preferia esperar pelo filme'"] },
    { id: "t3_ll_h_20", texto: "As 3 táticas para disfarçar quando não estou a ler e perdi o fio à meada na página", opcoes: ["Avançar 3 páginas e fingir que percebi o contexto", "Voltar atrás dois capítulos de vergonha", "Ver um resumo no Google do capítulo"] }
  ],
  "sub_23_1": [ // Histórias e Personagens
    { id: "t3_ll_c_01", texto: "Os 3 livros de leitura obrigatória na escola que me fizeram sofrer de sono e tédio", opcoes: ["Os Maias", "Os Lusíadas", "Memorial do Convento"] },
    { id: "t3_ll_c_02", texto: "As 3 adaptações de livros para o cinema/TV que estragaram tudo e deviam ser proibidas", opcoes: ["Percy Jackson (os filmes antigos)", "Eragon", "Divergente"] },
    { id: "t3_ll_c_03", texto: "As 3 mortes trágicas de personagens (em livros famosos) que até hoje não perdoei ao autor", opcoes: ["O Dobby ou o Sirius Black no Harry Potter", "O Ned Stark no Game of Thrones", "O Prim nos Jogos da Fome"] },
    { id: "t3_ll_c_04", texto: "Os 3 géneros literários que recuso categoricamente adicionar à minha estante", opcoes: ["Autoajuda ou Finanças Espirituais", "Ficção Científica muito complexa", "Biografias de youtubers"] },
    { id: "t3_ll_c_05", texto: "Os 3 universos fictícios retirados de livros onde eu me mudaria sem hesitar", opcoes: ["Hogwarts (Harry Potter)", "A Comarca / Shire (Senhor dos Anéis)", "Nárnia"] },
    { id: "t3_ll_c_06", texto: "As 3 coisas estereotipadas que a personagem principal do romance faz sempre", opcoes: ["Morder o lábio nervosamente ou corar imenso", "Ser super desajeitada e cair contra o 'bad boy'", "Não perceber que toda a gente a acha linda"] },
    { id: "t3_ll_c_07", texto: "Os 3 livros infantis ou contos de fadas que, bem analisados, são macabros e assustadores", opcoes: ["A Capuchinho Vermelho (O lobo come a avó)", "O Capuchinho Branco", "O Hansel e Gretel (A bruxa come as crianças)"] },
    { id: "t3_ll_c_08", texto: "As 3 grandes desilusões em finais de livros que me deixaram com cara de caso", opcoes: ["A personagem principal acabar com o tipo errado", "O clássico e preguiçoso 'Foi tudo um sonho'", "Finais em aberto que não explicam nada"] },
    { id: "t3_ll_c_09", texto: "Os 3 vilões muito bem escritos da literatura que acabei por adorar mais que os heróis", opcoes: ["O Voldemort (porque metia respeito)", "O Presidente Snow", "O Conde Drácula"] },
    { id: "t3_ll_c_10", texto: "As 3 sagas da minha adolescência que reli tantas vezes que as páginas quase descolaram", opcoes: ["Harry Potter", "Crepúsculo (Twilight)", "Os Jogos da Fome (Hunger Games)"] },
    { id: "t3_ll_c_11", texto: "As 3 frases de engate e declarações épicas de livros que na vida real dariam cadeia", opcoes: ["'Vou observar-te a dormir pela janela'", "'Sigo-te para qualquer parte do mundo sem avisar'", "'Escrevo-te 365 cartas sem tu responderes'"] },
    { id: "t3_ll_c_12", texto: "Os 3 elementos mágicos ou fantasiosos da literatura que me dariam mais jeito na vida real", opcoes: ["O feitiço 'Accio' para chamar comandos e comida", "Pós de Flu para viajar lareiras", "Uma varinha mágica multifunções"] },
    { id: "t3_ll_c_13", texto: "As 3 opiniões polémicas que defendo e metem os 'book lovers' a gritar comigo", opcoes: ["'Os filmes às vezes são melhores que os livros'", "'Ouvir Audiobooks não é ler de verdade'", "'Odeio os livros da Colleen Hoover'"] },
    { id: "t3_ll_c_14", texto: "Os 3 autores (nacionais ou internacionais) que eu compraria a lista de supermercado deles", opcoes: ["J.K. Rowling", "Stephen King", "José Saramago"] },
    { id: "t3_ll_c_15", texto: "Os 3 clichés de fantasia que têm de estar presentes num bom livro do género", opcoes: ["O mapa do mundo nas primeiras páginas", "O profecia do Escolhido que salva o mundo", "O mentor velho e sábio com barbas brancas"] },
    { id: "t3_ll_c_16", texto: "As 3 reações exageradas a 'Plot Twists' (reviravoltas) chocantes às 3 da manhã", opcoes: ["Gritar baixinho com a mão na boca para não acordar ninguém", "Atirar o livro contra a cama", "Ficar a olhar para o vácuo com o livro no colo"] },
    { id: "t3_ll_c_17", texto: "As 3 características dos protagonistas de livros policiais e thrillers que nunca mudam", opcoes: ["O detetive é divorciado e tem problemas com a bebida", "A polícia local odeia sempre o detetive", "O assassino esteve à frente deles o livro todo"] },
    { id: "t3_ll_c_18", texto: "As 3 obras clássicas ou de época que finjo que percebo muito bem, mas li o resumo", opcoes: ["O Romeu e Julieta", "O Orgulho e Preconceito", "O Auto da Barca do Inferno"] },
    { id: "t3_ll_c_19", texto: "As 3 melhores frases iniciais ou inícios de livros da história literária", opcoes: ["'Era o melhor dos tempos, era o pior dos tempos...' (A Tale of Two Cities)", "'Muitos anos depois, diante do pelotão de fuzilamento...' (Cem Anos de Solidão)", "'Num buraco no chão vivia um hobbit...' (O Hobbit)"] },
    { id: "t3_ll_c_20", texto: "As 3 histórias sobre as quais faria a minha autobiografia se escrevesse a minha vida", opcoes: ["As peripécias e misérias das minhas ex-relações", "A odisseia do ensino superior", "As viagens mais parvas que fiz sem planeamento"] }
  ]
};
