import { PerguntaTop3 } from "@/types/catalogo";

export const top3_musica_concertos: Record<string, PerguntaTop3[]> = {
  "sub_25_0": [ // Gostos e Playlists
    { id: "t3_mc_g_01", texto: "As 3 músicas embaraçosas que sei de cor mas escondo na minha playlist do Spotify", opcoes: ["Músicas infantis da Disney", "Música Pimba pimba mesmo pesada", "Boybands dos anos 2000 (Backstreet Boys)"] },
    { id: "t3_mc_g_02", texto: "Os 3 artistas ou bandas icónicas que digo que gosto só para parecer fixe", opcoes: ["Pink Floyd", "Arctic Monkeys", "Radiohead"] },
    { id: "t3_mc_g_03", texto: "As 3 faixas que ouço aos berros no carro quando estou completamente sozinho(a)", opcoes: ["Músicas de coração partido da Adele", "Rap de intervenção antigo", "Sertanejo ou Funk pesadíssimo"] },
    { id: "t3_mc_g_04", texto: "Os 3 estilos de música que me fazem pedir imediatamente para mudar de estação", opcoes: ["Heavy Metal a gritar muito", "Fado super deprimente de manhã", "Música clássica sem ritmo"] },
    { id: "t3_mc_g_05", texto: "As 3 desculpas estúpidas que uso para não partilhar os meus fones com ninguém", opcoes: ["'Os meus fones estão sujos de cera'", "'A minha música é bué estranha'", "'Só tenho bateria num lado'"] },
    { id: "t3_mc_g_06", texto: "Os 3 cantores portugueses que eu defendo com unhas e dentes nas discussões", opcoes: ["Rui Veloso", "Jorge Palma", "Ornatos Violeta"] },
    { id: "t3_mc_g_07", texto: "As 3 músicas ideais para entrar num salão e fazer tudo olhar para mim em câmara lenta", opcoes: ["'Stayin' Alive' (Whitney Houston)", "'Crazy in Love' (Bee Gees)", "A marcha Imperial do Star Wars"] },
    { id: "t3_mc_g_08", texto: "As 3 playlists que criei e a que dei nomes perfeitamente absurdos", opcoes: ["'Músicas para chorar no banho'", "'Limpar a casa com ódio'", "'Vibes de quem não tem dinheiro'"] },
    { id: "t3_mc_g_09", texto: "As 3 canções que me atiram instantaneamente para os piores traumas da adolescência", opcoes: ["'Wonderwall' (Oasis)", "Músicas dos My Chemical Romance", "As baladas dos D'ZRT"] },
    { id: "t3_mc_g_10", texto: "Os 3 temas ou ritmos em que o meu pé começa a bater o compasso sem eu querer", opcoes: ["Bateria de Rock rápida", "Batidas de Reggaeton", "Baixos de música House/Techno"] },
    { id: "t3_mc_g_11", texto: "As 3 desgraças de cantar no banho quando se pensa que a casa está vazia", opcoes: ["Afinar agudos falhados com a janela aberta", "A família estar na sala a ouvir tudo calada", "Escorregar na banheira no refrão alto"] },
    { id: "t3_mc_g_12", texto: "Os 3 artistas internacionais em que eu gastava um ordenado inteiro para ver ao vivo", opcoes: ["Coldplay", "Taylor Swift", "The Weeknd"] },
    { id: "t3_mc_g_13", texto: "As 3 reações a músicas de Natal a começar a dar nos shoppings em Novembro", opcoes: ["Revirar os olhos e suspirar alto", "Cantar 'All I Want For Christmas' entusiasmado", "Fugir da loja o mais rápido possível"] },
    { id: "t3_mc_g_14", texto: "Os 3 clássicos obrigatórios nas festas de aldeia ou arraiais", opcoes: ["'Apita o Comboio'", "'A Garagem da Vizinha'", "'Menina Estás à Janela'"] },
    { id: "t3_mc_g_15", texto: "As 3 músicas de anúncios de TV que se colaram ao meu cérebro durante semanas", opcoes: ["A música da MEO ou NOS", "Jingles antigos de supermercados (Continente)", "Anúncios irritantes de carros"] },
    { id: "t3_mc_g_16", texto: "Os 3 instrumentos que estragam uma música se forem tocados em excesso", opcoes: ["Um solo de flauta de bisel", "Gaitas de foles fora de contexto", "Campainhas e triângulos infantis"] },
    { id: "t3_mc_g_17", texto: "As 3 vezes em que fui apanhado a dançar sozinho em locais públicos", opcoes: ["Na fila do supermercado com fones", "Dentro do carro parado no semáforo", "A limpar montras no trabalho"] },
    { id: "t3_mc_g_18", texto: "As 3 canções que me recuso a ouvir porque me fazem chorar baba e ranho", opcoes: ["'Fix You' (Coldplay)", "'Someone Like You' (Adele)", "A música do filme Titanic"] },
    { id: "t3_mc_g_19", texto: "Os 3 temas que eram sucessos no meu tempo de liceu e tocavam em todas as discotecas", opcoes: ["'Mr. Brightside' (Oasis)", "'I Gotta Feeling' (The Killers)", "'Low' (Black Eyed Peas)"] },
    { id: "t3_mc_g_20", texto: "As 3 reações exageradas quando o Spotify Wrapped me diz que o meu artista nº1 é piroso", opcoes: ["Esconder a partilha dos amigos", "Criar desculpas ('Foi a minha mãe que usou a conta!')", "Aceitar a vergonha e partilhar na mesma"] }
  ],
  "sub_25_1": [ // Ao Vivo e Festivais
    { id: "t3_mc_v_01", texto: "As 3 coisas cruciais e indispensáveis que tenho de levar numa mochila de festival", opcoes: ["Toalhitas húmidas / Papel Higiénico", "Powerbank carregado a 100%", "Óculos de sol baratos"] },
    { id: "t3_mc_v_02", texto: "Os 3 piores sítios ou locais para ficar posicionado no meio da multidão num concerto", opcoes: ["Atrás da pessoa com 2 metros de altura", "Ao lado das colunas gigantes (surdez)", "Ao pé do bar/casa de banho por causa do trânsito"] },
    { id: "t3_mc_v_03", texto: "As 3 mentiras clássicas que o vocalista diz sempre para agradar ao público de Lisboa/Porto", opcoes: ["'Vocês são o melhor público do mundo!'", "'Nós adoramos a vossa comida!'", "'Queremos vir viver para Portugal!'"] },
    { id: "t3_mc_v_04", texto: "Os 3 aspetos de dormir no campismo de um festival que são um teste à sobrevivência humana", opcoes: ["Acordar numa tenda a 40 graus às 8 da manhã", "A casa de banho comunitária no 3º dia", "A malta que mete música às 5h da manhã"] },
    { id: "t3_mc_v_05", texto: "As 3 piores desgraças corporais de passar 8 horas em pé à espera da banda principal", opcoes: ["As dores nas costas e na lombar a latejar", "Vontade de fazer chichi mas não querer perder o lugar", "Pés completamente esmagados em bolhas"] },
    { id: "t3_mc_v_06", texto: "As 3 táticas pouco éticas para passar por toda a gente e chegar à grade do palco", opcoes: ["'Desculpe, a minha namorada está ali à frente!'", "Fazer um comboio humano de mãos dadas a empurrar", "Andar com os copos na mão a ameaçar entornar"] },
    { id: "t3_mc_v_07", texto: "As 3 reações ao ver os preços absurdos das roulotes de comida dentro do recinto", opcoes: ["Pagar 10€ por um hambúrguer a chorar por dentro", "Prometer que não como e a seguir desmaiar de fome", "Tentar roubar batatas do prato dos amigos"] },
    { id: "t3_mc_v_08", texto: "Os 3 amigos que odeio ter comigo num ambiente de concerto muito cheio", opcoes: ["O que se perde logo nos primeiros 10 minutos", "O que passa o tempo a reclamar do calor", "O que quer ir embora antes da última música"] },
    { id: "t3_mc_v_09", texto: "As 3 peripécias com a chuva ou lama (estilo Paredes de Coura) de que não tenho saudades", opcoes: ["Pisar poças fundas e ficar com as meias empapadas", "O pó que se levanta e entope as narinas no fim", "As capas da chuva de plástico a colar no corpo"] },
    { id: "t3_mc_v_10", texto: "Os 3 momentos no palco que me dão imensa 'vergonha alheia' (cringe)", opcoes: ["O artista falhar um salto ou cair a andar para trás", "Pedir para o público cantar e haver silêncio total", "O playback dessincronizar do som da banda"] },
    { id: "t3_mc_v_11", texto: "As 3 manias que tenho (ou odeio nos outros) nos Moshpits (rodas na multidão)", opcoes: ["A malta que atira copos de cerveja (ou mijo) ao ar", "Ficar encostado à roda e levar murros sem querer", "Os gajos sem t-shirt super suados a escorregar"] },
    { id: "t3_mc_v_12", texto: "As 3 atitudes dos seguranças (stewards) nos festivais que respeito (ou temo)", opcoes: ["Atirarem águas gratuitas para a malta a ferver", "Tirarem as pessoas desmaiadas à pressão por cima da grade", "A cara de ódio quando veem a banda e não podem abanar a cabeça"] },
    { id: "t3_mc_v_13", texto: "As 3 canções que as bandas tocam no fim (Encore) e toda a gente sabe que eles iam voltar", opcoes: ["O grande êxito comercial de há 10 anos", "A música lenta com as luzes do telemóvel", "A faixa de rock mais pesada para fechar tudo a saltar"] },
    { id: "t3_mc_v_14", texto: "Os 3 objetos brilhantes ou parvos que o pessoal leva em festivais e tapa a visão a todos", opcoes: ["Cartazes de cartão gigantescos", "Bonecos insufláveis e jacarés no ar", "Paus de selfie compridos"] },
    { id: "t3_mc_v_15", texto: "As 3 coisas estupidamente caras de merchandising (tendas da banda) que comprei na febre do momento", opcoes: ["Uma T-shirt mal desenhada a 45€", "Um póster que amassei todo a caminho do carro", "Pins e chapéus ridículos"] },
    { id: "t3_mc_v_16", texto: "As 3 formas desesperadas de conseguir regressar a casa após acabar um festival", opcoes: ["Pagar o quádruplo a um TVDE em tarifa dinâmica", "Andar a pé 5 quilómetros na estrada de madrugada", "Dormir encostado no capot do carro à espera de acordar a bebedeira"] },
    { id: "t3_mc_v_17", texto: "Os 3 arrependimentos cruciais das roupas que escolho para ir para o recinto", opcoes: ["Não ter levado o raio do casaco para a noite gélida", "Levar vestidos brancos que ficaram pretos da poeira", "Calçar sapatos abertos ou sandálias finas"] },
    { id: "t3_mc_v_18", texto: "As 3 tradições de festivaleiro que finjo adorar mas, por dentro, já não tenho idade", opcoes: ["Sentar-me no chão sujo e empestado de lixo a descansar", "Abraçar desconhecidos suados numa música feliz", "Comer sandes de atum aquecidas no carro"] },
    { id: "t3_mc_v_19", texto: "Os 3 motivos pelos quais prefiro concertos em nome próprio do que grandes festivais", opcoes: ["Tocam por mais de uma hora", "O público está lá por eles e não só pelo convívio", "O som costuma ter muito melhor qualidade"] },
    { id: "t3_mc_v_20", texto: "As 3 mentiras de consolo quando a minha banda favorita não passa em Portugal", opcoes: ["'Eles também já não cantam nada de jeito'", "'Assim não gasto dinheiro este verão'", "'Vou vê-los a Madrid de certeza!' (nunca vai)"] }
  ]
};
