import { PerguntaTop3 } from "@/types/catalogo";

export const top3_saude_bem_estar: Record<string, PerguntaTop3[]> = {
  "sub_17_0": [ // Cuidados Médicos
    { id: "t3_sbe_c_01", texto: "Os 3 sintomas perfeitamente normais que me fazem ir logo ao Google pesquisar cancro", opcoes: ["Dores de cabeça fortes", "Uma mancha ou sinal esquisito na pele", "Um alto/inchaço depois de bater em algo"] },
    { id: "t3_sbe_c_02", texto: "As 3 idas a médicos de especialidade que eu adio o máximo e odeio ir de morte", opcoes: ["Ida ao Dentista", "Ida ao Ginecologista/Urologista", "Exames de sangue ou análises (agulhas)"] },
    { id: "t3_sbe_c_03", texto: "As 3 mezinhas ou remédios caseiros das avós nos quais eu acredito cegamente", opcoes: ["Chá de limão e mel para a dor de garganta", "Canja de galinha para qualquer virose", "Gelo num pano para os galos na cabeça"] },
    { id: "t3_sbe_c_04", texto: "Os 3 medicamentos ou caixas vazias que andam sempre debaixo na minha gaveta", opcoes: ["Ben-u-ron (Paracetamol) caducado", "Brufen (Ibuprofeno) amassado", "Rennie para os enjoos noturnos"] },
    { id: "t3_sbe_c_05", texto: "As 3 reações ridículas e infantis que eu tenho na hora de levar uma vacina", opcoes: ["Virar a cara para a parede a suar", "Avisar o enfermeiro 'olhe que eu vou desmaiar'", "Apertar a mão de quem vai comigo até partir"] },
    { id: "t3_sbe_c_06", texto: "As 3 dores físicas com as quais juro não conseguir lidar com dignidade", opcoes: ["Dores de dentes lancinantes", "Bater com o dedo mindinho do pé num móvel", "Dores de ouvidos constantes"] },
    { id: "t3_sbe_c_07", texto: "Os 3 maiores perigos das salas de espera nos Centros de Saúde ou Urgências", opcoes: ["Apanhar doenças novas das pessoas a tossir ali", "A seca de esperar 4 horas pela pulseira", "Levar com os idosos a contar a vida toda deles"] },
    { id: "t3_sbe_c_08", texto: "As 3 desculpas monumentais que dou ao dentista por não passar o fio dental", opcoes: ["'As minhas gengivas sangram sozinhas'", "'Às vezes esqueço-me por causa do trabalho'", "'Eu passo, mas ontem acabou a caixa'"] },
    { id: "t3_sbe_c_09", texto: "As 3 vezes em que fui um valente herói(na) e me recusei a ir ao hospital doente", opcoes: ["Com uma febre de 39 graus na cama", "Com um pé quase torcido/partido a mancar 3 dias", "Com uma valente intoxicação do sushi rasca"] },
    { id: "t3_sbe_c_10", texto: "As 3 mentiras clássicas que digo a mim próprio na passagem de ano sobre saúde", opcoes: ["'Este ano vou fazer exames de rotina completos'", "'Vou finalmente entrar num ginásio a sério'", "'Vou deixar os doces de vez'"] },
    { id: "t3_sbe_c_11", texto: "Os 3 medos irracionais de hospitais que as séries (tipo Grey's Anatomy) me deram", opcoes: ["Cortarem-me a perna errada numa cirurgia", "Acordar a meio de uma anestesia geral", "Trocarem-me no berçário por outro bebé (já tarde)"] },
    { id: "t3_sbe_c_12", texto: "As 3 peças da caixa de primeiros socorros em casa que já deviam ter ido para o lixo", opcoes: ["Uma betadine dos anos 2000 seca", "Pensos rápidos que já não colam nada", "Água oxigenada caducada"] },
    { id: "t3_sbe_c_13", texto: "Os 3 truques perigosos que utilizo para tentar desentupir um nariz entupido", opcoes: ["Meter Vicks Vaporub dentro das narinas", "Inalar água do mar salgada aos litros", "Asoar com força até rasgar um capilar"] },
    { id: "t3_sbe_c_14", texto: "As 3 dores ou queixas típicas de 'idade avançada' que já começo a sentir nos ossos", opcoes: ["Dor na lombar a lavar a loiça", "Estalos nos joelhos ao agachar", "Ciática presa no sofá"] },
    { id: "t3_sbe_c_15", texto: "As 3 formas que encontrei de subornar a malta para ir a consultas por mim (ou comigo)", opcoes: ["'Pago-te o almoço se fores segurar-me na mão'", "'Conduz até lá que depois pago o estacionamento'", "'Vai lá tu levantar a minha receita médica sff'"] },
    { id: "t3_sbe_c_16", texto: "As 3 coisas que pergunto sempre desesperado(a) quando apanho uma valente gastroenterite", opcoes: ["'Quem é que teve a ideia do marisco ontem?!'", "'Isto passa se eu beber chá preto e comer tostas?'", "'Devo ir para o hospital ou morro na sanita?'"] },
    { id: "t3_sbe_c_17", texto: "Os 3 conselhos de saúde muito portugueses do 'Dr. Google' e da rua", opcoes: ["'Mete uma cebola aos pés da cama'", "'Toma um bagaço quente que isso mata o bicho'", "'Isso é corrente de ar, bota um cachecol'"] },
    { id: "t3_sbe_c_18", texto: "As 3 mentiras muito sérias que as pessoas dizem em exames de rotina ou análises", opcoes: ["'Sim doutor, eu só bebo socialmente'", "'Faço exercício 3 vezes por semana no mínimo'", "'Claro que como muitos vegetais'"] },
    { id: "t3_sbe_c_19", texto: "Os 3 maiores alívios após uma ida difícil ao dentista ou hospital", opcoes: ["Ouvir 'não é nada de grave, pode ir para casa'", "A anestesia do dente passar e sentir a língua", "A conta ser comparticipada a 100% pelo seguro"] },
    { id: "t3_sbe_c_20", texto: "As 3 manias mais esquisitas que tenho com curativos (pensinhos rápidos)", opcoes: ["Usar pensos infantis do Mickey na faculdade", "Arrançar de repente e ficar sem metade dos pêlos", "Usar betadine até a ferida parecer lama"] }
  ],
  "sub_17_1": [ // Saúde Mental e Ansiedade
    { id: "t3_sbe_m_01", texto: "As 3 coisas perfeitamente banais que me dão um pico de ansiedade instantâneo", opcoes: ["O telemóvel tocar e não conhecer o número", "Emails a dizer 'Preciso de falar contigo amanhã'", "Ouvir buzinas de ambulâncias atrás de mim no trânsito"] },
    { id: "t3_sbe_m_02", texto: "As 3 formas mais eficazes que uso para tentar desligar a cabeça e os nervos antes de dormir", opcoes: ["Ver vídeos de ASMR de chuva no Youtube", "Criar cenários irreais felizes na cabeça", "Ler 5 páginas de um livro e adormecer de cansaço"] },
    { id: "t3_sbe_m_03", texto: "Os 3 pensamentos ou paranóias que costumam assombrar as minhas noites de insónias", opcoes: ["Aquele erro estúpido que cometi no trabalho em 2016", "Pensar no sentido do Universo e da Morte", "Listas gigantescas do que tenho de fazer amanhã"] },
    { id: "t3_sbe_m_04", texto: "As 3 frases de conforto da treta que me irritam imenso quando estou triste", opcoes: ["'Anima-te, há quem esteja pior que tu'", "'Tudo acontece por uma razão'", "'A vida é mesmo assim, não penses nisso'"] },
    { id: "t3_sbe_m_05", texto: "Os 3 hábitos super tóxicos de coping (lidar com problemas) que adoto sem querer", opcoes: ["Fechar-me no quarto isolado(a) 3 dias", "Comer um pacote de gelado inteiro sozinho(a)", "Descarregar as frustrações nas pessoas mais próximas"] },
    { id: "t3_sbe_m_06", texto: "As 3 situações sociais onde o meu cérebro quer explodir de ansiedade", opcoes: ["Festas enormes cheias de gente que eu não conheço", "Apresentações em público (falar para mais de 5 pessoas)", "Momentos de silêncio num elevador com vizinhos"] },
    { id: "t3_sbe_m_07", texto: "As 3 coisas minúsculas que me estragam completamente o bom humor do dia todo", opcoes: ["Derramar café na minha camisa acabada de vestir", "Apanhar todos os semáforos vermelhos na ida", "Alguém responder 'K' no WhatsApp"] },
    { id: "t3_sbe_m_08", texto: "As 3 palavras ou adjetivos que eu usaria para descrever a minha 'Bateria Social'", opcoes: ["Descarrega num instante", "Depende muito das pessoas da sala", "Totalmente inexistente na maioria dos dias"] },
    { id: "t3_sbe_m_09", texto: "As 3 atividades terapêuticas não convencionais que me ajudam imenso", opcoes: ["Limpar e esfregar a casa com raiva aos domingos", "Montar Legos ou fazer puzzles em silêncio", "Conduzir na autoestrada à noite sem destino"] },
    { id: "t3_sbe_m_10", texto: "As 3 táticas milagrosas (e erradas) para evitar confrontos ou discussões duras", opcoes: ["Fingir que não vi a mensagem e apagar", "Concordar com tudo só para a pessoa se calar", "Dizer 'Já falámos sobre isto' e sair da divisão"] },
    { id: "t3_sbe_m_11", texto: "As 3 razões estúpidas que a minha mente arranja para sofrer com o 'Síndrome do Impostor'", opcoes: ["Achar que no trabalho vão perceber que sou incompetente", "Não merecer os elogios sinceros das pessoas", "Pensar que o meu parceiro(a) não devia estar comigo"] },
    { id: "t3_sbe_m_12", texto: "As 3 memórias humilhantes que a minha cabeça gosta de repetir aleatoriamente no banho", opcoes: ["A resposta errada e infantil que dei a um professor há 10 anos", "Apanharem-me a falar sozinho(a) ou a cantar mal", "Quando tropecei nas escadas do shopping cheio"] },
    { id: "t3_sbe_m_13", texto: "Os 3 maiores gatilhos (triggers) que me atiram de volta para estados de tristeza pura", opcoes: ["Ouvir cheiros/perfumes antigos do passado", "Aquelas fotos de memórias do telemóvel de 'Há 5 anos'", "Ir de carro a ouvir álbuns deprimentes inteiros"] },
    { id: "t3_sbe_m_14", texto: "As 3 'Auto-recompensas' que dou a mim mesmo para premiar dias difíceis no trabalho", opcoes: ["Comprar algo fútil online na Amazon", "Faltar ao ginásio porque 'o meu cérebro merece'", "Beber um copo de vinho logo à terça-feira"] },
    { id: "t3_sbe_m_15", texto: "Os 3 conselhos maravilhosos que dou aos outros, mas que eu nunca aplico à minha vida", opcoes: ["'Não deixes tudo para o último minuto'", "'Pede ajuda se estiveres a sofrer muito'", "'Larga as redes sociais e vive o momento'"] },
    { id: "t3_sbe_m_16", texto: "As 3 formas estranhas em que a ansiedade afeta o meu corpo fisicamente", opcoes: ["Ficar com borboletas / pedras na barriga", "Começar a ranger os dentes de noite", "Suar horrores das mãos do nada"] },
    { id: "t3_sbe_m_17", texto: "As 3 regras de 'Saúde Mental' no local de trabalho que exijo e não abdico", opcoes: ["Não responder a e-mails ou mensagens depois das 18h", "Poder ir à casa de banho chorar se for preciso", "Tirar a hora de almoço inteira longe do PC"] },
    { id: "t3_sbe_m_18", texto: "As 3 mentiras que digo mais vezes ao meu psicólogo (ou diria, se fosse a um)", opcoes: ["'Tenho feito os exercícios de respiração'", "'Esta semana até lidei bem com o stress'", "'Acho que já superei aquele trauma antigo'"] },
    { id: "t3_sbe_m_19", texto: "As 3 'Red Flags' (sinais de alarme) gigantes que provam que estou à beira do esgotamento", opcoes: ["Começar a chorar a ver anúncios de televisão", "Qualquer pergunta normal me faz gritar com a pessoa", "A casa virar um pântano autêntico sem ser arrumada"] },
    { id: "t3_sbe_m_20", texto: "As 3 pessoas chave do meu círculo restrito a quem recorro quando o mundo desaba", opcoes: ["O(A) meu(minha) melhor amigo(a) de infância", "A minha Mãe / O meu Pai", "O(A) meu(minha) parceiro(a) ou o meu bicho de estimação"] }
  ]
};
