import { PerguntaTop3 } from "@/types/catalogo";

export const top3_supersticoes_crencas: Record<string, PerguntaTop3[]> = {
  "sub_20_0": [ // Mitos e Tradições
    { id: "t3_sc_m_01", texto: "As 3 superstições mais clássicas que a minha avó me ensinou e que eu respeito", opcoes: ["Não deixar as tesouras abertas em cima da mesa", "Não abrir o guarda-chuva dentro de casa", "Apanhar a vassoura se cair no chão"] },
    { id: "t3_sc_m_02", texto: "Os 3 horrores que eu acredito que acontecem se eu varrer os pés a alguém solteiro", opcoes: ["A pessoa nunca mais casa", "Traz anos de azar ao amor", "Eu vou ser o padrinho do não-casamento"] },
    { id: "t3_sc_m_03", texto: "As 3 simpatias ou curas com ervas a que recorro em segredo quando as coisas correm mal", opcoes: ["Um banho com sal grosso", "Queimar folhas de louro ou alecrim em casa", "Fazer o sinal da cruz três vezes"] },
    { id: "t3_sc_m_04", texto: "Os 3 ditados ou provérbios portugueses que aplico em absolutamente qualquer conversa", opcoes: ["'Deus escreve direito por linhas tortas'", "'Quem tem boca vai a Roma'", "'Mais vale um pássaro na mão que dois a voar'"] },
    { id: "t3_sc_m_05", texto: "As 3 reações exageradas de uma típica mãe/avó tuga a uma previsão do tempo ou eclipse", opcoes: ["'Isto é o fim do mundo em cuecas!'", "'Nunca vi nada assim nos meus anos'", "'Fecha os espelhos da casa toda!'"] },
    { id: "t3_sc_m_06", texto: "Os 3 mitos sobre comida em que acreditei tempo demais durante a infância", opcoes: ["Laranjas com leite faz morrer", "O pão quente dá dores de barriga e encrava", "Não nadar depois de comer senão dás o estoiro"] },
    { id: "t3_sc_m_07", texto: "As 3 desgraças absolutas que vêm a caminho se entornar sal em cima da mesa", opcoes: ["Anos de falta de dinheiro", "Uma valente discussão de família à mesa", "Má sorte no trabalho"] },
    { id: "t3_sc_m_08", texto: "As 3 coisas que deito logo fora se estiverem partidas porque chamam mau-olhado", opcoes: ["Espelhos rachados", "Copos estalados no rebordo", "Relógios que não andam"] },
    { id: "t3_sc_m_09", texto: "Os 3 mitos urbanos portugueses mais assustadores e fascinantes das nossas estradas", opcoes: ["A rapariga da curva de Sintra (A Teresa)", "O fantasma das estradas de nevoeiro", "Dar boleia e a pessoa desaparecer no banco"] },
    { id: "t3_sc_m_10", texto: "As 3 reações físicas que me provam indubitavelmente que estão a falar mal de mim", opcoes: ["As orelhas ficam a arder de repente", "Sentir um arrepio pelo corpo", "O olho direito tremer"] },
    { id: "t3_sc_m_11", texto: "Os 3 objetos que nunca, mas mesmo nunca, ofereço como prenda para não dar azar", opcoes: ["Lenços de assoar (significam lágrimas)", "Facas ou coisas cortantes", "Sapatos (para a pessoa não fugir)"] },
    { id: "t3_sc_m_12", texto: "As 3 coisas bizarras que tento fazer na virada do ano para garantir os 12 meses de luxo", opcoes: ["Comer as 12 passas e não me engasgar", "Vestir roupa interior azul (ou vermelha)", "Subir com o pé direito a uma cadeira"] },
    { id: "t3_sc_m_13", texto: "Os 3 significados parvos que eu aplico quando encontro muito dinheiro ou pena na rua", opcoes: ["'Os anjos deixaram uma mensagem' (penas)", "'Hoje é o meu dia de sorte' (moedas)", "'Alguém de cima está a ver-me'"] },
    { id: "t3_sc_m_14", texto: "Os 3 medos enraizados que me impedem de testar o famoso Tabuleiro Ouija (espíritos)", opcoes: ["Atrair uma entidade manhosa para casa", "As portas começarem a bater sozinhas", "Não querer acreditar que há vida depois da morte"] },
    { id: "t3_sc_m_15", texto: "As 3 curas portuguesas infalíveis para o famoso e temido 'Cobrão' (Herpes Zoster)", opcoes: ["Ir à benzedeira lá da terra", "Cortar a cabeça de uma cobra (lenda)", "Rezas antigas sussurradas"] },
    { id: "t3_sc_m_16", texto: "As 3 tradições de Santo António, São João ou São Pedro que eu adoro vivamente", opcoes: ["Saltar a fogueira sem me queimar", "Pôr o manjerico ao lado da janela", "Comer sardinhas num bairro apertado"] },
    { id: "t3_sc_m_17", texto: "Os 3 medos gigantes ao dormir numa casa muito antiga (tipo turismo rural em pedra)", opcoes: ["Ouvir os soalhos de madeira a ranger", "A temperatura baixar de repente na sala", "A televisão ligar e desligar sozinha"] },
    { id: "t3_sc_m_18", texto: "As 3 lendas sobre o mau-olhado em bebés e o que se faz para o afastar", opcoes: ["Um fiozinho vermelho contra a inveja", "Rezar o quebranto com azeite num prato", "O banho com chá de arruda"] },
    { id: "t3_sc_m_19", texto: "As 3 mentiras de religião e inferno que as catequistas usavam para assustar a malta", opcoes: ["'Deus está a ver as tuas más ações'", "'Se mentes, vais para o inferno a arder'", "'O anjo da guarda fica a chorar'"] },
    { id: "t3_sc_m_20", texto: "As 3 mezinhas ou feitiços amorosos que já ouvi amigas ou conhecidos a tentar aplicar", opcoes: ["A famosa amarração com cabelo", "Acender velas cor-de-rosa ao lado de fotografias", "Pedir ao Santo António casamenteiro"] }
  ],
  "sub_20_1": [ // Sorte e Azar
    { id: "t3_sc_s_01", texto: "As 3 rotinas obrigatórias (tiques) de sorte que eu aplico antes de um momento importante", opcoes: ["Vestir as minhas meias de sorte felizes", "Bater na madeira do móvel mais próximo", "Entrar na sala com o pé direito primeiro"] },
    { id: "t3_sc_s_02", texto: "As 3 coisas banais que me fariam dar meia volta a casa se visse a caminho de uma entrevista", opcoes: ["Um gato preto cruzar-se à minha frente", "Passar debaixo de uns andaimes de obras", "Ouvir uma coruja de dia"] },
    { id: "t3_sc_s_03", texto: "Os 3 pequenos azares que dão o mote perfeito para a frase 'O meu dia hoje está virado do avesso'", opcoes: ["Bater com a testa no armário", "A chave não rodar na fechadura de manhã", "O café derramar na t-shirt limpa"] },
    { id: "t3_sc_s_04", texto: "As 3 razões pelas quais juro nunca mais jogar em apostas desportivas ou no Euromilhões", opcoes: ["Perco sempre por um único número/golo", "Tenho muito azar ao jogo e sorte no amor", "O Estado é que ganha tudo no fim"] },
    { id: "t3_sc_s_05", texto: "As 3 prendas da natureza que me dão a certeza absoluta de que terei um dia espetacular", opcoes: ["Encontrar um trevo de 4 folhas", "Apanhar e soprar um dente-de-leão inteiro", "Uma joaninha pousar no meu braço"] },
    { id: "t3_sc_s_06", texto: "As 3 mentiras que digo para disfarçar quando algo me corre super mal no trabalho", opcoes: ["'Foi o Karma a bater'", "'Mercúrio está Retrógrado, a culpa não é minha'", "'Tinha de ser, os astros alinharam-se assim'"] },
    { id: "t3_sc_s_07", texto: "As 3 coisas que considero um sinal inequívoco de 'bruxaria' ou azar encomendado", opcoes: ["Eletrónica toda de casa avariar no mesmo dia", "Ondas de muito azar e dinheiro a faltar", "Objetos caírem sozinhos da estante"] },
    { id: "t3_sc_s_08", texto: "Os 3 maiores perigos e azares de celebrar qualquer coisa antecipadamente", opcoes: ["'O peixe morre pela boca'", "Gera azar instantâneo e tudo vai falhar", "Criar expectativas para depois bater no fundo"] },
    { id: "t3_sc_s_09", texto: "As 3 táticas absurdas que eu uso para não passar na passadeira ao mesmo tempo que um carro de funerais", opcoes: ["Abrandar muito o passo no passeio", "Fingir que recebo uma chamada e paro", "Fazer um V com os dedos das mãos às escondidas"] },
    { id: "t3_sc_s_10", texto: "Os 3 amuletos ou proteções esquisitas que andam guardados na minha carteira ou carro", opcoes: ["Uma fita do Nosso Senhor do Bonfim rasgada", "Uma moeda dourada chinesa furada", "Um terço pequenino"] },
    { id: "t3_sc_s_11", texto: "As 3 consequências drásticas se eu partir um espelho de vidro lá em casa hoje", opcoes: ["São os infames 7 anos de azar amoroso", "Tenho de atirar os cacos a um rio ou mar", "Alguém vai ter uma lesão grave"] },
    { id: "t3_sc_s_12", texto: "Os 3 tipos de números em que aposto no Totoloto e nunca saem de maneira nenhuma", opcoes: ["A minha data de nascimento", "As datas de nascimento da minha família", "O número 7 e o 13"] },
    { id: "t3_sc_s_13", texto: "As 3 respostas clássicas e evasivas que dou quando uma taróloga lê algo péssimo sobre mim", opcoes: ["'O futuro não está escrito em pedra'", "'As cartas são apenas avisos sugestivos'", "Levanto-me, não pago e vou-me embora"] },
    { id: "t3_sc_s_14", texto: "Os 3 motivos de orgulho que sinto quando a sorte me calha por uma vez na vida", opcoes: ["Fingir que foi puro mérito do meu trabalho", "Dizer 'finalmente os meus guias acordaram!'", "Postar imediatamente as boas notícias no Instagram"] },
    { id: "t3_sc_s_15", texto: "As 3 situações onde ter o 'sexto sentido' mais apurado já me livrou de um desastre", opcoes: ["Cancelar um plano porque deu-me um pressentimento mau", "Duvidar da amizade de alguém que se revelou tóxico", "Não ultrapassar o carro que a seguir travou a fundo"] },
    { id: "t3_sc_s_16", texto: "As 3 frases parvas com que me consolo a mim mesmo após ter sofrido uma enorme maré de azar", opcoes: ["'O que não mata, torna mais forte'", "'Deus dá as batalhas mais difíceis aos melhores'", "'Pronto, já não pode piorar mais do que isto'"] },
    { id: "t3_sc_s_17", texto: "Os 3 objetos virados ao contrário que eu juro que trazem más energias", opcoes: ["O pão virado de pernas para o ar na mesa", "Os sapatos cruzados no chão", "Copos com o bocal virado para cima no escorredor"] },
    { id: "t3_sc_s_18", texto: "As 3 razões pelas quais consulto os signos do Zodíaco todas as semanas", opcoes: ["Para culpar o cosmos pelos meus erros", "Ver se arranjo coragem para namorar um Escorpião", "Dar um pretexto parvo para o meu mau feitio"] },
    { id: "t3_sc_s_19", texto: "Os 3 acidentes ridículos que aconteceram sexta-feira dia 13 e eu juro não ser coincidência", opcoes: ["O ecrã do telemóvel partiu sozinho no bolso", "Tropecei e entornei água nas cuecas", "Perdi a chave do carro no trabalho"] },
    { id: "t3_sc_s_20", texto: "As 3 reações que o meu 'anjo da guarda' deve ter quando me vê fazer asneiras graves", opcoes: ["Pôr a mão na cara a suspirar fundo (Facepalm)", "Fazer as malas e pedir demissão", "Rir muito porque acha que eu mereço"] }
  ]
};
