import { PerguntaTop3 } from "@/types/catalogo";

export const top3_televisao_reality: Record<string, PerguntaTop3[]> = {
  "sub_28_0": [ // Cultura Televisiva
    { id: "t3_tv_c_01", texto: "Os 3 programas ou concursos antigos da televisão portuguesa de que mais tenho saudades", opcoes: ["O Preço Certo (versão antiga)", "Salve-se Quem Puder (Soltem a Parede)", "Apanha Se Puderes"] },
    { id: "t3_tv_c_02", texto: "As 3 séries portuguesas (ou novelas) que toda a gente viu e marcou uma geração", opcoes: ["Morangos com Açúcar", "Inspetor Max", "Médico de Família"] },
    { id: "t3_tv_c_03", texto: "As 3 piores partes de ter de ver televisão em canal aberto hoje em dia", opcoes: ["Os intervalos publicitários de 20 minutos", "A quantidade de chamadas de valor acrescentado (760...)", "Os programas da tarde que são todos iguais"] },
    { id: "t3_tv_c_04", texto: "Os 3 apresentadores ou figuras da TV que me põem um sorriso na cara", opcoes: ["Fernando Mendes ('Espetáaaaculo!')", "Manuel Luís Goucha", "Cristina Ferreira"] },
    { id: "t3_tv_c_05", texto: "As 3 desculpas parvas para ficar colado a ver a 'TeleVendas' (Televendas) de madrugada", opcoes: ["O gajo a cortar uma bota com a faca afiada", "Os aparelhos de abdominais que dão choques", "A máquina que varre e esfrega o chão deitada"] },
    { id: "t3_tv_c_06", texto: "As 3 reações exageradas que tenho ao ver o telejornal e as notícias", opcoes: ["Gritar com a televisão a discordar dos políticos", "Ficar deprimido com as tragédias do mundo", "Mudar de canal quando a bola (futebol) demora muito"] },
    { id: "t3_tv_c_07", texto: "As 3 novelas da noite que acompanhei tão fanaticamente que faltei a jantares", opcoes: ["Ninguém como Tu (quem matou o António?)", "Laços de Sangue (a Diana e a Inês)", "Gabriela (Novela Brasileira)"] },
    { id: "t3_tv_c_08", texto: "As 3 piores tendências das telenovelas portuguesas que se repetem sempre", opcoes: ["A vilã deitar alguém pelas escadas abaixo", "As pessoas nunca trancarem a porta de casa e entrarem", "Alguém acordar do coma no último episódio"] },
    { id: "t3_tv_c_09", texto: "Os 3 momentos da televisão ao vivo em Portugal que se tornaram memes inesquecíveis", opcoes: ["O Hernâni Carvalho a dar raspanetes épicos", "As quedas em direto nos programas da tarde", "Gafes da informação ('O senhor está a ser agressivo')"] },
    { id: "t3_tv_c_10", texto: "As 3 séries da Netflix que vi numa única noite e não dormi nada", opcoes: ["La Casa de Papel", "Stranger Things", "Squid Game (Round 6)"] },
    { id: "t3_tv_c_11", texto: "As 3 atitudes dos comentadores de TV que mais me dão vontade de partir o ecrã", opcoes: ["Falarem uns por cima dos outros aos berros", "Não deixarem o pivot (apresentador) falar", "Serem do contra apenas para fazer espetáculo"] },
    { id: "t3_tv_c_12", texto: "Os 3 desenhos animados da RTP2 que eu via de manhã enquanto bebia o leite", opcoes: ["Rua Sésamo", "As Pistas da Blue", "Bob o Construtor"] },
    { id: "t3_tv_c_13", texto: "As 3 mentiras de espetador que digo quando me apanham a ver programas rascas", opcoes: ["'Eu mudei de canal agora mesmo!'", "'Isto é só ruído de fundo, não estou a ver'", "'Estou a ver isto de forma irónica para me rir'"] },
    { id: "t3_tv_c_14", texto: "Os 3 canais de televisão por cabo (box) que me salvam em dias de tédio profundo", opcoes: ["Fox Comedy (ou Star Comedy)", "National Geographic", "Canal Hollywood"] },
    { id: "t3_tv_c_15", texto: "As 3 músicas de separador ou genérico de programas que assombram a minha cabeça", opcoes: ["O genérico do Telejornal", "A música pimba dos programas de Domingo à tarde", "A sirene das notícias de última hora (Breaking News)"] },
    { id: "t3_tv_c_16", texto: "As 3 piores frustrações de acompanhar uma série na televisão (sem ser streaming)", opcoes: ["Eles mudarem o horário sem avisar ninguém", "Repetirem o mesmo episódio 4 semanas seguidas", "O episódio acabar no momento do clímax"] },
    { id: "t3_tv_c_17", texto: "Os 3 programas desportivos que são autênticas peixeiradas e não falam de tática", opcoes: ["Prolongamento", "Trio D'Ataque", "MaisFutebol"] },
    { id: "t3_tv_c_18", texto: "As 3 razões pelas quais não abdico de ver a final do Festival da Eurovisão", opcoes: ["Para gozar com as roupas e músicas dos outros países", "Para me revoltar quando Portugal tem zero pontos", "A distribuição de pontos dos vizinhos nórdicos"] },
    { id: "t3_tv_c_19", texto: "Os 3 concursos de talentos em que o júri me irritava mais que os concorrentes", opcoes: ["Ídolos (os primeiros com o Manuel Moura dos Santos)", "Got Talent Portugal", "The Voice Portugal"] },
    { id: "t3_tv_c_20", texto: "As 3 reações quando as pessoas cancelam o serviço de TV por cabo e ficam só com internet", opcoes: ["'Como é que tu vives sem canais normais?'", "'Então e o Preço Certo, como é que vês?'", "'Faz muito bem, aquilo é só lixo'"] }
  ],
  "sub_28_1": [ // Reality Shows e Polémicas
    { id: "t3_tv_r_01", texto: "Os 3 melhores reality shows da televisão em Portugal que eu vi (mesmo às escondidas)", opcoes: ["Casa dos Segredos (Secret Story)", "Big Brother", "Casados à Primeira Vista"] },
    { id: "t3_tv_r_02", texto: "As 3 frases ou bordões icónicos que ficaram para a história dos reality shows tugas", opcoes: ["'Isto agora é bater punho!'", "'A minha vida é um livro aberto'", "'És um falso e um mentiroso!'"] },
    { id: "t3_tv_r_03", texto: "Os 3 segredos mais ridículos ou forçados da Casa dos Segredos que me lembro", opcoes: ["'Comi um morcego'", "'Tenho o dom da cura'", "'Estou grávido' (homem)"] },
    { id: "t3_tv_r_04", texto: "As 3 situações onde os concorrentes de reality shows perdem toda a dignidade", opcoes: ["Quando discutem por causa de quem lavou a loiça", "Nos romances forçados debaixo dos lençóis", "Nas provas de cultura geral e não sabem a capital de Portugal"] },
    { id: "t3_tv_r_05", texto: "As 3 atitudes dos comentadores de reality shows que me fariam desligar a TV", opcoes: ["Defenderem sempre o concorrente mais tóxico", "Fazerem bullying gratuito aos menos populares", "Gritarem uns com os outros e bater na mesa"] },
    { id: "t3_tv_r_06", texto: "Os 3 tipos de concorrentes que entram SEMPRE nestes programas", opcoes: ["O galã bombado de ginásio que acha que tem piada", "A que chora no primeiro dia porque tem saudades da mãe", "O vilão manipulador que fala mal nas costas"] },
    { id: "t3_tv_r_07", texto: "As 3 desculpas monumentais que as pessoas dão para justificar verem estes programas", opcoes: ["'Isto é uma experiência sociológica interessante'", "'Só vejo as galas de domingo para rir um bocado'", "'A minha avó/mãe deixou a TV ligada nisto'"] },
    { id: "t3_tv_r_08", texto: "As 3 provas ou desafios de líder mais sádicos que a produção lhes faz", opcoes: ["Ficar 24 horas sem dormir a segurar num botão", "Comer coisas nojentas (olhos de boi, insetos)", "Tomar banho de água gelada na rua no inverno"] },
    { id: "t3_tv_r_09", texto: "As 3 coisas que eu faria no primeiro dia se entrasse numa casa vigiada por câmaras", opcoes: ["Descobrir onde estão os ângulos mortos para me esconder", "Arranjar um aliado forte logo nas primeiras horas", "Avisar que ressono para ninguém se chatear"] },
    { id: "t3_tv_r_10", texto: "Os 3 maiores micos em direto nas Galas de Domingo à noite", opcoes: ["A Teresa Guilherme ou Cláudio Ramos enganarem-se no nome", "Um concorrente tropeçar no vestido nas escadas", "A família cá fora começar aos berros com o apresentador"] },
    { id: "t3_tv_r_11", texto: "As 3 razões pela qual eu seria expulso de um Reality Show na primeira semana", opcoes: ["Ter um feitio horrível de manhã e mandar alguém à fava", "Recusar-me a participar nas danças parvas da piscina", "Dizer as verdades na cara da pessoa errada"] },
    { id: "t3_tv_r_12", texto: "Os 3 reality shows de canais americanos/estrangeiros que são viciantes (Guilty Pleasures)", opcoes: ["Kardashians", "Too Hot to Handle", "Hell's Kitchen"] },
    { id: "t3_tv_r_13", texto: "As 3 reações às curvas e choradeiras no 'Confessionário'", opcoes: ["'Isto é tudo lágrimas de crocodilo'", "'A produção mandou-o(a) chorar para dar audiências'", "'Que drama por causa de um pacote de massa'"] },
    { id: "t3_tv_r_14", texto: "Os 3 motivos que levam as pessoas a ligar e gastar dinheiro para votar", opcoes: ["O ódio profundo por um concorrente específico", "As avozinhas que adoram um casalinho", "Achar que o seu voto faz mesmo diferença (ilusão)"] },
    { id: "t3_tv_r_15", texto: "As 3 reações quando os casais de Reality Shows se separam mal saem da casa", opcoes: ["'Que choque... Ninguém estava à espera' (Sarcasmo)", "'Foi só para as revistas e capas'", "'Vão acabar juntos noutro programa qualquer'"] },
    { id: "t3_tv_r_16", texto: "Os 3 programas de remodelar casas (tipo Querido Mudei a Casa) que mais vejo na SIC Mulher", opcoes: ["Irmãos à Obra (Property Brothers)", "Love It or List It", "Querido Mudei a Casa (o original)"] },
    { id: "t3_tv_r_17", texto: "As 3 cenas constrangedoras no 'Casados à Primeira Vista' que dão vergonha de ver", opcoes: ["Quando um deles acha o outro feio no altar", "As discussões na lua de mel em tronco nu", "Os especialistas a tentarem explicar o que não tem explicação"] },
    { id: "t3_tv_r_18", texto: "Os 3 reality shows focados em comida ou culinária (Pesadelo na Cozinha) que geram stress", opcoes: ["O chef Ramsay a berrar 'IT'S RAW!'", "Os concorrentes suarem para cima dos pratos", "As cozinhas cheias de baratas escondidas"] },
    { id: "t3_tv_r_19", texto: "As 3 punições mais duras aplicadas pela 'Voz' por incumprimento de regras", opcoes: ["Retirar todo o tabaco da casa", "Ficar sem água quente durante uma semana", "Nomeação direta para expulsão"] },
    { id: "t3_tv_r_20", texto: "As 3 conclusões óbvias no fim de qualquer reality show português", opcoes: ["Ganha sempre o rapaz humilde ou a rapariga sofrida", "Os que fizeram o programa todo são expulsos na semifinal", "Passado 1 mês ninguém se lembra de quem ganhou"] }
  ]
};
