import { PerguntaTermometro } from "@/types/catalogo";

export const termometro_desastres_gafes: Record<string, PerguntaTermometro[]> = {
  "sub_26_0": [ // Em Público
    { id: "tm_dg_p_01", texto: "Numa escala de 0 a 100%, o quão intenso é o meu desejo de que a terra me engula quando tropeço num passeio invisível no meio da rua?", min: 0, max: 100, unidade: "%" },
    { id: "tm_dg_p_02", texto: "Quantas vezes por ano aceno de volta a alguém entusiasticamente na rua, só para perceber tarde demais que afinal a pessoa estava a cumprimentar a pessoa atrás de mim?", min: 0, max: 20, unidade: "Vezes" },
    { id: "tm_dg_p_03", texto: "Qual o número exato de vezes que atendo o telemóvel falso encostado à cara apenas para evitar cruzar-me com um conhecido ou ex na rua?", min: 0, max: 50, unidade: "Vezes" },
    { id: "tm_dg_p_04", texto: "A que percentagem (0-100%) da culpa e parvoíce eu me desfaço quando pergunto 'Como te chamas?' e a pessoa já tinha dito o seu nome cinco segundos antes?", min: 0, max: 100, unidade: "%" },
    { id: "tm_dg_p_05", texto: "Quantas portas de loja que dizem explicitamente 'PUXE' em letras grandes na vitrine eu esmago ativamente e empurro com toda a força?", min: 1, max: 30, unidade: "Portas" },
    { id: "tm_dg_p_06", texto: "Numa escala de 0 a 10, quão envergonhado(a) e cego fico quando percebo que andei uma hora a falar com alface nos dentes num evento público?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_dg_p_07", texto: "Quantos risos nervosos e asnos e estridentes soltei no exato momento menos apropriado de um velório ou de uma reprimenda/reunião séria?", min: 0, max: 10, unidade: "Risos Fora de Hora" },
    { id: "tm_dg_p_08", texto: "Qual a probabilidade (0-100%) de eu dizer 'Bom apetite para si também!' no cinema ao rapaz do bilhete de caixa e às pipocas doces?", min: 0, max: 100, unidade: "%" },
    { id: "tm_dg_p_09", texto: "Quantas vezes dei a minha famosa gafe no Whatsapp de enviar o print (captura de ecrã) de uma conversa à mesmíssima pessoa com quem estou a tentar coscuvilhar?", min: 0, max: 5, unidade: "Gafes" },
    { id: "tm_dg_p_10", texto: "Numa escala de 0 a 10, o quão alto grita o silêncio quando a minha barriga faz um enorme ruído do género monstro na sala de espera silenciosa de um médico?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_dg_p_11", texto: "Quantos cêntimos no chão caídos na caixa do supermercado seriam suficientes para me obrigarem ao ato vexatório de pedir desculpa e agachar a rabo no ar para apanhar da fila?", min: 1, max: 200, unidade: "Cêntimos" },
    { id: "tm_dg_p_12", texto: "Qual a percentagem (0-100%) de eu chamar 'mãe' à professora e ficar mortificado na vida escolar toda das aulas até de noite?", min: 0, max: 100, unidade: "%" },
    { id: "tm_dg_p_13", texto: "Quantas vezes por acidente entrei ativamente e abri a maçaneta na porta direita dum carro banal e estacionado à minha espera achando piamente e sem desvios que era o Uber pedido no telefone?", min: 0, max: 10, unidade: "Vezes" },
    { id: "tm_dg_p_14", texto: "Numa escala de 0 a 10, quão tenso e aflitivo é para o meu suor disfarçar a minha reação de aceitação de presente e sorriso falso por prenda trocada de Natal que não pedi?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_dg_p_15", texto: "Quantos alarmes dos pilares de lojas eu accionei (sem os furtos obviamente) pelas caixas do multibanco no pânico de pensar logo que todos os utentes ou as gentes de lá dirão e pensarão: 'Olhem o Ladrão!'?", min: 0, max: 15, unidade: "Vezes" },
    { id: "tm_dg_p_16", texto: "Qual a percentagem (0-100%) da gaguez ansiosa do disfarço em dar nomes estroinos às colegas que na vida se me varrem no instante das saudações nas praças onde não nos cruzamos de sempre?", min: 0, max: 100, unidade: "%" },
    { id: "tm_dg_p_17", texto: "Quantas escadas, desníveis e pisos sujos eu limpei pelas vias na vida, com as costas do corpo estendidas nas escorregadelas públicas dos azulejos e calçadas perante dezenas de estranhos mudos?", min: 0, max: 20, unidade: "Quedas de Rabo" },
    { id: "tm_dg_p_18", texto: "Numa escala de 0 a 10, quão forte eu sou de não deitar choro em apanhar repreensões públicas e injustas a vozes em filas perante desconhecidos a meter o bedelho nos esticões da via ou trânsito do caos?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_dg_p_19", texto: "Quantas gafes extremas nas mensagens automáticas trocadas na internet de beijos carinhosos e amores eu calhei remeter erradamente no grupo ou chat com as chefias de topo empresariais ou malta do RH no trabalho?", min: 0, max: 5, unidade: "Mensagens" },
    { id: "tm_dg_p_20", texto: "Qual a probabilidade e o risco absoluto (0-100%) de ser descoberto por andar com as calças à mostra (braguilha aberta e rasgada no fecho inferior nas idas dos jantares/conferências longos perante 50 clientes da minha sala)?", min: 0, max: 100, unidade: "%" }
  ],
  "sub_26_1": [ // Acidentes Pessoais
    { id: "tm_dg_a_01", texto: "Quantas pancadas com o meu dedo pequenino (mindinho do pé) numa quina ou sofá dei neste ano na minha casa?", min: 0, max: 30, unidade: "Pancadas no Mindinho" },
    { id: "tm_dg_a_02", texto: "Numa escala de 0 a 100%, qual o peso das dores atrozes e dos gemidos estáticos ao bater forte de nuca ao erguer nas quinas e tábuas cruas dos armários da cozinha nos tetos altos?", min: 0, max: 100, unidade: "%" },
    { id: "tm_dg_a_03", texto: "Quantos copos caros e frascos finos jurei partir este semestre apenas porque tenho o terrível instinto desastrado ou destreza nula nas garras escorregadias do manuseio nos dedos à pressa?", min: 0, max: 20, unidade: "Copos/Frascos" },
    { id: "tm_dg_a_04", texto: "Até a que nível de calor de bolhas escaldantes ou graus térmicos no pires do fogão costumo verificar a olho nu na mão se as brasas acenderam a frigideira para atirar os ovos e óleo e espirrar salpicos queimando a pele?", min: 40, max: 100, unidade: "Graus" },
    { id: "tm_dg_a_05", texto: "Qual a percentagem e destreza falhada (0-100%) em reverter sem pisar em dores cruéis os mal fadados legos da prateleira na passadeira da cama noturna com a pontinha sensível descalça e calcanhar de calo no escuro cerrado da divisão nas sestas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_a_06", texto: "Quantas manchas nos bolsos das calças atesto (ou marcas avermelhadas nas calças), devido à inclinação súbita do pingo final, por derramar sem cuidado ou de forma brutal líquidos ou café a conversar gesticulando muito com mãos no estaminé local?", min: 0, max: 30, unidade: "Manchas de Café" },
    { id: "tm_sc_a_07", texto: "Numa escala de 0 a 10, quão propício a estalar os ecrãs sensíveis dos vidros de smartphones nos bolsos, desastres de sanitas caindo ou balcões ou nas vias rápidas ao escorregar da perna se reflete a minha vida em euros sem seguro à vista?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_a_08", texto: "Quantas vezes dou por mim, ao levantar, a rasgar o fecho de laço com t-shirts (e prender e encravar fatal e brutalmente no fecho-éclair e tentar cortar aos dentes para desenrascar as malhas que ali prenderam o dia em ansiedade de desespero e dores)?", min: 0, max: 15, unidade: "Fechos Encravados" },
    { id: "tm_sc_a_09", texto: "Qual a percentagem (0-100%) de vergonha oculta na probabilidade real em que sou vitimado a trincar as maçãs com dentada dupla, ao mesmo encalço apanhar ativamente a carne mole dos cantos interiores da boca e língua a escorrer e sangrar calado o gosto acético nas papilas por burrice bruta mastigatória?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_a_10", texto: "Quantos sustos estúpidos nos degraus por falhar apenas 'esse derradeiro e pequeno' patamar do fundo com o calcanhar das pernas e julgar que de facto eu perdi a sustentação na caixa das varas ao ver-me sem asa e em queda do abismo livre pelo passeio liso e calcetado?", min: 0, max: 50, unidade: "Falhas de Degraus" },
    { id: "tm_sc_a_11", texto: "Numa escala de 0 a 10, a quão estúpida inércia corporal adormeço por completo os membros e a minha mão pende num membro balouçante e choco inerte após dormitar sobre eles uma meia horinha em curvas estranhas sobre as cruzetas dos sofás encorpados na via?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_a_12", texto: "Quantas tesouradas cortantes no banho (depilações alheias, giletes rombas) nos calcanhares da junta das tíbias jurei fazer no ano porque passo o fio afiado no encalço rápido em cinco segundos ao sol de água a escaldar nas limpezas?", min: 0, max: 30, unidade: "Cortes (Gilete)" },
    { id: "tm_sc_a_13", texto: "Qual a probabilidade cega e brutal (0-100%) em desatar ao choro infantil na ferida mínima nas papéis recém sacados das impressoras das papelarias ou nas resmas folheadas a ponta da navalha das arestas de cadernos folhosos que traçam um risco que arde até nas alma de picadas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_a_14", texto: "Quantas puxadas abruptas ou 'torcicolos matinais esticadores', das espinhas atadas na inércia crua nos ossos das costas que me impedem a virar da cara 3 dias na lide rodoviária de um vulgar espreguiçar em mau jeito das narinas eu crio por me achar do elástico de ginasta?", min: 0, max: 10, unidade: "Torcicolos" },
    { id: "tm_sc_a_15", texto: "Numa escala de 0 a 10, que patamar fóbico assume as minhas fugas dos animais e voadores com os meus calções nos pés enleados e com o esguicho regador aquático apontado e ligado em automático virado na frontaria das calças e sapatos a molhar a farpela do pijama sem nexo?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_a_16", texto: "Quantas maçanetas maçadoras de porta me engataram por completo as mangas ou as correias das mochilas e sacos pela alheta fazendo-me estancar recuado subitamente ou dar safanão duro das quedas no chão por a minha fúria apressada dar aso à puxada seca no trinco e da calça entalada e rota de seguida nas abas do bolso alheio?", min: 0, max: 20, unidade: "Maçanetas Assassinas" },
    { id: "tm_sc_a_17", texto: "Qual a percentagem da cegueira em pânico e a aflição por entrar no banho sujo e de esquecer que pousei a totalidade do vestuário e óculos com a toalha no quarto dos pais, levando ao deslize nos charcos no mosaico húmido para alcançar e fugir cego aos tropeções mortíferos em perna alçada na sala e sem ar?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_a_18", texto: "Quantas nódoas escuras, esmeraldas, roxas pisadas eu costumo envergar em simultâneo nos musculos, coxas e nos pulsos que nunca, mas absolutamente nunca sei dizer de onde saíram as cacetadas da dor nas amnésias noturnas nas gavetas de aberturas rústicas nos vãos de corredores e paredes na penumbra da vida sem dar do seu impacto à vez?", min: 0, max: 15, unidade: "Nódoas Negras Misteriosas" },
    { id: "tm_sc_a_19", texto: "Numa escala de 0 a 10, quão constrangedor e com a respiração em asma sou eu ao tentar de trincos abertos (dentes trincados nas cascas e nós em sacos plásticos ou fios grossos de atilhos nos presentes grossos de sacos encanitados das sandes no mato) em vez das lâminas da faca, dando cabo com lixamento esmifrado e dor incisiva em todos os meus esmaltes brancos até as finas gengivas de força desbocada sangrar aos dentes em esforço de ar comprimido parvo em esforço da face inútil e perdedor bruto?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_a_20", texto: "Qual a quantidade exata de chapéus de chuva dos bons ou normais desfeitos em molas frouxas espiraladas nos ventos agressivos dos furações de chuveiros e as molas finas rasgadas ao avesso virados com cara ridícula lutando feroz e patética figura pública no passadiço ou chuva nas pernas e da água fria com braços atados agarrados na base nas marés e poças no empurrão na rua dos pinheiros perante a humilhação do tempo?", min: 0, max: 20, unidade: "Chapéus Destruídos" }
  ]
};
