import { PerguntaTermometro } from "@/types/catalogo";

export const termometro_humor_comedia: Record<string, PerguntaTermometro[]> = {
  "sub_30_0": [ // Piadas e Risos
    { id: "tm_hc_p_01", texto: "Numa escala de 0 a 10, quão desajustado, negro e cruel eu considero, de portas adentro, ser a força natural do meu lado de humor sádico no grupo?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_p_02", texto: "Quantas gargalhadas incontroláveis e fora do compasso sou forçado a reprimir nos piores lugares e eventos inaceitáveis (como missas, palestras e velórios sérios)?", min: 0, max: 50, unidade: "Gargalhadas Proibidas" },
    { id: "tm_hc_p_03", texto: "Qual a percentagem (0-100%) da minha alegria matinal que descende de soltar piadas secas horríveis às custas do sofrimento leve de um amigo trambolhar nos degraus de uma calçada?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_04", texto: "Quantos segundos consigo escutar as minhas próprias anedotas em construção sem que eu próprio desate a rir e estrague o punchline todo antes dos ouvintes terem a deixa?", min: 1, max: 30, unidade: "Segundos" },
    { id: "tm_hc_p_05", texto: "Numa escala de 0 a 100%, qual o peso trágico do silêncio ensurdecedor que abafa a sala se eu atiro um comentário que julgo cómico mas as fisionomias presentes julgam horrível?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_06", texto: "Quantas quedas aparatosas e humilhantes em programas do YouTube/Apanhados consumo eu semanalmente a cuspir o chá pelas narinas em risos e cãibras nos maxilares?", min: 0, max: 100, unidade: "Vídeos" },
    { id: "tm_hc_p_07", texto: "A que percentagem (0-100%) aplico uma dose abusiva do mais alto sarcasmo como um autêntico filtro social base com colegas e clientes que fazem asneiras triviais nas rotinas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_08", texto: "Quantas histórias em tom de stand-up exageradas por condimentos fantásticos eu invento num café a sós por mês para garantir o estrelato momentâneo da comédia do grupo em redor da mesa redonda?", min: 0, max: 30, unidade: "Histórias Exageradas" },
    { id: "tm_hc_p_09", texto: "Numa escala de 0 a 10, de que maneira julgo o embaraço interno das pessoas alheias que recitam jargões de velhos 'Tem as barbas longas' a atirar charme nas velhas piadas de papagaio no tasco?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_p_10", texto: "Quantos 'choros e pinguinhas de líquido das micções' derivado ao rir excessivo em cólicas gástricas me sucederam a frente dos pares nestes tempos recentes da vida?", min: 0, max: 20, unidade: "Acidentes Físicos" },
    { id: "tm_hc_p_11", texto: "Qual a probabilidade e o risco (0-100%) da minha ironia cínica e sagaz de respostas não ser perfeitamente detetada nem lida pelo interlocutor simplório ou colega chato?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_12", texto: "Quantas comédias da sétima arte de clássicos 'enlatados' ou 'gags' baratos americanos rolam de escape no meu ecrã para lavar os neurónios entupidos e limpar um dia aborrecido e negro?", min: 0, max: 50, unidade: "Comédias" },
    { id: "tm_hc_p_13", texto: "Numa escala de 0 a 10, o quão propício eu estou de babar por completo as palavras cruzadas com a voz se alguém acidentalmente borrifar espirros a meio de um sermão e eu perder o tino?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_p_14", texto: "Quantos anos duram certas rábulas internas e piadas crípticas num núcleo de amizade fechado onde o contexto não atinge mais ninguém senão aquelas exatas cinco pessoas que riem disso em loop?", min: 1, max: 30, unidade: "Anos" },
    { id: "tm_hc_p_15", texto: "Qual a percentagem brutal e inata das coisas foleiras das telenovelas ou tricas de discussões parvas do supermercado onde retiro em silêncio uma hilariante e cómica visão e novela particular rindo a sós?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_16", texto: "Quantas e estonteantes desculpas enfio ao longo dos chás para camuflar um ronco alto das minhas mucosas bucais em que finjo sempre uma tosse esquisita após atirar risadas foleiras estridentes do nada na rua?", min: 0, max: 50, unidade: "Tosses Falsas" },
    { id: "tm_hc_p_17", texto: "Numa escala de 0 a 100%, em que ponto se avalia a insuportável azia alheia pelas bocas clássicas dos idosos de fato como a famigerada 'Se fosse um cão trincava-te!' ao perder objetos nas vistas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_18", texto: "Quantos episódios aclamados do Ricardo Araújo Pereira, Bruno Nogueira ou podcasts satíricos consumi religiosamente a bater a perna por vício cego nestas semanas duras de labuta ou de idas e vindas de transporte?", min: 0, max: 100, unidade: "Episódios de Comédia" },
    { id: "tm_hc_p_19", texto: "Qual a probabilidade fóbica e aterrante (0-100%) da boca dos outros de cuspir na mesa fluidos nas risadas explosivas na refeição por ter atirado uma pérola irónica durante o trincar das batatas e o engolir de goles das colas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_p_20", texto: "Numa escala de 0 a 10, quão exausto de sorrisos plásticos e falsos me deixam na alma aquelas trocas forçadas dos colegas da manhã no elevador: 'Só nos safamos nisto à sexta-feira!' com careta sorridente do inferno?", min: 0, max: 10, unidade: "Escala" }
  ],
  "sub_30_1": [ // Memes e Tangas
    { id: "tm_hc_m_01", texto: "Quantas imagens, montagens, trends e memes da treta espalho compulsivamente pelos canais do WhatsApp para o telemóvel dos outros com zero nexo diário num só dia preenchido e tediado no meu posto?", min: 0, max: 100, unidade: "Memes/Dia" },
    { id: "tm_hc_m_02", texto: "Numa escala de 0 a 100%, qual o vício em enviar figurinhas ou 'stickers' agressivos de pessoas a chorar grotescamente a amigos no auge duma desgraça insignificante em que recuso a pura digitação verbal lenta do teclado?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_m_03", texto: "Quantas tangas bem assentes de invenções mentirosas mas credíveis eu prego no descaramento absoluto a caloiros de café só para lhes detetar as caras de choque nos olhos até soltar a verdade cá para a luz com rir de troça?", min: 0, max: 50, unidade: "Mentiras Pregonadas" },
    { id: "tm_hc_m_04", texto: "Qual a percentagem irónica de reações e respostas sarcásticas como o 'Descobriste a Pólvora Sherloque' atiradas sem remorsos e pingo de emoção para calar pessoas de palas de quem não trago nem porto paciências em discursos circulares?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_m_05", texto: "Quantas fotos bizarras sob distorção do meu focinho em grandes ângulos de papadas caídas eu capto, seleciono do filtro da câmara suja frontal, e remeto para o arquivo do parceiro na intimidade na parvoíce das noites do pijama da paz?", min: 0, max: 200, unidade: "Selfies Feias" },
    { id: "tm_hc_m_06", texto: "Numa escala de 0 a 10, quão nostálgica assumo ser na alma as épocas de 'Rickrolling' (trolhas nos links) e do cão das pintas, com saudosismo a roer nas saudades da web nos primórdios onde os foros da parvoíce do trolanço reinavam nos sites cegos?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_m_07", texto: "Quantas lendas do folclore urbano, factos aleatórios de teorias ricas de chapéus alumínio dos ET's invento ou repito por escárnio aos familiares em deboche cru na ignorância por veres se caem que nem uns tolos incautos nas festividades solenes?", min: 0, max: 20, unidade: "Conspirações Falsas" },
    { id: "tm_hc_m_08", texto: "Qual a probabilidade (0-100%) da minha reaçao mortífera a quem responde a um meme top de novidade viral que remeti com muito entusiasmo ser atirado apenas para mim a frio com o seco e avassalador insulto de 'Esse formato arcaico já tem barbas brancas'? ", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_m_09", texto: "Quantos disparates ou imitações baratas aos berros em inglês de cinema atirei focado em frente a um espelho solitário e polido lavando lá os dentes na sanita fingindo nas pausas a conquista do Óscar perante plateias das palmas esmagadoras dos estádios irreais?", min: 0, max: 50, unidade: "Discursos Solitários" },
    { id: "tm_hc_m_10", texto: "Numa escala de 0 a 10, o quão fútil ou de risco caio por terra nos engodos e 'April Fools' parvos atirados na rede do Inimigo Público que por dois ou quatro minutos me tiram do sério com a farsa das notícias estapafúrdias assumindo ser verídico e espalhando a farsa grossa e alarvemente à ceia?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_m_11", texto: "Quantas das minhas alcunhas enigmáticas de pseudónimos disparatados fornecidas ativamente sem pudor algum em chamadas e trocas das listagens dos pedidos das lojas se contam nos cardápios onde as bebidas surgem sob as chancelas das brincadeiras tipo: Lorde, Batman ou Senhor Barão das Terras dos Cafés escuros?", min: 0, max: 15, unidade: "Nomes Falsos" },
    { id: "tm_hc_m_12", texto: "Qual a percentagem assidua e certeira em decibéis elevados (0-100%) da irritação interna das minhas ventas aos trocadilhos e trocas foleiras nos churrascos e petiscos solenes na lauda dos avôs no estilo das adivinhas dos pavões nos ramos sem nexo perante a cerveja dos copos fartos no churrasco de banha das mesas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_m_13", texto: "Quantos percalços, pegas de falsos alarmes ou roubos furtivos de chaves alheias dos amigos escondidos e calados meti em campo em pleno jantar do tédio em silêncios forçados só pela gáudio reles e rasca de lhes estragar as pilhas mentais para o riso dos tontos no gozo em grupo das cadeiras na farra barata?", min: 0, max: 30, unidade: "Pegas Práticas" },
    { id: "tm_hc_m_14", texto: "Numa escala de 0 a 10, quão avesso eu decerto me ponho a certas modas perigosas das chamadas 'trends' na internet dos baldes frios nas carolas geladas com neve dura nos anos gloriosos da internet em que comia em seco colheres e enxurradas de canelas das desgraças de tosse aguda nos ares das amigdalas inflamadas no chão dos banheiros húmidos do medo?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_m_15", texto: "Quantas respostas irónicas atiro no sarcasmo por impulso ou inércia da boca no cérebro a alguém que na sala ousa o questionar básico 'Estás aqui e vieste? Ou o que fazes de momento?' soltando em gáudio 'A desatar fios às poeiras do oxigénio' ou algo em calhas e descontextualizado para calar na ignorância o sujeito do nada?", min: 0, max: 100, unidade: "Respostas Sarcásticas" },
    { id: "tm_hc_m_16", texto: "Qual a probabilidade (0-100%) duma desculpa esfarrapada, irrealística por pura troça dos céus saltar com estrondo para safar uma gafe enorme ao cair do prato esbardalhado no lixo 'Cientificamente testava no limiar a gravidade Newtoniana em ação sem rédeas das molas do polegar esquerdo no ato divino de queda vertical e natural'? ", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_m_17", texto: "Quantos episódios a transbordar da foleirice nobre das lendas víricas da lide tuga e clássica da TV (Tonis azeiteiros e chamas do fogareu berrado nas chamas) repousam gravados no córtex frontal por eternidade vital em caixas da mente onde partilho nos almoços recitando correntemente de lábios as tricas e cenas folclóricas com os do sangue na sopa de caldo forte e lido e sabido em grupo nos ritos anuais?", min: 0, max: 50, unidade: "Vídeos Virais Decorados" },
    { id: "tm_hc_m_18", texto: "Numa escala de 0 a 10, na linha da parvoíce noturna sem redes de cérebro após as ressacas diurnas ou turnos lixados da jorna no balcão escuro e gélido de casa em que os neurónios cedem ao lixo da rede de ler os posts de tios irados num face nas notícias absurdas ou placas erróneas da montra falhada?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_hc_m_19", texto: "Qual a percentagem total de eu continuar a chular com frieza nas respostas e agravar as despesas irreais duma tanga e aldrabice na sala após uma das presenças do núcleo estragar do nexo tudo revelando ser tretas ao lesado onde na vez disso afundo mais o dedo com seriedade de chumbo de funeral não vergando o ego para a peripécia e o gozo supremo prolongado a mil no peito e na alma negra e pura do gozo alheio escondido num só pingo do copo vazio?", min: 0, max: 100, unidade: "%" },
    { id: "tm_hc_m_20", texto: "A que descarada e pura percentagem (0-100%) da rotina social envio aos canais atestados em 'replys' das partilhas foleiras alheias, os ícones ranhosos e emojis a piscarem reações de 'Ahah' em seca pura da lide forçada nas amizades de telemóvel quando de facto trago ao rosto nos traços físicos a plena, vazia, imóvel, neutra e cínica cara de um cão exausto de sofá ao sol morno da manhã fechada?", min: 0, max: 100, unidade: "%" }
  ]
};
