import { PerguntaTermometro } from "@/types/catalogo";

export const termometro_livros_leitura: Record<string, PerguntaTermometro[]> = {
  "sub_23_0": [ // Hábitos de Leitor
    { id: "tm_ll_h_01", texto: "Quantos livros novos admito ter na minha prateleira (Pilha da Vergonha) que eu comprei no impulso mas ainda não consegui arranjar tempo de abrir e ler uma única página?", min: 0, max: 100, unidade: "Livros não lidos" },
    { id: "tm_ll_h_02", texto: "Numa escala de 0 a 100%, quão criminoso(a) e terrível eu me sinto ao quebrar ou dobrar ativamente o cantinho da página do livro em vez de caçar pela mesa fora o devido marcador apropriado?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_h_03", texto: "Qual o limite de páginas diárias consecutivas num pico do clímax do livro que eu aguento devorar e 'comer' à noite na cama antes de a vista doer e a capa desabar a pique de cansaço em cima da testa ou do nariz?", min: 10, max: 400, unidade: "Páginas/Noite" },
    { id: "tm_ll_h_04", texto: "Quantas e variadíssimas posições ergonómicas contorcidas do meu corpo eu testo, da barriga para as costas até de pernas para o ar, num só capítulo a ver se arranjo um bom suporte sem as mãos darem caimbras fortes na cama?", min: 1, max: 15, unidade: "Posições" },
    { id: "tm_ll_h_05", texto: "Numa escala de 0 a 10, o quão rápido eu condeno, abandono e viro as costas à leitura da história nos inícios de capítulos se um protagonista não agradar à minha mente sensível no prazo de um ápice ou de escrita super seca?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_h_06", texto: "Quantos euros calculo que deixo escorrer compulsivamente (comprar) na euforia cultural que ataca durante a visita a um grande certame comercial que é a popular e lotada Feira do Livro de rua ou bancas dos alfarrabistas nas calçadas?", min: 10, max: 300, unidade: "Euros Feira do Livro" },
    { id: "tm_ll_h_07", texto: "Qual a percentagem brutal e arrebatadora de 'Ressaca Literária' (dias de depressão sem rumo ou pegar noutro título) que ataca na sequência dolorosa de engolir compulsivamente o último livro avassalador daquela saga que era amada?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_h_08", texto: "Quantos meses arrasto eu consecutivamente o ato de devolução ou cedência de obras pedidas/emprestadas que guardo ativamente a ganhar cheiros alheios lá na prateleira esquecida até a minha memória falhar de tal promessa aos outros na posse e ficar comigo?", min: 0, max: 24, unidade: "Meses" },
    { id: "tm_ll_h_09", texto: "Numa escala de 0 a 10, o quão feroz o meu zelo julgador ferve face ao clássico erro tipográfico hediondo nas margens, à desadequação da capa dos ecrãs modernos ou aos erros estúpidos de sintaxe gráfica visíveis aos meus olhos analíticos em obras do mercado caro a cheirar a gráfica fresca?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_h_10", texto: "Em que percentagem escorregadia sou propenso à ilusão visual das críticas literárias (ex: BookToks e Youtubers a dar notas e choro dramático forçado para a câmera do aparelho aos 3 prantos) na minha opção de gastar notas nas montras reais físicas pelo autor recomendado às moscas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_h_11", texto: "A que idade dos bancos liceais é que encarnei ativamente no meu orgulho intelectual falso a mentira de gabar aos cantos que entendia profundamente o enredo chato, críptico e entediante dos cânones nacionais (Maias e Lusíadas na mesa redonda)?", min: 12, max: 25, unidade: "Anos de Idade" },
    { id: "tm_ll_h_12", texto: "Quantas e inusitadas vezes sinto aquele vácuo do esquecimento onde subo e recuo ativamente à casa inicial as cinco longas páginas num volume físico apenas pelo facto de as ter desbravado visualmente na plenitude enquanto a cabeça ia a debater os ovos e fofocas no supermercado da vida?", min: 0, max: 30, unidade: "Vezes de Recuo" },
    { id: "tm_ll_h_13", texto: "Numa escala de 0 a 10, qual o meu desespero irado, a ranger de esmaltes nos caninos orais, a suportar o colega ou ente do lar que em vez de ficar calado entra nas falas no meio dos ápices ruidosos quebra-contextos a perturbar a via do meu imaginário visual em estado letárgico sagrado a sós na almofada?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_h_14", texto: "Quantos marcadores de luxos a preceito comprei nas viagens na vida mas asneiro usando na vez disso ativamente um papel comercial amarrotado vindo da tasca, bilhete do autocarro furado ou casca rasgada do Pingo Doce para segurar onde a página do capítulo jazia morta do dia anterior?", min: 0, max: 50, unidade: "Marcadores Desperdiçados" },
    { id: "tm_ll_h_15", texto: "Em percentagem, se não estiver enganado, quanto o meu coração bate em pânico da falta de rede à leitura nos formatos ditos digitais puros (nas chapas Kindle) pelas quebras nos piores clímax da narrativa a seco com o aparelho liso das descargas a cair aos zero ecrãs?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_h_16", texto: "Quantas vezes a tentar posar de 'culto' fotografei os meus almoços com o prato bonito no enquadramento foleiro das paletas de café das esplanadas e com a capa da capa virada à janela focada a 100% nas captações em ângulo com as minhas pernas?", min: 0, max: 50, unidade: "Fotos Falsas" },
    { id: "tm_ll_h_17", texto: "Numa escala de 0 a 10, quão rígido é meu cérebro a adotar ordens puramente estéticas a reger e a limpar, pelo alfabeto métrico puro a régua e por escalas do Pantone visual de tons coloridos das abas ao invés de ordenar o enquadramento pelas sagas e narrativas originais da casa?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_h_18", texto: "Até ao limite do exaustivo ou da seca monumental do verbo das obras clássicas, quantas resenhas em formato de texto sumário acedi via canais dos googles apenas e somente para não falhar o ponto dos contextos do final antes da folha da morte do autor chato ao meio de um compromisso de grupo escolar / do Clube da Leitura forçado?", min: 0, max: 100, unidade: "Resumos Lidos" },
    { id: "tm_ll_h_19", texto: "A que percentagem (0-100%) da minha veia 'Avarinha' (Tio Patinhas) culpo os aumentos vertiginosos avulsos nos preçários da capa ou portes abusivos e inflacionados editoriais pela estante não albergar nem mais calhamaços de sonho das bancas lisboetas na parede no meu T0 humilde de vida adulta?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_h_20", texto: "Quantos grossos e abismais volumes (número de livros grossos) a carregar mais de 600 laudas / páginas de grossura visual aprecio ou suporto pegar com a fraqueza dos ossos da minha munheca de pulso nas férias ao sol do estendal da areia grossa na praia dos longos banhos ao invés do tijolo de água móvel e prático?", min: 0, max: 10, unidade: "Calhamaços Tolereis" }
  ],
  "sub_23_1": [ // Histórias e Personagens
    { id: "tm_ll_c_01", texto: "Quantas noites passadas aos soluços ranhosos eu investi a derramar mágoa na almofada perante os funerais e perdas mortíferas e injustiçadas das minhas acarinhadas vozes do enredo traído sem piedade pelo autor sádico nas linhas da saga clássica (ex. do Sirius, Dobby ou até do Stark nas cadeiras reais de ferro aos pedaços)?", min: 0, max: 50, unidade: "Noites Chorosas" },
    { id: "tm_ll_c_02", texto: "Numa escala de 0 a 10, qual o meu desespero e ódio raivoso ou embaraço perante as produções visuais das telonas de Hollywood das sagas adoradas da prateleira que falham os fundos todos com escolhas cegas de enredo, personagens deturpadas e traem ao desbarato tudo das vírgulas mágicas narrativas?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_c_03", texto: "Qual a percentagem (0-100%) em que sou impulsionado à revolta do final das falhas com os ditos e claudicantes 'triângulos românticos' abismais nos ditos YAs (Young Adult) e romances pirosos de pacotilha quando a rapariga opta a final pelo galã menos atrativo e pálido e com traços nefastos face ao herói?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_c_04", texto: "Quantas e afáveis vezes a atracção do lado sombrio domina os atos do leitor da página ou as linhas turvas onde os cruéis antagonistas de peso literário com mentes calculistas, charme cínico nas barbas do herói ou vilões carismáticos no trono me provocam torcer no fundo do peito a aplaudi-los face aos fracos de bondade puritanos de coração de manteiga chato?", min: 0, max: 50, unidade: "Vezes" },
    { id: "tm_ll_c_05", texto: "Numa escala de 0 a 100%, qual o peso impenetrável ou taxa verídica do sono a adormecer no enredo críptico chato ou aborrecido da ficção científica complexíssima em vocábulos astrofísicos fora do meu universo normal nas naves perdidas em que o tédio atua mais eficaz ou pesado do que uma boa caneca avulsa recheada dum calmante quente e leitoso das 3h madrugadoras no lar escuro?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_c_06", texto: "Quantas realidades ou universos inventados da folha mágica aos contos medievos com feitiços das canetas (ex: Corredores do castelo do feitiço, Terra dos anéis mágicos e do hobbit careca) eu, a olhos abertos das fadas, abandonava já na vida em Terra sem mala, malas feitas do avião, num exato e fugaz portal inter-dimensional mal aparecesse num canto qualquer do quarto no dia?", min: 1, max: 20, unidade: "Universos" },
    { id: "tm_ll_c_07", texto: "Até que patamar (Idade em Anos) é que mantive a panca dos diários dos feitiços escondidos na fronha a replicar a vassoura com paus lá das florestas sem vergonhas aos familiares crendo que ia das calçadas ao mundo dos varinhosos no colégio secreto numa carruagem da via postal a voar?", min: 10, max: 30, unidade: "Anos" },
    { id: "tm_ll_c_08", texto: "Numa escala de 0 a 10, a que pico as expressões dos ditames ou chavões de falas e promessas líricas imponentes das cartas da janela poéticas na chuva dos heróis apaixonadíssimos dariam comigo direito nas celas com correntes algemadas caso ditos com uma normal pronúncia da esplanada num engate do mundo prático no bar ou passeio diurno nas vivências?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_c_09", texto: "Qual a percentagem exata (0-100%) da minha aceitação dos enredos com atalhos finais preguiçosos onde a epopeia imensa de contos nas laudas todas findam na célebre premissa 'Foi tudo um devaneio num sonho na almofada mole do rapaz desmaiado' levando as capas a caírem dos nervos com impacto frontal ruidoso contra as arestas foscas dos mosaicos ou no fundo e fundo falso de cesto no papelão por ofensa ao labor cerebral da compra do exemplar inútil da arte?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_c_10", texto: "Quantas e variadas expressões estéticas repletas dos clássicos de repetições, clichês básicos nos romances em que se cruzam na calçada atabalhoadamente, embatem esparramando os livros dos recados do sobrolho de um galã pálido a morder aos beiços nervosos ou suar e resfolgar na timidez de rosto rosado, me levam ou transportam visualmente do ecrã das retinas ou pupilar para a abissal sensação parva mas com atracção fatal cega ou viciante na repetição do enredo aos meus prazeres culpados mais afins e doentios da folha ao vento na lide das compras do mês na prateleira?", min: 0, max: 50, unidade: "Vezes" },
    { id: "tm_ll_c_11", texto: "Numa escala de 0 a 10, o quão obcecado(a) e cegueta da fan-base aos trambolhões de ciumeira ficava nos idos e áureos anos do secundário de crepúsculos aos triângulos parvos dos caninos e presas dentárias das sombras entre a escolha dividida entre bestas lupinas matreiras de mato, pelos nas garupas versus vampirismos gélidos na palidez com diamantes ou escamas que encarnavam nos postais na capa de lona dos recintos da minha escola?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_c_12", texto: "Qual a probabilidade e certeira percentagem que me acometeu de tentar em foros nas horas do vácuo recriar invenções baseadas nos ditos da ficção com adaptações pessoais no meu imaginário do diário para um universo meu de 'Fanfiction' com pseudónimo num PC das teclas baças da altura escolar com vergonha mortal alheia aos 14 da inocência juvenil na partilha dos fóruns em grupo de afins ceguetas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_c_13", texto: "Quantos anos luz distam, das velharias esquecidas do autor nas caves em bolores dos cânones lidos pela trela num exame forçado na pressão analítica do teste global escrito ou folha com quadriculados do liceu português (ex: Gil Vicente com barcas infernais em lide, romances maias ou o convento de estatuetas voadoras em cacos das lendas do passado na poeira dos sebos e cera na capa)?", min: 1, max: 40, unidade: "Anos" },
    { id: "tm_ll_c_14", texto: "Numa escala de 0 a 10, que talvação de repulsas nascem internamente e na veia das narinas ao sentir no comboio lotado dos vizinhos com lombadas enormes de tom azul ao calo da mão o ódio focado ou 'hate-reading' em sucessos best-sellers das tabelas dos top10 (tipo as obras lamechas repetidas em loop românticas contemporâneas que enjoam e enjoaram de massas e que juram ter tramas vazias que na net são levados aos ombros por devotos em falas e modas passageiras de clipes e cortes a rodar)?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_c_15", texto: "Qual a probabilidade ou chance realística contada dos zeros ao topo e pico limite do 100 do meu coração galopar nas pulsações com arritmia súbita nos arrepios e suores na página folheada por detrás da outra perante reviravoltas ou um vulgo 'Plot Twist' assassino brutal no cimo das três horas da noite sem luar sem que eu emita guincho abafado à mão na boca presa num esgar facial ou rebolo da fronha perante uma revelação mortal com assassinos não tidos a conta no plano no thriller policial à prova de bala lido do investigador nos alcoólicos anónimos do bar com cão velho no tapete ou asneiras da via?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_c_16", texto: "Quantos exemplares das listas (em compras) de livros encadeados, por prateleiras ou amontoados da fila do alfarrabista das caves no pó encordoado das tralhas compram pelo cheiro as narinas de que 'no digital não valem o toque e a lona colada' abdicando de aparelhos do tipo de leitura sem soltar o papel clássico e recusam Audiobooks e auriculares como não sendo 'livros reais em mente'?", min: 0, max: 500, unidade: "Exemplares" },
    { id: "tm_ll_c_17", texto: "Numa escala de 0 a 10, se me atentassem as rédeas no trilho ao escrever um conto de raiz para expor nas paragens as gentes e multidão das vendas, quão fiel da balança das fofocas faria espelho e réplica da minha dita vidinha mundana as aventuras da rotina tristonha com os chefes num escritório de esquina em vez de um dragão medieval cego a deitar fogo ao castelo e poções?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_ll_c_18", texto: "A que percentagem (0-100%) as capas atrativas coloridas das vitrines do shopping (em marketing dos grafismos na capa dos autores best-sellers de rosto das lojas e de montra à vista) corrompem e abafam num sopro as aborrecidas ou banais sinopses redigidas nas traseiras do calhamaço liso apenas e porque tem o selo ou as fitas nas vendas e no Instagram com filtro de fotos artísticas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_ll_c_19", texto: "Quantas sentenças, provérbios da velhice literária de bolso ou frases célebres das laudas soltas (como o 'Num buraco habitava um tipo pequenote da Terra com anel' ou similares clássicas de eras esquecidas pelo musgo), decorou o meu cérebro crente até aqui a transparecer que estudei, por gáudio falso e de presunção barata a meio de discursos casuais da rua e bares da vida para impor pose?", min: 1, max: 50, unidade: "Frases" },
    { id: "tm_ll_c_20", texto: "Numa escala de 0 a 10, de avó assustadora que tricotava de cadeirão e da corcunda encostada no soalho à mãe rainha do maléfico da estória bizarra em encantar ou da floresta assombrada ao longe por abóboras más envenenadas, quão macabro na análise e pesadelo se assumem nas lendas primordiais (ex. Capuchinhos com caninos falsos e Brancas de neves entaladas da garganta aos pedaços do reino em contos e grimm) no plano e juízo analítico e cínico final dum leitor maioritário e maturo da vida?", min: 0, max: 10, unidade: "Escala" }
  ]
};
