import { PerguntaTermometro } from "@/types/catalogo";

export const termometro_supersticoes_crencas: Record<string, PerguntaTermometro[]> = {
  "sub_20_0": [ // Mitos e Tradições
    { id: "tm_sc_m_01", texto: "Numa escala de 0 a 10, o quão aflito e supersticioso eu desvio os meus pés de passar debaixo de qualquer andaime numa obra ou escada na rua?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_m_02", texto: "Quantos temidos e míticos anos seguidos de azares contínuos considero caírem por cima, assim sem apelo nem agravo, ao partir um espelho caseiro?", min: 1, max: 21, unidade: "Anos de Azar" },
    { id: "tm_sc_m_03", texto: "Qual a percentagem (0-100%) em que consulto, levo a peito e avalio a minha personalidade nos textos ou dicas semanais de Astrologia/Signos do Zodíaco?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_m_04", texto: "Quantos papéis dobradinhos com santos, fitinhas rasgadas do Bonfim e outros talismãs afins se alojam no caos escuro da minha carteira e gaveta?", min: 0, max: 30, unidade: "Amuletos" },
    { id: "tm_sc_m_05", texto: "Numa escala de 0 a 100%, em que ponto avalio o peso da tradição de não deitar em sobressalto a minha bolsa ao chão senão reza a lenda 'lá se vai a fortuna'?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_m_06", texto: "Quantas e exaustivas vezes atinjo e raspo os nós dos dedos nas madeiras das mesas a tentar evitar aquele 'azar atraído e dito' que saiu numa conversa banal?", min: 0, max: 50, unidade: "Baterias (Vezes)" },
    { id: "tm_sc_m_07", texto: "Qual a real probabilidade instalada no meu cérebro criacionista que me faça persignar e benzer o corpo em frente ao cruzeiro dum cemitério calado?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_m_08", texto: "Quantas pitadas vigorosas e atabalhoadas de sal agresso atiro sobre os meus próprios ombros se por acaso entornar com os cotovelos este último na toalha de refeição?", min: 0, max: 5, unidade: "Pitadas" },
    { id: "tm_sc_m_09", texto: "Numa escala de 0 a 10, que pânico infundado assola a minha mente sensível no escuro se o felino mais sombrio da área (Gato Preto) transitar na via?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_m_10", texto: "A que percentagem considero vital e obrigatório dar o meu impulso corporal entrando fisicamente nos espaços sérios só e só primeiro com o pé da zona direita?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_m_11", texto: "Na meia noite do último dia da nossa órbita anual (Ano Novo), quantas dozes exatas de frutas passas tenho o fito impiedoso de deglutir com desejos?", min: 0, max: 24, unidade: "Passas" },
    { id: "tm_sc_m_12", texto: "Numa escala de 0 a 10, de que maneira me arrepia a mística das temidas e clássicas lendas rurais, como as noivas na serra de Sintra, etc.?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_m_13", texto: "No que toca a tesouros insólitos dos bosques de sorteio natural (trevos de quatro exatas folhagens), quantos desses juro possuir por encargo ou procura?", min: 0, max: 50, unidade: "Trevos Encontrados" },
    { id: "tm_sc_m_14", texto: "Qual a percentagem (0-100%) em que travo a minha respiração para ter o estrito cumprimento de apertar/fechar o bico das tesouras afiadas na mobília sem atrair bruxaria?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_m_15", texto: "Numa escala de 0 a 10, quão pavor e genuína paralisia sinto caso instiguem, de boa-fé, um convívio festivo regado com os perigos de contacto oculto da Ouija dos finados?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_m_16", texto: "Quantos litrais misturados em bacias caseiras de cloreto bruto e águas (mezinhas/sal grosso das avós) tive já e em absoluto sigilo despejado na nuca por purificação?", min: 0, max: 100, unidade: "Banhos Tomados" },
    { id: "tm_sc_m_17", texto: "Qual a probabilidade e transtorno (0-100%) de recuar em viagem pela desgraça do esquecimento e dar uma longa travagem com pernas em pausa sem sentar no estofo para evitar retrocessos fatais da vida?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_m_18", texto: "Numa escala de 0 a 10, em quanto assinalo e crio receios de feitiço ocular popular sobre a minha prosperidade por invejas visuais em terceiros ('Mau-olhado e quebrantos')?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_m_19", texto: "Quantas tentativas e explorações enigmáticas ou de futurologias (leituras com búzios ou manuseio de arcanos de Tarot) possuo catalogadas do lado crente da mente na vida?", min: 0, max: 50, unidade: "Consultas" },
    { id: "tm_sc_m_20", texto: "A que percentagem reavalia a minha vivência como balizada inteiramente nos provérbios arcaicos repletos de folclore dos mais idosos em diálogos corriqueiros (ditados do povo)?", min: 0, max: 100, unidade: "%" }
  ],
  "sub_20_1": [ // Sorte e Azar
    { id: "tm_sc_s_01", texto: "Numa escala de 0 a 10, do ponto de vista anímico de azar fúnebre, que grau temível assumem e inspiram certas 'Sextas Feiras do dia Treze' de cada mês negro da minha agenda?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_s_02", texto: "Ao cruzar esquinas da metrópole, quantas ínfimas moedas pisadas deduzo piamente e de espírito aquecido serem mensagens cósmicas em via postal direta de um anjo guardião ausente?", min: 0, max: 200, unidade: "Moedas 'Angélicas'" },
    { id: "tm_sc_s_03", texto: "A que percentagem divagadora do pensamento em modo diário ligo as falhas do Universo ou quedas ao balanço compensatório de causa natural por erro anterior no meu 'Karma' vivo?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_s_04", texto: "Aos exatos quantos dias repetentes e sequenciais de azares colados eu lanço, aos brados a quem me ouça, que por certo alguém alheio me plantou uma das vulgares e más amarrações/bruxarias?", min: 1, max: 30, unidade: "Dias Negros Seguidos" },
    { id: "tm_sc_s_05", texto: "Numa escala de 0 a 10, a que fervor assinalo uma cega fé com rezas nas roletas, boladas ou papéis da sorte (Jogos Oficiais, Raspadinhas) por um enriquecimento divino repentino sem labor nenhum?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_s_06", texto: "Quantos são em média, em algarismos de grelha a cruzar na raspagem, os repetitivos 'números chapa e fixos' vitais com sorte mágica agregada ou datas natais nos Euromilhões semanais de aposta?", min: 0, max: 20, unidade: "Números Sortudos Fixos" },
    { id: "tm_sc_s_07", texto: "Da responsabilidade universal das agruras, a que espantosa percentagem acuso cegamente um suposto planeta rochoso no encalço de 'Mercúrio Retrógrado' sempre e só quando não tenho melhor desculpa perante o deslize pessoal?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_s_08", texto: "Numa escala de 0 a 100%, qual o estado caótico mental caso divise relógios parados em paredes cujo ponteiro congelou o tempo marcando o presságio e sinal inegável da mácula mortífera sem fim no ar do domicílio?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_s_09", texto: "Quantos cacos, peças ou recipientes em estilhaço nos soalhos e tampos acumulo num ciclo de sete sois até bradar perante as testemunhas circundantes de que o edifício tem a 'carga e o pesar fantasmagórico' mais duro de curar?", min: 1, max: 50, unidade: "Objetos Estilhaçados" },
    { id: "tm_sc_s_10", texto: "Qual a mais pura e íntegra probabilidade (0-100%) da recusa fóbica num corredor tapado na urgência para acionar botões e soltar o raio das varas dum chapéu-de-chuva abafando assim os deuses e clamando as chuvas das dívidas a teto interno?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_s_11", texto: "A quantos despistes abruptos contorno ruas vizinhas ou cruzo os passeios empedrados num só mês para nem me debater ombro a ombro de olhar raso com o fatídico e funerário bólide e viaturas carregadas do luto nas vilas sombrias?", min: 0, max: 30, unidade: "Desvios" },
    { id: "tm_sc_s_12", texto: "Numa escala de 0 a 10, na modernidade das tendências teóricas, quão acérrimo e forte propago as falas na afamada 'Lei da Atração e Manifesto' vibracional das frequências a resgatar sonhos aos berros virados ao nada para reter os factos do bem querente?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_s_13", texto: "Num balanço final e fatídico dos azares, em que percentagem lanço, nos finais de peripécias desastrosas, a jura sentenciada pela boca ao mundo dos mortais presentes: 'Era o certo e dito no aviso matinal quando logo doíam os pés num pressentimento que a mim ninguém negou'?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_s_14", texto: "Por superstições rotineiras, e antes do suor sujo ou stressar nos degraus de uma arena dos desafios difíceis, de quantos incontáveis e curtos tiques, maneirismos em repetição corpórea do género ou rezas mudas faço escudo protetivo de blindar os maus agouros indesejáveis na totalidade?", min: 0, max: 50, unidade: "Tiques/Rotinas" },
    { id: "tm_sc_s_15", texto: "Numa escala de 0 a 10, por desfecho da penumbra num abrir de olhos nas auroras, com que peso dedico e torro minutos nas investigações na pesquisa web na leitura literal profunda sobre que desgraças um pesadelo visual das fases adormecidas possa ou não antecipar-me?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_s_16", texto: "Qual será, no computar das transações pecuniárias numa só vida das carteiras ou gavetas secretas das comodidades de limpezas de almas, o montante torrado e estourado (em moedas ou euros gastos sonantes) nos minérios polidos e quartzos aromáticos ou lenhas sagradas fumegantes?", min: 0, max: 1000, unidade: "Euros Gastos" },
    { id: "tm_sc_s_17", texto: "Na perspetiva probabilística percentual e factual na ótica mística, quão imperativo de reajuste instintivo de repulsa será para a minha atitude e toque a reversão apressada do calçado de rua tricotado ao ar cruzado e os pães invertidos nos sacos que incitam miséria no domicílio das famílias desavindas?", min: 0, max: 100, unidade: "%" },
    { id: "tm_sc_s_18", texto: "Na baliza duma nova volta solar no fecho astral do mapa estelar na linha domingueira e nas letras astrológicas das colunas, por quantas infindáveis e medrosas horas/dias retenho o juízo no engonhanço ou condicionado após o veredicto de perigo e desilusões traçadas sem remédio aparente perante os trânsitos de sol em oposição do signo de nascença na previsão rotineira e folhetinesca?", min: 0, max: 168, unidade: "Horas/Dias Vigiados" },
    { id: "tm_sc_s_19", texto: "Numa escala de 0 a 10, se pesar as contas globais nas voltas, quão bafejado, glorioso e dotado pelo prémio absoluto eu me proclamo ao universo do lado favorável desta roleta do cosmos e existencialmente perante outrem no cômputo da tal chamada ou badalada sorte ou fado na lotaria de estar com saúde respirante das lides terrestres na balança da humanidade presente sem ter a sombra das nuvens e males nas garras do azar fatal contínuo das tragédias?", min: 0, max: 10, unidade: "Escala" },
    { id: "tm_sc_s_20", texto: "A que percentagem inabalável defendo com garras a crença divina que as minhas safas a milímetros do caos, seja rodoviárias em acidentes ou de acidentes mortais caseiros por puro instinto reativo ou acaso, se traduzam na pura interferência milagrosa por toque dum tal dito anjo salvador das costas batendo à madeira?", min: 0, max: 100, unidade: "%" }
  ]
};
