import { PerguntaClassica } from "@/types/catalogo";

export const classico_animais_estimacao: Record<string, PerguntaClassica[]> = {
  "sub_13_0": [ // Cães vs Gatos
    { id: "c_ae_c_01", texto: "Na eterna guerra: Cães ou Gatos?", opcoes: ["Cães! São os melhores amigos e adoram o dono", "Gatos! São limpos, independentes e ronronam", "Gosto dos dois igualmente, sou um amante de animais", "Nenhum, não gosto de pelos nem de confusão em casa"] },
    { id: "c_ae_c_02", texto: "A passear um cão debaixo de chuva torrencial:", opcoes: ["Vou com todo o amor, ponho a gabardine e lá vamos", "O cão é rápido, vou de chinelos à porta de casa e volto", "O meu cão é que se recusa a sair com chuva, ele é um Lorde", "Odeio, fico cheio de raiva e a reclamar do tempo"] },
    { id: "c_ae_c_03", texto: "O que acho dos gatos deitarem coisas ao chão de propósito?", opcoes: ["Acho imensa piada, é a natureza deles de destruidores", "Dá-me vontade de os expulsar de casa", "Eles só querem chamar a atenção, coitadinhos", "É a prova de que a Terra não é plana, senão os gatos já tinham empurrado tudo para fora"] },
    { id: "c_ae_c_04", texto: "A limpar o 'wc' do meu animal (cocós/caixa de areia):", opcoes: ["Faço com nojo extremo mas tem de ser", "Estou 100% habituado/a, já não sinto nem o cheiro", "Empurro a tarefa sempre para a outra pessoa que vive comigo", "Uso 50 sacos plásticos para não sentir absolutamente nada"] },
    { id: "c_ae_c_05", texto: "Quando o cão/gato faz aqueles olhos de coitado a pedir comida:", opcoes: ["Não resisto e dou-lhe um bocadinho do meu prato", "Resisto fortemente! Só comem ração", "Dou-lhes os biscoitos de animal que estão no armário para desviar a atenção", "Finjo que não os vejo e viro as costas"] },
    { id: "c_ae_c_06", texto: "Receber 'lambidelas' de cães na cara:", opcoes: ["Amo! É uma demonstração pura de amor", "Deixo que me lambam as mãos, a cara não, que nojo", "Tenho pânico de germes, fujo deles a sete pés", "Até retribuo e dou beijinhos no focinho"] },
    { id: "c_ae_c_07", texto: "Quando o meu gato me ignora durante 24 horas:", opcoes: ["Sinto-me traído/a e rejeitado/a", "Acho normal, ele também precisa do seu espaço pessoal", "Vou persegui-lo e pegá-lo ao colo até ele bufar", "Nem dou por ele, às vezes acho que nem tenho um gato"] },
    { id: "c_ae_c_08", texto: "Sobre deixar os cães/gatos dormir na cama comigo:", opcoes: ["Óbvio! Eles dormem em cima dos meus pés e não me mexo", "Dormem ao fundo da cama, mas não em cima das almofadas", "Nem pensar, a cama é o meu templo sagrado de higiene", "Eles começam na cama e eu expulso-os a meio da noite porque me dão pontapés"] },
    { id: "c_ae_c_09", texto: "Quando chego a casa e o meu cão faz uma festa gigante:", opcoes: ["Deito-me no chão com ele a fazer festas", "Faço festas rápidas mas tenho de pousar as compras primeiro", "Falo com voz de bebé estridente para ele", "Tenho medo que ele me suje a roupa do trabalho com as patas"] },
    { id: "c_ae_c_10", texto: "Ao ver vídeos de gatinhos fofos na internet:", opcoes: ["Perco 3 horas a fazer scroll sorrindo para o ecrã", "Mando para todos os meus amigos no Instagram", "Faço skip, prefiro vídeos de pessoas a cair", "Guardo-os todos numa pasta para ver quando estiver triste"] },
    { id: "c_ae_c_11", texto: "Apanhar pêlos nas roupas escuras:", opcoes: ["Ando sempre com um rolo tira-pêlos no carro e na mala", "Já desisti da luta, agora a roupa preta tem pêlos brancos por padrão", "Irrita-me solenemente, odeio ter as calças cheias de pêlos", "Visto a roupa suja de pêlos na mesma e não me importo"] },
    { id: "c_ae_c_12", texto: "Qual a atitude mais chata que um cão pode ter?", opcoes: ["Ladrar para todas as moscas ou vizinhos que passam", "Saltar para cima das visitas e sujá-las", "Roubar a comida que está na bancada", "Cheirar o rabo de outros cães na rua e não andar"] },
    { id: "c_ae_c_13", texto: "Qual a atitude mais chata que um gato pode ter?", opcoes: ["Fazer corridas pela casa às 3 da manhã a deitar tudo ao chão", "Arranhar o sofá novo", "Trazer um bicho morto (pássaro/rato) como prenda para o meu travesseiro", "Ficar a miar à porta e depois não entrar"] },
    { id: "c_ae_c_14", texto: "Na rua, se vejo um cão muito fofinho num passeio:", opcoes: ["Pergunto ao dono: 'Posso fazer festinhas?' e atiro-me a ele", "Fico só a sorrir como um tonto/a a olhar para ele", "Atravesso a estrada porque tenho medo que morda", "Ignoro, é só mais um cão"] },
    { id: "c_ae_c_15", texto: "A escolha do nome de um animal:", opcoes: ["Nomes humanos normais (João, Alfredo, Lurdes)", "Nomes fofos e redondos (Bolinha, Fofucho, Pipoca)", "Nomes mitológicos/sérios (Thor, Zeus, Ares)", "Um nome completamente absurdo (Pantufa de Manteiga)"] },
    { id: "c_ae_c_16", texto: "O que acho de roupinhas para animais no Inverno?", opcoes: ["O meu tem camisolas, impermeáveis e botinhas", "Usa um casaco só quando chove muito e tem frio", "Acho super azeiteiro e desnecessário", "Gosto da ideia, mas eles tentam sempre tirar e eu desisto"] },
    { id: "c_ae_c_17", texto: "Sobre dar banho ao cão/gato em casa:", opcoes: ["Um campo de batalha de 2 horas onde acabo mais molhado que ele", "Ele porta-se muito bem e até gosta do secador", "Levo ao veterinário/loja para darem banho, não tenho paciência", "Lavar o gato? Ele limpa-se com a língua e acabou"] },
    { id: "c_ae_c_18", texto: "Quando o cão quer brincar e traz a bola:", opcoes: ["Atiro a bola 50 vezes até um de nós cair para o lado", "Atiro 2 vezes e depois ignoro", "Fingo que atiro e ele vai a correr procurar o vazio", "Tento tirar-lhe a bola mas ele recusa-se a largar e ficamos num cabo-de-guerra"] },
    { id: "c_ae_c_19", texto: "O que dizem dos 'donos de gatos'?", opcoes: ["São mais caseiros e introvertidos", "São 'Crazy Cat Ladys' que vão morrer sozinhos com 10 gatos", "São inteligentes, escolheram o animal com menos manutenção", "Têm as mãos sempre arranhadas"] },
    { id: "c_ae_c_20", texto: "Se o meu animal rasgar ou destruir algo meu importante:", opcoes: ["Fico furioso/a e ralho a sério com ele", "Olho para aquela cara e não consigo ficar chateado/a", "Fico chateado/a mas a culpa é minha de ter deixado ao alcance dele", "Tiro-lhe uma foto ao lado da destruição para meter nas redes sociais"] }
  ],
  "sub_13_1": [ // Aventuras com Bichos
    { id: "c_ae_a_01", texto: "Falar com animais como se fossem pessoas:", opcoes: ["Falo e ainda respondo por eles usando uma voz diferente", "Apenas desabafo com eles sobre o meu dia cansativo", "Faço aquela voz fininha 'Quem é o menino lindooo?'", "Acho que as pessoas que fazem isso são malucas"] },
    { id: "c_ae_a_02", texto: "Comprar brinquedos caros para os animais:", opcoes: ["Gasto balúrdios e eles ignoram para ir brincar com a caixa de cartão", "Só lhes dou bolas velhas de ténis e cordas antigas", "Eles têm 50 peluches mas brincam sempre com o mesmo roto", "Prefiro comprar guloseimas do que brinquedos"] },
    { id: "c_ae_a_03", texto: "Quando vou de férias, o que faço com o meu animal?", opcoes: ["Levo-o comigo, a família vai toda ou não vai ninguém", "Fica num hotel para animais caríssimo a ter tratamentos de spa", "Deixo em casa dos pais/amigos com lista de instruções", "Fica sozinho em casa e um amigo vai lá todos os dias pôr comida"] },
    { id: "c_ae_a_04", texto: "Levar o animal ao veterinário:", opcoes: ["O meu carro vira um filme de terror com gritos e miados", "Fica quietinho mas a tremer de pânico o tempo todo", "Ele gosta da viagem mas não gosta da agulha", "É um poço de dinheiro cada vez que pisa lá dentro"] },
    { id: "c_ae_a_05", texto: "Ter a foto do cão/gato como fundo de ecrã do telemóvel:", opcoes: ["Claro, é o meu filho de 4 patas!", "Tenho mas é uma foto dele a fazer uma careta parva", "Não tenho, meto uma paisagem genérica", "O telemóvel está recheado com 3.000 fotos só do meu cão a dormir"] },
    { id: "c_ae_a_06", texto: "Quando o meu animal faz um barulho super estranho (ex: quase a vomitar):", opcoes: ["Dou um salto do sofá para não sujar o tapete caro", "Fico logo em pânico achando que ele está a sufocar", "Mando-o logo ir fazer 'isso' para o chão da cozinha que é mais fácil de limpar", "Ignoro, ele há-de engolir a bola de pêlo outra vez"] },
    { id: "c_ae_a_07", texto: "Passear cães na rua e cruzar com outros donos:", opcoes: ["Paro a dar a maior das conversas aos outros donos enquanto os cães cheiram as rabos", "Faço contacto visual, aceno e afasto-me (antissocial)", "O meu cão é louco e ataca todos os que aparecem, atravesso a estrada", "Grito 'Ele é amigável!' enquanto o cão me arrasta pela relva"] },
    { id: "c_ae_a_08", texto: "A relação do meu animal com a árvore de Natal:", opcoes: ["Destruição total: as bolas de natal rolam pela casa", "Tento que não puxe a árvore abaixo prendendo com fios atados ao teto", "Ele só quer dormir em cima das decorações e fitas", "Tenho sorte, não liga muito à árvore de Natal"] },
    { id: "c_ae_a_09", texto: "Qual a pior prenda que um gato ou cão nos pode dar?", opcoes: ["Um pássaro meio vivo na porta do quarto", "Trazer uma pinha inteira cheia de formigas da rua", "Enrolar-se em cocó lá fora e tentar saltar para cima de nós de seguida", "Lamber-nos a cara depois de comer as suas próprias necessidades"] },
    { id: "c_ae_a_10", texto: "Quando chega a hora de tosquiar (cortar o pêlo) do cão:", opcoes: ["Ele parece que emagreceu 5 kilos e fica com um cabeçote gigante", "Fica super triste e amuado como se tivesse nu", "Tento tosquiar eu em casa e fica a parecer que foi atacado por traças", "Vai sempre de 2 em 2 meses ficar impecável no cabeleireiro canino"] },
    { id: "c_ae_a_11", texto: "Comprar comida/ração para os animais:", opcoes: ["Compro sempre as premium super caras sem cereais", "Qualquer marca do Pingo Doce serve, são animais rijos", "Ando sempre a testar marcas porque eles fartam-se rápido", "Acabo a juntar lata ou frango, senão eles nem tocam naquilo"] },
    { id: "c_ae_a_12", texto: "Como acalmar os cães no Ano Novo/Fogo-de-artifício?", opcoes: ["Fecho as persianas todas, meto a TV alta e sento-me com ele", "Meto-lhes um comprimido ou xarope calmante no queijo", "Ele nem liga aos foguetes, passa o tempo a dormir", "Fica debaixo da mesa a tremer, mas sem stress de maior"] },
    { id: "c_ae_a_13", texto: "Quando os animais acham que é hora de acordar no Domingo:", opcoes: ["Dão-me patadas na cara até eu levantar", "Ficam a miar ou chorar do lado de fora da porta", "Lambem-me as pálpebras como se eu fosse pão de forma", "Tenho a sorte divina de ter um animal que adora dormir até tarde"] },
    { id: "c_ae_a_14", texto: "Andar com cães no carro:", opcoes: ["Eles enfiam a cabeça fora da janela com a língua de fora", "Passam a viagem toda a resmungar ou ganir atrás", "Apanham enjoos no carro e eu vivo sempre com medo disso", "Têm um cinto próprio e andam como autênticos cavalheiros"] },
    { id: "c_ae_a_15", texto: "Sobre criar perfis de Instagram para o animal:", opcoes: ["Tem mais seguidores e fotos boas do que eu", "Criei por piada para os meus amigos e cansei-me", "Acho super absurdo e recuso-me", "Meto as fotos dele todas na minha própria conta mesmo que reclamem"] },
    { id: "c_ae_a_16", texto: "A fazer uma mala, o que eles fazem?", opcoes: ["Metem-se dentro da mala para impedir que eu vá", "Ficam com um ar triste encostados ao canto a culpar-me com os olhos", "Atacam as rodas da mala de cabine", "Nem reparam, estão a dormir profundamente no sofá"] },
    { id: "c_ae_a_17", texto: "Quando tenho visitas em casa que 'não gostam de animais':", opcoes: ["Aviso que a casa é do bicho e a visita é ele/a", "Fecho o cão/gato no quarto mas fico cheio/a de pena", "O cão decide logo adorar essa visita e atirar-se a ela só para chatear", "Deixo não confio em pessoas que não gostam de animais"] },
    { id: "c_ae_a_18", texto: "Animais e o aspirador de pó:", opcoes: ["Fazem guerra com o robô aspirador e atiram-se a ele", "Fugiam em pânico sempre que se liga o monstro barulhento", "Não se importam, e chegam a ser aspirados no sofá", "Ladam histericamente para o cabo elétrico"] },
    { id: "c_ae_a_19", texto: "A maior proeza do meu animal a roubar coisas:", opcoes: ["Roubou um bife de cima do balcão em 2 segundos de desatenção", "Comeu um sapato meu preferido de 100€", "Levou a minha roupa interior e pôs no meio da sala", "Nunca roubou nada, é um animal exemplar, quase um santo"] },
    { id: "c_ae_a_20", texto: "A velhice dos animais de estimação:", opcoes: ["Deixa-me super sensível e mimo-os a dobrar com guloseimas", "Ficam mais rabugentos e cheios de dores, tadinhos", "Gastam-me o salário todo nas contas do veterinário", "Parecem gatos/cães novos até terem 15 anos, são imortais"] }
  ]
};
