import { PerguntaClassica } from "@/types/catalogo";

export const classico_artes_criatividade: Record<string, PerguntaClassica[]> = {
  "sub_19_0": [ // Dotes Artísticos
    { id: "c_ac_d_01", texto: "Se eu tentar desenhar um retrato teu neste momento:", opcoes: ["Sai uma obra de arte digna do Louvre", "Parece um monstro de filme de terror ou um boneco de palitos", "Fica abstrato e digo que é arte moderna", "Recuso-me, sei que vou passar vergonha"] },
    { id: "c_ac_d_02", texto: "A minha relação com instrumentos musicais:", opcoes: ["Toco guitarra / piano como um anjo", "Sei tocar 3 acordes na viola de 2012 e canto mal", "Tentei a flauta de bisel na escola e chumbi mentalmente", "Zero dotes, mas sou excelente a tocar air-guitar"] },
    { id: "c_ac_d_03", texto: "Se for a um museu de arte contemporânea ver um quadro com um risco vermelho:", opcoes: ["Entendo a profunda mensagem e choro de emoção", "Acho que aquilo é uma anedota e qualquer criança de 3 anos fazia igual", "Finjo que percebo e digo 'interessante o uso do espaço'", "Procuro onde está a saída para ir beber um café"] },
    { id: "c_ac_d_04", texto: "Escrever poesia ou letras de música:", opcoes: ["Escrevo poemas profundos quando estou melancólico/a", "Escrevo rimas parvas e rimadas a 'cão' com 'pão'", "Tentei rimar na adolescência e enterrei os papéis de vergonha", "Nem pensar, a minha escrita criativa resume-se à lista do supermercado"] },
    { id: "c_ac_d_05", texto: "A minha habilidade em trabalhos manuais / cerâmica:", opcoes: ["Faço potes de barro incríveis à Ghost (Patrick Swayze style)", "O vaso de barro fica com uma forma disforme e deprime-me", "Parto o barro todo e sujarei a sala inteira", "Nunca experimentei, mas julgo quem o faz"] },
    { id: "c_ac_d_06", texto: "Dançar numa festa ou casamento:", opcoes: ["Rei da pista, dou passos de dança coreografados", "Com dois copos em cima, danço qualquer coisa sem vergonha", "Fico hirto/a a mexer os ombros discretamente", "Sento-me na mesa a beber e a criticar quem dança mal"] },
    { id: "c_ac_d_07", texto: "A cantar no chuveiro (ou carro):", opcoes: ["Tenho uma voz celestial, ganhava o The Voice facilmente", "Canto aos berros desafinado/a mas com muita alma e paixão", "Canto baixinho para os vizinhos não chamarem a polícia", "Só abro a boca se a música do rádio abafar a minha voz"] },
    { id: "c_ac_d_08", texto: "Se me pedirem para fazer uma caricatura de alguém:", opcoes: ["Capturo os traços perfeitos e cómicos da pessoa", "A pessoa fica parecida com um ET ou uma batata com olhos", "Faço um círculo com caracóis e chamo-lhe o retrato", "Peço desculpa e ofereço-me para tirar uma foto em vez disso"] },
    { id: "c_ac_d_09", texto: "A minha tática quando tenho de fazer trabalhos manuais de última hora:", opcoes: ["Tesoura, cola UHU, purpurinas e fica incrível", "Fita-cola preta e agrafos resolvem tudo na vida", "Fica uma verdadeira tragédia visual mas com amor", "Mando fazer a outra pessoa ou compro feito"] },
    { id: "c_ac_d_10", texto: "Interpretar uma pequena peça de teatro / representar:", opcoes: ["Nasci para a representação, ganhava um Óscar", "Fico com o cérebro em branco e esqueço o texto todo", "Rio-me a meio das minhas próprias falas dramáticas", "Recuso-me categoricamente a subir a um palco"] },
    { id: "c_ac_d_11", texto: "A minha caligrafia (letra à mão):", opcoes: ["Letra de médico cirurgião, ninguém decifra", "Letra super bonitinha, redondinha e perfumada", "Começa legível na primeira linha e acaba em gatafunho", "Uso letra maiúscula em tudo como se fosse um engenheiro"] },
    { id: "c_ac_d_12", texto: "Fazer origami (dobrar papel em animais/figuras):", opcoes: ["Faço tsurus e dragões complexos em 2 minutos", "O meu avião de papel é o único veículo que consigo fazer", "Amachuco o papel numa bola e acerto no caixote do lixo", "Fico irritado/a com as pontas e desisto"] },
    { id: "c_ac_d_13", texto: "O que acho da minha própria criatividade:", opcoes: ["Sou uma fonte inesgotável de ideias geniais", "Só tenho ideias brilhantes às 3h da manhã na cama", "A minha criatividade morreu na primária", "Copio o que vejo no Pinterest e finjo que inventei"] },
    { id: "c_ac_d_14", texto: "Decorar uma festa de anos (balões, serpentinas):", opcoes: ["Fica com nível de wedding planner profissional", "Encho 3 balões com a boca, fico tonto/a e espalho serpentinas na mesa", "Compro um kit pronto no chinês e disfarço", "A festa é num bar, que se lixe a decoração"] },
    { id: "c_ac_d_15", texto: "Se comprasse uma máquina de costura:", opcoes: ["Fazia a minha própria roupa à medida", "Costurava um botão e depois a máquina ia para o sótão para sempre", "Picava os dedos todos e cosia os lençóis às calças por engano", "Nem sei ligar aquilo à tomada"] },
    { id: "c_ac_d_16", texto: "Criar memes ou conteúdos engraçados para a net:", opcoes: ["Os meus memes batem recordes de partilhas", "Faço piadas secas que só eu acho graça", "Tento editar um vídeo no CapCut e demoro 6 horas", "Não crio, sou apenas um consumidor de conteúdos"] },
    { id: "c_ac_d_17", texto: "A desenhar graffitis ou murais com spray:", opcoes: ["Banksy quem? Sou o mestre da lata de spray", "Faço um 'tag' ranhoso e fujo da polícia a tremer", "Sujo os sapatos e as mãos todas de tinta", "Nunca toquei num spray na vida"] },
    { id: "c_ac_d_18", texto: "Fazer esculturas com comida (fruta, puré):", opcoes: ["Faço castelos de puré de batata com fosso de azeite", "Furo uma maçã para parecer uma caveira assustadora", "Estrago a comida toda e acabo a comê-la mal feita", "Isso é coisa de chefes estrelados, eu como a comida normal"] },
    { id: "c_ac_d_19", texto: "Tirar fotografias artísticas (com sombras, perspetivas):", opcoes: ["Saco de fotos incríveis com o telemóvel no chão", "Tiro fotos tortas com o dedo à frente da lente", "Coloco filtros dramáticos a preto e branco para parecer profundo", "Não tenho paciência para arte fotográfica"] },
    { id: "c_ac_d_20", texto: "O meu maior elogio artístico foi quando alguém disse:", opcoes: ["'Isto podia estar num museu!'", "'Tens jeito para as artes, podias vender isto'", "'Epá... está fofinho, parece feito por um miúdo'", "'Ao menos tentaste, e isso é o que conta'"] }
  ],
  "sub_19_1": [ // Projetos DIY
    { id: "c_ac_p_01", texto: "Quando vejo um móvel do IKEA para montar:", opcoes: ["Adoro o desafio, nem olho para as instruções (e sobra peças)", "Choro a meio do processo e chamo alguém para me salvar", "Sigo passo a passo com o nível de paciência de um monge", "Fico com o móvel meio torto na sala e aceito o destino"] },
    { id: "c_ac_p_02", texto: "A minha caixa de ferramentas em casa:", opcoes: ["Completa, com berbequim, nível e parafusos de todas as cores", "Tem um martelo meio roto e uma chave de fendas enferrujada", "É o fundo de uma gaveta com pilhas gastas e elásticos", "Não tenho ferramentas, se algo avaria chamo o senhor das obras"] },
    { id: "c_ac_p_03", texto: "Tentar pendurar um quadro na parede da sala:", opcoes: ["Fica direitinho ao milímetro com o nível a laser", "Faço 5 buracos na parede até acertar e o quadro continua torto", "Uso fita-cola de dupla face e rezo para que não caia em cima da TV", "Desisto e apoio o quadro no chão encostado à parede (estilo moderno)"] },
    { id: "c_ac_p_04", texto: "Se precisar de pintar uma parede de casa:", opcoes: ["Fico um mestre pintor com fita crepe e rolo perfeito", "Pinto a parede, o teto, o chão, o gato e a minha cara", "Farto-me a meio da primeira parede e deixo a cor dois tons diferente", "Contrato um pintor profissional para não passar vergonha"] },
    { id: "c_ac_p_05", texto: "A usar o berbequim (furador de paredes):", opcoes: ["Furo a parede com precisão cirúrgica", "Acerto num cano de água e inundo a casa inteira", "A broca escorrega no azulejo e risco a parede toda", "Tenho medo do barulho e tremo a furar"] },
    { id: "c_ac_p_06", texto: "Restaurar móveis antigos (lixar, envernizar):", opcoes: ["Transformo tralha velha em peças vintage caríssimas", "Começo a lixar, farto-me do pó e o móvel fica a apodrecer na garagem", "Deito o móvel velho fora e compro um novo no IKEA", "Pinto tudo de branco por cima e finjo que ficou novo"] },
    { id: "c_ac_p_07", texto: "A minha relação com fita-cola isolamento / fita amarela (duct tape):", opcoes: ["Salva vidas! Conserto carros, tubos e lares com ela", "Uso só quando preciso de embrulhar uma caixa para os CTT", "Acho foleiro mas está sempre à mão na gaveta", "Colo tudo o que está partido em minha casa com ela"] },
    { id: "c_ac_p_08", texto: "Quando uma torneira começa a pingar em casa:", opcoes: ["Mudo a anilha sozinho/a em 5 minutos", "Coloco um balde por baixo e espero que o barulho pare", "Fico a ouvir 'ping... ping...' a enlouquecer lentamente de madrugada", "Ligo a chorar ao canalizador"] },
    { id: "c_ac_p_09", texto: "Fazer remodelações caseiras inspiradas no Pinterest:", opcoes: ["Fica exatamente igual à foto inspiradora", "Fica uma tragédia autêntica digna de programa de comédia", "Gasto 200€ em material para no fim estragar tudo", "Vejo o vídeo, acho lindo, mas nem me levanto do sofá para tentar"] },
    { id: "c_ac_p_10", texto: "Trocar uma lâmpada fundida:", opcoes: ["Faço-o em segundos, mesmo no escuro", "Preciso de um escadote de 3 metros, luvas e óculos de proteção", "Deixo a lâmpada fundida e vivo na penumbra durante semanas", "Tento desenroscar e parto o vidro na mão"] },
    { id: "c_ac_p_11", texto: "Guardar parafusos, pregos e peças sobresselentes de móveis:", opcoes: ["Tenho um frasco/caixa organizada com todas as peças guardadas", "Atiro tudo para dentro de um copo de iogurte vazio", "Deito fora e depois claro que falta o parafuso principal", "Ficam espalhados pelo chão para picar os pés descalços"] },
    { id: "c_ac_p_12", texto: "Construir algo em madeira (tipo uma estante ou casota):", opcoes: ["Faço cortes perfeitos com serra circular", "Fica tudo torto e a abanar por todos os lados", "Farpo os dedos todos e corto a madeira torta", "Prefiro comprar feito, o meu tempo vale mais"] },
    { id: "c_ac_p_13", texto: "Aplicar papel de parede num quarto:", opcoes: ["Fica sem uma única bolha de ar, perfeito", "Fica cheio de vincos, bolhas e torto, arranco tudo a chorar", "Só consigo colar na primeira tira, o resto estraga-se", "Acho super antiquado, nunca meteria papel de parede"] },
    { id: "c_ac_p_14", texto: "O que acontece às sobras de tinta ou cimento após um arranjo?", opcoes: ["Guardo religiosamente num frasco rotulado", "Ficam a secar na lata na varanda durante 5 anos", "Deito pelo cano abaixo (poluição máxima)", "Atiro para o caixote do lixo comum"] },
    { id: "c_ac_p_15", texto: "Abrir uma porta ou fechadura emperrada:", opcoes: ["Uso WD-40 (spray milagroso) e fica como nova", "Forço a chave até ela partir lá dentro", "Dou pontapés na porta até ceder", "Fico trancado/a do lado de fora em pânico"] },
    { id: "c_ac_p_16", texto: "Fazer projetos de costura ou arrurmar bainhas com agulha:", opcoes: ["Crio vestidos e arranjo calças sem problema", "Picam-me os dedos todos e acabo a usar agrafos ou fita cola", "Peço sempre à avó ou à tia para fazerem por mim", "Se um botão cai, a camisa vai para o lixo"] },
    { id: "c_ac_p_17", texto: "A minha relação com o silicone (para vedar banheiras/janelas):", opcoes: ["Aplico um cordão liso e perfeito como um profissional", "Fico com silicone colado aos braços todos, ao cabelo e à cara", "Fica uma nojeira pegajosa que vira fungo preto ao fim de um mês", "Nem sei o que é o silicone"] },
    { id: "c_ac_p_18", texto: "Quando um eletrodoméstico faz um barulho esquisito:", opcoes: ["Abro-o com uma chave de fendas para ver as engrenagens", "Dou-lhe uma chapada lateral e o barulho passa", "Ignoro o barulho até o aparelho explodir ou deitar fumo", "Fico aterrorizado/a a achar que vai pegar fogo à casa"] },
    { id: "c_ac_p_19", texto: "Construir algo com caixas de cartão e fita-cola (estilo MacGyver):", opcoes: ["Faço um suporte de telemóvel ou organizador incrível", "Fica uma torre de lixo que desaba ao primeiro sopro", "Dá-me preguiça e compro o suporte oficial na Amazon", "Uso caixas de sapatos para arrumar tralha"] },
    { id: "c_ac_p_20", texto: "O meu orgulho máximo em projetos DIY (Faça Você Mesmo):", opcoes: ["'Fui eu que fiz!' (e mostro a todos os orgulhosos)", "'Fui eu que fiz...' (mas escondo as falhas com uma planta à frente)", "O orgulho de não ter amputado nenhum dedo no processo", "Nunca tive orgulho nenhum, só humilhação"] }
  ]
};
