import { PerguntaClassica } from "@/types/catalogo";

export const classico_beleza_cuidados: Record<string, PerguntaClassica[]> = {
  "sub_24_0": [ // Rotinas de Skincare
    { id: "c_bc_s_01", texto: "Qual é a minha rotina de Skincare de manhã?", opcoes: ["10 passos coreanos com séruns e cremes caríssimos", "Lavo a cara com água fria e está a andar", "Uso o mesmo sabonete de lavar as mãos para a cara", "Passo só uma toalhita desmaquilhante para tirar as remelas"] },
    { id: "c_bc_s_02", texto: "A minha relação com o Protetor Solar na cara:", opcoes: ["Uso religiosamente todos os dias, até no Inverno com chuva", "Só uso quando vou para a praia assar ao sol", "Odeio, fico com a cara a colar e cheio de espinhas", "Uso o creme de corpo na cara para despachar"] },
    { id: "c_bc_s_03", texto: "Quando me aparece uma borbulha gigante no meio da testa:", opcoes: ["Meto um adesivo fofinho e não toco", "Espremo imediatamente até sangrar e deixo uma marca para a vida", "Tento espremer mas dói tanto que desisto a chorar", "Finjo que é um terceiro olho e sigo em frente com confiança"] },
    { id: "c_bc_s_04", texto: "A usar máscaras faciais de argila ou papel (Sheet masks):", opcoes: ["Faço todos os domingos como terapia de spa em casa", "Comprei uma há dois anos, meti e assustei a família toda", "Acho que não fazem nada, é só para tirar foto para o Insta", "Meto a máscara e acabo a adormecer com aquilo a secar na cara"] },
    { id: "c_bc_s_05", texto: "Comprar produtos na Sephora / Wells / Pluricosmética:", opcoes: ["Sento-me a chorar quando vejo o preço do creme de 15ml", "Gasto o meu salário todo e saio de lá a sentir-me milionário/a", "Vou lá só pedir amostras grátis à descarada", "Fico tonto/a com os cheiros todos da loja e fujo"] },
    { id: "c_bc_s_06", texto: "Sobre tirar a maquilhagem antes de dormir:", opcoes: ["Nunca durmo maquilhado/a, é um crime contra a pele", "Adormeço no sofá e no dia seguinte a almofada está cheia de rímel", "Esfrego os olhos com água no banho e fico a parecer um panda", "Uso a maquilhagem de ontem para hoje, o famoso 'Smokey Eye natural'"] },
    { id: "c_bc_s_07", texto: "O creme hidratante de corpo:", opcoes: ["Espalho no corpo todo a seguir ao banho religiosamente", "Tenho tanta preguiça que a pele do meu joelho parece um deserto", "Só ponho quando as pernas já estão a descamar brancas", "Não suporto ficar com a roupa a colar, não uso"] },
    { id: "c_bc_s_08", texto: "Qual a minha atitude com esfoliantes faciais (Scrub)?", opcoes: ["Uso suavemente uma vez por semana", "Esfrego a cara com tanta força que pareço um pimentão a arder", "Uso o da areia da praia no Verão, não gasto dinheiro nisso", "Uma vez meti nos olhos e nunca mais recuperei do trauma"] },
    { id: "c_bc_s_09", texto: "Quando vejo vídeos de rotinas de famosos na Vogue:", opcoes: ["Tento copiar os produtos e fico pobre", "Acho ridículo fingirem que a pele perfeita é só de beber água", "Critico os 50 passos mas no fundo tenho bué inveja", "Adormeço a ver os vídeos porque a voz é super calmante"] },
    { id: "c_bc_s_10", texto: "Em relação ao creme dos olhos (contorno de olhos):", opcoes: ["Gasto 40€ num tubo minúsculo e aplico com o dedo mindinho", "Isso é um mito das marcas para gastarmos mais dinheiro", "Uso o creme normal da cara e esfrego os olhos à bruta", "Coloco rodelas de pepino e acredito que vai tirar as olheiras"] },
    { id: "c_bc_s_11", texto: "Depilação no geral:", opcoes: ["Tenho a tolerância à dor de um guerreiro do laser/cera", "Uso gilete à pressa no banho e corto sempre o tornozelo", "Deixo crescer no Inverno e chamo-lhe 'pêlo de aquecimento natural'", "Grito só de ver a tira de cera a aquecer"] },
    { id: "c_bc_s_12", texto: "Qual a minha desculpa para não cuidar da pele?", opcoes: ["'Não tenho tempo para 5 passos de manhã'", "'Sou tão giro/a ao natural que não preciso'", "'O sabonete azul e branco do meu avô funcionou até aos 90 anos'", "'A água do banho a escorrer já limpa o suficiente'"] },
    { id: "c_bc_s_13", texto: "A minha relação com protetor labial (batom do cieiro):", opcoes: ["Tenho um em cada casaco, mala e divisão da casa", "Uso o mesmo até o fim e raspo com o dedo no fundo", "Perco-o sempre no segundo dia que o compro", "Só uso quando os lábios já estão a deitar sangue do frio"] },
    { id: "c_bc_s_14", texto: "Envelhecimento e rugas de expressão:", opcoes: ["Meto botox mentalmente todos os dias ao espelho", "Aceito cada ruga como uma história de vida (sou profundo/a)", "Puxo a pele com os dedos para trás a ver como seria com lifting", "Uso cremes anti-rugas desde os 20 anos, em pânico"] },
    { id: "c_bc_s_15", texto: "Ao sol a apanhar bronze:", opcoes: ["Uso acelerador de bronzeado até ficar a cheirar a coco torrado", "O meu único bronze é a famosa 'marca do trolha' da t-shirt", "Tento apanhar sol mas fico com escaldões horríveis e durmo em pé", "Fujo do sol como se fosse um vampiro"] },
    { id: "c_bc_s_16", texto: "Usar tónico facial com algodão:", opcoes: ["O algodão sai preto e fico a pensar 'onde andei a esfregar a cara?'", "Nunca usei, a água da torneira faz o mesmo", "Gasto meia garrafa de produto num só disco de algodão", "Uso toalhas felpudas e dispenso as mariquices do algodão"] },
    { id: "c_bc_s_17", texto: "Tirar pontos negros do nariz:", opcoes: ["Uso aquelas tiras colantes e fico fascinado/a a ver a sujidade sair", "Espremo com as duas unhas até ter de chamar uma ambulância", "Vou a uma esteticista para sofrer nas mãos de um profissional", "Tenho o nariz limpinho, sou abençoado/a pela genética"] },
    { id: "c_bc_s_18", texto: "A usar creme para as mãos no Inverno:", opcoes: ["As minhas mãos estão tão secas que o creme arde", "Ponho e depois não consigo abrir maçanetas das portas", "Odeio ficar com as mãos escorregadias e limpo às calças", "Adoro espalhar e cheirar as mãos o dia todo"] },
    { id: "c_bc_s_19", texto: "Beber água para 'limpar a pele':", opcoes: ["Ando sempre agarrado/a ao meu garrafão Stanley", "Bebo tanta água que o meu escritório principal passa a ser a casa de banho", "Se a água das sopas e do café contar, estou hidratadíssimo/a", "Isso é mito, e como mito, eu bebo só sumos"] },
    { id: "c_bc_s_20", texto: "A minha última loucura em cuidados estéticos foi:", opcoes: ["Comprar uma daquelas pedras rolo de Jade para a cara", "Gastar balúrdios numa limpeza de pele de 1 hora", "Tentar fazer um banho turco caseiro com uma toalha e panela de água quente", "Aceitar a minha cara de zombie matinal"] }
  ],
  "sub_24_1": [ // Cabelo e Maquilhagem
    { id: "c_bc_c_01", texto: "O meu drama matinal com o cabelo:", opcoes: ["Acordo com o cabelo impecável, pareço ator/atriz", "Parece que levei um choque elétrico, vai de boné/rabo-de-cavalo", "Demoro 45 minutos a alisar ou enrolar", "Meto água na pia e tento acalmar os remoinhos em vão"] },
    { id: "c_bc_c_02", texto: "Ir ao cabeleireiro / barbeiro:", opcoes: ["Vou de mês a mês religiosamente", "Vou uma vez por ano e peço 'só as pontinhas'", "Tento cortar a franja em casa às 3 da manhã e arrependo-me para sempre", "O barbeiro faz o mesmo corte sempre e eu digo 'tá top chefe'"] },
    { id: "c_bc_c_03", texto: "No salão, quando acabam de cortar e pergunto 'Está bom assim?':", opcoes: ["Ficou horrível, mas sorrio, pago 20€ e choro no carro", "Adoro! Fico a admirar-me nos espelhos todos", "Digo 'tá um bocado curto' com uma lágrima no canto do olho", "Digo a verdade e exijo que mude (corajoso/a)"] },
    { id: "c_bc_c_04", texto: "Sobre arriscar mudar de cor de cabelo:", opcoes: ["Mudo a cor tantas vezes que já nem sei qual é a minha natural", "Nunca pintei, sou super fiel à minha cor aborrecida", "Fiz uma descoloração em casa que correu mal e ficou laranja-cenoura", "Só arrisco nas luzes / madeixas discretas para não chocar a avó"] },
    { id: "c_bc_c_05", texto: "A minha relação com champô seco (Dry Shampoo):", opcoes: ["Salva-me a vida quando estou com preguiça de lavar a cabeça", "Fico com o cabelo branco a parecer que tenho pó de talco", "Nunca usei, aprecio um bom banho de água", "Uso para dar volume mas fico com o couro cabeludo a arder"] },
    { id: "c_bc_c_06", texto: "Fazer o Eyeliner (Delineador):", opcoes: ["Faço perfeito nos dois olhos em 30 segundos (mestre)", "O direito fica lindo, o esquerdo fica um monstro ondulado", "Depois de 5 cotonetes e desmaquilhante, desisto e saio sem nada", "Nem tento, tenho a coordenação motora de uma ervilha"] },
    { id: "c_bc_c_07", texto: "A usar rímel (máscara de pestanas):", opcoes: ["Fico de boca aberta a aplicar para não piscar", "Borro sempre a pálpebra e arruíno a sombra toda", "As pestanas ficam todas coladas num monobloco tipo aranha", "Compro do chinês e depois os olhos ficam a arder"] },
    { id: "c_bc_c_08", texto: "Cabelos brancos aparecerem:", opcoes: ["Arranco com a pinça imediatamente em negação absoluta", "Assumo os brancos com grande estilo (tipo George Clooney)", "Começo a pintar a raiz de 15 em 15 dias em pânico", "Entro numa crise de idade aos 25 anos"] },
    { id: "c_bc_c_09", texto: "Fazer o contorno da cara (Bronzer/Blush):", opcoes: ["Sou perito/a em tutorial de Kim Kardashian", "Fico a parecer que esfreguei a bochecha num tijolo", "Nem sei para que serve isso, só ponho pó", "Uso o tom errado e o meu pescoço fica branco e a cara laranja"] },
    { id: "c_bc_c_10", texto: "Como lido com dias de 'Bad Hair Day'?", opcoes: ["O clássico gorro ou chapéu, faça 40 graus na rua", "Encho o cabelo de gel ou laca e fica empastado", "Faço um rabo de cavalo super apertado que me estica as sobrancelhas", "Não saio de casa, a minha autoestima não permite"] },
    { id: "c_bc_c_11", texto: "Sobre o famoso Baton Vermelho:", opcoes: ["Amo! Sinto-me confiante e arrasadora", "Tenho medo, parece que estou com a boca manchada de sangue", "Fica-me nos dentes todos e passo o jantar a sorrir vermelho", "Compro batons caros, uso 1 vez numa festa e ganham bolor"] },
    { id: "c_bc_c_12", texto: "Quando não meto maquilhagem e vou trabalhar:", opcoes: ["Toda a gente pergunta 'estás doente? Tens má cara'", "Não muda nada, sou perfeitamente normal", "Escondo a cara nos casacos para ninguém olhar para mim", "Acho ótimo, respiro liberdade e coço os olhos à vontade"] },
    { id: "c_bc_c_13", texto: "O secador de cabelo e eu:", opcoes: ["Seco perfeitamente com a escova redonda e dou volume", "Seco à bruta, atirando o cabelo todo para a frente", "Odeio o barulho, deixo secar ao natural e apanho constipações", "Queimo o couro cabeludo no nível máximo para despachar"] },
    { id: "c_bc_c_14", texto: "As sobrancelhas:", opcoes: ["Faço-as de pinça em casa e tiro sempre pêlos a mais", "Vou fazer a linha e choro com a dor mas fica 'on fleek'", "A minha sobrancelha é um matagal natural e orgulhoso", "Desenho com lápis e uma fica redonda e a outra quadrada"] },
    { id: "c_bc_c_15", texto: "Gastar dinheiro no salão para fazer um penteado de festa:", opcoes: ["Vale cada cêntimo, duro o dia inteiro intacto/a", "Pago 60€, chego a casa, odeio, desmancho e faço eu um coque", "Chove e o penteado vai à vida em 10 minutos", "Não pago, vejo vídeos no YouTube de tranças e improviso"] },
    { id: "c_bc_c_16", texto: "Sobre os alisadores (pranchas de cabelo):", opcoes: ["Uso todos os dias, as minhas pontas parecem palha frita", "Já queimei a testa, a orelha e o pescoço 5 vezes", "Guardo a prancha na gaveta com ela ainda quente e derreto coisas", "Tenho caracóis rebeldes e a prancha nem lhes faz cócegas"] },
    { id: "c_bc_c_17", texto: "Usar unhas de gel / gelinho:", opcoes: ["Estou sempre no salão, não vivo sem as minhas garras", "Tento tirar o gelinho em casa com os dentes e arruíno as unhas", "Acho super anti-higiénico para cozinhar ou limpar", "Não consigo teclar no telemóvel nem abrir latas de atum"] },
    { id: "c_bc_c_18", texto: "No Verão, a maquilhagem derrete:", opcoes: ["Uso spray fixador potente e fico impecável nos 40 graus", "O meu rímel escorre e pareço o Alice Cooper", "Não uso nada no Verão, transpiro só de respirar", "Fico com a base encrostada aos pedaços na cara"] },
    { id: "c_bc_c_19", texto: "Fazer a barba (homens) ou cuidados faciais:", opcoes: ["Aparo na perfeição com degradê na máquina", "Corto-me na bochecha, meto papel higiénico e saio à rua", "Deixo a barba crescer como um lenhador isolado do mundo", "Faço a barba toda e fico a parecer que tenho 12 anos e arrependo-me"] },
    { id: "c_bc_c_20", texto: "Como removo a maquilhagem quando chego da festa às 5h da manhã?", opcoes: ["Desmaquilho, lavo, tonifico e hidrato religiosamente (Mito)", "Esfrego a cara na toalha branca do hotel e deixo a cara desenhada lá", "Passo toalhita de bebé, que arranha a cara, e caio na cama", "Durmo com ela e vou ao brunch do dia seguinte ainda com brilhantes"] }
  ]
};
