import { PerguntaClassica } from "@/types/catalogo";

export const classico_carros_conducao: Record<string, PerguntaClassica[]> = {
  "sub_16_0": [ // Stress no Trânsito
    { id: "c_cc_s_01", texto: "Quando apanho trânsito pesado de manhã:", opcoes: ["Falo sozinho/a e insulto toda a gente que se mete na frente", "Meto música aos berros e faço um concerto ao vivo", "Oiço podcasts para tentar não perder a sanidade mental", "Choro por dentro a pensar que devia ter ido de transportes"] },
    { id: "c_cc_s_02", texto: "Alguém me dá um 'apito' (buzinadela) na estrada. O que eu faço?", opcoes: ["Levanto o dedo do meio e buzino de volta sem olhar", "Fico cheio/a de medo e peço desculpa com a mão", "Travo a fundo de propósito só para chatear o gajo de trás", "Finjo que não ouvi e começo a assobiar para o lado"] },
    { id: "c_cc_s_03", texto: "Estacionar em paralelo (entre dois carros):", opcoes: ["Sou o mestre do estacionamento, à primeira sem suar", "Faço 18 manobras, bato no passeio, suo, e acabo por ir dar a volta ao quarteirão", "Peço ao meu pendura para sair e ir lá fora ver a distância", "Estaciono a um metro do passeio para não raspar as jantes"] },
    { id: "c_cc_s_04", texto: "Ao ver a luz amarela do semáforo:", opcoes: ["Acelero a fundo para passar tipo Fast and Furious", "Travo a fundo e deixo os pneus a chiar", "Passo num laranja super avermelhado e rezo que não haja polícia", "Travo normalmente como uma pessoa decente"] },
    { id: "c_cc_s_05", texto: "O que acho dos ciclistas e trotinetes na estrada?", opcoes: ["Odeio! Acham que são donos da faixa de rodagem", "Tento ultrapassar dando um 'razão' para se assustarem", "Sou um deles, por isso exijo o meu espaço", "Faço a ultrapassagem com 1,5m de distância como diz o código (anjo)"] },
    { id: "c_cc_s_06", texto: "Qual a minha relação com rotundas?", opcoes: ["Faço-as sempre por fora, mesmo que vá sair na 3ª saída", "Uso sempre os piscas, sou o salvador da Pátria", "Entro 'à patrão' e que travem os outros", "Fico parado/a na entrada 5 minutos à espera de um buraco gigante"] },
    { id: "c_cc_s_07", texto: "Quando vejo um carro de instrução (a tirar a carta) à frente:", opcoes: ["Tenho zero paciência e ultrapasso logo", "Lembro-me de mim e tenho pena do pobre coitado", "Cola-me à traseira para dar ansiedade ao novato", "Buzino se o carro for abaixo nos semáforos"] },
    { id: "c_cc_s_08", texto: "Sobre deixar o carro a lavar num lugar pago:", opcoes: ["Lavo e aspiro sempre religiosamente", "O meu carro lava-se quando chove", "Uso as moedas na máquina de lavar a pressão mas fico todo molhado/a", "Escrevo 'Lava-me' no vidro traseiro cheio de pó"] },
    { id: "c_cc_s_09", texto: "A conduzir com a reserva da gasolina/gasóleo acesa:", opcoes: ["Entro em pânico e vou à bomba mais cara que vir", "Aposto com a vida que ainda consigo fazer mais 50 km com a luzinha", "Só atesto 10€ de cada vez, viver no limite", "Nunca deixo chegar à reserva, mal desce do meio vou atestar"] },
    { id: "c_cc_s_10", texto: "Como lido com radares de velocidade (pardais)?", opcoes: ["Tenho o Waze/Google Maps sempre ligado para não me apanharem", "Travo a fundo mal vejo a caixa cinzenta", "Ando sempre abaixo do limite, medo extremo de multas", "Levo com os flashes todos e espero pelas cartas do Governo"] },
    { id: "c_cc_s_11", texto: "A usar os 'Piscas' (Indicadores de Mudança de Direção):", opcoes: ["Uso religiosamente", "Só uso se vir que vem lá a polícia", "Piscas? Isso vem nos extras do carro, não paguei por isso", "Às vezes ligo o pisca da esquerda e viro à direita"] },
    { id: "c_cc_s_12", texto: "Quando um pendura começa a criticar a minha condução:", opcoes: ["Digo-lhe 'queres conduzir tu?' e travo a fundo", "Mando-o calar imediatamente, 'quem vai ao volante sou eu!'", "Fico com suores frios e começo a conduzir ainda pior de nervos", "Aumento o som do rádio para o não ouvir"] },
    { id: "c_cc_s_13", texto: "Conduzir à chuva torrencial à noite:", opcoes: ["Ando a 20 km/h com as duas mãos agarradas ao volante a suar", "Nem reparo, sou o rei da aquaplanagem", "Ligo os faróis de nevoeiro todos para encandear os outros", "Fico em casa, não pego no carro nem por cima do meu cadáver"] },
    { id: "c_cc_s_14", texto: "O que faço quando vejo um lugar de estacionamento no shopping a ficar livre?", opcoes: ["Meto o pisca e espero o tempo que for preciso como uma águia", "Roubo o lugar à descarada a quem estava a piscar do outro lado", "Prefiro estacionar no fim do parque e andar 5 minutos a pé", "Sigo o condutor até ao carro devagarinho a pressionar"] },
    { id: "c_cc_s_15", texto: "A arrancar com o carro numa subida muito íngreme:", opcoes: ["Ponto de embraiagem perfeito, nem recua 1 mm", "Puxo o travão de mão à antiga porque tenho pânico de descair", "O carro vai abaixo 3 vezes e apago com os nervos e buzinões", "Tenho caixa automática, não sinto essa dor tuga"] },
    { id: "c_cc_s_16", texto: "Em autoestradas, a minha faixa preferida é:", opcoes: ["A da esquerda, sempre a 150 km/h a fazer sinal de luzes", "A do meio, sinto-me mais seguro/a (o famoso empate)", "A da direita, a 90 km/h atrás dos camiões TIR", "Vou saltando que nem um sapo de faixa em faixa para ultrapassar"] },
    { id: "c_cc_s_17", texto: "Quando me engano no caminho com o GPS ligado:", opcoes: ["Culpo o telemóvel e chamo nomes à voz do Google Maps", "Dou uma valente volta mas finjo que era por ali na mesma", "Faço inversão de marcha a meio de um traço contínuo com perigo", "Entro em pânico se vir o ecrã a 'Recalcular Rota'"] },
    { id: "c_cc_s_18", texto: "A cantar no trânsito, e de repente o carro do lado olha para mim:", opcoes: ["Fecho o vidro lentamente e finjo que estava a coçar o nariz", "Faço contacto visual e continuo a cantar para ele/ela", "Finjo que estava numa chamada de alta-voz a discutir", "Calar-me? Nem pensar, estava a chegar ao refrão!"] },
    { id: "c_cc_s_19", texto: "Qual a pior praga que os pássaros podem atirar para o carro?", opcoes: ["O clássico 'cocó gigante' mesmo a meio do vidro logo após o lavar", "Sujarem o capô e deixar a tinta a queimar com o sol", "Odeio quando fica seco e tenho de arrancar aquilo com a unha ou raspador", "Viver com o facto de ter sido alvo enquanto tinha a janela aberta"] },
    { id: "c_cc_s_20", texto: "Quando a polícia manda parar numa Operação Stop de rotina:", opcoes: ["O coração bate a 200 à hora mesmo não tendo feito nada ilegal", "Faço o teste do balão relaxado e a sorrir", "Dou grande conversa ao Sr. Agente para tentar evitar confusões", "Esqueço-me sempre de onde tenho os papéis do carro no porta-luvas"] }
  ],
  "sub_16_1": [ // Roadtrips e Viagens
    { id: "c_cc_r_01", texto: "O meu papel oficial numa roadtrip de amigos é:", opcoes: ["O motorista principal, nunca largo o volante", "O DJ de serviço (tenho o cabo AUX ou Bluetooth na mão)", "O fornecedor de sandes e bolachas", "O pendura que dorme a viagem toda a babar"] },
    { id: "c_cc_r_02", texto: "Qual a minha atitude na hora de pagar as portagens (Via Verde):", opcoes: ["Tenho Via Verde, passo rasgado e partilhamos a conta depois", "Tento ir sempre por estradas Nacionais para não pagar um cêntimo a esses ladrões", "Paro sempre na caixa manual, demoro 10 min a procurar as moedas", "Fico com o papelinho da portagem 3 meses perdido na pala do sol"] },
    { id: "c_cc_r_03", texto: "Quando a viagem é longa (mais de 3 horas), a música ideal é:", opcoes: ["Uma playlist de músicas de karaoke para gritar os anos 2000", "Podcasts sobre crimes reais ou coisas intensas", "Música eletrónica/house para não me dar o sono na autoestrada", "Silêncio absoluto. Quero ouvir o vento e não aturar a vossa voz"] },
    { id: "c_cc_r_04", texto: "Para lanches no carro durante a viagem, eu prefiro:", opcoes: ["Pringles e gomas (e encher os estofos de sal/açúcar)", "Umas sandes de panado parando numa estação de serviço", "Água e uma maçãzinha saudável (não gosto de engordar no carro)", "Parar num McDonald's Drive-In e comer no andamento"] },
    { id: "c_cc_r_05", texto: "A necessidade de parar para ir à casa de banho:", opcoes: ["Sou o que manda parar o carro a cada 40 minutos", "Aguento desde o Porto até Faro sem pestanejar (bexiga de aço)", "Digo que não preciso e passado 5 min na autoestrada começo aos berros", "Obrigo o motorista a parar numa berma do mato porque não aguento à bomba"] },
    { id: "c_cc_r_06", texto: "Qual a pior coisa que um passageiro me pode fazer?", opcoes: ["Encostar os pés sujos no tablier (chofleur) do carro", "Mudar de rádio / música a meio do refrão", "Abrir os vidros quando está o ar condicionado ligado", "Mandar postas de pescada sobre a minha velocidade"] },
    { id: "c_cc_r_07", texto: "No banco de trás numa viagem em grupo:", opcoes: ["Vou encostado/a a uma almofada a ressonar", "Vou os 300 kms a falar com quem vai à frente", "Fico mal-disposto/a e agoniado/a (enjoo das curvas)", "Sou ensanduichado/a no lugar do meio, que é rijo e não tem espaço"] },
    { id: "c_cc_r_08", texto: "O que acho de dar boleias a amigos (carpooling)?", opcoes: ["Adoro, quanto mais malta melhor", "Exijo gasolina e portagens calculadas ao décimo de cêntimo no MBWay", "Digo que sim mas chego lá com o carro minúsculo cheio de lixo nos bancos", "Odeio, fico logo a inventar desculpas que vou por outro caminho"] },
    { id: "c_cc_r_09", texto: "Se o carro avaria no meio do nada:", opcoes: ["Visto o colete refletor e meto o triângulo como um ninja da assistência", "Não sei o que fazer e começo a gritar em pânico sem bateria no telemóvel", "Tento abrir o capô e olho para o motor com ar sério (não percebo nada)", "Chamo a assistência em viagem, sento-me no Rails a comer bolachas"] },
    { id: "c_cc_r_10", texto: "Viajar de autocarro noturno (ex: FlixBus):", opcoes: ["Adoro a poupança financeira e durmo bem", "É o maior sofrimento para a minha coluna, fico sem joelhos", "A pessoa da frente reclina sempre o banco e eu sofro calado/a", "Sou a pessoa simpática que cheira bem e mete o Netflix a dar"] },
    { id: "c_cc_r_11", texto: "A escolha do destino num fim de semana prolongado:", opcoes: ["Gerês ou Serra da Estrela, ver verde e ovelhas", "O clássico 'Algarve', mesmo que não esteja tempo de praia", "Ir ao IKEA no Porto/Lisboa e voltar com o carro cheio de móveis", "Vou por instinto, ligo o carro e decido nas rotundas"] },
    { id: "c_cc_r_12", texto: "Qual a minha desculpa oficial para me perder numa viagem longa?", opcoes: ["'O raio da voz do GPS estava em inglês!'", "'As placas nesta zona não fazem sentido nenhum'", "'A culpa é tua que ias a falar ao meu ouvido e não vi a saída'", "'Eu não me perdi, apenas decidi explorar um caminho mais pitoresco'"] },
    { id: "c_cc_r_13", texto: "Quando pergunto 'Já estamos a chegar?' aos outros no carro:", opcoes: ["Sou a criança de 8 anos do grupo a cada meia hora", "É porque estou desesperado/a para esticar as pernas ou fumar", "Apenas quando o GPS morre e entro em negação", "Nunca pergunto, durmo até me mandarem sair"] },
    { id: "c_cc_r_14", texto: "Ao cruzar a fronteira de carro (Espanha):", opcoes: ["Tiro uma foto na placa 'España' enquanto conduzo", "Vou imediatamente ver os preços da gasolina para atestar", "Tento sintonizar a rádio nos êxitos de reggaeton espahol", "Compro tabaco e caramelos que lá são mais baratos"] },
    { id: "c_cc_r_15", texto: "Se estiver bué sol de frente a conduzir:", opcoes: ["Abaixo a pala do sol e ponho os meus Ray-Ban de alta pinta", "Fico com as pálpebras franzidas a lacrimejar mas recuso-me a parar para procurar óculos", "Bato na pála do sol e parto-a sem querer", "Obrigo o passageiro a meter o mapa a fazer sombra no vidro"] },
    { id: "c_cc_r_16", texto: "Ao conduzir em estradinhas da Serra (muitas curvas):", opcoes: ["Entro no modo Rally e atiro o carro às curvas", "Faço a estrada a 30 km/h porque as ribanceiras assustam-me de morte", "Buzino em cada curva cega a rezar para não vir um jipe no lado errado", "Peço a alguém para trocar porque começo a vomitar as alheiras do almoço"] },
    { id: "c_cc_r_17", texto: "A minha capacidade de fazer jogos do carro (Ver carros amarelos, matrícula, etc):", opcoes: ["Sou bué competitivo e não perdoo um carro amarelo", "Passado 3 minutos já me fartei dessa infantilidade", "Invento regras nojentas só para dar beliscões aos outros", "Sou eu quem tenta convencer todos a jogar para não me adormecerem"] },
    { id: "c_cc_r_18", texto: "A passar por um acidente ou obra grande na autoestrada:", opcoes: ["Vou a 'pastar' só para ver o que se passou e fazer bicha (cusco)", "Passo furioso com quem trava só para ver desgraças", "Reclamo dos impostos e das portagens caras que pago para estar ali", "Começo a ver trajetos de fuga no Google Maps por terrinhas esquecidas"] },
    { id: "c_cc_r_19", texto: "Como reajo aos mosquitos mortos esborrachados no pára-brisas?", opcoes: ["Esguicho logo água e escovas em cima e só espalho uma nuvem nojenta", "Guardo a dor para quando parar numa bomba com aquele balde de água azul", "O meu carro é um cemitério ambulante de bichos, não lavo", "Acho super asqueroso e odeio o barulho de os matar em andamento"] },
    { id: "c_cc_r_20", texto: "Para mim, o verdadeiro objetivo de uma Roadtrip é:", opcoes: ["O destino em si, quero chegar rápido", "A jornada! Parar, tirar fotos e as conversas profundas a meio da noite", "A comida de estrada e os cafés estranhos das Áreas de Serviço", "Poder conduzir descalço/a ou só de meias a sentir a liberdade (se não estiver ao volante)"] }
  ]
};
