import { PerguntaClassica } from "@/types/catalogo";

export const classico_casa_decoracao: Record<string, PerguntaClassica[]> = {
  "sub_11_0": [ // Limpeza e Arrumação
    { id: "c_cd_l_01", texto: "O meu 'Dia das Limpezas' (normalmente Sábado):", opcoes: ["Música aos berros e a casa a cheirar a lixívia às 9h da manhã", "Faço as coisas com calma, ao meu ritmo, demora o dia todo", "Invento desculpas para ir dar uma volta", "Empurro as coisas para debaixo do tapete ou cama e disfarço"] },
    { id: "c_cd_l_02", texto: "Na cozinha, a loiça suja:", opcoes: ["É lavada e arrumada mal se acaba de comer", "Fica na bancada até se fazer uma Torre de Pisa", "Esconde-se tudo na máquina e quando enche liga-se", "Fica a demolhar em água com Fairy (durante dias)"] },
    { id: "c_cd_l_03", texto: "A cadeira do quarto (a 'cadeira da roupa'):", opcoes: ["Não existe. Guardo tudo no armário.", "Tem uma montanha de roupa que não está nem suja nem limpa", "Eu atiro as coisas para o chão, a cadeira é muito formal", "Tiro de lá a roupa para dormir e ponho na cama de dia"] },
    { id: "c_cd_l_04", texto: "Como lido com estendal e passar a ferro?", opcoes: ["Gosto da roupa a cheirar bem, passo tudo no próprio dia", "Apanho do estendal e fica num cesto 3 semanas à espera", "Passar a ferro? Eu estico com a mão e o corpo resolve", "Tenho medo do ferro, queimo as camisas todas"] },
    { id: "c_cd_l_05", texto: "Quando recebo visitas em casa (amigos):", opcoes: ["A casa está sempre imaculada, não mudo nada", "Faço uma arrumação de pânico em 15 minutos", "Peço imensa desculpa pela 'bagunça' (e está mesmo bagunçado)", "Atiro as coisas todas do sofá para o quarto e tranco a porta"] },
    { id: "c_cd_l_06", texto: "Para mim, varrer ou aspirar o chão é:", opcoes: ["Uma terapia relaxante", "O meu pior pesadelo, odeio o barulho do aspirador", "Comprei um aspirador robô para me livrar dessa chatice", "Dou um jeitinho rápido no meio, os cantos ficam com pó"] },
    { id: "c_cd_l_07", texto: "O meu armário debaixo do lava-loiças (limpeza):", opcoes: ["Parece um laboratório, tenho um produto para cada milímetro", "Tenho só lixívia e lava-tudo multiusos para resolver TUDO", "Cheio de embalagens de Sonasol vazias que não deito fora", "Não tenho, roubo ao vizinho ou colega de casa"] },
    { id: "c_cd_l_08", texto: "Fazer a cama de manhã:", opcoes: ["É um ritual obrigatório mal me levanto", "Sacudo os cobertores vagamente para não parecer um ninho", "Deixo desfeita porque 'logo à noite vou deitar-me lá na mesma'", "Só faço se tiver frio e precisar dos cobertores alinhados"] },
    { id: "c_cd_l_09", texto: "Quando deixo cair um copo ou prato e ele parte-se:", opcoes: ["Apanho tudo imediatamente e passo o aspirador 3 vezes", "Apanho os bocados grandes e empurro o pó para o canto", "Fico a olhar para o chão a pensar na minha desgraça", "Digo 'foi sem querer!' (vivo sozinho/a)"] },
    { id: "c_cd_l_10", texto: "Limpar o pó (móveis, prateleiras):", opcoes: ["Todas as semanas, aprecio os móveis a brilhar", "Só limpo antes do Natal ou na Páscoa", "Limpo com o dedo ou com a camisola quando noto muito", "Acho que o pó faz parte da decoração vintage"] },
    { id: "c_cd_l_11", texto: "O que acho de ter plantas verdadeiras em casa?", opcoes: ["Amo, parece uma selva, limpo as folhas todas", "Gosto mas esqueço-me de as regar e morrem", "As minhas são todas de plástico", "Sujam a casa com folhas caídas, prefiro não ter"] },
    { id: "c_cd_l_12", texto: "Como lido com o lixo e reciclagem?", opcoes: ["Tenho ecopontos com cores todas direitinhas em casa", "Levo logo o saco quando enche, não suporto odores", "Fica ao lado da porta 4 dias porque me esqueço de levar", "Misturo tudo no mesmo balde e não digo a ninguém"] },
    { id: "c_cd_l_13", texto: "Na casa de banho, o espelho:", opcoes: ["É limpo com limpa-vidros até me refletir o futuro", "Está todo salpicado de pasta dos dentes", "Uso a toalha húmida do banho para o limpar", "Só é limpo quando já não consigo ver a minha cara"] },
    { id: "c_cd_l_14", texto: "A limpar o frigorífico eu:", opcoes: ["Tiro tudo para fora e esfrego as prateleiras com vinagre", "Atiro fora aquela alface que já é líquido", "Só limpo se alguma coisa verter e ficar pegajoso", "Nunca limpei um frigorífico na vida, isso limpa-se?"] },
    { id: "c_cd_l_15", texto: "Em relação ao interior do meu carro (considerado 'casa' secundária):", opcoes: ["Ando sempre com toalhitas, parece acabado de sair do stand", "Tem pacotes de batatas e talões do McDonald's espalhados", "Tem um cheirinho na ventilação e está 'razoável'", "É o armazém da minha vida inteira, até roupa lá tenho"] },
    { id: "c_cd_l_16", texto: "Quando o ralo do chuveiro entope com cabelos:", opcoes: ["Tiro sem nojo nenhum e sigo em frente", "Finjo que não é nada e empurro a água com o pé", "Entro em pânico e chamo outra pessoa da casa para tratar", "Compro ácido no supermercado e derreto tudo lá dentro"] },
    { id: "c_cd_l_17", texto: "O meu armário do guarda-roupa:", opcoes: ["Cabides todos virados para o mesmo lado e por cor", "Dobro, mas passados 2 dias está tudo revolvido", "Enfio tudo em gavetas e rezo para conseguir fechar", "Roupa limpa misturada com suja, é a lotaria de manhã"] },
    { id: "c_cd_l_18", texto: "Sobre o chão e andar descalço em casa:", opcoes: ["O chão é brilhante, e exijo que as visitas tirem os sapatos", "Ando descalço e no fim do dia os pés estão pretos", "Uso chinelos de quarto religiosamente", "Meto o aspirador robô a trabalhar e fujo da frente dele"] },
    { id: "c_cd_l_19", texto: "Limpar as janelas é para mim:", opcoes: ["A tarefa de Mestre, ficam transparentes!", "Sujam-se no dia a seguir a chover, nem vale a pena", "Limpo com jornal e limpa-vidros como antigamente", "Chamo a vizinha para ir lá a casa ajudar"] },
    { id: "c_cd_l_20", texto: "Depois de dar um grande jantar ou festa em casa:", opcoes: ["Arrumo tudo nessa noite para acordar com a casa limpa", "Vou dormir e lidar com a catástrofe de ressaca", "Obrigo os convidados a lavar a loiça antes de saírem", "Atiro com os sacos de lixo pela janela"] }
  ],
  "sub_11_1": [ // Dias de Preguiça
    { id: "c_cd_p_01", texto: "No meu dia de descanso supremo (ex: Domingo à chuva):", opcoes: ["Acordo cedo na mesma, tomo o pequeno-almoço e relaxo", "Levanto-me ao meio-dia e não saio do pijama", "Faço os meus tachos todos de Meal Prep", "Fico deitado no escuro a contemplar o teto"] },
    { id: "c_cd_p_02", texto: "Qual a minha relação com a entrega de comida a casa (Uber Eats)?", opcoes: ["Acho um crime pagar a taxa de entrega", "Mando vir porque o esforço de cozinhar é demasiado", "Acabo a mandar vir McDonald's porque é mais rápido", "Mando vir almoço e deixo o resto para o jantar"] },
    { id: "c_cd_p_03", texto: "A ver Netflix no sofá:", opcoes: ["Estou com postura correta com cházinho na mão", "Embrulhado na manta tipo 'burrito' com a cara de fora", "Deitado de pernas para o ar e a meio da almofada", "Com a mão a meio caminho do pacote de batatas fritas"] },
    { id: "c_cd_p_04", texto: "O que me faz cancelar um plano para ficar em casa?", opcoes: ["O facto de estar a chover lá fora", "Se me disserem que a festa vai ter muita gente que não conheço", "A cama chama por mim mais alto", "Zero, eu nunca cancelo planos (FOMO)"] },
    { id: "c_cd_p_05", texto: "Se estiver com sede mas estiver deitado(a) hiper confortável:", opcoes: ["Levanto-me de um salto, hidratação é importante", "Fico ali a agonizar e tento adormecer a sede", "Peço a alguém (mãe, parceiro/a) para me trazer água", "Bebo do copo de água da noite anterior que está na mesa de cabeceira"] },
    { id: "c_cd_p_06", texto: "No Inverno, o meu aquecimento passa por:", opcoes: ["Vestir as calças polares, 2 casacos e meias grossas", "Ligar os aquecedores no máximo como se fosse Agosto", "Fazer um chá e ficar agarrado/a à caneca", "Ficar encostado/a ao/à parceiro/a para roubar o calor dele/a"] },
    { id: "c_cd_p_07", texto: "Quando encomendo algo e a transportadora toca à porta de manhã:", opcoes: ["Vou atender vestido/a decentemente", "Finjo que não estou e vou buscar depois aos CTT", "Vou atender com a remela no olho e pijama ridículo", "Grito 'ESTÁ ABERTO, DEIXE NO TAPETE!'"] },
    { id: "c_cd_p_08", texto: "Se um filme for aborrecido no sofá:", opcoes: ["Paro o filme e vou limpar alguma coisa", "Fico no telemóvel até o filme acabar sozinho", "Adormeço em literalmente 4 minutos e começo a ressonar", "Começo a chatear e a picar quem estiver a ver comigo"] },
    { id: "c_cd_p_09", texto: "Na casa de banho, com o telemóvel:", opcoes: ["Entro e saio num minuto, higiénico", "Perco 30 minutos a fazer scroll no TikTok e fico com as pernas dormentes", "Levo o telemóvel e deixo cair ao chão ou no banho", "Aproveito para pôr as fofocas em dia no grupo do WhatsApp"] },
    { id: "c_cd_p_10", texto: "Comer na cama:", opcoes: ["Jamais! Cama é feita para dormir e descansar", "Só comer o pequeno-almoço tipo nos filmes", "Como bolachas e acordo a roçar em migalhas na cama toda", "Levo até tabuleiro com bife e batatas para a cama"] },
    { id: "c_cd_p_11", texto: "A minha capacidade para adiar alarmes (Snooze):", opcoes: ["Não adio, tocou, pulei!", "Meto 5 minutos a mais, uma única vez", "Adio durante uma hora inteira até ser impossível não me atrasar", "Desligo o alarme sem querer e adormeço para a vida"] },
    { id: "c_cd_p_12", texto: "Tomar banho aos fins de semana de preguiça:", opcoes: ["Tomo mal acordo, para ativar", "Deixo para o fim do dia, depois do lanche ajantarado", "A água do banho é um momento sagrado de 40 minutos", "Banho ao fim de semana? Fico a marinar no pijama"] },
    { id: "c_cd_p_13", texto: "Se a lareira ou aquecedor estiver longe:", opcoes: ["Faço o esforço para ir ligar", "Convenço outra pessoa de que ela é que tem frio para a obrigar a ligar", "Arrasto o tapete/manta pelo chão como um casulo", "Fico a tremer em silêncio"] },
    { id: "c_cd_p_14", texto: "Em relação ao estafeta do UberEats/Glovo:", opcoes: ["Estou no prédio à espera dele de máscara e vestido/a", "Peço para deixar à porta e rezo para que ninguém roube", "Digo 'pode subir ao 3º' porque não quero calçar sapatos", "Odeio que me liguem a perguntar onde é a rua"] },
    { id: "c_cd_p_15", texto: "O que acho da roupa 'Lounge Wear' (fatos de treino, calças confortáveis)?", opcoes: ["Eu saio à rua assim, é um estilo de vida!", "É só para usar dentro de casa", "Acho super azeiteiro, prefiro ganga mesmo em casa", "Lounge wear para mim é dormir de t-shirt rasgada de 2012"] },
    { id: "c_cd_p_16", texto: "Se me pedirem para ajudar em casa num Domingo:", opcoes: ["Eu sou a pessoa que já ajudou no Sábado todo", "Fujo e finjo que estou a estudar/trabalhar no PC", "Faço as coisas tão mal feitas que me mandam parar de ajudar", "Levanto-me bufando e a rosnar com os deuses"] },
    { id: "c_cd_p_17", texto: "Como passo o fim de uma noitada (Domingo ressacado/cansado)?", opcoes: ["Com óculos escuros dentro de casa e Ben-u-ron", "A comer fast-food até rebentar a ver filmes estúpidos", "Com energia surpreendente, vou dar uma corrida", "Prometo a todos os deuses que 'nunca mais bebo/saio'"] },
    { id: "c_cd_p_18", texto: "A fazer o pequeno almoço em dia de preguiça:", opcoes: ["Faço as super panquecas com mel e banana", "Meto leite e cereais diretos no estômago", "Não faço, peço no Glovo / Uber", "Como restos da pizza de ontem fria"] },
    { id: "c_cd_p_19", texto: "Dormir sestas (no sofá):", opcoes: ["Nunca durmo, perco o ritmo do dia", "Sesta de poder de 20 minutinhos é top", "Adormeço às 14h e acordo às 18h desorientado/a no tempo", "Fico com mau humor insuportável quando acordo"] },
    { id: "c_cd_p_20", texto: "Qual a minha desculpa oficial se estiver muito preguiçoso/a para sair?", opcoes: ["'Pah, estou exausto da semana de trabalho'", "'Já me tirei os sapatos e o pijama, agora não dá'", "'O meu animal de estimação precisa de mim'", "Não uso desculpas, digo na lata que não me apetece"] }
  ]
};
