import { PerguntaClassica } from "@/types/catalogo";

export const classico_comida_bebida: Record<string, PerguntaClassica[]> = {
  "sub_1_0": [ // Restaurantes e Fast Food
    { id: "c_cb_r_01", texto: "Como escolho o prato num restaurante?", opcoes: ["Vejo o menu online antes de ir", "Peço sempre exatamente a mesma coisa", "Demoro uma hora a decidir", "Pergunto ao empregado o que ele sugere"] },
    { id: "c_cb_r_02", texto: "Qual é a minha atitude quando a comida demora muito a chegar?", opcoes: ["Fico mal humorado/a e em silêncio", "Entupo-me de pão e azeitonas", "Começo a reclamar com os empregados", "Fico na boa, a conversa está boa"] },
    { id: "c_cb_r_03", texto: "Em relação a Sushi, qual é a minha posição?", opcoes: ["Amo de paixão, podia comer todos os dias", "Só como as peças fritas (Hot Rolls)", "Vou só pela companhia, não aprecio", "Detesto peixe cru, recuso-me a ir"] },
    { id: "c_cb_r_04", texto: "Como peço o ponto da minha carne?", opcoes: ["Em sangue (quase a mugir)", "Médio, no ponto perfeito", "Bem passada (autêntica sola de sapato)", "Não ligo, só como frango ou porco"] },
    { id: "c_cb_r_05", texto: "O que bebo normalmente à refeição num jantar fora?", opcoes: ["Água, sempre a opção segura", "Coca-cola ou outro sumo", "Cerveja ou um copo de Vinho", "Jarra de Sangria para dividir"] },
    { id: "c_cb_r_06", texto: "Qual é o meu fast food de eleição para o fim de noite/ressaca?", opcoes: ["McDonald's, clássico", "Um Kebab bem gorduroso", "Pizza às fatias", "Uma sandes de panado nas roulotes"] },
    { id: "c_cb_r_07", texto: "Num restaurante de Buffet / All-You-Can-Eat:", opcoes: ["Faço 5 rondas, dou prejuízo à casa", "Fico cheio/a logo no primeiro prato", "Foco-me estrategicamente só nas sobremesas", "Evito ir, acho que não tem qualidade"] },
    { id: "c_cb_r_08", texto: "Qual é a minha tolerância a picante?", opcoes: ["Meto picante em absolutamente tudo", "Gosto daquele toque suave", "Choro e suo com uma pimenta preta", "Peço 'extra picante' para me armar e depois sofro"] },
    { id: "c_cb_r_09", texto: "Quando sobra comida no prato no restaurante:", opcoes: ["Peço sempre uma caixa para levar para casa", "Tenho vergonha de pedir caixa", "Como até rebentar para não deixar nada", "Deixo no prato, não sou de me forçar"] },
    { id: "c_vp_r_10", texto: "Como atuo num rodízio de Pizzas?", opcoes: ["Como fatias até me doer a barriga", "Foco-me muito mais nas pizzas doces", "Só como 3 ou 4 fatias, não compensa", "Roubo os rebordos recheados aos outros"] },
    { id: "c_cb_r_11", texto: "A minha opinião sobre comer sozinho num restaurante:", opcoes: ["Faço na boa, adoro a minha própria companhia", "Sinto-me um extraterrestre julgado por todos", "Só se for um fast food rápido", "Fico agarrado ao telemóvel para disfarçar"] },
    { id: "c_cb_r_12", texto: "Qual é a minha política de gorjetas?", opcoes: ["Deixo sempre, a não ser que corra mal", "Só se o serviço for incrivelmente bom", "Apenas arredondo a conta para não haver trocos", "Nunca deixo, já pago o serviço na conta"] },
    { id: "c_cb_r_13", texto: "Se apanhar um cabelo na minha comida:", opcoes: ["Faço um escândalo e exijo o livro de reclamações", "Tiro disfarçadamente para o lado e como o resto", "Chamo o empregado à parte com educação", "Perco a fome imediatamente, quero ir embora"] },
    { id: "c_cb_r_14", texto: "Sobre encomendar comida para casa (Uber Eats, Glovo):", opcoes: ["Mando vir quase todos os dias, que vício", "Só como recompensa ao fim de semana", "Prefiro ir buscar lá para não pagar taxas", "Acho um roubo, cozinho ou vou lá"] },
    { id: "c_cb_r_15", texto: "Na hora de escolher o restaurante com um grupo de amigos:", opcoes: ["Deixo os outros decidirem, sou fácil", "Faço uma lista com votações", "Tento sempre impor a minha vontade", "Digo 'qualquer um' e depois reclamo da escolha"] },
    { id: "c_cb_r_16", texto: "As entradas no restaurante (pão, azeitonas, queijo):", opcoes: ["Mando logo para trás para não cobrar", "Como tudo e ainda peço mais uma dose", "Só toco no pão com manteiga", "Não toco para guardar espaço para o prato"] },
    { id: "c_cb_r_17", texto: "Na hora de pagar uma conta de grupo:", opcoes: ["Dividimos em partes iguais por todos", "Faço as contas ao cêntimo ao que eu comi", "Eu pago tudo e depois façam-me MBWay", "Fujo para a casa de banho na hora da conta"] },
    { id: "c_cb_r_18", texto: "Em jantares de aniversário grandes eu sou o/a:", opcoes: ["O primeiro a bazar a dar desculpas", "O que fica a beber até o restaurante fechar", "O que vai só pela comida e fala pouco", "O que organiza as prendas e a vaquinha"] },
    { id: "c_cb_r_19", texto: "O que faço com o guardanapo no fim da refeição?", opcoes: ["Dobro direitinho e deixo na mesa", "Faço uma bola toda amarrotada", "Atiro para cima do prato sujo", "Levo no bolso sem reparar"] },
    { id: "c_cb_r_20", texto: "A minha relação com vinho no restaurante:", opcoes: ["Adoro provar vinhos diferentes e bons", "Peço sempre o vinho da casa, mais barato", "Não ligo a vinho, só bebo para acompanhar", "Fico 'alegre' logo no primeiro copo"] }
  ],
  "sub_1_1": [ // Gostos Peculiares
    { id: "c_cb_g_01", texto: "Pizza com ananás?", opcoes: ["É um crime contra a culinária mundial", "A melhor invenção, adoro a mistura doce/salgado", "Como se me derem, mas não é a minha 1ª escolha", "Tiro os pedaços de ananás disfarçadamente"] },
    { id: "c_cb_g_02", texto: "Qual é a minha relação com coentros?", opcoes: ["Amo, metia coentros em absolutamente tudo", "Sabe-me literalmente a sabão, fujo disso", "Como mas não aquece nem arrefece", "Só tolero na comida alentejana"] },
    { id: "c_cb_g_03", texto: "O que faço com a borda da pizza?", opcoes: ["Como sempre, é pão!", "Deixo sempre abandonada no prato", "Uso para limpar o molho de alho/ketchup", "Só como se tiver recheio de queijo"] },
    { id: "c_cb_g_04", texto: "Comer restos de comida fria do dia anterior (ex: pizza fria):", opcoes: ["O pequeno-almoço dos campeões, adoro", "Tenho SEMPRE de aquecer no micro-ondas", "Que nojo, não como comida fria", "Faço-o por pura preguiça de aquecer"] },
    { id: "c_cb_g_05", texto: "A acompanhar as batatas fritas: Ketchup ou Maionese?", opcoes: ["Ketchup a inundar as batatas", "Maionese sempre", "Misturo os dois para fazer molho rosa", "Não ligo a molhos, como simples"] },
    { id: "c_cb_g_06", texto: "Entre Doce ou Salgado?", opcoes: ["Sou formiga, doce sempre", "Salgados e petiscos para toda a vida", "Preciso de um doce depois do salgado", "Depende puramente do meu estado de espírito"] },
    { id: "c_cb_g_07", texto: "O meu nível de obsessão por queijo:", opcoes: ["Sou um rato autêntico, como qualquer um", "Só como derretido (pizzas, tostas, gratinados)", "Cheira a chulé, não consigo comer", "Só gosto daqueles tipo Flamengo ou Limiano"] },
    { id: "c_cb_g_08", texto: "O que faço às crostas/côdeas do pão de forma?", opcoes: ["Tiro sempre com uma faca", "É a melhor parte, como tudo", "Como sem pensar nisso", "Só tiro se forem daquelas sandes de festa infantis"] },
    { id: "c_cb_g_09", texto: "A minha relação com o café?", opcoes: ["Sobrevivo à base de 4 ou 5 cafés diários", "Bebo só um de manhã para abrir os olhos", "Detesto o sabor a café, nunca bebo", "Bebo cheio de leite e açúcar, que nem sabe a café"] },
    { id: "c_cb_g_10", texto: "Como é a minha relação com a Sopa?", opcoes: ["Como sempre antes do prato principal", "Só como no Inverno profundo", "Detesto sopa, traumatismos de infância", "Só gosto se for um creme bem passado sem pedaços"] },
    { id: "c_cb_g_11", texto: "Quando abro um pacote de bolachas:", opcoes: ["Como duas ou três e fecho bem apertado", "Marcha o pacote todo num instante", "Deixo abertas e no dia seguinte estão moles", "Apenas abro as Oreo para comer o recheio do meio"] },
    { id: "c_cb_g_12", texto: "A comer peixe assado:", opcoes: ["Adoro, sou um mestre a limpar espinhas", "Gosto do sabor mas não tenho paciência para espinhas", "Só como lombos, tranches ou douradinhos", "Fica a cheirar mal, prefiro carne 1000 vezes"] },
    { id: "c_cb_g_13", texto: "Misturar várias comidas no prato:", opcoes: ["Sim, no estômago junta-se tudo na mesma", "Não, as comidas não podem tocar umas nas outras", "Faço um 'vulcão' de puré com molho no meio", "Misturo tudo num monte antes de comer"] },
    { id: "c_cb_g_14", texto: "A minha escolha na secção das Gomas:", opcoes: ["Ursinhos e coisas fofas de morango/laranja", "Aquelas com muito açúcar ácido que queimam a língua", "Aquelas pretas esquisitas de Alcaçuz", "Não sou nada pessoa de gomas"] },
    { id: "c_cb_g_15", texto: "O meu hábito de comer fruta:", opcoes: ["Como as minhas várias peças de fruta diárias", "Sou demasiado preguiçoso/a para descascar fruta", "Só como maçãs e bananas que são mais práticas", "A minha dose de fruta vem do sumo Compal"] },
    { id: "c_cb_g_16", texto: "A textura de comida que eu mais odeio é:", opcoes: ["Coisas gelatinosas e moles demais", "Coisas muito secas que encalham a engolir", "Pedaços duros escondidos no meio de coisas moles", "Qualquer coisa com sementes ou grainhas"] },
    { id: "c_cb_g_17", texto: "A minha posição oficial sobre cebola crua:", opcoes: ["Amo, dá aquele 'crunch' nas saladas", "Retiro os cubinhos todos do prato com precisão cirúrgica", "Dá-me logo azia e passo o dia a arrotar a cebola", "Só como se for muito disfarçada ou caramelizada"] },
    { id: "c_cb_g_18", texto: "Como tempero a minha salada?", opcoes: ["Tem que estar a nadar num oceano de azeite e vinagre", "Só um fiozinho muito subtil de azeite", "Sal e chega", "Não tempero, como tipo coelho"] },
    { id: "c_cb_g_19", texto: "A minha sobremesa de eleição num restaurante costuma ser:", opcoes: ["Uma daquelas 'mousses' pesadas (Baba de Camelo, Chocolate)", "Um clássico bolo de bolacha", "Uma peça de fruta só por descargo de consciência", "Já não há espaço para doces, peço só o café"] },
    { id: "c_cb_g_20", texto: "Água das Pedras (com gás)?", opcoes: ["Adoro, fresquinha com limão é espetacular", "Sabe a água de bateria misturada com TV estática", "Bebo quando estou mal do estômago", "Prefiro cerveja logo de uma vez"] }
  ]
};