import { PerguntaClassica } from "@/types/catalogo";

export const classico_cozinha_culinaria: Record<string, PerguntaClassica[]> = {
  "sub_21_0": [ // Desastres na Cozinha
    { id: "c_cc_d_01", texto: "Qual é o meu nível de habilidade a fritar um ovo?", opcoes: ["Mestre pasteleiro, gema perfeita no centro", "Rebento sempre a gema a tirar para o prato", "O óleo salpica-me e eu fujo com a espumadeira na mão", "Ovo frito? Eu queimo a frigideira só a aquecer o azeite"] },
    { id: "c_cc_d_02", texto: "Quando decido cozinhar massa (esparguete) para uma pessoa:", opcoes: ["Meso a dose perfeitamente com o medidor", "Faço um olho clínico impecável", "Faço comida que dá para um batalhão de 10 fuzileiros", "Sai um bloco de massa colada que parece cimento"] },
    { id: "c_cc_d_03", texto: "O que acontece ao arroz que eu faço?", opcoes: ["Fica soltinho e maravilhoso, arroz de restaurante", "Fica em papa (quase arroz doce salgado)", "Queimo sempre o fundo do tacho", "Esqueço-me do sal e sabe a papelão molhado"] },
    { id: "c_cc_d_04", texto: "Ao tentar fazer um bolo com pacote de supermercado (Banca Branca):", opcoes: ["Fica esponjoso e divinal, como diz a caixa", "Fica espalmado como uma panqueca rija", "Esqueço-me do fermento ou troco sal por açúcar", "Queima por fora e fica líquido por dentro"] },
    { id: "c_cc_d_05", texto: "Se estiver a cozinhar e faltar um ingrediente na receita:", opcoes: ["Vou a correr ao supermercado comprar", "Substituo por outra coisa à sorte e estrago tudo", "Desisto do prato e mando vir comida de fora", "Faço sem isso e finjo que a receita era mesmo assim"] },
    { id: "c_cc_d_06", texto: "Ao tentar virar uma panqueca/crepe no ar na frigideira:", opcoes: ["Viro com pinta e estilo de chef com 3 estrelas Michelin", "A massa fica colada ao teto ou cai no chão", "Uso 3 espátulas em pânico para não a partir a meio", "Nunca tentei, prefiro usar uma pinça com as duas mãos a tremer"] },
    { id: "c_cc_d_07", texto: "A descongelar carne para o jantar:", opcoes: ["Tiro de véspera para o frigorífico, super organizado", "Lembro-me às 19h e tento descongelar no micro-ondas de urgência", "Tento separar os bifes com uma faca de talho à bruta", "A carne vai direta do congelador para o tacho a parecer uma pedra"] },
    { id: "c_cc_d_08", texto: "Como lido com cebola a cozinhar?", opcoes: ["Corto a cebola de óculos de sol/mergulho a chorar", "Corto tão rápido que nem dou por isso", "Queimo a cebola até ficar preta ('está bem caramelizada')", "Compro daquela já picada e congelada no saco para não sofrer"] },
    { id: "c_cc_d_09", texto: "O que costumo deitar no tacho enquanto 'experimento':", opcoes: ["O clássico toque de noz-moscada e ervas aromáticas", "Deito molho de soja, natas, mostarda e rezo aos santos", "Meto alho em pó, pimenta e sal em quilos industriais", "Nada, tenho medo de temperar e ficar salgado"] },
    { id: "c_cc_d_10", texto: "Quando cozinho, o estado final da cozinha é:", opcoes: ["Vou lavando enquanto cozinho, fica tudo limpo", "Caos absoluto, pingo óleo na parede e farinha no teto", "Uma desgraça, uso 10 tachos para fazer um refogado básico", "Obrigo quem vai comer a limpar tudo depois"] },
    { id: "c_cc_d_11", texto: "Tentar fazer pipocas no tacho à antiga:", opcoes: ["Saiem douradas, estaladiças e com o sal perfeito", "Ficam mais de metade dos milhos pretos no fundo por estourar", "O tacho pega fogo e soa o alarme de incêndio", "Compro sempre pipocas de micro-ondas, quem tem paciência?"] },
    { id: "c_cc_d_12", texto: "Ao assar qualquer coisa no forno:", opcoes: ["Sigo o tempo do relógio e tiro no ponto ideal", "Abro a porta do forno de 2 em 2 minutos para cuscar", "Esqueço-me completamente e só dou por ela quando cheira a queimado", "Deixo lá o pirex depois do jantar a ganhar bolor até à próxima semana"] },
    { id: "c_cc_d_13", texto: "A usar o liquidificador / batedeira:", opcoes: ["Faço smoothies fitness impecáveis", "Esqueço-me de pôr a tampa e a cozinha fica forrada a sumo", "Tenho pavor do barulho que aquilo faz e tapo os ouvidos", "Faço purés que ficam sempre com bocados rijos gigantes a meio"] },
    { id: "c_cc_d_14", texto: "A minha capacidade para cortar alho:", opcoes: ["Pico fininho como ensinam na TV", "Fica em cubos do tamanho de berlindes para quem quiser tropeçar neles", "Esmago tudo com o punho e mando lá para dentro com a casca", "A minha mão cheira a alho durante 3 dias seguidos"] },
    { id: "c_cc_d_15", texto: "Em caso de pequeno fogo na frigideira:", opcoes: ["Desligo o bico e abfo com uma tampa tranquilamente", "Grito em pânico, atiro água para cima e faço uma bola de fogo", "Começo a soprar a achar que é uma vela de anos", "Pego no tacho a correr pela casa toda à procura da rua"] },
    { id: "c_cc_d_16", texto: "Tentativas de seguir tutoriais de cozinha do TikTok/Instagram:", opcoes: ["Saco o prato igual e meto nas minhas redes também", "Faço igual mas gasto o triplo do dinheiro dos ingredientes", "A meio desisto e acabo a fazer esparguete com atum", "Não tento, eu só vejo os vídeos para me abrir o apetite"] },
    { id: "c_cc_d_17", texto: "Como abro latas de conservas/cogumelos?", opcoes: ["Com o abre-latas clássico super profissional", "Puxo a anilha, a anilha parte e fico a olhar para a lata indignado", "Uso uma faca afiada a tentar abrir à bruta com perigo de morte", "Esguicho a água da lata diretamente para os olhos e roupa"] },
    { id: "c_cc_d_18", texto: "Quando não sei se o óleo está quente o suficiente:", opcoes: ["Uso um termómetro ou testo com uma ponta de pão", "Atiro água e queimo-me na cara quando espirra", "Meto o dedo a ver se escalda (sim, eu sou doido)", "Atiro a comida lá para dentro, se borbulhar, está feito"] },
    { id: "c_cc_d_19", texto: "Ao escorrer a água da massa:", opcoes: ["Uso o passador de rede como um mestre italiano", "Seguro com a tampa meia torta e a massa cai toda na banca e ralo", "Queimo as mãos sempre com o vapor de água a subir", "Deixo a massa na água até servir no prato cheia de caldo"] },
    { id: "c_cc_d_20", texto: "A minha desculpa favorita para um desastre culinário:", opcoes: ["'Isto chama-se comida rústica, é de propósito'", "'A receita na internet estava toda mal escrita'", "'O meu fogão aquece demais de um lado'", "'Se não gostarem, há iogurtes no frigorífico'"] }
  ],
  "sub_21_1": [ // Pratos de Assinatura
    { id: "c_cc_p_01", texto: "Se convidar amigos para jantar em minha casa, o meu prato principal (seguro) é:", opcoes: ["Lasanha à Bolonhesa ou Esparguete com natas e cogumelos", "Arroz de Pato, strogonoff ou bacalhau com natas de chorar por mais", "Mando vir pizzas grandes e sirvo nos pratos de loiça", "Salsichas com esparguete cruzado e finjo que é alta gastronomia"] },
    { id: "c_cc_p_02", texto: "O toque secreto que uso sempre na comida:", opcoes: ["Uma folha de louro e vinho branco para deglaçar", "Encher tudo de queijo derretido por cima (queijo esconde tudo)", "Ketchup, serve para tapar os piores defeitos", "Manteiga em quantidades desumanas para dar sabor"] },
    { id: "c_cc_p_03", texto: "Quando sirvo comida aos meus convidados:", opcoes: ["Limpo as bordas do prato para parecer um Masterchef", "Atiro com a concha e fica a parecer comida de cantina escolar", "Faço doses minúsculas e digo 'quem quiser repete'", "Sirvo direto do tacho no meio da mesa para se aviarem sozinhos"] },
    { id: "c_cc_p_04", texto: "Na hora das entradas de um jantar preparado por mim:", opcoes: ["Tábua de queijos, presunto, patés e uvas super 'aesthetic'", "Ponho Ruffles num tigelão de plástico e azeitonas", "Pão e manteiga com pacote de tostas redondas", "Não há entradas, passem direto ao prato que eu não tenho tempo"] },
    { id: "c_cc_p_05", texto: "Quando perguntam 'O que tem isto?', a minha atitude é:", opcoes: ["Dar a receita toda orgulhoso, com medidas", "Dizer 'É segredo de família!' (Achei a receita no Google)", "Invento nomes de especiarias que nem estão no prato", "Digo 'tem amor e carinho' porque não me lembro do que pus lá"] },
    { id: "c_cc_p_06", texto: "A sobremesa típica que eu ofereço:", opcoes: ["Mousse de chocolate caseira divinal ou Doce da Casa", "Tarte de Maçã/Bolo de bolacha que dá muito trabalho", "Gelado de caixa de 2L do supermercado com colher à bruta", "Salada de frutas a encher para compensar os estragos da refeição"] },
    { id: "c_cc_p_07", texto: "Ao fazer um prato de churrasco / barbecue:", opcoes: ["Sou o mestre da grelha, viro o febras com timing exato", "Esqueço as carnes na grelha e ficam pretas estilo carvão", "Pico os hambúrgueres todos e as salsichas com o garfo", "Fico só a ver os outros fazer e venho com o pratinho estendido"] },
    { id: "c_cc_p_08", texto: "No que toca a pratos tradicionais portugueses (ex: Cozido à Portuguesa):", opcoes: ["Faço de olhos fechados, a minha avó ensinou-me", "Gosto de comer mas dá muito trabalho, não faço", "Acho que levo o triplo do tempo que as outras pessoas a fazer", "Tento dar 'toques modernos' (tipo pôr abacate) e estrago a receita"] },
    { id: "c_cc_p_09", texto: "A minha sopa de assinatura é:", opcoes: ["Sopa da pedra com enchidos, cenoura, e feijão", "Creme de legumes verde genérico onde bato tudo com a varinha mágica", "Canjinha de galinha para os doentes", "Sopa instantânea de pacote que junto água quente e fervo"] },
    { id: "c_cc_p_10", texto: "Quando a comida não está boa num jantar que fiz:", opcoes: ["Passo o jantar inteiro a justificar-me e a pedir desculpa", "Nem menciono, finjo que a receita original era assim", "Pergunto 'Está bom?' 50 vezes e obrigo as pessoas a elogiar", "Fico com pena de mim mesmo e digo 'não comam, vou mandar vir sushi'"] },
    { id: "c_cc_p_11", texto: "Quando vou a jantares em casas alheias (poto-luck):", opcoes: ["Levo uma travessa com comida feita por mim no forno", "Compro um Bolo-Rei ou uma garrafa de vinho à pressa nas bombas", "Levo a barriga vazia e a fome, apenas", "Levo coca-cola, sumos e cervejas, safa sempre"] },
    { id: "c_cc_p_12", texto: "Qual é a minha refeição de conforto (para mim próprio)?", opcoes: ["O clássico Mac and Cheese (Massa e Queijo)", "Bife com ovo a cavalo e batata frita", "Sopa e tostas, super básico", "Cereais Chocapic numa taça gigante às 21h"] },
    { id: "c_cc_p_13", texto: "Como avalio a minha própria comida:", opcoes: ["Acho que sou autêntico Gordon Ramsay disfarçado", "Acho super sem sal mas os outros dizem que está bom", "Odeio a minha própria comida depois de ficar 2 horas a sentir o cheiro no tacho", "Como porque não tenho outra opção e odeio gastar guito na rua"] },
    { id: "c_cc_p_14", texto: "Qual o ingrediente que eu ponho sempre a mais sem querer?", opcoes: ["Natasss, a comida fica a nadar em natas líquidas", "Alho, para afastar os vampiros todos da localidade", "Picante, acabo a suar sozinho a comer", "Queijo parmesão que custa uma fortuna a grama"] },
    { id: "c_cc_p_15", texto: "Na cozinha para vegetarianos/vegans:", opcoes: ["Faço um caril de lentilhas super espetacular", "Frito um bocado de Tofu que sabe a borracha queimada", "Faço massa com tomate, não sei inventar mais", "Digo-lhes para trazerem um tupperware de casa porque só sei fazer bifes"] },
    { id: "c_cc_p_16", texto: "A cozer bifes de frango ou peru:", opcoes: ["Ficam tenros e suculentos, com limão e mostarda", "Ficam rijos como chinelos, passo meia hora a mastigar um bocado", "Acabo a cortar tudo aos cubinhos para disfarçar no prato", "Banho a carne em maionese para dar humidade"] },
    { id: "c_cc_p_17", texto: "Fazer francesinhas caseiras:", opcoes: ["Faço o molho todo do zero, demora horas mas compensa", "Compro o molho no frasco do supermercado e meto no pão", "Acaba por ser só uma tosta mista com bife e não cheira a francesinha", "Isso come-se é no restaurante no Porto, em casa não invento!"] },
    { id: "c_cc_p_18", texto: "Para agradar às crianças (sobrinhos/filhos):", opcoes: ["Faço Douradinhos e Esparguete, o prato mundial da miudagem", "Obrigo a comerem sopa de peixe porque 'tem que ser'", "Pizzas de massa fresca caseiras, viro o padeiro", "Compro nuggets e eles acham que sou o máximo"] },
    { id: "c_cc_p_19", texto: "Quando sobram restos do grande jantar do dia anterior:", opcoes: ["Faço o famoso 'Empadão de restos' ou 'Roupa Velha'", "Como religiosamente os tupperwares 4 dias seguidos sem reclamar", "Deixo a estragar no frigorífico e deito ao lixo passada 1 semana", "Dou o que sobrou aos meus cães ou aos animais da rua"] },
    { id: "c_cc_p_20", texto: "A melhor frase sobre mim como anfitrião/ã:", opcoes: ["'Come-se bem, mas a cozinha fica um horror'", "'O melhor cozinheiro do grupo'", "'Vamos a casa dele, mas temos de encomendar pizza de certeza'", "'Ele serve muito álcool para o pessoal não reparar no sabor da comida'"] }
  ]
};
