import { PerguntaClassica } from "@/types/catalogo";

export const classico_cultura_lazer: Record<string, PerguntaClassica[]> = {
  "sub_3_0": [ // Filmes e Séries
    { id: "c_cl_f_01", texto: "No cinema, o que faço às pipocas?", opcoes: ["Acabam antes do filme começar", "Como devagar ao longo do filme", "Faço imenso barulho nas partes silenciosas", "Não compro, trago gomas escondidas na mala"] },
    { id: "c_cl_f_02", texto: "Quando vejo uma série com o/a meu/minha parceiro/a:", opcoes: ["Sou fiel e espero sempre por ele/a", "Vejo episódios às escondidas e finjo surpresa", "Adormeço sempre a meio", "Passo o tempo a perguntar 'quem é este gajo?'"] },
    { id: "c_cl_f_03", texto: "O meu género favorito para ver à noite:", opcoes: ["Comédia para relaxar e dormir bem", "Terror para ter pesadelos", "Documentários sobre serial killers", "Dramas românticos para chorar a chorar"] },
    { id: "c_cl_f_04", texto: "Como lido com spoilers?", opcoes: ["Odeio, corto relações com quem me der spoilers", "Não me importo nada, até vou ler à Wikipédia", "Dou spoilers aos outros sem querer", "Só vejo coisas 5 anos depois de saírem, logo, levo com tudo"] },
    { id: "c_cl_f_05", texto: "Quando digo 'só mais um episódio':", opcoes: ["É mesmo só mais um e vou dormir", "Vejo a temporada inteira até às 5 da manhã", "Adormeço nos primeiros 10 minutos desse episódio", "Digo isso 4 vezes seguidas"] },
    { id: "c_cl_f_06", texto: "Qual a minha reação em cenas de choro?", opcoes: ["Choro desalmadamente, preciso de lenços", "Fica-me uma lágrima no canto do olho, mas disfarço", "Fico a olhar para os outros a ver se estão a chorar", "Rio-me do quão irrealista é"] },
    { id: "c_cl_f_07", texto: "Para ver um filme em casa, o ambiente tem de ser:", opcoes: ["Luzes apagadas, silêncio absoluto, nível cinema", "Pode estar malta a falar, não me chateia", "Com o telemóvel na mão a fazer scroll ao mesmo tempo", "Cheio de comida e mantas à mistura"] },
    { id: "c_cl_f_08", texto: "O que faço quando um filme não me cativa nos primeiros 15 minutos?", opcoes: ["Desisto e vou ver a minha série de conforto de sempre", "Vou ver até ao fim, agora já comecei", "Começo a ver o telemóvel mas deixo o filme a dar", "Adormeço logo ali"] },
    { id: "c_cl_f_09", texto: "Em relação a ver filmes repetidos:", opcoes: ["Adoro, vejo os meus favoritos 20 vezes", "Odeio, se já sei o final não tem piada", "Só se for um clássico na época de Natal (tipo Sozinho em Casa)", "Vejo e esqueço-me sempre do que acontece, parece novo"] },
    { id: "c_cl_f_10", texto: "Qual é a minha opinião sobre filmes de terror?", opcoes: ["Amo, quanto mais sustos melhor", "Vejo mas com a almofada a tapar os olhos", "Odeio, perco noites de sono", "Acho aborrecido, nunca me assusto"] },
    { id: "c_cl_f_11", texto: "No que toca a reality shows (Big Brother, Casa dos Segredos):", opcoes: ["Vejo tudo religiosamente e comento no Twitter", "Vejo e finjo que não vejo para não me julgarem", "Não vejo mas sei tudo pelos memes", "Odeio e critico quem vê"] },
    { id: "c_cl_f_12", texto: "Qual o meu snack favorito para maratonas no sofá?", opcoes: ["Pipocas de micro-ondas", "Gelado direto da caixa", "Gomas e chocolates", "Batatas fritas do pacote familiar"] },
    { id: "c_cl_f_13", texto: "Quando um personagem favorito morre:", opcoes: ["Faço o luto durante uma semana", "Fico aziado/a e ameaço deixar de ver", "Vou ao Google ver se ressuscita", "Não me apego a personagens, é só ficção"] },
    { id: "c_cl_f_14", texto: "Prefiro ver filmes dobrados ou legendados?", opcoes: ["Legendados sempre, som original", "Dobrados, não tenho paciência para ler", "Dobrados só se for de animação", "Tanto me faz, só quero ver as imagens"] },
    { id: "c_cl_f_15", texto: "Qual a minha desculpa para adormecer a meio de um filme?", opcoes: ["'Estava só a descansar os olhos'", "'O filme era bué chato'", "'Estive a ouvir tudo, podes perguntar!'", "'O sofá é demasiado confortável'"] },
    { id: "c_cl_f_16", texto: "Se fosse um personagem de cinema, eu seria:", opcoes: ["O herói de ação que salva o mundo", "O alívio cómico (palhaço de serviço)", "O vilão com um plano brilhante", "O primeiro a morrer no filme de terror"] },
    { id: "c_cl_f_17", texto: "Quando sai um filme muito falado (hype):", opcoes: ["Vou logo no dia de estreia ver ao cinema", "Espero que chegue às plataformas de streaming", "Ganho aversão e recuso-me a ver", "Vejo pirata no PC com péssima qualidade"] },
    { id: "c_cl_f_18", texto: "Na hora de escolher o que ver na Netflix:", opcoes: ["Passo 40 minutos a escolher e acabo por ir dormir", "Vejo logo a primeira sugestão que aparece", "Tiro à sorte ou deixo outra pessoa decidir", "Vejo a mesma série pela 5ª vez (The Office/Friends)"] },
    { id: "c_cl_f_19", texto: "Séries longas (8 temporadas) vs Minisséries:", opcoes: ["Séries longas, adoro apegar-me aos personagens", "Minisséries, começo e acabo no mesmo dia", "Tanto faz, desde que seja bom", "Séries longas, mas desisto na 3ª temporada"] },
    { id: "c_cl_f_20", texto: "O que eu mais odeio que façam enquanto vemos um filme:", opcoes: ["Fazer perguntas sobre o enredo sem parar", "Estar no telemóvel com o brilho no máximo", "Mastigar de boca aberta", "Adivinhar o final em voz alta"] }
  ],
  "sub_3_1": [ // Hobbies e Tempos Livres
    { id: "c_cl_h_01", texto: "Quando começo um novo hobby:", opcoes: ["Compro o material todo caro e desisto passada uma semana", "Dedico-me a 100% e viro um perito nisso", "Faço meia dúzia de vezes e esqueço", "Só pesquiso muito sobre o assunto e nunca chego a começar"] },
    { id: "c_cl_h_02", texto: "Qual é a minha relação com a leitura?", opcoes: ["Devoro dezenas de livros por ano", "Compro imensos livros mas só servem de decoração", "Só leio nas férias na praia", "Ler? Só as legendas da Netflix"] },
    { id: "c_cl_h_03", texto: "No que toca a videojogos:", opcoes: ["Sou um 'tryhard' competitivo que berra com a TV", "Jogo só coisas chill (Sims, Animal Crossing)", "FIFA ou FIFA, o resto é conversa", "Só jogo Candy Crush no telemóvel ou no trânsito"] },
    { id: "c_cl_h_04", texto: "O meu dia ideal para 'não fazer nada' envolve:", opcoes: ["Ficar de pijama da manhã até à noite", "Ir para uma esplanada apanhar sol", "Jogar playstation até me doerem os olhos", "Dormir sestas de 3 horas"] },
    { id: "c_cl_h_05", texto: "Se me derem tintas e uma tela:", opcoes: ["Faço uma obra de arte digna de museu", "Desenho um boneco de palitos trágico", "Pinto a cara, as mãos e a roupa toda", "Faço algo abstrato e digo que tem 'significado profundo'"] },
    { id: "c_cl_h_06", texto: "A minha relação com plantas e jardinagem:", opcoes: ["Tenho uma selva em casa, falo com elas", "Deixo morrer até os cactos", "Compro plantas de plástico no IKEA", "Rego um dia a mais, no outro esqueço-me, elas sobrevivem"] },
    { id: "c_cl_h_07", texto: "No meu tempo livre, a minha prioridade é:", opcoes: ["Dormir e recuperar energias", "Estar com amigos e socializar", "Fazer algo produtivo e aprender coisas novas", "Fazer scroll no telemóvel até o dedo ficar dormente"] },
    { id: "c_cl_h_08", texto: "Quando tento fazer uma receita complicada que vi no TikTok:", opcoes: ["Fica perfeito e partilho no Instagram", "Incendeio a cozinha e mando vir Uber Eats", "Fica feio mas o sabor até se come", "Fica a meio, farto-me e vou comer pão"] },
    { id: "c_cl_h_09", texto: "Qual a minha desculpa para desistir do ginásio?", opcoes: ["'Não tenho tempo com o trabalho/faculdade'", "'Dói-me o corpo todo, hoje é dia de descanso'", "'Está a chover/muito calor lá fora'", "Eu não desisto, eu vou sempre (mentira)"] },
    { id: "c_cl_h_10", texto: "Em relação a coleções (selos, moedas, figuras):", opcoes: ["Tenho uma coleção valiosíssima desde criança", "Tentei fazer coleções quando era miúdo/a mas perdi tudo", "Coleciono mas é tralha e lixo em casa", "Acho isso uma perda de dinheiro"] },
    { id: "c_cl_h_11", texto: "A cantar no karaoke, eu sou:", opcoes: ["O artista principal, dou tudo no palco", "O que canta baixinho cheio de vergonha", "O que só vai se estiver bêbado", "O que fica na mesa a rir e a gravar para chantagear"] },
    { id: "c_cl_h_12", texto: "O que acho de atividades ao ar livre (caminhadas, trilhos)?", opcoes: ["Amo a natureza, respiro ar puro", "Vou, mas passo a vida a queixar-me que estou cansado/a", "Mosquitos, suor e terra? Não, obrigado.", "Só vou pelas fotos para meter no Instagram"] },
    { id: "c_cl_h_13", texto: "Sobre fazer puzzles ou puzzles 3D:", opcoes: ["Tenho paciência de santo, adoro", "Faço a borda e perco a vontade", "Meto uma peça mal e atiro o puzzle pela janela", "Acho super secante"] },
    { id: "c_cl_h_14", texto: "Quando tenho a casa só para mim:", opcoes: ["Metos a música aos berros e danço de cuecas", "Aproveito para fazer uma limpeza profunda", "Ando a vaguear pelos quartos sem rumo", "Fecho tudo a cadeado com medo do escuro"] },
    { id: "c_cl_h_15", texto: "Em relação a jogos de tabuleiro (Monopólio, Catan):", opcoes: ["Sou o que lê as regras e explica a todos", "Roubo dinheiro ao banco quando ninguém vê", "Viro a mesa quando estou a perder", "Deixo de prestar atenção a meio do jogo"] },
    { id: "c_cl_h_16", texto: "O meu conhecimento de cultura geral em quizzes é:", opcoes: ["Sou uma enciclopédia viva", "Só sei coisas inúteis sobre celebridades", "Sou aquele que diz respostas à toa com grande confiança", "Zero, sou uma vergonha para a equipa"] },
    { id: "c_cl_h_17", texto: "Qual a minha relação com a fotografia?", opcoes: ["Tenho câmara profissional e edito tudo", "Acho que sou fotógrafo/a mas é só filtros do Instagram", "As minhas fotos saem sempre desfocadas ou com o dedo à frente", "Odeio tirar fotos e fujo das câmaras"] },
    { id: "c_cl_h_18", texto: "Quando decido arrumar a casa como hobby:", opcoes: ["Começo e acabo impecavelmente", "Começo a arrumar, encontro coisas antigas e fico a vê-las horas", "Arrumo as coisas atirando tudo para dentro do armário", "Desisto logo na primeira gaveta"] },
    { id: "c_cl_h_19", texto: "Para relaxar, a minha melhor tática é:", opcoes: ["Um banho de espuma longo", "Música clássica ou chill-out", "Bater boca com malta na internet", "Um copo de vinho ou cerveja"] },
    { id: "c_cl_h_20", texto: "Se tivesse um ano sabático com tudo pago:", opcoes: ["Viajava de mochila às costas pelo mundo", "Passava o ano a fazer absolutamente zero", "Abria um negócio de artesanato manhoso", "Passava o ano na festa"] }
  ]
};
