import { PerguntaClassica } from "@/types/catalogo";

export const classico_desastres_gafes: Record<string, PerguntaClassica[]> = {
  "sub_26_0": [ // Momentos Embaraçosos
    { id: "c_dg_m_01", texto: "Quando aceno de volta a alguém na rua e afinal não era para mim:", opcoes: ["Meto logo a mão no cabelo a fingir que estava a ajeitar o penteado", "Baixo a cabeça, fico roxo/a e apresso o passo em pânico", "Continuo a acenar e finjo que acenei para um pombo atrás deles", "Rio-me alto e assumo a vergonha na cara dura"] },
    { id: "c_dg_m_02", texto: "Tropeçar e quase cair na rua no meio de imensa gente:", opcoes: ["Dou uma corridinha parva a disfarçar o desequilíbrio", "Fico a olhar para o chão e chuto o passeio a fingir que a culpa foi da pedra", "Caio no chão e fico à espera que os bombeiros me levem", "Olho em volta de forma agressiva a ver se alguém se riu"] },
    { id: "c_dg_m_03", texto: "A clássica gafe de puxar uma porta que diz 'Empurre' (ou vice-versa):", opcoes: ["Forço a porta três vezes antes de reparar na placa", "Olho para os lados a ver se alguém viu a minha burrice", "Bato com a cara no vidro porque ia a andar lançado/a", "Critico a arquitetura da porta e do edifício para justificar o erro"] },
    { id: "c_dg_m_04", texto: "Quando envio uma mensagem/print a falar mal de alguém... PARA ESSA MESMA PESSOA:", opcoes: ["Atiro o telemóvel ao rio e mudo de identidade", "Digo 'Ups, enganei-me na janela, era para o/a X' e fujo do país", "Apago para todos num milissegundo e finjo loucura", "Tento inventar uma justificação esfarrapada de que era uma piada"] },
    { id: "c_dg_m_05", texto: "Ao ir cumprimentar alguém: A pessoa vai para dar dois beijos e eu dou aperto de mão (ou aperto no ar):", opcoes: ["Acabamos a dar cabeçadas desajeitadas", "Fico preso/a a meio caminho com a mão estendida e a cara na cara da pessoa", "Transformo o aperto de mão num abraço de urso estranho", "Peço desculpa e refaço a coreografia de cumprimento do zero"] },
    { id: "c_dg_m_06", texto: "A barriga a dar roncos altíssimos numa sala ou reunião hiper silenciosa:", opcoes: ["Tusso ou arrasto a cadeira para abafar o som", "Meto as mãos na barriga e aperto-a para ver se cala", "Finjo que o barulho veio da cadeira ou da pessoa do lado", "Digo a rir 'eia, que fominha!' e assumo a vergonha"] },
    { id: "c_dg_m_07", texto: "Deixar cair a garfo/copo num restaurante super requintado:", opcoes: ["O restaurante todo silencia-se e eu fico a querer desaparecer", "Mergulho debaixo da mesa para apanhar, batendo com a cabeça", "Finjo que não fui eu e peço desculpa ao empregado super baixinho", "Começo a rir de nervoso enquanto me tentam limpar a mesa"] },
    { id: "c_dg_m_08", texto: "Cumprimentar uma grávida perguntando 'de quantos meses estás?' e a pessoa não estar grávida:", opcoes: ["'Desculpa, era o corte do vestido!' e choro por dentro", "Quero, de facto, desaparecer num buraco negro para a eternidade", "Tento desviar o assunto elogiando-lhe os sapatos", "O silêncio fica tão constrangedor que vou embora a meio da conversa"] },
    { id: "c_dg_m_09", texto: "Estar no autocarro e ceder o lugar a uma pessoa idosa, e a pessoa ficar ofendida ('eu não sou velho!'):", opcoes: ["Fico de pé o resto da viagem com cara de parvo", "Sento-me de volta a murmurar desculpas à janela", "Insisto até a pessoa se sentar para provar o meu ponto", "Saio na paragem seguinte mesmo que não seja a minha"] },
    { id: "c_dg_m_10", texto: "Cuspir para os sapatos/telemóvel de alguém a falar com muito entusiasmo:", opcoes: ["Limpo discretamente a gota de saliva com a manga do casaco", "Finjo que começou a chover dentro da sala", "Peço desculpa e perco toda a vontade de falar a seguir", "A pessoa limpa com nojo e eu faço de conta que não vi"] },
    { id: "c_dg_m_11", texto: "Estar com o microfone ligado no Zoom sem saber, e dizer algo vergonhoso:", opcoes: ["Desligo a chamada em pânico e digo que a net foi abaixo", "Ouçou os colegas rir e fico mudo/a até à reunião acabar", "Digo que era o meu cão ou irmão no fundo a falar", "Assumo a idiotice e começo a pedir desculpa a todos"] },
    { id: "c_dg_m_12", texto: "Andar na rua com papel higiénico colado ao sapato:", opcoes: ["Se alguém avisar, tento chutar para o arbusto a disfarçar", "Ando 3 quarteirões com estilo e não noto de nada", "Entro em choque porque percebo que 500 pessoas olharam", "Acho que a rua é suja e eu estou a ajudar a limpar"] },
    { id: "c_dg_m_13", texto: "Apresentarem-me alguém e, 5 segundos depois, perguntar 'desculpa, qual era o nome?':", opcoes: ["Pergunto sempre, a minha memória de curto prazo é um lixo", "Chamo 'amigo' ou 'querida' o dia todo para esconder", "Espero que outro colega diga o nome dele para eu apanhar", "Digo 'Eu sei o teu nome, queria era o teu apelido!'"] },
    { id: "c_dg_m_14", texto: "Chamar 'Mãe' ou 'Pai' à professora / chefe:", opcoes: ["Finjo logo uma tosse gigante para camuflar", "Fica a sala toda a olhar para mim enquanto o meu rosto derrete de calor", "Corrijo rápido e gaguejo 3 vezes a seguir", "Digo que foi uma piada (ninguém se ri)"] },
    { id: "c_dg_m_15", texto: "Estar a ouvir música com fones, soltar um pum e achar que foi silencioso (mas não foi):", opcoes: ["Olho em choque para as pessoas ao redor, elas olham, e eu tiro os fones", "Culpo as solas dos sapatos na tijoleira", "Odeio o meu corpo e evito essa loja para sempre", "Tusso com força para cobrir o eco"] },
    { id: "c_dg_m_16", texto: "Cantar uma música num inglês enrolado, e de repente o som desliga e toda a gente ouve a minha voz:", opcoes: ["Fico mudo/a com a boca aberta num 'O'", "Finjo que estava a fazer um sotaque jamaicano de propósito", "Rio-me e digo 'Grande cantor, hã?'", "Peço ao DJ para não voltar a fazer isso porque me arruinou a moral"] },
    { id: "c_dg_m_17", texto: "Dar os parabéns à pessoa errada no dia errado do Facebook:", opcoes: ["A pessoa agradece confusa e eu não digo nada", "Apago a mensagem à ninja antes que ela veja", "Aviso que 'foi adiantado para não me esquecer'", "Culpo a app por me notificar mal"] },
    { id: "c_dg_m_18", texto: "Ficar com um bocado de alface ou feijão preso nos dentes da frente e sorrir horas para o crush:", opcoes: ["Quando descubro no espelho em casa deito-me no chão de vergonha", "A pessoa que estava comigo não avisou, e eu corto relações com ela", "Tento tirar discretamente com a língua enquanto falo (e fico a fazer macacadas com a boca)", "Sempre que pergunto 'tenho algo nos dentes' dizem que não (mentirosos)"] },
    { id: "c_dg_m_19", texto: "Andar e ir de cara contra um poste ou placar de rua enquanto olhava para o telemóvel:", opcoes: ["Dou uma cabeçada monumental, meto o telemóvel no bolso e ando o dobro da rapidez", "Fico tonto/a a olhar para os lados a ver quem filmou o momento trágico", "Culpo a Câmara Municipal por pôr sinais onde não deve", "Começo a sangrar do nariz e aceito que foi karma digital"] },
    { id: "c_dg_m_20", texto: "Ao ir a uma porta de vidro extremamente limpa num shopping:", opcoes: ["Esmago o nariz e o vidro fica com uma mancha oleosa da minha cara", "Tento desviar à Matrix à última hora", "Culpo a senhora da limpeza por ser demasiado boa no seu trabalho", "Bato, afasto-me, e uso a porta da esquerda com dignidade destruída"] }
  ],
  "sub_26_1": [ // Erros a Falar
    { id: "c_dg_e_01", texto: "Quando o empregado do restaurante diz 'Bom Apetite!', a minha resposta automática é:", opcoes: ["'Igualmente!' e quero a eutanásia de imediato", "'Obrigado!' mas gaguejo porque ia dizer a frase acima", "Digo 'Pra ti também' como se ele fosse partilhar a batata frita", "Sorrio de boca cheia de pão de alho sem dizer nada"] },
    { id: "c_dg_e_02", texto: "Na bilheteira do cinema dizem 'Bom Filme!', eu:", opcoes: ["Digo 'Bom Filme também para si!' e fujo com o balde das pipocas", "Respondo 'Ok!' num tom estúpido de nervoso", "Fico calado/a e sinto-me mal educado/a", "Sou mestre e digo só 'Obrigado', sem deslizes"] },
    { id: "c_dg_e_03", texto: "Engasgar-me com a minha própria saliva a meio de uma frase importante:", opcoes: ["Fico a tossir 5 minutos de olhos vermelhos em agonia pura", "Tento continuar a falar com uma voz de guincho de porco", "Aviso que 'falei demasiado rápido' enquanto choro a tossir", "Sinto que estou a afogar-me no deserto e peço água a berrar"] },
    { id: "c_dg_e_04", texto: "Quando quero dizer uma palavra super simples (ex: Vassoura) mas esqueço-me:", opcoes: ["Fica 'Aquela cena de varrer com pêlos no fim'", "Faço a mímica de varrer intensamente até me perceberem", "Mudo o assunto da conversa porque a vergonha é muita", "Fico a estalar os dedos a dizer 'coiso... tu sabes o coiso'"] },
    { id: "c_dg_e_05", texto: "Trocar as palavras e dizer asneiras sem querer (ex: Cagalho em vez de Cavalo):", opcoes: ["Fico a rir histericamente com a minha própria asneira", "Faço de conta que disse a palavra certa muito rápido", "A pessoa fica a olhar em choque e eu peço desculpas divinas", "Começo a suar frio e arruíno o meu argumento sério"] },
    { id: "c_dg_e_06", texto: "Ao dizer adeus a um grupo de amigos, despeço-me e... vamos todos na mesma direção:", opcoes: ["Andamos lado a lado em silêncio de morte", "Saco do telemóvel e ando devagar para os deixar ir à frente", "Digo 'Olha que giro, vamos para o mesmo lado!' e forço conversa", "Vou por outra rua e dou uma volta ao quarteirão para evitar o pânico"] },
    { id: "c_dg_e_07", texto: "Quando dou uma resposta num exame ou numa aula com convicção e está ERRADA:", opcoes: ["O professor responde com desprezo e eu derreto na cadeira", "Tento argumentar que foi 'noutro contexto' ou que me enganei no século", "Rio e digo 'estava a testar se os meus colegas estavam com atenção'", "Calo-me e passo o resto da aula a olhar furiosamente para os sapatos"] },
    { id: "c_dg_e_08", texto: "Gaguejar a meio de uma discussão onde eu tinha toda a razão:", opcoes: ["Perco logo o direito à razão e eles gozam comigo", "Re-arranco a frase com ainda mais fúria", "Fico tão enervado/a com o gaguejo que me calo e vou embora", "A voz desafina para os agudos e faço figura de miúdo/a ofendido/a"] },
    { id: "c_dg_e_09", texto: "Quando o dentista me faz perguntas com as mãos e brocas dentro da minha boca:", opcoes: ["Tento falar e sai um 'Uuhh guuh ghh'", "Faço só sons guturais de aprovação e aceno as sobrancelhas", "Odeio e finjo que não percebi a pergunta", "O dentista faz a própria conversa e responde por mim"] },
    { id: "c_dg_e_10", texto: "Quando o corretor automático me trama no WhatsApp do chefe/sogra:", opcoes: ["Mando beijinhos ou javardices à minha chefe por erro do corretor", "Corrijo com um 'asterisco (*)' num pânico transpirado", "Apago a mensagem a mil à hora e meto um 'emoji' de sorriso para tapar", "Invento que o meu telemóvel estava no bolso e teclou sozinho"] },
    { id: "c_dg_e_11", texto: "Alguém conta-me uma coisa séria, eu não ouço e sorrio dizendo 'Pois é...':", opcoes: ["A pessoa diz 'A minha avó morreu' e eu sorrio", "Tento salvar a situação dizendo 'Que pena' com a cara de luto", "Descobrem que eu não ouvi e levo um sermão", "Uso o 'Pois é...' para 90% dos meus problemas de audição"] },
    { id: "c_dg_e_12", texto: "Atender o telemóvel numa língua ou sotaque sem querer ('Alôôô?'):", opcoes: ["Faço voz de locutor de rádio e a seguir dou por ela", "Mando uma voz tão grossa de 'Estou?' que não me reconhecem", "Atendo bué profissional e é só o meu amigo a chamar-me estúpido", "As minhas chamadas começam sempre com um gaguejo inicial"] },
    { id: "c_dg_e_13", texto: "Estar a tentar contar uma anedota super engraçada, mas...:", opcoes: ["Rio-me tanto a meio que não consigo dizer as palavras, e perco o 'punchline'", "Esqueço-me do fim e estrago a piada à frente de toda a gente", "Conto a piada toda e no fim ninguém se ri. Um silêncio terrível.", "Demoro 10 minutos a dar contexto e a malta desinteressa-se a meio"] },
    { id: "c_dg_e_14", texto: "Trocar nomes de ex-namorados/as no meio de uma conversa:", opcoes: ["O erro fatal. Chamo Inês à Joana e vou comprar a campa", "Corrijo a meio da sílaba 'A I-Joana' e parece que tive um AVC", "Acuso a minha cabeça de estar cheia de problemas de trabalho", "Se me fizerem isso a mim, acabo com a pessoa no minuto seguinte"] },
    { id: "c_dg_e_15", texto: "Ao tentar ler um texto em inglês ou francês em voz alta na frente da turma/chefe:", opcoes: ["Pronuncio 'The' como 'De' e 'Apple' como 'Apél'", "Mando um sotaque hiper-britânico/americano para fingir que domino (cringe)", "Falo rápido e em tom baixo para os erros não se notarem", "Odeio, fico a suar do bigode e leio devagarinho a suar do sobaco"] },
    { id: "c_dg_e_16", texto: "Dizer a palavra do regionalismo (ex: Sapatilhas/Ténis) na zona errada do país:", opcoes: ["Sou insultado/a se pedir um 'fino' no Porto em vez de um 'Príncipe'", "Sou gozado/a pelos meus amigos do Norte se disser 'bitoque' e não 'prego'", "Defendo as minhas palavras até à morte e começo uma guerra regional na mesa", "Mudo o meu vocabulário à força para me encaixar e pareço um falso"] },
    { id: "c_dg_e_17", texto: "Cantar uma música em português e perceber anos depois que a letra era OUTRA completamente diferente:", opcoes: ["A vida toda cantei 'São vacas gerdas' em vez de 'são macacas meias'", "Quando os meus amigos me corrigiram jurei que eles é que estavam errados", "Fico com o meu cérebro destruído e agora nem consigo cantar a certa", "Continuo a cantar a minha versão porque é bem mais engraçada"] },
    { id: "c_dg_e_18", texto: "Apresentar um colega a outro e esquecer o nome de um deles naquele SEGUNDO:", opcoes: ["'Vou deixar-vos apresentar-vos' (fuga tática de mestre)", "Aponto e digo 'Este é o meu grande amigo... hã... o craque'", "Assumo e pergunto na cara dura: 'Desculpa, deu-me uma branca. Nome?'", "Fico calado a engolir em seco enquanto as duas pessoas se olham confusas"] },
    { id: "c_dg_e_19", texto: "Mandar um áudio ao caminhar na rua de Inverno ou com vento forte:", opcoes: ["A pessoa só ouve furacões e ruídos e eu repito 3 vezes a mesma coisa", "Eu oiço o meu próprio áudio depois, tenho nojo da minha voz e apago", "Gravo o áudio enquanto estou ofegante das escadas e pareço asmático", "Grito para o microfone do telemóvel à frente de velhotes chocados"] },
    { id: "c_dg_e_20", texto: "Começar uma frase com grande emoção e terminar com um 'portanto...' para não saber como acabar:", opcoes: ["Uso 'e coiso', 'e cenas' para fechar buracos nas minhas ideias brilhantes", "Deixo a frase pendurada à espera que o outro a acabe por mim", "Faço gestos com as mãos como se o silêncio explicasse tudo", "Digo 'percebeste o que eu quis dizer?' para escapar de livre"] }
  ]
};
