import { PerguntaClassica } from "@/types/catalogo";

export const classico_desporto_fitness: Record<string, PerguntaClassica[]> = {
  "sub_8_0": [ // Idas ao Ginásio
    { id: "c_df_g_01", texto: "A minha relação com o ginásio:", opcoes: ["Vou 5 dias por semana, não falho!", "Pago a mensalidade como doação e vou 2x ao mês", "Entro em Janeiro motivado e desisto em Março", "Ginásio? Prefiro sofá e Netflix"] },
    { id: "c_df_g_02", texto: "Qual é a minha rotina típica num dia de treino?", opcoes: ["Faço 20 mins na passadeira, pego em dois pesos e vou para casa", "Sigo o plano de treino à risca com cronómetro", "Vou para os aparelhos ver o telemóvel 10 mins de cada vez", "Vou para as aulas de grupo saltar e dançar Zumba"] },
    { id: "c_df_g_03", texto: "Como escolho a roupa de ir ao ginásio?", opcoes: ["Combino tudo perfeitamente para parecer um atleta", "Uso t-shirts de propaganda (ex: MEO Sudoeste 2014) largas", "Os calções mais confortáveis, não me importo com a estética", "Passo mais tempo a escolher a roupa do que a treinar"] },
    { id: "c_df_g_04", texto: "Quando vejo aquelas pessoas ultra-fit no ginásio:", opcoes: ["Fico super motivado/a e tento imitar", "Sinto-me um pudim de batata e fujo para as passadeiras", "Ignoro, estou ali na minha própria jornada", "Acho ridículo estarem a tirar selfies ao espelho o tempo todo"] },
    { id: "c_df_g_05", texto: "O que toca nos meus fones durante o treino?", opcoes: ["Hip-Hop e Rap para levantar peso pesado", "Música pimba ou reaggeton, tenho de ir animado/a!", "Podcasts (vou lá só para caminhar)", "Aquelas playlists de 'Beast Mode' que o Spotify sugere"] },
    { id: "c_df_g_06", texto: "No que toca a suar no ginásio:", opcoes: ["Saio de lá a escorrer, deixo tudo ensopado", "Transpiro só o suficiente para o brilho na foto", "Não suo, mas fico a parecer um tomate na cara", "Levo a minha toalhinha para disfarçar o cheiro"] },
    { id: "c_df_g_07", texto: "Qual a minha desculpa número um para falhar o treino?", opcoes: ["'Está a chover, não dá para sair de casa'", "'Trabalhei imenso hoje, o meu cérebro já treinou'", "'Tenho uma dorzita mínima no joelho'", "'Sexta-feira já não conta, só emagreço se treinar à segunda'"] },
    { id: "c_df_g_08", texto: "A minha tática para máquinas muito ocupadas:", opcoes: ["Fico a olhar intensamente para a pessoa até se ir embora", "Pergunto se 'podemos revezar'", "Vou fazer outra coisa qualquer e nunca mais volto lá", "Aproveito e vou logo beber água e fazer pausas"] },
    { id: "c_df_g_09", texto: "Depois de um treino pesado (Leg Day), eu:", opcoes: ["Não me consigo sentar na sanita nos dois dias seguintes", "Sinto-me um semi-deus e ando aos saltos", "Queixo-me a toda a gente que me dói as pernas", "Como um McDonald's inteiro porque 'hoje mereço'"] },
    { id: "c_df_g_10", texto: "Uso suplementos (Whey, Creatina, Pré-treino)?", opcoes: ["Bebo o meu shake de proteína no balneário cheio de força", "Tentei tomar mas acho que sabe tudo a pó e giz", "O meu único pré-treino é um café a correr", "Sou team comida a sério (arroz com frango)"] },
    { id: "c_df_g_11", texto: "No balneário, depois do banho eu:", opcoes: ["Fico logo a conversar nú/nua com toda a gente (vergonha zero)", "Escondo-me no canto com a toalha feita de tenda", "Nem tomo banho lá, vou logo para casa", "Demoro 45 minutos a secar o cabelo e a meter cremes"] },
    { id: "c_df_g_12", texto: "Tirar fotos ao espelho do ginásio:", opcoes: ["Tiro sempre, se não postar o treino não contou", "Tiro só nos dias em que sinto o músculo a inchar", "Tiro de longe para mandar aos amigos e fingir que vou", "Acho super azeiteiro, nunca tiro"] },
    { id: "c_df_g_13", texto: "Quando os PT's do ginásio vêm falar comigo:", opcoes: ["Adoro a atenção e finjo que estava a fazer tudo bem", "Abaixo a cabeça e ignoro, não quero comprar planos", "Entro em pânico achando que estava a fazer os movimentos todos mal", "Fico a fazer perguntas sobre tudo durante meia hora"] },
    { id: "c_df_g_14", texto: "Sobre o famoso cárdio (corrida/passadeira):", opcoes: ["Corro 10 km sem suar a gota", "Aguento 5 minutos a correr e sinto o pulmão a rasgar", "Faço sempre a inclinação no máximo a andar devagar e a ver o Insta", "Para cárdio já me basta correr para o autocarro"] },
    { id: "c_df_g_15", texto: "Qual a minha relação com a passadeira/bicicleta?", opcoes: ["Odeio de morte, os minutos nunca mais passam", "Levo a série da Netflix e passo lá 40 minutos fáceis", "Gosto mais do elítico, parece que não custa tanto", "Tento competir com a pessoa do lado sem que ela saiba"] },
    { id: "c_df_g_16", texto: "Nas Aulas de Grupo (BodyPump, RPM), eu sou:", opcoes: ["O super-coordenado que vai à frente da sala", "O que tropeça nos próprios pés e perde os passos todos", "O que desiste a meio e fica a fingir atrás", "Aquele/a que canta e grita quando o instrutor pede"] },
    { id: "c_df_g_17", texto: "Quando vejo um amigo no ginásio:", opcoes: ["Paro de treinar e ficamos 40 minutos na conversa", "Dou um aceno de cabeça de macho no espelho e sigo", "Fujo porque estou feio/a, suado/a e não quero falar", "Treinamos juntos a gritar 'VAMOS LÁ CARALHO!'"] },
    { id: "c_df_g_18", texto: "Se estiver com pressa, o que dispenso no treino?", opcoes: ["O aquecimento, vou logo pegar em carga", "Os abdominais, faço-os amanhã (nunca faço)", "Os alongamentos finais, fujo logo para o banho", "Dispenso o treino todo e volto noutro dia"] },
    { id: "c_df_g_19", texto: "A garrafa de água no ginásio:", opcoes: ["Levo o garrafão gigante de dois litros", "Levo uma garrafinha chique e bebo chiques pequenos", "Esqueço-me sempre e vou ao bebedouro meter a boca", "Bebo tanta água que passo o treino a ir à casa de banho"] },
    { id: "c_df_g_20", texto: "Fazer pesos livres vs Máquinas:", opcoes: ["Adoro agarrar nos halteres e ir para a zona dos 'pesados'", "Fico pelas máquinas, têm imagens a explicar e sinto-me seguro", "Máquinas é para fracos, eu faço levantamentos livres de força", "Sento-me na máquina e fico a mandar SMSs"] }
  ],
  "sub_8_1": [ // Futebol e Competição
    { id: "c_df_f_01", texto: "A ver o meu clube de futebol a jogar, eu sou quem:", opcoes: ["Grito com a TV, insulto o árbitro e os jogadores todos", "Fico super ansioso/a, como as unhas todas", "Vejo de forma chill, é só um jogo de futebol", "Só vejo os resumos dos golos e pergunto 'como ficou?'"] },
    { id: "c_df_f_02", texto: "Quando jogo FIFA ou outro jogo de desporto:", opcoes: ["Parte o comando se sofro golo no último minuto", "Sou o gajo chato que faz pausas táticas para gastar tempo", "Gosto de humilhar os amigos com dribles impossíveis", "Sou um bocado azelha, perco sempre mas aceito rindo"] },
    { id: "c_df_f_03", texto: "A minha reação numa peladinha ou jogo amigável:", opcoes: ["Entro a rasgar canelas, quero ganhar ou ganhar!", "Fico à defesa/baliza e corro o mínimo possível", "Sou aquele que corre imenso mas tem zero pés", "Se tiver a perder faço bico e digo que é injusto"] },
    { id: "c_df_f_04", texto: "O que acho de Padel (o desporto da moda)?", opcoes: ["Fiquei completamente viciado, comprei logo raquete caríssima", "Fui jogar 2 vezes para a foto do Instagram", "Acho que é só um desporto 'azeiteiro' mas jogo", "Recuso-me a jogar, só gosto de desportos a sério"] },
    { id: "c_df_f_05", texto: "Qual a minha especialidade desportiva natural?", opcoes: ["Correr rápido/Sprint (se o cão do vizinho se soltar)", "Força bruta (abrir os frascos de doce)", "Equilíbrio/Flexibilidade (para não cair nas passadeiras)", "Zero talento atlético, sou tipo um panda"] },
    { id: "c_df_f_06", texto: "Num jogo da seleção nacional no Euro/Mundial:", opcoes: ["Pinto a cara, uso o cachecol e vou para a rua celebrar", "Fico aziado se as táticas não forem as que eu disse ao ecrã", "Só vejo na hora dos golos e grito, nem sei os jogadores", "Gosto mais dos dias de folga no trabalho que os jogos dão"] },
    { id: "c_df_f_07", texto: "A lidar com as derrotas do meu clube:", opcoes: ["Aziado, não falem comigo no dia a seguir", "Meto as culpas todas no árbitro e na liga corrupta", "Não me afeta nada, a vida continua", "Escondo-me dos grupos de WhatsApp para não ser gozado"] },
    { id: "c_df_f_08", texto: "Num torneio de matraquilhos/ping-pong de bar:", opcoes: ["Faço roletas ilegais e festejo", "Fico em silêncio e destruo os adversários", "Bebo mais cervejas do que os golos que marco", "Acabo a discutir as regras e levo aquilo super a sério"] },
    { id: "c_df_f_09", texto: "Praticar desportos aquáticos ou de Inverno (Surf, Ski):", opcoes: ["Tenho alto estilo e agrado-me sempre a tentar cenas novas", "Engulo imensa água ou neve e acabo no hospital", "Fico pela areia ou pelo barzinho a beber imperial e a ver", "Adoro mas estou sempre gelado/a e a reclamar do frio"] },
    { id: "c_df_f_10", texto: "Quando organizo jogos entre amigos (ex: futsal às quintas):", opcoes: ["Sou quem aluga o campo e chateia o pessoal todo", "Digo 'vou' mas arranjo desculpas na hora para não aparecer", "Vou para dar pau, não me importa se o campo é caro", "Normalmente sou quem leva a bola para poder ser o capitão"] },
    { id: "c_df_f_11", texto: "A minha capacidade numa aula de natação / mar livre:", opcoes: ["Nado como um golfinho profissional", "Só nado à 'cãozinho' e fico aflito no fundo", "Apenas mergulho se não desfizer o cabelo", "Água acima da cintura é morte certa, fujo."] },
    { id: "c_df_f_12", texto: "Participar em maratonas ou corridas populares:", opcoes: ["Treino meses antes, compro ténis caros e tiro a foto na meta", "Vou só pelo convívio e caminho 90% do tempo", "Esquece, se estou a correr é porque a polícia vem aí", "Vou, arrependo-me a meio e prometo a mim mesmo não repetir"] },
    { id: "c_df_f_13", texto: "Qual a minha desculpa preferida ao falhar um golo / remate?", opcoes: ["'O sol bateu-me nos olhos'", "'Esta relva tem buracos / o piso escorrega'", "'Os meus sapatos não são apropriados'", "Digo só 'que azelha' e começo a rir"] },
    { id: "c_df_f_14", texto: "Competitividade em jogos de Família (Cartas, Party Games):", opcoes: ["Sou o pesadelo, berro com a minha avó se for preciso", "Tento fazer com que os putos mais pequenos percam, sem dó", "Desisto a meio para ir comer", "Sou o chato das regras: 'Não podem jogar assim!'"] },
    { id: "c_df_f_15", texto: "A minha postura sobre apostas e Placard (Jogos):", opcoes: ["Faço apostas loucas de 0.50 cêntimos com 20 equipas", "Sou profissional: analiso as estatísticas de equipas estranhas", "Acho isso uma perda de dinheiro, nunca jogo", "Só jogo quando há os grandes clássicos para a emoção"] },
    { id: "c_df_f_16", texto: "Quando os jogos de futebol dão grandes clássicos/derbis:", opcoes: ["Junto os amigos todos em casa e mando vir 10 pizzas", "Vou a correr para o tasco ver o jogo com minis", "Tranco a porta e vejo sozinho/a para não me chatearem", "Aproveito para ir ao shopping, não deve haver ninguém lá"] },
    { id: "c_df_f_17", texto: "Desportos Radicais (Skydiving, Bungee Jumping):", opcoes: ["Adorava fazer, zero medo!", "Faço, mas choro ou desmaio de pânico antes de saltar", "Só se me empurrarem e pagarem balúrdios", "Prefiro que o sofá radicalize até às minhas costas"] },
    { id: "c_df_f_18", texto: "Na escola, quando chegava o momento de escolher equipas para jogar:", opcoes: ["Era logo um dos dois capitães a escolher", "Era escolhido/a em segundo lugar por simpatia", "Ficava sempre para o fim a olhar para o chão", "Dava sempre o desculpa de ter dores de cabeça para não ir"] },
    { id: "c_df_f_19", texto: "Quando vejo a Super Bowl ou Finais desportivas gringas:", opcoes: ["Fico acordado de madrugada só pelo Show do Intervalo", "Finjo que percebo as regras, grito 'Touchdown!' fora de horas", "Adormeço passados 15 minutos", "Vejo o jogo no Youtube ao outro dia a saltar partes"] },
    { id: "c_df_f_20", texto: "Saber os nomes dos jogadores de futebol:", opcoes: ["Sei o plantel das 18 equipas da liga e suplentes", "Só sei o nome do Cristiano Ronaldo e do Messi", "Sei o nome, a idade e quem são as namoradas/mulheres deles", "Finjo conhecer 'Ah sim, o número 7 jogou muito'"] }
  ]
};
