import { PerguntaClassica } from "@/types/catalogo";

export const classico_dilemas_cenarios: Record<string, PerguntaClassica[]> = {
  "sub_14_0": [ // Escolhas Difíceis
    { id: "c_dil_e_01", texto: "Dilema de luxo: preferias ter internet super lenta para sempre ou nunca mais beber café/chá?", opcoes: ["Internet lenta, não vivo sem a cafeína diária", "Nunca mais bebia café, mas deixem-me a minha fibra ótica", "Já tenho os dois maus por isso estou habituado/a", "Mudo para sumos e não abdico do wi-fi da NASA"] },
    { id: "c_dil_e_02", texto: "Preferias saber exatamente COMO vais morrer ou QUANDO vais morrer?", opcoes: ["COMO, para poder evitar essa situação a vida toda", "QUANDO, assim faria um mega plano até lá de viagens e loucuras", "Nenhum dos dois, queria ser apanhado/a completamente de surpresa", "QUANDO, ia fazer créditos para não ter de pagar"] },
    { id: "c_dil_e_03", texto: "Para o resto da tua vida, só podes escolher um condimento:", opcoes: ["Ketchup, pões em absolutamente tudo", "Maionese, a gordura da felicidade", "Sal, o mais básico essencial", "Picante, para sofrer o resto da vida"] },
    { id: "c_dil_e_04", texto: "Ter o poder de voar (mas a 5km/h) ou poder de ficar invisível (mas a deitar um cheiro forte)?", opcoes: ["Voar a 5km/h, passava os engarrafamentos e o trânsito", "Invisível a cheirar mal, o pessoal que tapasse o nariz", "Ficar invisível e usava perfume fortíssimo para disfarçar", "Voar devagarinho e gozar com quem estava lá em baixo"] },
    { id: "c_dil_e_05", texto: "Para sempre: comer comida incrível servida com pelos, ou comer comida banal impecável?", opcoes: ["Comida banal. Pelos metem-me vómitos viscerais.", "Comida incrível, eu passava a vida a cuspir pelinhos", "Sou um cão de rua, como comida boa e marcham os pêlos!", "Banal. Gosto das coisas básicas."] },
    { id: "c_dil_e_06", texto: "Viajar no tempo 100 anos para o PASSADO ou 100 anos para o FUTURO?", opcoes: ["FUTURO, quero ver os carros voadores e as curas todas", "PASSADO, para ver como eles viviam e investir o dinheiro", "PASSADO, ia levar aspirina e ser o Deus lá do burgo", "FUTURO, mas tenho pânico dos robôs mandarem nisto tudo"] },
    { id: "c_dil_e_07", texto: "Nunca mais teres acesso a streaming (Netflix/Spotify) ou a Redes Sociais?", opcoes: ["Perder as redes sociais! A minha vida ficava tão mais pacífica.", "Perder o streaming. Consigo ver filmes cortados no TikTok.", "Não consigo escolher, preciso da injeção de dopamina de ambas.", "Sobrevivo a ler livros e ver o Preço Certo na TVI."] },
    { id: "c_dil_e_08", texto: "Dilema eterno: Nunca mais poder lavar os dentes ou nunca mais tomar banho?", opcoes: ["Não tomo banho, encho-me de perfume", "Não lavo os dentes, e ando sempre a mastigar pastilha elástica", "Os dois são nojentos, ia viver isolado no monte", "Banho não, eu tomava banho no mar com areia e ficava esfoliado"] },
    { id: "c_dil_e_09", texto: "Preferias ter o emprego dos teus sonhos com salário mínimo, ou um emprego aborrecido mas ganhar 10.000€/mês?", opcoes: ["10.000€! O meu sonho é só nas folgas e fins de semana", "O emprego dos sonhos! A paz de espírito não tem preço.", "Aborrecido a 10k! Passava os dias a chorar, mas num iate.", "Emprego de sonho, arranjava part-times para não morrer à fome."] },
    { id: "c_dil_e_10", texto: "Saber todos os idiomas do mundo fluente, ou saber tocar todos os instrumentos como um mestre?", opcoes: ["Idiomas! Viajava e nunca mais era enganado nos turismos", "Instrumentos! Virava o maior rockstar mundial a dar concertos", "Idiomas, para poder cuscar as conversas dos estranhos nos cafés", "Tanto faz, eu já mal sei falar o meu próprio português"] },
    { id: "c_dil_e_11", texto: "Perder todos os dentes e usar dentadura aos 30 anos, ou nunca mais poder cortar o cabelo?", opcoes: ["Dentadura! Assim eles são super brancos e tiro para dormir", "Cabelo gigante infinito. Ao menos atava e andava", "Dentadura, o dentista é o meu maior pesadelo logo", "Cabelo à Rapunzel, faria dreads que limpavam a rua toda"] },
    { id: "c_dil_e_12", texto: "Ler a mente das pessoas ou poder teletransportar-te?", opcoes: ["Teletransporte! Acordava em Bora-Bora, jantava em Roma.", "Ler mentes! Eu adoro saber a verdade de todos e fofocas.", "Ler mentes ia deixar-me deprimido/a (saber o que acham de mim)", "Teletransporte para nunca mais ter de conduzir em trânsito"] },
    { id: "c_dil_e_13", texto: "Trabalhar debaixo d'água no fundo do mar, ou no espaço sideral (estação espacial)?", opcoes: ["ESPAÇO. Gravidade zero, ver a Terra e flutuar com estilo.", "MAR. Ver sereias, peixes gigantes e ter paz submarina.", "Nenhum. Tenho claustrofobia extrema com as duas ideias.", "Espaço não, ia vomitar com a ausência de gravidade todos os dias."] },
    { id: "c_dil_e_14", texto: "Viver num Inverno constante (sempre neve) ou num Verão de 40 graus perpétuo?", opcoes: ["Neve! Lareira, mantas, sopa e roupa quente.", "40 graus! Praia, havaianas e ar condicionado. Odeio o frio.", "Verão, que a neve na cidade fica um asfalto sujo horrível.", "Neve, nos 40º e a suar no metro cheira tudo mal!"] },
    { id: "c_dil_e_15", texto: "Nunca mais poder comer batatas fritas (todas as versões) ou nunca mais comer chocolates?", opcoes: ["Tirava os chocolates na boa, sou team Salgado forever.", "Tirava as batatas fritas. Sobrevivo sem elas, mas o chocolate é Deus.", "Nem pensar, cortem um dedo em vez disso.", "Tirava o chocolate se pudesse compensar com 5Kg de gomas."] },
    { id: "c_dil_e_16", texto: "Renunciar ao telemóvel para sempre ou ter um onde a tua avó/mãe consiga ler todas as tuas mensagens?", opcoes: ["Sem telemóvel! Jamais os meus pais poderiam ver essas coisas.", "A avó que veja, ia ter ataques cardíacos diários a ler aquilo.", "Tinha o telemóvel e passava a falar em código secreto com os amigos.", "Deitava o telemóvel pela sanita abaixo agora mesmo."] },
    { id: "c_dil_e_17", texto: "Estar numa relação onde amas 100% mas és ignorado/a, ou onde não amas nada mas a pessoa te ama loucamente?", opcoes: ["A de não amar nada, ao menos é super prestável.", "Amar a 100%. Sou masoquista emocional.", "Prefiro ficar solteiro com 5 gatos e 3 cães.", "Ser amado/a não custa, faria amizade de negócios com ele/a."] },
    { id: "c_dil_e_18", texto: "Acordar amanhã de novo como um bebé recém-nascido (com as memórias de agora) ou com 80 anos (e as memórias do futuro)?", opcoes: ["Bebé! Refazia a vida toda a parecer um génio na primária.", "80 anos! Já não tinha de trabalhar, ia viver da reforma de luxo.", "Bebé, passava 5 anos a dormir e a comer sem preocupações.", "Ficar com 80 anos, dava o spoiler da lotaria aos netos."] },
    { id: "c_dil_e_19", texto: "Para o resto da vida: só poder andar a correr/sprint, ou só poder deslocar-te a rastejar?", opcoes: ["Correr! Ficava o rei das maratonas e fit, sem querer.", "Rastejar! Como um soldado americano para todo o lado.", "Correr, ia estar sempre a suar, mas andar de gatas ia rasgar a roupa toda.", "Punha rodas num sofá e nem corria nem rastejava."] },
    { id: "c_dil_e_20", texto: "Preferias ter um braço a nascer na tua testa ou não ter as duas orelhas?", opcoes: ["Sem orelhas! O cabelo/chapéus cobriam e metia um implante auditivo.", "O braço na testa! Ia ser útil para agarrar coisas quando tenho os dois braços cheios.", "Sem orelhas, ia parecer um alien mega fixolas.", "O braço ia tirar-me a visibilidade toda, por isso, ouvidos à vida."] }
  ],
  "sub_14_1": [ // Cenários Improváveis
    { id: "c_dil_c_01", texto: "Começa um Apocalipse Zombie agora mesmo. A tua primeira reação é:", opcoes: ["Ir a correr esvaziar o Continente e as prateleiras de enlatados", "Trancar a porta de casa e jogar consola até acabar a luz", "Pego numa panela e num esfregão de ferro e vou dar luta", "Ser a primeira pessoa a ser mordida para despachar já a ansiedade"] },
    { id: "c_dil_c_02", texto: "O teu animal de estimação passa a falar português fluente de um dia para o outro:", opcoes: ["Peço-lhe desculpa por tantas conversas embaraçosas que ele ouviu", "Tento convencê-lo a não contar aos outros o que me viu fazer em casa", "Conversamos sobre política e vida, adoro", "Fico com medo dele e fujo da casa porque é macabro"] },
    { id: "c_dil_c_03", texto: "Recebes uma caixa com um milhão de euros, com o aviso: se gastares, uma pessoa desconhecida aleatória sofre as consequências.", opcoes: ["Gasto logo a caixa inteira. O mundo é um sítio duro, lamento.", "Não toco no dinheiro, o meu peso na consciência não deixava.", "Gasto mas doo parte a instituições para compensar o Karma.", "Gasto tudo aos pouquinhos para 'não dar nas vistas' da maldição."] },
    { id: "c_dil_c_04", texto: "Acordas com 15 anos de idade na escola secundária. O que fazes diferente?", opcoes: ["Estudo para ter as melhores notas do mundo.", "Invento as Bitcoins e o TikTok", "Falo com a pessoa que eu tinha medo de convidar para sair.", "Teria dito umas valentes verdades aos meus pais mais cedo."] },
    { id: "c_dil_c_05", texto: "Na invasão dos Extra-Terrestres (UFOs) a chegar a Lisboa:", opcoes: ["Meto-me no monte em Trás-os-Montes escondido numa caverna", "Faço as malas e atiro-me aos pés deles a pedir para me levarem", "Tiro o telemóvel e faço um direto no TikTok.", "Saio a correr com um chapéu de folha de alumínio a berrar."] },
    { id: "c_dil_c_06", texto: "Vais parar sozinho/a a uma ilha deserta e só levas três coisas (banais):", opcoes: ["Uma faca, isqueiro e um livro do Bear Grylls.", "Um livro aborrecido, um telemóvel (sem rede) e os fones.", "Um colchão, óculos de sol e protetor solar.", "Levo o cão/gato, a Playstation e um gerador sem gasolina."] },
    { id: "c_dil_c_07", texto: "De repente ficas minúsculo (tamanho de uma formiga) na tua sala de estar:", opcoes: ["Monto um cavalo nas costas da minha gata e luto pela sobrevivência", "Tento não ser aspirado/a pelo aspirador automático", "Vou para debaixo do fogão viver com as baratas e ser o líder delas", "Morro esmagado/a por uma batata frita em 2 minutos"] },
    { id: "c_dil_c_08", texto: "A Netflix propõe fazer um Reality Show sobre a tua vida:", opcoes: ["Aceito, mas exijo o direito de edição porque sou azeiteiro/a às vezes", "Recuso, as pessoas iam fartar-se a ver-me comer pão no sofá o dia todo", "Aceito! Adoro o drama e eu criaria barracos falsos para render", "Só se me pagassem muito dinheiro para eu poder chorar rico"] },
    { id: "c_dil_c_09", texto: "Durante 24 horas as leis e regras não existem (Purga):", opcoes: ["Tranco-me no sótão da casa com 5 trincos e não respiro", "Vou à loja de tecnologia roubar todos os iPhones e portáteis caros", "Vou assaltar os supermercados todos de chocolates", "Levo a minha vingança a peito com aquela pessoa do escritório..."] },
    { id: "c_dil_c_10", texto: "Acordas no corpo do teu/tua parceiro/a (ou melhor amigo/a) (Sexta-Feira Louca):", opcoes: ["Vou gastar o dinheiro dele todo em prendas para o meu eu verdadeiro", "Passo o dia no quarto a inspecionar o novo corpo", "Vou ao trabalho dele fazer figura de estúpido para o queimar", "Mando mensagens estranhas aos contactos todos do telemóvel"] },
    { id: "c_dil_c_11", texto: "Recebes o poder de 'Parar o Tempo' (Stop). O que fazes?", opcoes: ["Durmo 12 horas extra todos os dias de manhã sem me atrasar", "Roubo coisas de lojas caras devagarinho", "Paro o tempo nas discussões para pesquisar argumentos e destruir a pessoa", "Aproveito para viajar de avião à pala do sistema parado"] },
    { id: "c_dil_c_12", texto: "Vais parar ao ano 1800. Qual é a tua técnica para enriquecer?", opcoes: ["Invento o hambúrguer/pizza e viro rei da restauração", "Tento inventar a lâmpada/carro primeiro e chamo-lhe o meu nome", "Dizem que sou bruxo/a por causa da higiene e cortam-me a cabeça", "Aproveito e digo 'eu é que faço os mapas, confiem'"] },
    { id: "c_dil_c_13", texto: "Um gênio oferece 3 desejos irreais. O que pedes?", opcoes: ["Dinheiro infinito, Comer sem engordar e Falar com animais", "Viajar no tempo, Não precisar de dormir, Dinheiro", "Ter beleza eterna, Que os outros façam o que mando e Dinheiro", "Peço mais desejos num loop infinito à tuga"] },
    { id: "c_dil_c_14", texto: "Tens que casar com a primeira pessoa que vês hoje quando saíres de casa:", opcoes: ["Rezo que seja o carteiro bonitão do prédio", "Tento não sair de casa nunca mais na vida para evitar acidentes", "Cruzei-me com a minha vizinha de 80 anos... é aceitar.", "Olho-me ao espelho... vou casar comigo mesmo!"] },
    { id: "c_dil_c_15", texto: "Vives no mundo do 'Harry Potter'. Que disciplina reprovas logo?", opcoes: ["Poções: Ia fazer um vulcão na sala de aula sem querer.", "Voo de Vassoura: Tenho pânico de alturas, chumbava no chão", "Transfiguração: Eu mal sei transformar massa em comida", "História da Magia: Ia adormecer como um tronco, chato demais"] },
    { id: "c_dil_c_16", texto: "Se a comida só se servisse em formato de 'Cápsula Nutritiva' futura:", opcoes: ["Adorava! Zero tempo gasto a cozinhar ou a lavar a loiça.", "Ficava deprimido, eu mastigo com os olhos e adoro enfartar-me.", "Tentava cozinhar as pílulas na mesma na frigideira para dar sabor", "Comia 10 cápsulas por refeição na mesma por vício"] },
    { id: "c_dil_c_17", texto: "Todas as manhãs acordas com um penteado horrível permanente novo:", opcoes: ["Ando sempre, e o resto da vida, de gorro e boné.", "Assumo o estilo 'maluco do bairro' e dou o litro nas roupas coloridas", "Rapo o cabelo a pente zero na máquina todos os dias", "Digo que sou influenciador de modas vanguardistas"] },
    { id: "c_dil_c_18", texto: "Ao chegares a casa tens lá um Dragão gigante que adora fazer festas:", opcoes: ["Pego nas rédeas e vou montá-lo no trânsito de amanhã", "Fecho a porta, e fujo para um hotel.", "Vou tentar assar salsichas na boca dele a cuspir fogo", "Crio um TikTok viral 'Como cuidar de lagartos de fogo'"] },
    { id: "c_dil_c_19", texto: "Tens a possibilidade de saber o maior segredo do governo. O que preferias?", opcoes: ["O Segredo da Área 51 (Extra-terrestres existem?)", "Onde está o ouro escondido pelo mundo", "Saber os vencedores dos campeonatos mundiais e apostar na Betano", "Não queria saber nada, depois matavam-me a saber demais"] },
    { id: "c_dil_c_20", texto: "Se as plantas do teu quarto tivessem sentimentos e pudessem falar:", opcoes: ["Começavam logo a insultar-me por me esquecer de as regar", "Agradeciam a música dos Pink Floyd que lhes dou de vez em quando", "Julgavam todas as figuras estranhas que eu faço a cantar ao espelho", "Choravam a pedir para não serem atiradas para o lixo"] }
  ]
};
