import { PerguntaClassica } from "@/types/catalogo";

export const classico_dinheiro_compras: Record<string, PerguntaClassica[]> = {
  "sub_10_0": [ // Hábitos de Consumo
    { id: "c_dc_h_01", texto: "No dia em que recebo o ordenado:", opcoes: ["Transfiro logo uma percentagem para a poupança", "Sinto-me rico/a e vou logo comer fora / fazer compras", "Pago as faturas e deprimo ao ver o saldo", "Fica lá quieto, tenho pânico de mexer no dinheiro"] },
    { id: "c_dc_h_02", texto: "A passear num Centro Comercial (Shopping):", opcoes: ["Tenho as lojas estudadas, vou, compro e saio em 10 mins", "Entro 'só para ver' e saio com 3 sacos de compras", "Fico o tempo todo na zona da restauração", "Acompanho os outros e seguro nos sacos deles"] },
    { id: "c_dc_h_03", texto: "Sobre as compras na Shein/Temu/AliExpress:", opcoes: ["Mando vir caixas gigantes todas as semanas", "Só encomendo coisas idiotas para a casa por 2 cêntimos", "Não uso, prefiro ver o que compro ao vivo", "Desconfio e não quero que roubem os meus dados"] },
    { id: "c_dc_h_04", texto: "Como lido com a secção de saldos?", opcoes: ["Odeio remexer em molhos de roupa atirada", "Mergulho de cabeça e encontro tesouros por 3€", "Compro coisas feias só porque estão baratas", "Ignoro os saldos e vou direto à nova coleção (mais cara)"] },
    { id: "c_dc_h_05", texto: "Na Primark ou no IKEA eu sou:", opcoes: ["O/a que compra 10 velas perfumadas e almofadas que não precisa", "O/a que se perde lá dentro e tem ataques de pânico", "Vou lá só pela comida/almôndegas", "Levo a lista e sigo as setas até ao fim rigidamente"] },
    { id: "c_dc_h_06", texto: "O que me faz abrir os cordões à bolsa mais rapidamente?", opcoes: ["Comida boa (Jantares, Uber Eats)", "Roupa e sapatilhas (Ténis)", "Experiências e viagens", "Gadgets e tecnologia que não preciso"] },
    { id: "c_dc_h_07", texto: "A pagar contas em jantares ou almoços:", opcoes: ["Sou o primeiro a sacar do cartão e a dizer 'MBWay?'", "Faço-me de distraído à espera que os outros paguem", "Tenho pânico de ficar a dever, pago no próprio segundo", "Tento sempre impingir a opção 'dividir por igual'"] },
    { id: "c_dc_h_08", texto: "Quando compro uma roupa e não me serve:", opcoes: ["Vou à loja trocar no próprio dia", "Fica 3 anos com a etiqueta guardada na gaveta", "Dou aos meus irmãos / amigos / mãe", "Deito para o lixo ou para doar, não tenho paciência"] },
    { id: "c_dc_h_09", texto: "Nas compras online:", opcoes: ["Encho o carrinho de coisas, vejo o total e fecho o site", "Sigo para pagamento à velocidade da luz sem pensar", "Deixo no carrinho 3 dias à espera que mandem cupão", "Farto-me de pesquisar códigos de desconto primeiro"] },
    { id: "c_dc_h_10", texto: "No que toca a dar esmolas ou doar dinheiro:", opcoes: ["Dou sempre as moedinhas soltas que tenho no bolso", "Digo 'não tenho trocos' e ando rápido", "Não dou na rua, mas faço donativos a associações", "Odeio as pessoas com pranchetas que abordam na rua"] },
    { id: "c_dc_h_11", texto: "Sobre assinaturas e mensalidades (Netflix, Spotify, Ginásio):", opcoes: ["Partilho contas com toda a família para poupar", "Pago 5 serviços de streaming e só vejo um", "Esqueço-me de cancelar o ginásio há meses", "Ando a criar e-mails novos para ter o primeiro mês grátis"] },
    { id: "c_dc_h_12", texto: "A minha reação quando alguém quer cobrar 2€ no MBWay:", opcoes: ["Mando logo, dívida é dívida", "Acho ridículo e sovina mas pago", "Finjo que me esqueci e espero que a pessoa desista", "Mando 5€ para compensar futuras cervejas"] },
    { id: "c_dc_h_13", texto: "Onde gasto a maioria do meu orçamento 'inútil'?", opcoes: ["Cafés, garrafas de água e pequenos lanches diários", "Jogos de raspadinhas ou Euromilhões", "Acessórios para o telemóvel e capas", "Skincare e produtos de beleza estupidamente caros"] },
    { id: "c_dc_h_14", texto: "Ir às compras ao supermercado com fome:", opcoes: ["O maior erro, trago o corredor dos doces inteiro", "Consigo controlar-me estoicamente", "Trago o carrinho cheio e nada que dê para cozinhar o jantar", "Acabo a comer pão na viagem de regresso a casa"] },
    { id: "c_dc_h_15", texto: "Quando vejo que um produto encareceu 20 cêntimos:", opcoes: ["Começo a reclamar da inflação mas levo na mesma", "Recuso-me a levar por princípio e vou a outro supermercado", "Nem reparo nos preços, passo o cartão e choro em casa", "Levo a versão 'marca branca' imediatamente"] },
    { id: "c_dc_h_16", texto: "Se vejo uma promoção de 'Pague 1, Leve 2':", opcoes: ["Levo logo 4", "Desconfio que está fora de validade", "Levo só se for de um produto não perecível (ex: papel higiénico)", "Ignoro, odeio acumular tralha na dispensa"] },
    { id: "c_dc_h_17", texto: "A minha relação com devoluções:", opcoes: ["Tenho os talões todos organizadinhos numa capa", "Perco o talão na viagem entre a loja e o meu carro", "Tenho vergonha de ir lá devolver coisas", "Tento ir devolver depois dos 30 dias com lábia"] },
    { id: "c_dc_h_18", texto: "Quando peço Uber/Bolt:", opcoes: ["Fico a ver o mapa em direto para os apressar", "Cancelado se vir que custa mais de 10€", "Peço, esqueço-me e deixo o motorista à espera na rua", "Dou conversa ao condutor a viagem inteira"] },
    { id: "c_dc_h_19", texto: "Numa loja cara (ex: Louis Vuitton, Gucci):", opcoes: ["Entro armado/a em rico e peço para ver as coisas", "Tenho medo de tocar em algo e ter de pagar", "Só passo à porta, não é para o meu bico", "Entro, olho para a etiqueta de preços e saio a rir"] },
    { id: "c_dc_h_20", texto: "Qual a minha desculpa para compras ridículas?", opcoes: ["'Foi merecido, a semana foi dura'", "'Estava em promoção, no fundo poupei dinheiro'", "'A vida é curta e eu posso morrer amanhã'", "'O dinheiro volta, as sapatilhas não'"] }
  ],
  "sub_10_1": [ // Gestão de Poupanças
    { id: "c_dc_p_01", texto: "Qual é o meu nível de controlo com o dinheiro?", opcoes: ["Tenho um Excel com categorias para cada despesa", "Olho para a app do banco com um olho tapado de medo", "Vou gastando até o cartão dar 'não autorizado'", "Saco do dinheiro todo em numerário e meto em envelopes"] },
    { id: "c_dc_p_02", texto: "A minha atitude em relação ao dinheiro que ponho de parte (poupança):", opcoes: ["Intocável! A não ser que seja vida ou morte", "Tiro de lá todos os meses porque chego ao fim a zeros", "O que é isso? O meu lema é 'vive hoje'", "Meto num PPR e finjo que não existe"] },
    { id: "c_dc_p_03", texto: "Quando os meus amigos me chamam para jantar fora num mês de 'vacas magras':", opcoes: ["Digo logo que não e fico a chorar misérias", "Vou, mas só como uma sopa e bebo água", "Vou, peço bife e no fim do mês choro no banho", "Minto e digo que já tenho outro jantar marcado"] },
    { id: "c_dc_p_04", texto: "O que acho de investir em coisas como Criptomoedas ou Ações?", opcoes: ["Sou o Lobo de Wall Street, vejo os gráficos todos os dias", "Meti lá 20€ uma vez e perdi-os, nunca mais", "Acho que isso é um esquema em pirâmide gigante", "Deixo o meu dinheiro num depósito a prazo, seguro!"] },
    { id: "c_dc_p_05", texto: "Se encontrasse uma nota de 50€ na rua:", opcoes: ["Olhava à volta, pisava, e enfiava no bolso", "Gritava 'Alguém perdeu isto?!'", "Entregava à polícia (ou na loja mais próxima)", "Tinha medo que fosse daqueles apanhados da TV"] },
    { id: "c_dc_p_06", texto: "Como lido com imprevistos grandes (ex: carro avariar)?", opcoes: ["Tenho o meu fundo de emergência robusto e intocável", "Entro em pânico e peço um empréstimo rápido", "Ligo aos pais a chorar", "Uso o cartão de crédito e lido com o problema no futuro"] },
    { id: "c_dc_p_07", texto: "A minha tática para poupar água/luz em casa:", opcoes: ["Ando aos gritos para os outros apagarem as luzes", "Tomo banhos militares de 3 minutos", "Durmo com 3 cobertores em vez de ligar o aquecimento", "Zero. Gosto de conforto, a conta logo se vê"] },
    { id: "c_dc_p_08", texto: "A minha relação com Mealheiros/Moedeiros em casa:", opcoes: ["Tenho um porco cheio de moedas e uso para viajar", "Acabo a abrir com uma faca a meio do mês para tirar dinheiro", "Perco as moedas soltas nos sofás, nem uso mealheiro", "Hoje em dia quem é que anda com dinheiro vivo?"] },
    { id: "c_dc_p_09", texto: "Como lido com a época do IRS (impostos)?", opcoes: ["Submeto logo no dia 1 e peço faturas com NIF em TUDO", "O meu contabilista/pai trata disso, não pesco nada", "Faço no último dia possível a suar e a rezar", "Ainda não percebo como é que a tabela de escalões funciona"] },
    { id: "c_dc_p_10", texto: "Se alguém me devesse 10€ há duas semanas:", opcoes: ["A cobrança já teria sido feita à bofetada", "Esquecia, não vou perder amizades por 10 paus", "Mando uma mensagem passivo-agressiva 'então, aquele dinheiro?'", "Perguntava diretamente, sem vergonha"] },
    { id: "c_dc_p_11", texto: "Qual a minha atitude perante créditos ou prestações (Cetelem, etc)?", opcoes: ["Fujo disso, só compro se tiver o dinheiro inteiro na mão", "Compro tudo a 10 vezes sem juros, adoro!", "Tenho tantos créditos que nem durmo de noite", "Uso com muita cautela só para eletrodomésticos caros"] },
    { id: "c_dc_p_12", texto: "O que diz o meu 'EU' consumista?", opcoes: ["'Poupar é para quem quer ser o mais rico do cemitério'", "'O dinheiro na conta a render dá-me mais paz do que sapatilhas'", "'O dinheiro é energia, tem de circular'", "'Se eu não vir o saldo na app, a dívida não é real'"] },
    { id: "c_dc_p_13", texto: "Como poupo na comida/supermercado?", opcoes: ["Faço refeições para a semana toda (Meal Prep)", "Ando à caça das etiquetas laranjas de fim de validade", "Comparo o 'preço por Kilo' com precisão matemática", "Não poupo, os supermercados roubam-me o ordenado todo"] },
    { id: "c_dc_p_14", texto: "A minha postura sobre comprar carros usados vs novos?", opcoes: ["Sempre usado, os novos desvalorizam mal saem do stand", "Novo, adoro o cheiro e sei que não dá problemas de início", "Não me importo, desde que ande e tenha o rádio a funcionar", "Carro? O meu meio de transporte é o passe navegante"] },
    { id: "c_dc_p_15", texto: "A usar Multibanco (ATM), eu:", opcoes: ["Tiro sempre 10€ ou 20€ no máximo", "Levanto sempre quantias absurdas para ter na carteira", "Fico 5 minutos a ler as operações todas do menu", "Aperto os botões na velocidade da luz para quem vem atrás"] },
    { id: "c_dc_p_16", texto: "Em que é que me custa MESMO gastar dinheiro?", opcoes: ["Roupa interior e meias", "Taxas de envio de entregas em casa (UberEats/CTT)", "Estacionamento (dou 5 voltas para não pagar paquímetro)", "Comida. Tudo o que seja mastigar é um desperdício de guito"] },
    { id: "c_dc_p_17", texto: "Se tivesse de organizar as finanças de um casal:", opcoes: ["Fazíamos uma conta conjunta e partilhávamos tudo", "Cada um com a sua conta, dividimos as despesas", "Eu mandava no dinheiro porque a pessoa gastava tudo", "Tinha uma conta secreta minha 'só por precaução'"] },
    { id: "c_dc_p_18", texto: "O que acho da lotaria (Euromilhões, Raspadinhas)?", opcoes: ["É o imposto dos pobres, nunca jogo", "Jogo uma vez por mês e imagino a vida de milionário", "Sou o velho da raspadinha na tabacaria todos os dias", "Costumo dar raspadinhas nos anos como prenda forreta"] },
    { id: "c_dc_p_19", texto: "Quando me proponho a guardar 100€ num mês:", opcoes: ["Guardo religiosamente no dia em que recebo", "Guardo mas tiro 20€ para jantares, depois 30€... fica a zero", "Começo com muita fé e acabo a gastar 200€ na Zara", "É impossível, isso é uma lenda urbana"] },
    { id: "c_dc_p_20", texto: "Qual a minha relação com a ideia de ser 'rico'?", opcoes: ["Se me pagarem bem, trabalho 16 horas por dia", "Quero ser rico sem ter de fazer nada por isso", "Não quero ser rico, só quero não ter de olhar para o preço das coisas", "Acho que o dinheiro só atrai falsidade e problemas"] }
  ]
};
