import { PerguntaClassica } from "@/types/catalogo";

export const classico_estudos_escola: Record<string, PerguntaClassica[]> = {
  "sub_29_0": [ // Cábulas e Truques
    { id: "c_ee_c_01", texto: "A minha técnica suprema de cábulas (copianço) na escola era:", opcoes: ["O clássico papelinho dentro do estojo da régua", "Escrever nas pernas/braços por baixo da manga comprida", "Fazia tudo minúsculo no Word e metia na tampa da calculadora/borracha", "Nunca copiei, tinha pânico de ser apanhado/a e morrer de vergonha"] },
    { id: "c_ee_c_02", texto: "Quando o professor passava por mim durante o teste:", opcoes: ["Ocultava a cábula num milissegundo como um ninja", "Ficava paralisado/a a suar e a olhar fixamente para a folha", "Tampava a resposta com o braço e fingia pensar profundamente", "Pedia para ir à casa de banho só para me acalmar"] },
    { id: "c_ee_c_03", texto: "Copiar pelo teste do colega do lado (girafão):", opcoes: ["Eu tinha o olho biónico, copiava até o nome dele sem querer", "Combinávamos sinais de tosse para as de escolha múltipla (1 tosse = A)", "Era impossível, a professora fazia a fila A e fila B", "Eu era a pessoa de quem os outros copiavam!"] },
    { id: "c_ee_c_04", texto: "A técnica de ir à casa de banho a meio do teste:", opcoes: ["Escondia o livro de Biologia atrás do autoclismo antes do teste", "Levava os apontamentos nos bolsos e lia sentado na sanita", "Tirava dúvidas com o colega que ia lá ao mesmo tempo", "Ia só mesmo para chorar e lavar a cara de desespero"] },
    { id: "c_ee_c_05", texto: "Na apresentação de um trabalho de grupo feito à última da hora:", opcoes: ["Eu era quem gaguejava a ler os slides da Wikipédia com links a azul", "Eu enchia chouriços com conversa fiada ('Como o meu colega bem referiu...')", "O professor fazia uma pergunta e nós ficávamos todos a olhar uns para os outros", "Eu não dizia nada, ficava a segurar na cartolina apenas"] },
    { id: "c_ee_c_06", texto: "Para justificar não ter feito os Trabalhos de Casa (TPC):", opcoes: ["Fingia estar a procurar furiosamente na mochila até a aula acabar", "Dizia a verdade: 'Deixei o caderno na outra mochila'", "Soprava a resposta ao vizinho da frente quando a professora não via", "Copiava à pressa no intervalo de 10 minutos antes da aula"] },
    { id: "c_ee_c_07", texto: "Como escondia telemóveis na aula (quando os smartphones começaram)?", opcoes: ["Dentro do estojo com o brilho no mínimo", "Entre as pernas/debaixo da mesa a teclar sem olhar", "Fingia que estava a assoar o nariz para esconder o ecrã", "Eu era apanhado/a sempre e ia para a caixa do professor"] },
    { id: "c_ee_c_08", texto: "Quando a matéria era de decorar (História, Biologia):", opcoes: ["Gravava a matéria em áudio e punha fones tapados pelo cabelo", "Memorizava só os títulos e inventava o resto do texto com lógica", "Apostava as fichas todas no que achava que saía e não lia o resto", "Estudava a sério, o meu cérebro é uma esponja"] },
    { id: "c_ee_c_09", texto: "A melhor mentira para faltar às aulas e ir ao café:", opcoes: ["'A stora faltou' (um clássico que a minha mãe acreditava sempre)", "Fingia febres e dores de cabeça épicas de manhã", "Falsificava as assinaturas na caderneta amarela/justificação", "Saltava o muro da escola quando os contínuos não viam"] },
    { id: "c_ee_c_10", texto: "A minha caligrafia de cábulas:", opcoes: ["Parecia árabe misturado com chinês, usava códigos secretos que eu percebia", "Imprimia fonte tamanho 4 no computador", "Escrevia com caneta de tinta invisível que só se via à luz azul (caneta mágica)", "Acabava a não conseguir ler a minha própria letra e errava a resposta"] },
    { id: "c_ee_c_11", texto: "Se apanhassem um colega a copiar na minha sala:", opcoes: ["Eu metia as minhas cábulas logo no bolso em pânico de revista às mesas", "Ficava a olhar chocado/a e adorava o drama", "Fingia demência, 'não conheço este indivíduo'", "Sentia pena dele/a, porque ia a chumbo direto"] },
    { id: "c_ee_c_12", texto: "Sobre o famoso truque do estojo transparente de plástico:", opcoes: ["Escrevia as respostas com lápis no plástico que só dava para ver de lado", "Colava uma folha no fundo do estojo", "Não funcionava, o professor inspecionava os estojos todos", "Eu usava o rótulo da garrafa de água da Luso para meter texto lá dentro"] },
    { id: "c_ee_c_13", texto: "Quando a professora mandava ler um texto em voz alta:", opcoes: ["Contava os parágrafos para tentar prever qual me calhava e ensaiava mentalmente", "Pedia logo para ler porque adorava a minha própria voz", "Fingia um ataque de tosse quando chegava a minha vez", "Lia com tanta monotonia que a turma inteira adormecia"] },
    { id: "c_ee_c_14", texto: "O que fazia no livro enquanto a aula estava uma valente seca?", opcoes: ["Pintava os dentes e metia cornos em todas as caras históricas", "Fazias esculturas e estrelas ninjas de papel", "Meto o livro em pé como escudo e deitava a cabeça na mesa", "Sublinhava com régua linhas imaginárias para parecer focado/a"] },
    { id: "c_ee_c_15", texto: "Para conseguir um ponto extra nas notas no final do período:", opcoes: ["Ia lá chorar que o 'Satisfaz Bastante' decidia a minha vida", "Fazia o trabalho voluntário e limpezas do quadro", "Nunca pedia, aceitava o meu humilde 9.4", "Argumentava que a pergunta 3 estava ambígua e eu tinha razão"] },
    { id: "c_ee_c_16", texto: "Como eu fazia as margens do papel de teste?", opcoes: ["Obrigatórias e perfeitamente a régua", "Dobrava o papel a meio e estava a margem feita", "Não fazia, escrevia até cair da folha abaixo", "Perdias 10 minutos a fazer letras gordas artísticas a dizer 'TESTE'"] },
    { id: "c_ee_c_17", texto: "O truque para trabalhos de 10 páginas quando só tinha 7:", opcoes: ["Aumentava o espaçamento entre linhas e o tamanho da fonte para 13", "Enchia de imagens que ocupavam meia página cada uma", "Aumentava as margens laterais a níveis ilegais", "Repetia o mesmo parágrafo com palavras diferentes 5 vezes"] },
    { id: "c_ee_c_18", texto: "Se me esquecesse da calculadora no teste de Matemática:", opcoes: ["Era o meu fim, entregava em branco e aceitava a zero", "Implorava ao stor para me emprestar a dele do armário", "Fazia as contas à mão na folha de rascunho com 50 erros", "Pedias ao colega do lado mal ele acabasse de usar a dele"] },
    { id: "c_ee_c_19", texto: "Na hora de escolher os colegas de grupo para trabalhos:", opcoes: ["Vou a correr para os cromos inteligentes da turma para eles fazerem tudo", "Ficava com os meus melhores amigos (íamos chumbar mas divertíamo-nos)", "Era o último a ser escolhido e ficava com os 'sobras'", "Preferia fazer sozinho para não ter de aturar a preguiça alheia"] },
    { id: "c_ee_c_20", texto: "Qual a melhor cábula mental de todos os tempos?", opcoes: ["Canções com as matérias ou mnemónicas estúpidas (ex: SOHCAHTOA)", "Usar a mão esquerda para memorizar fórmulas matemáticas", "Apenas rezar para que as opções fossem ABCD e jogar ao calhas", "Saber que se a resposta for longa, deve ser a correta"] }
  ],
  "sub_29_1": [ // Testes e Exames
    { id: "c_ee_t_01", texto: "A minha rotina no dia de um exame nacional (ou teste final):", opcoes: ["Acordava com diarreia nervosa e não conseguia comer nada", "Tomava um belo pequeno-almoço e ia rever o resumo na paragem", "Acordava atrasado/a e esquecia-me do Bilhete de Identidade", "Ia súper relaxado/a, já não havia nada a fazer ('seja o que Deus quiser')"] },
    { id: "c_ee_t_02", texto: "Quando acabava um exame cedo demais:", opcoes: ["Entregava logo orgulhoso/a e ia para o café", "Ficava 1 hora a olhar para o teto com vergonha de ser o primeiro a entregar", "Começava a rever tudo e acabava a mudar as certas para erradas", "Dormia na mesa até a professora mandar sair"] },
    { id: "c_ee_t_03", texto: "No fim do teste, as conversas à porta da sala:", opcoes: ["'O que é que deu o teu exercício 4? O meu deu 1030...' (O deles dava 2)", "Fugia dessas conversas para não ir deprimir antes da nota sair", "Fingia que me tinha corrido bem para não chorar ali mesmo", "Discutia a resposta certa com argumentos até o professor mostrar a correção"] },
    { id: "c_ee_t_04", texto: "A véspera do exame era para:", opcoes: ["Fazer uma direta de estudo a base de Monster e desespero", "Dormir 10 horas, o cérebro tem de estar fresco", "Ver 3 episódios de uma série porque 'não entra mais matéria'", "Fazer mapas mentais lindíssimos com canetas que nunca ia reler"] },
    { id: "c_ee_t_05", texto: "Nas perguntas de desenvolvimento onde eu não sabia a resposta:", opcoes: ["Enrolava, enchia chouriços e metia palavras caras", "Deixava em branco com dignidade", "Escrevia uma carta à professora a pedir pena e meio valor", "Copiava o enunciado da pergunta por outras palavras"] },
    { id: "c_ee_t_06", texto: "O material obrigatório em cima da mesa nos Exames Nacionais:", opcoes: ["3 canetas pretas, lápis HB2 e uma régua que não ia usar", "Levava a caneta azul que me roubassem e a professora tirava-ma", "O meu Bilhete de Identidade, um sumo de lata e pastilhas", "O amuleto da sorte (fio, santinho, ou borracha especial)"] },
    { id: "c_ee_t_07", texto: "Quando a nota saía na pauta no vidro da escola:", opcoes: ["Ia a correr ver de todos antes de ver a minha", "Mandava um amigo ver por mim porque eu não tinha coragem", "Passava discretamente, via o vermelho e ia para casa", "Ficava na primeira fila a ostentar o meu 19 a toda a gente"] },
    { id: "c_ee_t_08", texto: "As disciplinas em que eu mais sofria nos exames:", opcoes: ["Matemática e Físico-Química (fórmulas malditas)", "Português (os textos do Camões eram mandarim para mim)", "História (datas infindáveis, nasci no século errado)", "Eu sofria em TODAS, a escola não era a minha praia"] },
    { id: "c_ee_t_09", texto: "Quando lia o enunciado e a primeira pergunta era um 'rasganço' (difícil):", opcoes: ["Suava frio e pensava 'estou lixado'", "Passava logo para a última página a ver se algo era mais fácil", "Ficava a olhar para o professor com cara de ódio", "Respirava fundo, escrevia o nome na folha e entregava aos 30 mins"] },
    { id: "c_ee_t_10", texto: "Em perguntas de Escolha Múltipla:", opcoes: ["C era sempre a resposta, e se houvesse dúvidas, ia a B", "Fazia o cálculo de 'já pus muitas As, deve ser D'", "Só marcava com a certeza absoluta (e depois apagava e borrava tudo)", "Dava o toque no joelho do parceiro do lado para comparar"] },
    { id: "c_ee_t_11", texto: "Como eu justificava uma má nota aos meus pais?", opcoes: ["'A professora fez o teste para a turma toda chumbar'", "'A nota mais alta foi um 12, a turma correu mal!'", "'Tive uma branca e confundi-me nas perguntas com rasteira'", "Assumia que não estudei e arcava com o castigo de ficar sem Playstation"] },
    { id: "c_ee_t_12", texto: "A entregar testes antigos com recados do professor ('Assinatura do Encarregado de Educação'):", opcoes: ["Falsificava a assinatura com perfeição e requinte", "Metia a minha avó a assinar que via mal", "Assinavam, mas só depois de eu ouvir um sermão de 2 horas", "Tirava excelentes, mostravam sempre na porta do frigorífico"] },
    { id: "c_ee_t_13", texto: "O desespero do branco de memória a meio do teste:", opcoes: ["Fechava os olhos e tentava invocar a foto da página do livro", "Batia na cabeça com a caneta até lembrar", "Escrevia a parte que me lembrava e o resto deixava a meio da frase", "Pedia para ir ao WC, lavava a cara e tentava reiniciar o cérebro"] },
    { id: "c_ee_t_14", texto: "Sobre canetas corretoras (Tipp-Ex / Fita Mágica):", opcoes: ["O meu teste cheirava a corretor branco e parecia uma obra nas paredes", "A professora proibia e eu tinha de riscar tudo entre parênteses", "Gastava o corretor todo a brincar nas carteiras e depois não tinha", "Eu não falhava, não precisava de apagar nada (Mentira)"] },
    { id: "c_ee_t_15", texto: "Quando faltava 5 minutos para acabar e eu ainda estava a meio:", opcoes: ["Começava a escrever em hieróglifos a 300 à hora", "Resumia o final com tópicos de bala a pedir clemência ('e assim por diante')", "Desistia, já estava já estava, que se lixe", "A professora tinha de arrancar a folha da minha mão fisicamente"] },
    { id: "c_ee_t_16", texto: "O rascunho dos Exames Nacionais:", opcoes: ["Fazias um esboço limpo de todo o teste antes de passar a limpo", "Só usava para desenhar corações e estrelas", "Usava para fazer contas aos pontos que já tinha para chegar ao 9.5", "Não usava rascunho, ia direto a caneta para viver a vida no limite"] },
    { id: "c_ee_t_17", texto: "Fazer revisões (estudar a matéria) no dia do teste nos corredores:", opcoes: ["Adorava testar os meus amigos e ensiná-los (sentia-me professor/a)", "Isso dava-me nervos, eu tapava os ouvidos", "Perguntava 'Espera, isso sai?? Não estudei esse capítulo!' e chorava", "Eu era quem pedia resumos de boca à porta da sala de aula"] },
    { id: "c_ee_t_18", texto: "Os meus resumos no secundário e faculdade:", opcoes: ["Ficheiros de Word hiper-organizados a negrito e itálico que partilhava com todos", "Não fazia resumos, grifava o livro até ele ficar amarelo fosforescente", "Pedia resumos dos anos anteriores a malta mais velha", "O meu resumo era o índice do livro lido de raspão"] },
    { id: "c_ee_t_19", texto: "Num teste de Matemática, quando a solução dava uma fração impossível ('13/198'):", opcoes: ["Apagava e começava de novo 4 vezes até dar um número inteiro (ex: 2)", "Deixava lá a fração monstruosa e rezava", "Olhava para o teto e aceitava a minha derrota lógica", "Escrevia 'Erro no enunciado' com grande atrevimento"] },
    { id: "c_ee_t_20", texto: "A pior sensação após os exames:", opcoes: ["Sair com a sensação de dever cumprido e perceber à noite que faltou uma página do teste", "Sonhar que chumbei na noite da pauta", "Ir ver a pauta de óculos de sol para evitar os professores", "Saber que agora tinha a família toda no jantar a perguntar 'então a nota?'"] }
  ]
};
