import { PerguntaClassica } from "@/types/catalogo";

export const classico_festa_noite: Record<string, PerguntaClassica[]> = {
  "sub_12_0": [ // Saídas à Noite
    { id: "c_fn_s_01", texto: "No grupo de amigos que vai sair, eu sou:", opcoes: ["O/A que organiza e avisa a que horas é para arrancar", "O/A que atrasa toda a gente porque ainda está a arranjar o cabelo", "O/A que diz que vai e depois cancela no próprio dia", "O/A que já está no bar à espera há meia hora"] },
    { id: "c_fn_s_02", texto: "O que eu bebo antes de ir para a discoteca (Aquecimento/Esquenta)?", opcoes: ["Umas minis ou cerveja na boa", "Shots, quero é ficar torto/a rápido", "Vinho barato que sobra dos jantares", "Não bebo álcool, sou o motorista de serviço"] },
    { id: "c_fn_s_03", texto: "Quando entro na discoteca, a minha primeira ação é:", opcoes: ["Ir direto para o meio da pista dançar", "Ir para a fila do bar buscar logo uma bebida", "Encontrar um canto/sofá para me sentar", "Ir à casa de banho tirar selfies no espelho"] },
    { id: "c_fn_s_04", texto: "Na pista de dança, as minhas skills são:", opcoes: ["O John Travolta, domino a pista toda", "Danço de forma irónica para os outros se rirem", "O clássico 'dois passinhos para a esquerda, dois para a direita'", "Fico encostado à parede a segurar no copo e acenar com a cabeça"] },
    { id: "c_fn_s_05", texto: "Se a música que está a dar for muito má:", opcoes: ["Vou lá pedir ao DJ para mudar (e ele ignora-me)", "Vou à zona de fumadores apanhar ar", "Continuo a dançar, para mim é igual", "Começo a reclamar que as noites antigamente é que eram boas"] },
    { id: "c_fn_s_06", texto: "O clássico 'amigo que desaparece' na noite:", opcoes: ["Sou sempre eu, desapareço sem avisar ninguém", "Sou o que anda à procura do amigo perdido a noite toda", "Ignoro, ele/a que se oriente", "Ligo 20 vezes até me atenderem"] },
    { id: "c_fn_s_07", texto: "A minha tática de engate na noite é:", opcoes: ["Sorrisos intensos e contacto visual do outro lado do bar", "Ir oferecer uma bebida à pessoa", "Dançar à beira da pessoa até ela reparar em mim", "Nenhuma, eu não engato, só existo"] },
    { id: "c_fn_s_08", texto: "Ir à casa de banho na discoteca:", opcoes: ["Vou sozinho/a e demoro 2 minutos", "Vou em grupo de 5 pessoas e ficamos lá meia hora na conversa", "Seguro até rebentar porque odeio as filas", "Acabo a fazer amizades eternas com pessoas que nunca mais vou ver"] },
    { id: "c_fn_s_09", texto: "Quando começo a ficar 'alegre' (bêbado/a):", opcoes: ["Fico super carinhoso/a e digo 'amo-te' a toda a gente", "Fico agressivo/a e quero discutir", "Fico hiperativo/a e não paro de falar e saltar", "Sento-me a chorar por motivos estúpidos"] },
    { id: "c_fn_s_10", texto: "O calçado perfeito para sair à noite:", opcoes: ["Saltos altos / Sapatos clássicos, a sofrer mas com estilo", "Umas sapatilhas (ténis) velhas para poderem ser pisadas", "Sapatilhas novas a estrear (o maior erro)", "Botas confortáveis para aguentar as dores nas pernas"] },
    { id: "c_fn_s_11", texto: "Como lido com o bengaleiro da discoteca?", opcoes: ["Deixo lá o casaco e perco sempre a senha", "Não levo casaco para a noite para não pagar o euro do bengaleiro", "Ato o casaco à cintura à moda dos anos 90", "Fico agarrado ao casaco a noite toda a suar em bica"] },
    { id: "c_fn_s_12", texto: "Qual a minha desculpa para sair cedo da festa?", opcoes: ["'Tenho de ir passear o cão amanhã de manhã'", "'Dói-me muito a cabeça'", "Não dou desculpas, digo 'estou farto, vou bazar'", "Fujo à francesa (o famoso 'ghosting') sem ninguém ver"] },
    { id: "c_fn_s_13", texto: "Para mim, a melhor parte de sair à noite é:", opcoes: ["O jantar com os amigos antes e o convívio", "Dançar até não sentir os pés", "A comida 'suja' às 5 da manhã no regresso a casa", "Acordar no dia seguinte com fofocas novas"] },
    { id: "c_fn_s_14", texto: "A meio da noite, quando dá uma fome terrível:", opcoes: ["Agarrar um hambúrguer do McDonald's a caminho de casa", "Ir à clássica Roulote das bifanas ou Kebab", "Esquecer a fome e beber mais água/álcool", "Atacar o frigorífico quando finalmente chego a casa"] },
    { id: "c_fn_s_15", texto: "O que acho de noites de Karaoke?", opcoes: ["Adoro, sou o primeiro a escolher o 'Bohemian Rhapsody'", "Só com meia dúzia de cervejas em cima", "Odeio, fico cheio de vergonha alheia", "Gosto de ir mas recuso-me a cantar"] },
    { id: "c_fn_s_16", texto: "Se a discoteca fechar e ainda houver malta com energia:", opcoes: ["'Siga para o after em casa de alguém!'", "'Já chega por hoje, chamem um Uber'", "Fico a fazer tempo à porta na conversa com desconhecidos", "Eu sou o/a que tem a casa livre e convida todos (e depois arrepende-se)"] },
    { id: "c_fn_s_17", texto: "Quando pedem fotos na noite com o flash ligado:", opcoes: ["Faço pose e meto logo um filtro", "Fico com os olhos fechados em 99% das fotos", "Fujo do flash, não quero provas que estive ali", "Tiro mas obrigo o meu amigo a apagar no dia seguinte"] },
    { id: "c_fn_s_18", texto: "Quem me leva a casa depois da saída?", opcoes: ["O amigo que não bebeu (glorioso)", "Chamo Uber / Bolt mas engano-me sempre na morada", "Vou a pé se for perto (péssima ideia)", "Os transportes públicos matinais (autocarro cheio de ressacados)"] },
    { id: "c_fn_s_19", texto: "Sobre perder coisas na noite:", opcoes: ["Já perdi o telemóvel/chaves/carteira mais que uma vez", "Ando sempre a apalpar os bolsos a cada 5 minutos em pânico", "Nunca perdi nada, tenho uma bolsinha à prova de roubo", "Sou eu que encontro as coisas que os meus amigos perdem"] },
    { id: "c_fn_s_20", texto: "Se estiver a passar 'aquela' música da minha adolescência:", opcoes: ["Perco a cabeça e berro a plenos pulmões", "Grito pelo meu amigo e aponto para o teto", "Não conheço, ouço a música mais recente", "Tento fazer uma roda com o pessoal todo"] }
  ],
  "sub_12_1": [ // Ressacas e Arrependimentos
    { id: "c_fn_r_01", texto: "Na manhã seguinte, a minha primeira frase é:", opcoes: ["'Nunca mais bebo na minha vida'", "'Que horas são? Onde estou?'", "'Quem me manda ir trabalhar segunda-feira?'", "'Estou incrível, quando é a próxima?'"] },
    { id: "c_fn_r_02", texto: "Como curo a ressaca?", opcoes: ["Mergulhado em água, Ben-u-ron e Ibuprofeno", "A comer comida muito gordurosa (pizza, hambúrguer)", "A dormir até às 17h, o tempo cura tudo", "Eu nunca tenho ressaca (superpoder)"] },
    { id: "c_fn_r_03", texto: "Quando olho para o extrato da conta bancária de manhã:", opcoes: ["Tenho vontade de chorar, onde gastei tanto dinheiro?!", "Nem abro a app do banco para não ter um ataque de pânico", "Até acho que não gastei muito, fui poupadinho", "Pergunto aos amigos se paguei algo que não devia"] },
    { id: "c_fn_r_04", texto: "O maior 'Walk of Shame' (regresso a casa de manhã):", opcoes: ["Ir no autocarro de fato de treino da noite com os velhotes a olhar", "Entrar em casa e os pais estarem a tomar o pequeno-almoço", "Bater com a porta sem querer e acordar o prédio todo", "Puxar a roupa amarrotada para baixo e fingir que vou trabalhar"] },
    { id: "c_fn_r_05", texto: "Ver o histórico de mensagens/chamadas no dia seguinte:", opcoes: ["Mandei áudios embaraçosos ao meu ex", "Liguei para a minha mãe às 4h da manhã", "Declarei o meu amor a um amigo de forma aleatória", "Tenho o telemóvel intacto, eu controlo-me"] },
    { id: "c_fn_r_06", texto: "As feridas de guerra de uma noite louca:", opcoes: ["Joelho esfolado de cair no chão e não me lembrar", "Os pés cheios de bolhas de saltos/sapatos apertados", "Roupa com manchas de bebidas desconhecidas", "Uma nódoa negra misteriosa num braço"] },
    { id: "c_fn_r_07", texto: "Se estiver com 'amnésia alcoólica' (branca):", opcoes: ["Ligo aos amigos a exigir um resumo detalhado da noite", "Monto o puzzle através dos stories do Instagram do pessoal", "Prefiro não saber, o que acontece na noite fica na noite", "Acho sempre que fiz a maior vergonha do mundo e peço desculpa"] },
    { id: "c_fn_r_08", texto: "A ler o grupo de WhatsApp no dia seguinte:", opcoes: ["Fico a rir sozinho/a com as fotos terríveis que mandam", "Sou o alvo da gozação geral pelas figuras que fiz", "Mando mensagem a perguntar se toda a gente chegou bem viva", "Muto o grupo, dói-me a cabeça para estar a ler aquilo"] },
    { id: "c_fn_r_09", texto: "Quando prometo 'só vou beber um copo e vou-me deitar':", opcoes: ["Isso nunca acontece, acabo a fechar a discoteca", "Cumpro mesmo, se é para ir dormir, vou", "Passo o copo para 3 ou 4 copos mas não exagero", "Esse copo transforma-se num balde de sangria"] },
    { id: "c_fn_r_10", texto: "Sobre pedir desculpa às pessoas no dia seguinte:", opcoes: ["Mando mensagem formal a pedir perdão por ser chato", "Faço uma piada e pergunto 'dei muito trabalho?'", "Não peço desculpa a ninguém, eles que me aturem", "Chamo as pessoas para almoçar para compensar"] },
    { id: "c_fn_r_11", texto: "O que acho da dor de cabeça latejante ao acordar?", opcoes: ["Rezo a todos os deuses que conheço para parar", "Tomo café forte e finjo que não existe", "Deixo a janela toda fechada e não suporto qualquer raio de luz", "Ponho gelo na testa e sofro em silêncio"] },
    { id: "c_fn_r_12", texto: "Se encontrar coisas estranhas no bolso (senhas, copos de plástico):", opcoes: ["Guardo como souvenir da noite épica", "Deito fora e pergunto-me por que raio roubei aquilo", "Acho que tirei isso ao meu amigo", "Não encontro nada, chego a casa sempre sem a carteira"] },
    { id: "c_fn_r_13", texto: "Quando a minha voz desaparece (rouco/a) no dia seguinte:", opcoes: ["Foi de cantar aos berros as músicas pimba", "Foi do fumo no bar / discoteca", "Falei tão alto para superar o som que rasguei as cordas vocais", "Fico feliz, dá-me um ar sexy e rouco"] },
    { id: "c_fn_r_14", texto: "Em que estado fica o meu estômago no dia seguinte?", opcoes: ["Odeio comer, se vir comida começo a enjoar", "Parece um buraco negro, como o triplo do normal", "Bebo só uma coca-cola ou Sprite para acalmar o gás", "Odeio a vida mas tento empurrar uma tosta mista"] },
    { id: "c_fn_r_15", texto: "Sobre o famoso banho quente de ressaca:", opcoes: ["Sento-me no chão do chuveiro e deixo a água cair nas costas", "Tomo o mais rápido possível e volto para o pijama", "Não tomo, só tenho forças para me deitar a cheirar a tabaco", "Tomo um banho frio para me dar um choque no sistema"] },
    { id: "c_fn_r_16", texto: "Como lido com vizinhos muito barulhentos num domingo de ressaca?", opcoes: ["Choro na cama e enfio a almofada na cabeça", "Vou bater na parede ou à porta deles com fúria cega", "Meto os fones a tocar som de chuva a ver se abafa", "Praguejo muito mas não tenho coragem de fazer nada"] },
    { id: "c_fn_r_17", texto: "Ao ver as publicações que fiz na noite anterior:", opcoes: ["Apago 90% delas porque são vergonhosas e desfocadas", "Deixo estar, foi a minha vibe e assumo o risco", "Normalmente sou eu o/a engraçado/a dos stories, fica lá tudo", "Tenho pânico de ter posto para o 'Público' e não 'Melhores Amigos'"] },
    { id: "c_fn_r_18", texto: "Quando um amigo diz 'Logo à noite vamos outra vez?':", opcoes: ["'Nem morto/a, apaga o meu número'", "'Dá-me 2 horinhas e já fico novo/a para seguir'", "'Talvez vá só beber um cafezinho com vocês' (mentira, vou sair)", "Ignoro a mensagem até segunda-feira"] },
    { id: "c_fn_r_19", texto: "Ressaca moral (arrependimento de atitudes) vs Ressaca física (dor):", opcoes: ["Sofro muito mais com a dor de cabeça e enjoos", "Fico com ataque de pânico pelas figuras que fiz, é pior", "Não sofro de nenhuma, sou um anjo", "Sofro o dobro com ambas misturadas"] },
    { id: "c_fn_r_20", texto: "Um clássico do meu dia seguinte:", opcoes: ["Beber um Ice Tea e um Rissol misto", "Andar em pantufas e roupão pela casa até às 19h", "Prometer que na próxima saída só bebo cerveja e evito os shots", "Reclamar de estar velho/a demais para estas coisas"] }
  ]
};
