import { PerguntaClassica } from "@/types/catalogo";

export const classico_humor_comedia: Record<string, PerguntaClassica[]> = {
  "sub_30_0": [ // Consumo de Memes
    { id: "c_hc_m_01", texto: "A minha utilização de Memes no telemóvel:", opcoes: ["A minha galeria de fotos é 90% memes roubados e 10% selfies", "Tenho uma pasta inteira chamada 'Reações' para enviar nas conversas", "Não guardo, só mando print screen para o WhatsApp", "Eu pergunto aos mais novos o que significa o meme"] },
    { id: "c_hc_m_02", texto: "No Instagram/TikTok, como partilho coisas engraçadas?", opcoes: ["Envio DM a cada amigo separadamente", "Tag (identifico) os amigos nos comentários para todos verem", "Meto nos meus Stories e acho que sou comediante", "Não partilho, rio-me sozinho no quarto às escuras"] },
    { id: "c_hc_m_03", texto: "Qual a minha reação a uma piada muito parva que me enviam:", opcoes: ["Mando a sigla 'LMAO' ou 'LOL' mas estou com cara séria", "Mando 15 emojis de chorar a rir (😂😂😂)", "Mando um GIF/Sticker de uma pessoa a olhar para o vazio", "Se não tem graça eu não respondo e deixo em 'Visto'"] },
    { id: "c_hc_m_04", texto: "O meu estilo de Humor principal é:", opcoes: ["Humor Negro e pesado (do qual sinto culpa mas adoro)", "Piadas Secas e Trocadilhos (sou o rei do 'Não percebi')", "Humor de Observação (Situações do dia a dia tipo Seinfeld/RAP)", "Humor Físico (Pessoas a cair e gatos a assustarem-se)"] },
    { id: "c_hc_m_05", texto: "Quando a minha mãe ou tia me mostra um meme do Facebook de 2013:", opcoes: ["Dou um riso falso de pena 'Ahahah, muito giro mãe'", "Reviro os olhos e digo 'Mãe, isso é tão antigo'", "Explico pacientemente que isso já não tem graça", "Eu sou o gajo que se ri de memes do Facebook com os Minions"] },
    { id: "c_hc_m_06", texto: "Sobre vídeos de pessoas a esbardalharem-se (cair) no chão:", opcoes: ["Rio-me até perder a respiração e faço replay", "Tenho empatia e sinto a dor da pessoa, não tem piada", "Só tem piada se for um amigo meu, estranhos não", "Se tiverem um som estúpido por trás rio de chorar"] },
    { id: "c_hc_m_07", texto: "No WhatsApp, a minha coleção de Figurinhas/Stickers é:", opcoes: ["Uma lixeira: tenho figurinhas do António Costa, cães tristes e insultos", "Super arranjada, uso só pacotes de gatinhos fofos", "Só roubo as figurinhas que os outros usam", "Acho azeiteiro e só comunico por palavras cultas"] },
    { id: "c_hc_m_08", texto: "A contar uma piada a um grupo:", opcoes: ["Sou excelente contador, tenho tempo cómico e gesticulo", "Esqueço a punchline (final) a meio e fica um silêncio", "Começo a rir-me antes de contar o fim da piada", "Eu sou quem ouve, contar piadas dá-me ansiedade social"] },
    { id: "c_hc_m_09", texto: "Qual a melhor página de humor em Portugal para mim?", opcoes: ["O Insónias em Carvão (Mestre das montagens)", "Bilbia mt engarsada (E as suas calinadas clássicas)", "Nilton/Humoristas do Twitter a debitar postas", "Apenas consumo TikToks de gajos brasileiros a cair de mota"] },
    { id: "c_hc_m_10", texto: "O que acho de partidas/apanhados (Pranks) do Youtube?", opcoes: ["Acho hilariante meterem pimenta na pasta de dentes", "Odeio, acho cruel e irrita-me a falta de respeito", "Só tem piada os sustos inofensivos em casas com fantasmas falsos", "Vejo, mas sei que são todos combinados e com atores pagos"] },
    { id: "c_hc_m_11", texto: "Quando mostro um vídeo super engraçado no meu telemóvel a alguém:", opcoes: ["A pessoa não ri e eu fico a justificar 'tens de ver até ao fim'", "A pessoa fica com o telemóvel na mão 10 minutos a ver outras cenas", "Obrigo a pessoa a rir e pergunto 'Não tem bué graça?'", "O ecrã apaga-se ou entra notificação vergonhosa a meio do vídeo"] },
    { id: "c_hc_m_12", texto: "A usar ironia e sarcasmo na vida real:", opcoes: ["Uso a 100%, é o meu dialeto principal (e os outros ofendem-se)", "Uso, mas acabo a dizer 'Estou a brincar!' para não baterem em mim", "As pessoas acham que falo sempre a sério", "Odeio ironia, prefiro a sinceridade direta"] },
    { id: "c_hc_m_13", texto: "Em relação ao Stand-up Comedy (Espetáculos de humor):", opcoes: ["Vejo Netflix specials sempre que saem e cito piadas nas conversas", "Fui ver ao vivo e fiquei com medo de ir parar à primeira fila para não gozarem", "Prefiro as sketches curtas no TikTok, não tenho paciência de uma hora", "Ofendo-me facilmente com os temas e desligo a televisão"] },
    { id: "c_hc_m_14", texto: "Os áudios de rádio / WhatsApp de gente a enganar-se a falar ou irritada:", opcoes: ["São o topo do humor, reencaminho para 15 grupos", "Só acho piada ao 'Que informação dramática' ou clássicos de TV", "Enerva-me a quantidade de palavrões nesses áudios", "Se for a minha voz gravada de ressaca, odeio"] },
    { id: "c_hc_m_15", texto: "Criar os meus próprios memes:", opcoes: ["Tiro fotos aos meus amigos desprevenidos e ponho texto em cima", "Sou o lorde do Paint/Photoshop nas horas vagas", "Nunca criei, deixo o trabalho duro para os profissionais da net", "Apenas adiciono legendas dramáticas nas minhas selfies"] },
    { id: "c_hc_m_16", texto: "Piadas de 'Pai' (secas e com trocadilhos de mau gosto):", opcoes: ["Eu rio-me genuinamente e uso-as nos jantares de família", "Reviro os olhos com muita força e digo 'Valha-me Deus'", "Digo 'essa foi tão má que teve piada'", "Eu sou a pessoa que conta piadas sobre tomates e alfaces"] },
    { id: "c_hc_m_17", texto: "O que acho da Cultura de 'Cancelamento' no Humor?", opcoes: ["O humor não devia ter limites, é suposto ofender e fazer rir", "Há coisas com as quais não se deve brincar, ponto", "Depende se a piada teve mesmo graça ou se foi só ódio", "Não ligo a essas polémicas e vivo a rir em silêncio"] },
    { id: "c_hc_m_18", texto: "O clássico Trocadilho Tuga nas placas dos cafés (Ex: O Bar Ti-mão):", opcoes: ["Acho incrível, adoro publicidade rasca de rua", "Dá-me vontade de tirar fotos para uma página de Cringe Tuga", "Faço coleções dessas parvoíces mentais", "Não reparo nada nisso no dia a dia"] },
    { id: "c_hc_m_19", texto: "Quando não entendo o humor Gen Z (skibidi, rizz, sigma):", opcoes: ["Sinto-me com 80 anos repentinamente e vou pesquisar", "Uso essas palavras ironicamente e pareço um otário", "Digo 'vocês têm um atraso de vida' e fecho a porta", "Adoto a gíria e irrito os meus amigos mais sérios"] },
    { id: "c_hc_m_20", texto: "O meme que me define como pessoa é:", opcoes: ["O cão no meio do fogo a dizer 'This is fine' (Está tudo bem)", "Aquele boneco a chorar com uma máscara a sorrir por cima", "O macaco a olhar de lado disfarçado no carro", "O Gato a gritar com a mulher (eu sou o gato)"] }
  ],
  "sub_30_1": [ // Ataques de Riso
    { id: "c_hc_a_01", texto: "Qual a pior altura para ter um ataque de riso?", opcoes: ["Numa reunião séria com o patrão ou professores", "Num funeral ou momento de silêncio (o pânico total)", "No autocarro, as pessoas olham para mim como se eu fosse maluco/a", "Quando estou a tentar ralhar com alguém a sério"] },
    { id: "c_hc_a_02", texto: "Como é a minha 'gargalhada'?", opcoes: ["Silenciosa, parece que estou a ter um ataque de asma a bater palmas", "Escandalosa, super alta como uma hiena", "Como um porquinho, mando o famoso 'snort' pelo nariz", "Começo a rir e acabo por chorar e tossir ao mesmo tempo"] },
    { id: "c_hc_a_03", texto: "Tentar segurar o riso num local proibido:", opcoes: ["Mordo o interior das bochechas até sangrar a tremer o lábio", "Explodo num som nasal que parece um balão a esvaziar e é pior", "Tusso e finjo que tenho um ataque de engasgo a chorar de rir", "Eu não aguento, levanto-me e saio a correr do sítio"] },
    { id: "c_hc_a_04", texto: "Quando um amigo cai mesmo à minha frente:", opcoes: ["Grito 'Estás bem?!' a tentar ajudar com preocupação", "Rio descontroladamente e deixo o coitado no chão 5 minutos", "Tiro o telemóvel para gravar enquanto me rio", "Fico aflito a achar que ele partiu os dentes, perco a piada"] },
    { id: "c_hc_a_05", texto: "Acontece-me ter ataques de riso sozinho(a) em casa ao lembrar algo?", opcoes: ["Frequentemente, no banho ou a ir dormir, lembro-me e choro a rir", "Às vezes solto um 'Pfff' pelo nariz a olhar para o teto", "Não, o meu humor precisa de audiência", "Se os meus animais me virem, fogem a achar que passei-me"] },
    { id: "c_hc_a_06", texto: "Qual a piada mais eficaz para me fazer perder a compostura?", opcoes: ["Asneirolas e piadas badalhocas dos amigos (Nível 5º ano)", "As ironias rápidas e cortantes ditas na hora perfeita", "Barulhos estranhos do corpo humano a meio de jantares de luxo", "Um cão a fazer uma cara muito humana e parva num vídeo"] },
    { id: "c_hc_a_07", texto: "Ao ver comédias no cinema (filmes super engraçados):", opcoes: ["Rio para o lado de dentro, sou uma pessoa discreta", "Bato nas costas da cadeira da frente de tantas gargalhadas", "O meu riso é mais engraçado que o filme e o público ri de mim", "Adormeço, porque o cinema dá-me sono e a piada passa-me ao lado"] },
    { id: "c_hc_a_08", texto: "O que me acontece quando choro de rir:", opcoes: ["Fico sem ar, agarro-me à barriga, dói-me as costelas", "As lágrimas destroem-me a maquilhagem/cara em dois segundos", "Mijo-me um bocadinho (o clássico das bexigas soltas)", "Fico roxo/a a tossir e dizem 'calma que o moço morre'"] },
    { id: "c_hc_a_09", texto: "O fenómeno de 'rir de nervos' (quando alguém diz más notícias e eu rio):", opcoes: ["Faço-o sempre, rio quando estou em pânico e sou julgado", "Nunca me aconteceu, sei agir com seriedade no pânico", "Quando rio de nervos, tento disfarçar com uma tosse violenta", "Meto a mão na boca e olho para baixo a fingir que estou a chorar"] },
    { id: "c_hc_a_10", texto: "Alguém começa a contar uma história e tu já sabes que vais rir:", opcoes: ["Peço para a pessoa parar de contar que eu não estou aguentar já", "Olho fixamente para outro lado da mesa para quebrar o contacto visual", "A pessoa também não consegue contar e rimos 10 min por nada", "Sou eu quem está sempre a contar, mas chego ao fim e não teve piada"] },
    { id: "c_hc_a_11", texto: "Brincar de 'Quem se rir primeiro, perde' (Olhar nos olhos):", opcoes: ["Perco ao 1º milissegundo de olhar para a cara de otário do meu amigo", "Ganho sempre, faço cara de pedra, sou impenetrável", "Fico estrábico e ganho porque eles fogem a rir", "Faço caretas tão absurdas que o outro quebra o gelo logo"] },
    { id: "c_hc_a_12", texto: "A cena mais constrangedora com saliva a rir:", opcoes: ["Guspo pingo na cara dos outros sem querer quando solto o riso explosivo", "Engasgo-me e o sumo/água sai disparado pelo nariz, a doer a alma", "Nunca me baba, sou uma lady/lorde até nas emoções intensas", "Deito a cerveja toda para a t-shirt branca que comprei ontem"] },
    { id: "c_hc_a_13", texto: "Como eu paro um ataque de riso no sítio errado?", opcoes: ["Penso em contas a pagar ou em entes queridos a falecer (terapia de choque)", "Dou fortes beliscões na minha própria perna/braço com as unhas", "Foco-me nas manchas das paredes com cara de assustado", "Não paro. Sou expulso do restaurante e saio a rir pelas portas"] },
    { id: "c_hc_a_14", texto: "Qual a minha relação com vídeos do Gato Fedorento antigos e tesourinhos?", opcoes: ["Rio-me às gargalhadas na cena do 'Batam Palmas e cantem...'", "Adoro os bloopers (cenas falsas onde eles se riem uns dos outros)", "Não vejo isso desde 2005, já envelheceu bué da mal", "Sei as falas de cor e recito nas festas com os amigos"] },
    { id: "c_hc_a_15", texto: "Ataques de Riso em funerais/Missas: (O diabo atenta)?", opcoes: ["Aconteceu-me e mordi o lábio, o padre olhou para mim", "O meu medo número um, tento nunca pensar na piada ali", "Ajo de cabeça curvada, parecendo que estou de facto em reza chorosa", "Não vou a missas nem funerais porque perco a noção da cerimónia"] },
    { id: "c_hc_a_16", texto: "O amigo que tem o riso mais contagioso do grupo:", opcoes: ["Sou eu, o meu riso é a principal atração nas saídas à noite", "É a Susana, que ri feito uma gaivota asmática (todos temos uma)", "Rimo-nos todos iguais, parecemos um coro de patos mudos", "Acho isso de riso 'contagioso' muito irritante em público"] },
    { id: "c_hc_a_17", texto: "Se estiver com dores musculares no dia seguinte de um ataque de riso:", opcoes: ["Alegro-me e digo 'Fiz abdominais incríveis hoje malta!'", "Sinto que foi um dos melhores serões da minha vida", "Fico com dor de estômago e digo 'Parem de me fazer rir que até dói!'", "Não chego a essa dor, o meu riso é só um suspiro rápido"] },
    { id: "c_hc_a_18", texto: "A ver apanhados clássicos do Youtube, o que mais me destrói:", opcoes: ["Malta a resvalar e a espalhar-se no gelo das ruas russas", "Sustos nos cantos das portas a familiares mais idosos em vídeo", "Gatos a caírem dos móveis depois de calcularem mal o salto em matemática", "Crianças a levarem com as bolas de basquete na cara no parque (sou um monstro)"] },
    { id: "c_hc_a_19", texto: "Sobre o famoso trocadilho da língua portuguesa que mata:", opcoes: ["'Ó Zé, trouxeste as chaves? - Não, trouxe a porta'. Riso estético mental e rio no carro depois", "Não consigo suportar piadas de tios de tasca e meto os auscultadores.", "Digo isso aos meus putos e netos porque adoro destruir o ego juvenil deles.", "Sempre que as oiço choro, a minha mente tem 12 aninhos de vida de tasco!"] },
    { id: "c_hc_a_20", texto: "Num ataque de rir sem limites com o teu melhor amigo(a):", opcoes: ["Ficamos estendidos no alcatrão/chão sem nos podermos mexer em pleno passeio", "Os dois paramos e dizemos 'Eish fds... já me doe o peito do peito'", "A senhora do lado grita 'Eles devem tar embriagados no gás hilariante'", "Um de nós bufa o muco ranho com o riso sonoro, corta a magia e é só gozo na lide"] }
  ]
};
