import { PerguntaClassica } from "@/types/catalogo";

export const classico_jogos_videojogos: Record<string, PerguntaClassica[]> = {
  "sub_22_0": [ // Vício nas Consolas
    { id: "c_jv_v_01", texto: "Quando perco uma partida renhida no FIFA / Call of Duty / LoL:", opcoes: ["Respiro fundo e digo 'bom jogo, aprendi algo novo'", "Dou um grito que acorda os vizinhos do 3º andar", "Atiro o comando à parede ou para o sofá à bruta", "Fecho o jogo de repente (Rage Quit) e vou dormir amuado/a"] },
    { id: "c_jv_v_02", texto: "A minha clássica desculpa quando estou a jogar mal:", opcoes: ["'Isto é lag! A internet está cheia de ping!'", "'O meu comando está com os botões presos'", "'Este jogo é Pay-to-Win, o gajo tem as cartas todas'", "Assumo que estou a jogar pessimamente"] },
    { id: "c_jv_v_03", texto: "O que me acontece quando jogo The Sims?", opcoes: ["Construo casas milionárias e uso os códigos do 'Motherlode'", "Passo 5 horas a fazer a cara do Sim e jogo só meia hora", "Tiro a escada da piscina ou ponho-os num quarto sem portas", "Sigo as carreiras certinhas para formar uma família exemplar"] },
    { id: "c_jv_v_04", texto: "Sobre gastar dinheiro em jogos (Microtransações, Skins, FIFA Points):", opcoes: ["Nunca gastei 1 cêntimo, sou um guerreiro puro e duro", "Gasto fortunas só para o meu boneco ter roupa diferente (Skins)", "Meto só 5 euros de vez em quando", "Saco o cartão de crédito e fecho os olhos para não ver o saldo"] },
    { id: "c_jv_v_05", texto: "Se a minha mãe / namorada(o) diz 'O jantar está na mesa!' a meio de um jogo Online:", opcoes: ["Digo 'Não dá para fazer pause, é um jogo online!!!'", "Digo 'Estou a ir!' e chego lá meia hora depois com a comida fria", "Saio a meio da partida, prefiro comer do que ouvir sermões", "Levanto o prato e como à frente do PC a olhar de lado"] },
    { id: "c_jv_v_06", texto: "A jogar com 'Randoms' (desconhecidos) em chat de voz:", opcoes: ["Insulto as gerações todas da família deles em inglês manhoso", "Sou super prestável e digo 'Nice try guys!'", "Meto-os a todos no 'Mute' porque gritam demasiado", "Nem ligo o microfone, sou um espião silencioso"] },
    { id: "c_jv_v_07", texto: "A jogar GTA ou jogos de mundo aberto, o que faço 90% do tempo?", opcoes: ["Faço as missões da história religiosamente", "Atropelo pessoas nos passeios e fujo da polícia com 5 estrelas", "Passo nos sinais vermelhos e respeito as regras de trânsito (para inovar)", "Só ando a tunar carros e a pintar a cor das rodas"] },
    { id: "c_jv_v_08", texto: "Quando prometo 'Só mais uma partidinha antes de ir dormir':", opcoes: ["É mesmo só uma e deito-me (disciplina total)", "Quando olho pela janela já o sol está a nascer às 7h da manhã", "Jogo até ganhar (ou seja, perco 5 seguidas e deito-me a chorar)", "Acabo com dores de cabeça e arrependido/a no dia seguinte no trabalho"] },
    { id: "c_jv_v_09", texto: "Em jogos de terror (ex: Resident Evil, Outlast):", opcoes: ["Jogo com os auscultadores no máximo, luzes apagadas a tremer", "Avanço 10 metros, assusto-me e desligo a consola", "Vejo youtubers a jogar em vez de jogar eu", "Adoro, dou risadas dos monstros porque nada me assusta"] },
    { id: "c_jv_v_10", texto: "O que acho de consolas portáteis / jogos de telemóvel (Candy Crush, etc)?", opcoes: ["Isso não é ser Gamer, é para passar o tempo na casa de banho", "Sou 100% viciado/a e gasto as vidas todas", "Jogo sempre que estou à espera em filas de pão", "Só compro consolas da Nintendo (Switch) para a fazenda no Mario"] },
    { id: "c_jv_v_11", texto: "O meu nome / Nickname nos jogos de consola costuma ser:", opcoes: ["Um nome bué 'Edgy/Dark' (Ex: ShadowSlayer99)", "O meu nome verdadeiro com o meu ano de nascimento (Joao_1995)", "Um nome completamente parvo para as pessoas se rirem", "Um Nickname de que me orgulho desde que tinha 12 anos"] },
    { id: "c_jv_v_12", texto: "A organizar a minha secretária de Gaming / setup:", opcoes: ["Luzes RGB por todo o lado, parece uma discoteca a piscar", "Super simples e minimalista, apenas rato e teclado", "Cheio de copos sujos, migalhas de batatas e garrafas de água", "Jogo com o portátil em cima da cama a queimar as pernas"] },
    { id: "c_jv_v_13", texto: "Se um amigo novo me pedir para partilhar conta/jogo:", opcoes: ["Partilho a minha conta na boa", "Invento que me esqueci da password para não o fazer", "Recuso logo, a minha segurança não se vende", "Partilho mas no dia seguinte mudo a password de fininho"] },
    { id: "c_jv_v_14", texto: "Como comemoro quando faço a jogada da minha vida num jogo?", opcoes: ["Salto da cadeira e grito 'TOMA!' à varanda", "Guardo logo um clip do vídeo para enviar aos amigos todos", "Fico sério e digo no chat de voz 'Pssh, muito fácil'", "O meu coração acelera e as mãos suam-me na mesma"] },
    { id: "c_jv_v_15", texto: "Qual a postura da minha coluna (costas) enquanto jogo?", opcoes: ["O clássico 'pescoço de abutre', com a cara colada ao ecrã", "Sentado/a bem recostado na cadeira ergonómica caríssima", "A meio do sofá todo/a torto/a com os pés em cima da mesa", "Deitado/a na cama até me dar cãibras no braço"] },
    { id: "c_jv_v_16", texto: "Se a minha operadora de Internet me falhar a ligação na final de um torneio:", opcoes: ["Rasgo o contrato nesse segundo e atiro o router pela janela", "Choro de impotência a ver o jogo cair", "Escrevo mensagens insultuosas no Twitter à operadora", "Faço hotspot do telemóvel em pânico a rezar que funcione"] },
    { id: "c_jv_v_17", texto: "Jogos tipo RPG (The Witcher, Skyrim, Elden Ring):", opcoes: ["Exploro todos os cantos, apanho as flores todas e falo com os NPCs", "Passo as conversas/filmes todos à frente a carregar 'X', quero é lutar", "Acumulo toneladas de itens no inventário e ando super devagar", "Farto-me de tentar matar o Boss principal e vejo guias no Youtube"] },
    { id: "c_jv_v_18", texto: "No Minecraft ou jogos de construção, o que crio?", opcoes: ["Um castelo gigante com passagens secretas", "Uma caixa de sapatos de terra ou pedra e meto lá uma cama", "Ando só lá a explodir com TNT as aldeias dos outros", "Caio em lava e perco os meus diamantes todos"] },
    { id: "c_jv_v_19", texto: "A jogar jogos cooperativos (Overcooked, It Takes Two):", opcoes: ["Falo super calmo/a e dou as indicações certas", "Grito com o meu parceiro e perco a amizade 'CORTA OS TOMATES!!'", "Ando às voltas sem perceber a minha tarefa", "Rio-me à brava e atiro a comida para o fogo ou para o rio"] },
    { id: "c_jv_v_20", texto: "O que acho do estilo do meu boneco online?", opcoes: ["Passo 2 horas a customizar a cara e não ponho capacetes para se ver", "Odeio customizar, clico 'Random' (Aleatório) e fica um monstro", "Faço sempre uma mulher careca ou um homem roxo fluorescente", "Tem de ter sempre uma pala nos olhos e cicatrizes, para ser mau"] }
  ],
  "sub_22_1": [ // Jogos de Tabuleiro
    { id: "c_jv_t_01", texto: "Quando jogamos Monopólio, eu sou:", opcoes: ["O banqueiro que desvia dinheiro para debaixo do tabuleiro", "O magnata que compra tudo e esfola os outros na renda", "O gajo que vai à falência nos primeiros 20 minutos", "O que se aborrece a meio e abandona o jogo"] },
    { id: "c_jv_t_02", texto: "A jogar UNO e metem um '+4' para mim:", opcoes: ["Respondo com outro '+4' e lido o problema ao próximo (batoteiro)", "Ajoelho-me e choro a comprar 4 cartas", "Invento que as regras dizem que se pode passar", "Acuso o amigo de arruinar as minhas esperanças e sonhos"] },
    { id: "c_jv_t_03", texto: "A ler as regras dos jogos novos:", opcoes: ["Sou o cromo que lê o livrinho todo e explica ao grupo", "Adormeço a meio da explicação e digo 'a gente aprende a jogar'", "Tento impor as regras da 'minha casa'", "Jogo à sorte e pergunto 'posso fazer isto?' em cada jogada"] },
    { id: "c_jv_t_04", texto: "Em jogos de Mímica ou Desenho (Pictionary, Activity):", opcoes: ["Desenho bonecos de pau horríveis que ninguém entende", "Sou o Leonardo Da Vinci do quadro magnético", "Mando saltos, berros e rebolo no chão na mímica e adivinham logo", "Fico com tanta vergonha na mímica que fico parado a abanar os braços"] },
    { id: "c_jv_t_05", texto: "Ao jogar cartas (Sueca ou Bisca) com o avô/tio velhote:", opcoes: ["Jogo a sério mas deixo-os ganhar para não armarem confusão", "Bato com os nós dos dedos na mesa e grito 'ÁS DE TRUNFO!'", "Não sei as regras e deito os trunfos à rua na pior altura", "Eles descobrem que estou a contar cartas e chamam-me batoteiro"] },
    { id: "c_jv_t_06", texto: "Qual é a minha capacidade de mentir em jogos como o Máfia ou Lobisomem?", opcoes: ["O meu coração dispara, começo a rir-me e descobrem-me logo", "Minto com a frieza de um psicopata, ninguém desconfia", "Apenas fico calado num canto o jogo inteiro para não dar nas vistas", "Eu acuso os meus próprios amigos só para ver o circo arder"] },
    { id: "c_jv_t_07", texto: "Numa partida de Catan (o jogo dos recursos):", opcoes: ["Negoceio tijolos por ovelhas como um agiota agressivo", "Ninguém quer trocar nada comigo e fico bloqueado na ilha", "Construo as maiores estradas só para ganhar esses pontos", "Roubo nos dados sem ninguém notar"] },
    { id: "c_jv_t_08", texto: "Quando perco gravemente num jogo de tabuleiro:", opcoes: ["Ameaço virar a mesa do avesso", "Acuso que as regras são estúpidas e o jogo é uma seca", "Dou os parabéns e aceito, foi renhido", "Fico a aziar durante os próximos três dias"] },
    { id: "c_jv_t_09", texto: "Quando o jogo inclui 'Dados' (rolete, gamão):", opcoes: ["Faço rituais como beijar ou soprar os dados para a sorte", "Atiro os dados com tanta força que vão parar debaixo do sofá", "Queixo-me sempre que os meus dados estão viciados contra mim", "Tento lançar suavemente para cair no número que quero"] },
    { id: "c_jv_t_10", texto: "Jogos tipo Trivial Pursuit ou Cultura Geral:", opcoes: ["Eu sei as datas históricas e os rios de Portugal todos", "Sou uma vergonha, erro nas cores da bandeira nacional", "Adivinho à sorte (chutómetro) e acerto sempre", "Passo o tempo a contestar e ir ao Google provar que o cartão está errado"] },
    { id: "c_jv_t_11", texto: "O que acho de Puzzles de 1000 peças?", opcoes: ["Adoro! Enrolo-me na manta e fico ali o fim de semana todo a fazer as bordas", "Acho super desanimador, nunca chego ao meio do puzzle", "Alguém esconde sempre a última peça para chatear", "Farto-me, guardo o pó do puzzle e vou ver TV"] },
    { id: "c_jv_t_12", texto: "Em jogos de cartas 'rápidos' (tipo Dobble ou Halli Galli):", opcoes: ["As minhas mãos são ninjas, rebento com as palmas e chego primeiro", "Fico baralhado com a pressão e os símbolos e perco sempre", "Começo a suar e a gaguejar sem encontrar a figura repetida", "Dou encontrões ou chapadas na mão dos outros sem querer"] },
    { id: "c_jv_t_13", texto: "Quando organizo a noite de jogos na minha casa:", opcoes: ["Crio cocktails temáticos e snacks perfeitos na mesa", "A casa é minha mas os outros têm de trazer os jogos e a comida", "Comemos logo ao chegar e depois a malta já está ensonada para jogar", "No fim da noite atiro a caixa do jogo toda desorganizada para a prateleira"] },
    { id: "c_jv_t_14", texto: "Se estiver a ganhar incrivelmente muito num jogo:", opcoes: ["Sou humilde e digo 'tive muita sorte'", "Gabanço-me e começo a picar e rebaixar os adversários", "Ajudo os meus amigos e dou-lhes dicas de como jogar", "Tenho pânico de ficar confiante e perder na última volta"] },
    { id: "c_jv_t_15", texto: "Em relação ao jogo Twister (de meter os pés nas cores redondas):", opcoes: ["Tenho a flexibilidade de um ginasta soviético", "Caio em cima da malta aos primeiros 30 segundos, pareço um urso", "Fujo com desculpas que tenho problemas na lombar", "Gosto mais de ser aquele que roda a seta ditadora"] },
    { id: "c_jv_t_16", texto: "Em jogos como Poker com feijões/dinheiro falso:", opcoes: ["Faço all-in em todas as rondas 'só pela adrenalina'", "Faço grandes bluff e meto a minha 'poker face' imbatível", "Tenho boas cartas e começo logo a sorrir e mostro a jogada", "Meto as apostas tão baixas que aborreço as pedras de calçada"] },
    { id: "c_jv_t_17", texto: "A meio de um jogo super demorado (tipo Risk):", opcoes: ["Foco-me com a precisão do Napoleão e faço alianças", "Crio estratégias e depois espeto a faca nas costas do meu amigo", "Já não sei jogar e ataco à sorte o país que estiver mais perto", "Começo a mexer no telemóvel e pergunto 'quando é a minha vez?'"] },
    { id: "c_jv_t_18", texto: "Quando há amizades ou casais a jogar contra nós:", opcoes: ["Tento logo arranjar divórcios entre eles 'ele roubou-te um boi no jogo!'", "Aliamo-nos eu e os outros para destruir esse casal abençoado", "Odeio quando eles mostram as cartas um ao outro por baixo da mesa", "Eles chateiam-se mesmo a sério no fim e a noite acaba ali"] },
    { id: "c_jv_t_19", texto: "Jogos tipo Cards Against Humanity (Gatilhos escuros):", opcoes: ["Ganho sempre, tenho o humor mais negro e sujo da sala", "Sinto-me culpado a meter cartas absurdas e más", "Acho super sem piada e deprimente ver a mente dos meus amigos", "Guardo a carta branca vencedora para a ronda de ouro"] },
    { id: "c_jv_t_20", texto: "Em suma, no mundo dos jogos de mesa eu sou:", opcoes: ["O General Controlador (as regras primeiro!)", "O Sabotador (vou só para o caos, nem quero ganhar)", "O Conformado (vão-me comendo as peças todas em silêncio)", "O Mal-Educado (rego a mesa a cerveja e palavrões)"] }
  ]
};
