import { PerguntaClassica } from "@/types/catalogo";

export const classico_livros_leitura: Record<string, PerguntaClassica[]> = {
  "sub_23_0": [ // Hábitos de Leitura
    { id: "c_ll_h_01", texto: "Quando compro livros novos (o fenómeno Tsundoku):", opcoes: ["Leio religiosamente o que comprei", "A pilha na mesa de cabeceira está enorme e acabo a ver Netflix", "Compro só pelas lombadas coloridas para ficar estético na estante", "Leio as primeiras 10 páginas e abandono-os"] },
    { id: "c_ll_h_02", texto: "A ler na cama antes de adormecer:", opcoes: ["Leio e o livro cai-me em cima da cara (magoo o nariz)", "Faço de propósito, leio e adormeço de forma zen", "Leio um capítulo e fico acordado a pensar no drama a noite toda", "Tenho preguiça de ligar a luz de cabeceira, nem pego no livro"] },
    { id: "c_ll_h_03", texto: "Qual a minha atitude com os cantos das páginas (orelhas)?", opcoes: ["Odeio! Dobrar as páginas é um crime! Uso um marcador.", "Dobro sempre o canto, é prático e rápido", "Deixo o livro virado de bruços aberto e estrago a lombada", "Uso um talão das finanças ou um bocado de papel higiénico como marcador"] },
    { id: "c_ll_h_04", texto: "O aroma dos livros físicos:", opcoes: ["Sou como um aspirador, cheiro as páginas todas dos livros novos", "Acho o cheiro do papel velho ou das bibliotecas divinal", "Não sinto cheiro nenhum, mas gosto de sentir as páginas", "Dá-me alergias ao pó, prefiro livros digitais"] },
    { id: "c_ll_h_05", texto: "Livros Físicos de Papel vs E-readers (Kindle, Kobo):", opcoes: ["E-reader! Carrego a biblioteca na mala e leio no escuro", "Livro Físico! Não dispenso o toque e passar a página", "Ouço Audiobooks a lavar a loiça, sou demasiado ocupado/a", "Qualquer um serve desde que eu não tenha de carregar no lombo"] },
    { id: "c_ll_h_06", texto: "Ao emprestar um livro meu a amigos:", opcoes: ["Empresto mas chateio a pessoa todas as semanas: 'Estás em que página?'", "Nunca mais os vejo, transformam-se em fantasmas", "Meto o meu nome escrito gigante na 1ª página com data", "Não empresto! São os meus bebés, vão lá comprá-los."] },
    { id: "c_ll_h_07", texto: "Na praia / férias grandes, os meus livros:", opcoes: ["Devoro uns 3 livros na espreguiçadeira com classe", "Levo-os na mala, enchem-se de areia e regresso sem os ter lido", "Apanho com o sol na cabeça, adormeço e o livro esvoaça ao vento", "Leio revistas ou fofocas do Instagram, poupa trabalho cerebral"] },
    { id: "c_ll_h_08", texto: "Como reajo quando um livro me aborrece:", opcoes: ["Forço-me a ler até à última página, como um dever moral", "Tento ler por alto (na diagonal) para ver se melhora no fim", "Bato com o livro, deito-o fora e digo mal no Goodreads", "Leio logo a última página e guardo-o na prateleira"] },
    { id: "c_ll_h_09", texto: "O hábito de sublinhar / riscar nos livros:", opcoes: ["Blasfémia! O livro tem que ficar intocável, sem vincos", "Sublinho, meto setas, rabiscos e escrevo notas com caneta preta", "Ponho post-its transparentes e coloridos hiper organizados", "Só risco livros de estudo ou da escola, mas choro à mesma"] },
    { id: "c_ll_h_10", texto: "Qual a minha velocidade de leitura?", opcoes: ["Devoro livros de 400 páginas num fim de semana a chover", "Leio duas páginas por noite e demoro um ano civil num livro", "Sou de fases: leio 3 num mês e depois passo 6 meses sem abrir nenhum", "Sou um leitor dinâmico da diagonal das páginas (tipo exame nacional)"] },
    { id: "c_ll_h_11", texto: "Ler no autocarro, comboio ou em andamento:", opcoes: ["O meu melhor local, abstraio-me das cusquices das pessoas à volta", "Fico profundamente enjoado/a após duas frases e paro", "Adoro para parecer intelectual a quem passa de pé no metro", "O barulho distrai-me, acabo a ler o mesmo parágrafo 20 vezes"] },
    { id: "c_ll_h_12", texto: "Organizar as minhas prateleiras em casa:", opcoes: ["Organizados pelas cores da lombada em modo Arco-Íris", "Por Ordem Alfabética de autor, como numa livraria ou biblioteca", "Tamanhos do maior pó menor (TOC clássico)", "Estão atirados em pilhas empilhadas a apanhar a humidade"] },
    { id: "c_ll_h_13", texto: "Quando estou a ler e perco o foco:", opcoes: ["Dou por mim a pensar na lista do supermercado e no que o chefe disse", "Tenho que voltar atrás 5 páginas porque não prestei atenção a uma única letra", "Continuo a ler e espero que o meu cérebro resgate a informação algures", "Fico com fome e acabo por ir à cozinha comer chocolates"] },
    { id: "c_ll_h_14", texto: "Sobre as longas descrições num livro clássico (tipo Eça ou Saramago):", opcoes: ["Adoro a poesia da descrição e os pormenores infinitos de cada parede do quarto", "Passo logo essas secções de 3 páginas só para ver onde os diálogos voltam", "Leio a meio gás e acabo sem perceber sequer o nome da personagem", "Esses só li (mal) no Secundário, recuso ler fora da obrigação letiva"] },
    { id: "c_ll_h_15", texto: "O que diz a capa ou sinopse do livro sobre a minha compra?", opcoes: ["Compro 100% livros pelas capas bonitas ilustradas, sou culpado/a", "Sou seduzido pelos títulos tipo Tiktok ou por ter 'Bestseller no Times'", "Demoro meias horas a ler as costas dos livros sentadinho no tapete da Bertrand", "Se a grossura do livro passar dos 4 centímetros, recuo de medo"] },
    { id: "c_ll_h_16", texto: "Qual o meu lanche perfeito com leitura de Outono?", opcoes: ["Chá / Café quente com a almofadinha grande", "Bolachas Maria que migalham a capa toda do livro no sofá", "Um copo de vinho e muita melancolia a bater", "Só leio com pastilhas nos dentes!"] },
    { id: "c_ll_h_17", texto: "A ler o Goodreads (a aplicação de ranking dos livros):", opcoes: ["Guardo e pesquiso como uma agenda de excel", "Sou um crítico cruel que dou 2/5 estrelas e rebaixo com classe os autores", "Leio críticas depois de comprar e fico deprimido porque todos dizem mal do meu livro!", "Good..what? Prefiro não mostrar aos outros que não leio."] },
    { id: "c_ll_h_18", texto: "Quando vejo pessoas a ver TV até tarde na cama enquanto tento ler a história do século:", opcoes: ["Enfio tampões de ouvido e peço o silêncio de ouro com cara de mau", "Abandono o meu santuário de leitura que devia ser relaxante e ligo a TV também", "Ligo o meu tablet em desespero e sinto um ódio interior", "Mando ler o parágrafo em alta voz e aborrecer quem tá na cama até desistirem!"] },
    { id: "c_ll_h_19", texto: "A sensação de chegar ao fim de um livro BRUTAL:", opcoes: ["Fico em modo de 'luto de ressaca de livros', onde é que me agarro agora?!", "Fecho e não espero, começo logo outro da saga a varrer tudo à frente", "Fico feliz e ponho na foto no Insta do Booktok!", "A meio das partes choro se a morte dita for amarga de aturar!"] },
    { id: "c_ll_h_20", texto: "Sobre ler várias coisas ao mesmo tempo:", opcoes: ["Só consigo devotar o meu amor e cérebro a um livro único!", "Leio o e-book, no quarto um triller e no WC leio as BDs aos bocadinhos!", "Misturo os enredos todos das 3 obras!", "Isso não é ser leitor, é a loucura extrema de perder a narrativa!"] }
  ],
  "sub_23_1": [ // Livros Favoritos
    { id: "c_ll_f_01", texto: "O que acho da frase eterna 'Ah, mas o livro era muito melhor do que o filme':", opcoes: ["Eu sou e serei sempre o porta-voz dessa grande verdade (Snoob dos Livros)", "Nalgumas cenas sim, mas admito que os filmes de Harry Potter/Senhor dos anéis dão mais magia", "Eu digo essa frase apenas depois de ver no Wikipedia e sem nunca ter lido a obra original", "Prefiro que mo contem no grande ecrã. Não tenho paciência para a teoria do calhamaço grosso."] },
    { id: "c_ll_f_02", texto: "Qual é o grande e sagrado 'Livro Clássico' da escola que as pessoas fingem ter lido e gostado?", opcoes: ["'Os Maias', aquela malta no Ramalhete é doida mas adoro Eça!", "'Memorial do Convento', que não tem o ponto do teclado... aborreci-me", "'Os Lusíadas' (só com os resumos das notas de fim de caderno de professor de canto)", "Eu adorei, sinceramente a Mensagem é daquelas merdas top! (Nerd puro e honesto)"] },
    { id: "c_ll_f_03", texto: "Os livros da adolescência que nos marcaram (Vampiros ou Bruxos):", opcoes: ["Crepúsculo (Twilight) - eu queria ser o Edward / Bella", "Harry Potter forever (Revolto as gavetas do Chapéu Selecionador em miúdo)", "Saga do Percy Jackson / Jogos da Fome, revolução na veia", "Lia o Gerónimo Stilton e não passava do ratinho jornalista"] },
    { id: "c_ll_f_04", texto: "Os livros mais românticos e Pimpona da vida de capa mole (Romances Eróticos/Melo-Dramáticos):", opcoes: ["Choro imenso a devorar os 'Colleen Hoover' ou os livros de praia do Nicolas Sparks", "Compro em segredo e escondo com panfletos da Cristina Ferreira nas prateleiras", "Desdenho isso! Pura palha. Prefiro História Europeia de não sei o que..", "Lia o '50 Sombras de Grey' na adolescência, no autocarro escolar com vergonhas"] },
    { id: "c_ll_f_05", texto: "Quando os meus personagens morrem ou levam cornos do(a) amado(a) nos capítulos do fim de livro:", opcoes: ["Escrevo raiva no Twitter ao autor e rasgo o final imaginário nas entrelinhas!", "Tenho a coragem de voltar páginas a ver se entendi o contexto falso das entrelinhas!", "Rio e digo 'Grande Twist ou Reviravolta de Mestre!' e admito que adoro choradeiras trágicas", "Atiro com a lombada no caixote de reciclagem, odeio o Game of Thrones dos livros."] },
    { id: "c_ll_f_06", texto: "Auto-Ajuda e Livros para Empreendedores e Desgraças Místicas Financeiras (Pai Rico Pai Pobre / Segredo):", opcoes: ["Odeio de morte! Promessas ao vento das aldrabices dos ricos das Maldivas", "Tenho 5 e só li a cotação das passagens das águas mansas onde nada serve para PT", "Inspiraram a minha vida e digo sempre que o Universo atrai fortunas boas aos amigos", "Comprei porque achei que amanhã acordaria sem faturas das finanças ou da EDP"] },
    { id: "c_ll_f_07", texto: "Livros e a saga do Fantástico nas entrelinhas (Reinos, Elfos, Espadas, Misticismos):", opcoes: ["Amo profundamente o universo denso de mil anos a ler Senhor dos Anéis em paz", "Gosto mais quando roça ali na Idade média crua (Game of Thrones no Inverno a sofrer o sangue e neve)", "Perco o raciocínio nos 50 nomes começados pela Letra 'E' ao virar das prateleiras do papel", "Não dá, se a pessoa não conduz um Honda Civic nos livros ou tem Wi-Fi eu desligo!"] },
    { id: "c_ll_f_08", texto: "Banda Desenhada e Mangas a torto e direito na FNAC, o que fazer?", opcoes: ["Comprei o DragonBall / Naruto aos montinhos na primária dos meus 15 euros dados pelos Tios", "Astérix / Tintim era as lendas supremas no WC", "A BD da Tio Patinhas na sala de espera do Dentista era de chorar com amor verdadeiro!", "Isso não é ser um livro a sério..."] },
    { id: "c_ll_f_09", texto: "O que acho dos livros super populares recomendados na internet do Tiktok (Booktok)?", opcoes: ["Comprei as capas coloridinhas e de que todos gritam de adoração no scroll do insta da vizinha do lado!", "Devem ser super aborrecidos.. detesto cenas modernas", "Sou a vitima clássica da promoção dos vídeos das americanas em lágrimas e arranco para Fnacs", "Nem tenho redes. Leio comédias parvas da livraria pingo doce à moda velha.."] },
    { id: "c_ll_f_10", texto: "Em que lugar da ficção preferia eu viver a minha vida como protagonista eterno da glória nas prateleiras dos meus livros favoritos?", opcoes: ["Numa base secreta ou espaço super longínquo, da Star Wars a viver a saga de heróis em rebeliões espaciais e a andar aos tiros de luzes", "Numa biblioteca ou castelo onde existisse paz eterna! Nos reinos tipo Senhor dos Anéis de perninhas pro ar numa aldeia com Hobbitos do meu lado do fogo com caldos das panela. Paz!", "Em reinos feudais medievais de Game Of Thrones (Mas rezo p/ q os dragões p/ não me darem chamas logo à noite)", "No mundo fantástico dos livros dos feiticeiros da Escola da Rua com feitiços! Magia!! Hogwarts de fato preto à lenda de óculos e gravatinha à antiga!"] },
    { id: "c_ll_f_11", texto: "Sobre biografias e histórias da vida das celebridades no papel impresso na prateleira lá de casa ou do amigo:", opcoes: ["Lia se for do Zlatan, CR7 ou de músicos rock dos velhos tempos dos anos oitenta em pânico do desastre! Vida a bater as rochas do abismo da perdição", "Compro porque adoro a fofocada da malta! Especialmente se a princesa ou ator rasgar os podres das noites ocultas do cinema ou das coroas!! Tudo lá!!", "Livro onde malta se acha o topo! Gaba muito e o autor fantasma fantasiou e escreveu tudo. Detesto biografias de vaidades!! E as falsidades!", "Leio dos génios das teorias pesadas do mundo das galáxias e dos cérebros antigos dos Einsteins. Cultura intelectual sem filtros!!"] },
    { id: "c_ll_f_12", texto: "Livros de Suspense ou Policiais da moda que prendem da capa à letra no canto dos sofás com mistérios dos detetives e as poças do molho vermelho dos assaltos noturnos:", opcoes: ["Adoro e devoro e nunca passo a parte dos culpados. Agatha Christie na alma a puxar pelo mistério da velha panela!", "Tento adivinhar logo aos fins de meia hora o culpado e, se errar, o autor das folhas do thriller enganou-me com golpes fáceis e mentirosos!", "Passo para o final (na página 300 e trocas) só para deitar água às dúvidas do meu coração. Não aguento a tensão do psicopata do mato na minha mente a ler a dor da senhora da corda!", "Enjoa e aborrecimento nas entrelinhas das mortes trágicas. Sou fã das coisas meigas tipo romances asquerosos e florzinhas pelo vale da vida mansa com amores!"] },
    { id: "c_ll_f_13", texto: "O que preferes como prenda perfeita?", opcoes: ["O clássico Vale da Livraria com guito nas caixas a dar os bons mimos da liberdade para ir correr à secção policial e esgotar 3 livros num saque. O cheiro da escolha do leitor clássico!", "Prefiro um livro em concreto já dos famosos escolhidos. Que tenham lido! Ou a edição dourada de capa dura encadernada (para os ricaços da sala dos quadros)! Daqueles que mostram o brilho da cultura a todos lá de fora das janelas da alma estática", "Uma T Shirt de malha ou jantares. Se oferecerem, livro com letras eu vou deitar nas poças dos quartos das prateleiras no escuro por séculos!", "Kindle. Edição top das batarias longas e digitais do futuro que não dão calos às mãos e carregam de forma livre as piratarias pdf nos bolsos pequenos e sem os papéis! Custo zero no mato. Só se perdem cabos no fim."] },
    { id: "c_ll_f_14", texto: "Sobre sagas épicas e grossas com mais de sete volumes grossos espalmados pelas costas que doem das sacas pesadas (Ex: A Roda do Tempo, Game of Thrones)?", opcoes: ["Eu meto o meu pijama do luto! O compromisso. E vou dar tudo e jurar no altar da leitura do abismo escuro da vida a mergulhar de cabeça nos mapas da contra capa das cidades falsas aos tombos e ver a saga de pernas altas do trono ao meio do chão!!", "Desisto ao segundo tomo grosso! Sou crente nas letras de mil folhas e depois os capítulos das mortes desanimam e dão azia profunda. Arrependo por pagar logo na caixa a trilogia inteira no escuro por fé das publicidades da fama..", "Espero a série oficial da televisão! HBO Netflix Amazon e dobras do teto do ecrã das 50 polegadas!! Leio os resumos nas publicações. Gasto menos guito da net. E passo horas no pijama no lanche sem o esforço e vejo imagens sem puxar o cérebro à corda.. Sou prático/a!!", "Começo pelo fim a ler a Wiki ou a Wiki. Nomes das arvores ou generais com títulos de Srs de Lanças nas lendas medievais dão sono à vida! Não entendo o drama do dragão se o Rei muda e não explica logo na página primeira das entrelinhas finas! Letra Míope das letras que matam pálpebras!"] },
    { id: "c_ll_f_15", texto: "O melhor local na rua com a brisa mansa das leituras do livro favorito do ano?", opcoes: ["A relva. As árvores verdes num pano quente. Parques de silêncio de domingo com luz de ouro", "Esplanadas de sol do meio do café. Ouço e pico da orelha atenta o chisme da vizinha na mesa e aponto as rimas! No barulho branco eu foco na leitura da paz e bebo o galão escuro de torradas à sombra. É vício do tuga intelectual", "Areia. Praia ou Beira de mares! Com barulheira e bica nos lençóis do chapéu velho.. Adormeço, deito areia no papel do livro que range nas juntas.. e acabo os 3 volumes mas não me recordo de 1 letra sequer.. e trago pó..", "Viajante eterno.. Comboios e os metros na calada. Ignorar multidões densas e enfiar o pescoço de abutre na cara do Kindle até parar na saída certa ou ser assaltado na mochila.. Paz urbana do transporte e viagens das carreiras.."] },
    { id: "c_ll_f_16", texto: "Para ti o livro é melhor que a série... Mas quando o livro vira uma série que de facto destrói as raízes todas e as fofocas das entrelinhas no ecrã e muda caras e pormenores, tu como fã dos puristas originais fazes o que no escuro dos cinemas ou sofás com pipocas quentes?", opcoes: ["O clássico insultar de pragas na TV! Fico a dar 'Pause' nas cenas do desastre do ator! O 'O MÁRIO NÃO TINHA CABELO LOIRO!!' aos gritos no escuro para os meus coitados dos amigos! A pessoa mais aborrecida com dores do livro!", "Se a cena for decentemente porreira de CGI (Gráficos), e as músicas mexem o meu ego interior, eu cago! Juro focar nas cenas fixes! Deixo o livro na gaveta no cérebro a fechar e encarno o zé pipocas e atiro sorrisos à série a desligar purismos!", "Faço textões da raiva do luto no Twitter (agora 'X'). Reclamo das alterações dos roteiristas amadores nos diretos das redes a dar com paus nos gajos porque mataram o enredo das 300 paginas no meu mundo de cor.. e a capa foi mudada na loja para pôr o Ator. Crime!!!", "Eu até fico com ódio interior silencioso a revirar do olho em 3D, mas passo o pão nos filmes na mesma só p poder ter argumentos reais com as pessoas do trabalho na segunda feira das pausas com poder total!! Sou o rei do debate! E se choram eu aponto."] },
    { id: "c_ll_f_17", texto: "Com os grandes ensaios das coisas mais longas do abismo do secante como a poesia mista grossa portuguesa e rimas parvas sem vírgulas nenhumas dos velhotes intelectuais e antigos da vida do bigode (Fernando Pessoa ou os génios complexos do nada), a atitude do teu cerne é da honestidade total:", opcoes: ["Eu encosto-me e desfruto das letras doces dos grandes gênios em profundezas e o chá escuro quente.. Amo e compreendo o 'Ó Mar salgado, quanto do teu sal..'", "Eu pego e deito o livro para trás! Odeio não haver parágrafos de ações diretas! Falta o bico de ação no poema. Tanta lágrima escrita por pedras, pássaros das serras e rimas tristes do luto de Lisboa num banco? Não dá, fecho e encosto!", "Finjo sempre. Quando as gajas ou gajos ou chefes estão perto na roda ou de visita eu cito o 'Tabacaria' do Campos nas calçadas de Sintra para dar estilo de culta! E encorajo aos intelectuais as capas das rimas com canetas. Sou poser das livrarias clássicas das modas!", "Saramago sem pontos finais. Choro do olho e do cérebro na ansiedade e pego num lápis e faço vírgulas nas folhas brancas porque não consigo ler o amasso do texto denso como bolo mal cozido! Juro a Deus.. Dores de alma as letras de Camões do peito."] },
    { id: "c_ll_f_18", texto: "O que preferes: Livros e Histórias Verídicas Fortes da dor do drama autêntico das guerras e diários dos sofredores ou os grandes SciFi de ETs loucos no planeta Vermelho com laser e fantasias dos monstros dos anéis mágicos e bruxos com fadas gordas de dragão a cuspir o terror de cima dos arranha-céus na cabeça do duende triste de espada?", opcoes: ["O Drama. A Força dura do choro da senhora da segunda guerra a comer farinha escondida no sótão. Não consigo com o bicho verde a rir na lua alien na nave que chupa água da estrela. Prefiro história verídica com dor profunda de factos nos dentes da história real da humanidade", "SciFi dos ETs nas nuvens espaciais com raio laser dos anos mil duzentos! É espetáculo! Ligo para fugir das minhas rendas e finanças! Histórias da vida de prantos da guerra na minha prateleira já chega o que eu ouço a cuscar os telejornais tristes dos velhotes da mesa das tascas..!", "Fantasias e Dragões a arder a lenha e Reinos a batalhar coroa. Amo castelos fortes no meio do gelo! Não dispenso o medieval puro com Elfos das espadas na garganta dos anões da corte de pedra.. o resto do ET aborrece porque parece carros a dar e não me identifico! E de choradeiras a Sra da guerra é pior q o telejornal das oito da CMTV. Fuja!!", "Apenas Histórias Verídicas se forem polícias reais, crimes, bandidos da vida crua dos assassinos das meias noites que foram parar ao tribunal! E documentários da polícia! Investigação até à medula do cérebro. Mas os dois, SciFi com Et's dos ares ou Reis com dragão que cospem a tosta, fujo e acho super estúpido na mentira amarga dos adultos a brincarem.."] },
    { id: "c_ll_f_19", texto: "Os livros da comédia da piada no calhamaço com o cromo parvo (A vida secreta ou Memórias de gajos estranhos dos standups da rotina de humor e afins do tipo Ricardo de Araújo). Na leitura no sofá a sorrir:", opcoes: ["Gargalho tão alto que choro baba nas almofadas e pareço um maluco nos cantos ou no autocarro a virar páginas a rir para mim no fundo, com as velhas a julgar! Amo as piadas da leitura de papel das comédias!! Bato nas pernas às gargalhadas na piada da tosse do avô e leio de boca aberta no comboio de lisboa e tudo.. sem vergonha no peito e espirro!!", "Nunca entendo o ritmo do bico da rima do standup de papel sem ouvir a boca do artista. Fica tudo pálido e não abro os cantos dos lábios. Acho as letras um aspeto tristonho para fazer do rir. É que ler humor é tão seco como beber sumos sem o açúcar. Falta som! Comédia e humor no papel grosso a bater no sofá é pior que ir às pedras.. não rola. Deito pro lado do móvel", "Acabo a dar só as lidas da tanga do que me rir e passo as piadas aos outros como se eu as gerasse no momento num jantar da roda de copos com minis e rissol a mandar os bitaites. Passo pelos gênios nas frases das piadas lidas nos livros secos dos humores.. E recolho glórias e risadas do mundo. Sou aldrabão nos memes e standup falsos no meu ego!", "Leio os diários e comédias de humor negro da malta dos USA a gozar da dor alheia no sofá! Bato nas mesas a rir mas escondo o que estou a ler na capa das revistas do gajo para não me julgarem de psicopata nos autocarros na linha de baixo dos fundos, o povo diz que não há decência de rir disso e mudo de face!" ] },
    { id: "c_ll_f_20", texto: "No grande desfecho (Spoiler Alert) da vida das personagens no enredo final de romance. Ficam felizes no fundo da vila, com filhos na praça de beijos ao luar eternamente na casa do fim do mundo sem dinheiros mas repletos das vitórias e rosas: E a tua atitude no cair da capa do calhamaço grosso do papel?", opcoes: ["O meu peito do amor grita nos ventos do abismo da emoção! 'Eles mereciam depois da tormenta das chamas e traições!!'. Limpo com panos quentes a ranheta de chorar! Deixo no peito a esperança viva das fadas! Boto o livrinho com estrelas douradas debaixo da travesseira para dormir nos sonhos de encantar da Disney moderna! É um 'Uaaaaau, amor' no fundo da alma do tuga chibato meigo!", "Que treta mais foleira do cliché de Hollywood americano nos baldes das letras! Já sabia nos inícios do capítulo dois a bater as chamas.. detesto os finas meiguinhos das felizes aves e canções do mato. Queria mortes da noiva! Gajo fugia das dívidas, o castelo despencava em escombros com vilões nos cavalos a rir por cima dos dois amantes rotos. Isto não é da lida da vida bruta e real. Chateio-me e boto o livro nas lareiras.. fujo", "Deixo a folha cair.. Fico no grande vazio dos mundos. Olho os brancos do tecto da janela com o peito escavado na depressão clássica das ressacas das tramas do ler... 'A minha vida não tem esta profundidade na treta do café do Ti Manel. Qual amores de rosas ao luars?? Eu nem arranjo cães p passear, eles estão lá nas magias, onde pego nas personagens que viraram os meus primos no final do papel branco?!'. Abismo escuro nas almas", "Dou as costas! E o final era obvio que eu passava as últimas doze do nada. Vou p/ Goodreads do livro meter a boca no asfalto nas entrelinhas. Dou duas estrelas do rating com críticas dos diálogos, culpo os buracos das ações, acuso de forçar cenas do romance só p sacar lagrimas do adolescente nas estantes e passo a vida p as publicações seguintes do calhamaço e cago o rol do assunto nas noites vadias das críticas. Frio como gelos!" ] }
  ]
};
