import { PerguntaClassica } from "@/types/catalogo";

export const classico_moda_estilo: Record<string, PerguntaClassica[]> = {
  "sub_15_0": [ // Gostos de Roupa
    { id: "c_me_g_01", texto: "Qual é a minha farda oficial de fim de semana em casa?", opcoes: ["O mesmo pijama o fim de semana inteiro", "Fato de treino cheio de borbotos mas confortável", "Uma t-shirt de propaganda gigante e desbotada", "Roupa normal de sair, gosto de me sentir arranjado/a"] },
    { id: "c_me_g_02", texto: "Como defino o meu estilo diário?", opcoes: ["O clássico 'básico': jeans e t-shirt", "Parece que vou sempre para o ginásio", "Visto a primeira coisa que não esteja suja", "Sempre 'on point', pareço saído/a do Pinterest"] },
    { id: "c_me_g_03", texto: "Qual é a minha regra sobre passar roupa a ferro?", opcoes: ["Passo tudo, até as meias e cuecas", "Só passo camisas se tiver reuniões", "O meu ferro de engomar serve a própria roupa no corpo quente", "Tenho fobia ao ferro, sacudo bem ao secar e rezo"] },
    { id: "c_me_g_04", texto: "Sobre usar sapatos em casa:", opcoes: ["Ando calçado com sapatilhas de rua pela casa toda", "Tiro imediatamente os sapatos à porta e meto pantufas", "Ando só de meias e depois ficam pretas na sola", "Ando descalço e apanho farpas e migalhas"] },
    { id: "c_me_g_05", texto: "O que acho da moda de vestir tudo 'Oversized' (tamanhos gigantes)?", opcoes: ["Adoro, parece que ando vestido/a com uma tenda de campismo", "Uso, esconde perfeitamente os jantares de ontem", "Acho horrível, parece que não temos espelhos em casa", "Só uso no Inverno para enfiar camadas por baixo"] },
    { id: "c_me_g_06", texto: "Quando não sei o que vestir para uma saída à noite:", opcoes: ["Vou de preto total, nunca falha", "Mando 50 fotos diferentes aos meus amigos a pedir opinião", "Acabo a vestir a mesma roupa que usei no fim de semana passado", "Faço uma crise de choro deitada na cama a dizer 'não tenho roupa!'"] },
    { id: "c_me_g_07", texto: "A minha gaveta da roupa interior:", opcoes: ["Tudo dobrado à Marie Kondo", "Meias todas sem par e misturadas numa bola", "Cheia de cuecas rotas que me recuso a deitar fora 'para pintar a casa'", "Tenho as meias boas e as meias com buraco no dedo grande"] },
    { id: "c_me_g_08", texto: "Comprar roupa na secção de criança:", opcoes: ["Sou bué pequenino/a, faço isso para poupar guito!", "Acho bizarro e nunca caberia lá dentro", "Compro as camisolas lá porque fica mais barato e dá igual", "Só para os sapatos, não pago o mesmo imposto que o calçado de adulto"] },
    { id: "c_me_g_09", texto: "A atitude perante os casacos de Inverno:", opcoes: ["Tenho um único casaco para a chuva, neve e vento", "Tenho 10 casacos e queixo-me na mesma que tenho frio", "Uso hoodies (camisolas de capuz) e finjo que chega", "Ando a bater o dente em t-shirt porque 'o casaco estragava o outfit'"] },
    { id: "c_me_g_10", texto: "Sobre roupa de marcas caras com logos enormes:", opcoes: ["Uso e abuso, quero que vejam que tenho estilo (e dinheiro)", "Só uso se for em promoção, mas não gosto de logos gigantes", "Acho super azeiteiro, parecem outdoors andantes", "Prefiro marcas brancas que não dizem nada"] },
    { id: "c_me_g_11", texto: "A roupa de andar por casa na rua:", opcoes: ["Ir ao supermercado de pijama por baixo do casaco? Culpado/a.", "Meto fato de treino e chinelos, não quero saber", "Jamais! Mudo de roupa até para ir pôr o lixo à porta", "Se não virem o pijama, o crime não existiu"] },
    { id: "c_me_g_12", texto: "Quando vejo as minhas fotos de há 10 anos atrás:", opcoes: ["Sinto vergonha extrema, quem me deixou vestir aquilo?!", "Acho que tinha grande estilo, ainda vestia hoje", "Questiono porque é que as sobrancelhas e o cabelo eram assim", "Rio-me e posto logo no grupo dos amigos para gozar"] },
    { id: "c_me_g_13", texto: "O que acho sobre combinar as meias?", opcoes: ["Têm de ser iguais e do mesmo tamanho", "Se forem as duas pretas, está bom", "Uso uma de cada cor de propósito, é estilo", "O que vier à rede na gaveta de manhã cedo serve"] },
    { id: "c_me_g_14", texto: "A minha relação com os sapatos apertados:", opcoes: ["Se doerem muito, atiro-os para o fundo do armário", "A beleza custa, sofro em silêncio com a bolha a sangrar", "Levo sempre chinelos na mala para trocar a meio da noite", "Metos-lhe jornais e álcool para alargar como a avó ensinou"] },
    { id: "c_me_g_15", texto: "Roupa branca no Verão:", opcoes: ["Visto-me e mancho-me com ketchup 10 minutos depois", "Sou cuidadoso/a, chego ao fim do dia imaculado/a", "Odeio branco, prefiro preto para suar sem que se note", "Só uso na Passagem de Ano ou em casamentos na praia"] },
    { id: "c_me_g_16", texto: "Com que frequência lavo os meus jeans (calças de ganga)?", opcoes: ["Uso 1 vez e vai para o cesto da roupa suja", "Uso umas 5 vezes antes de lavar", "Lavar jeans? Eu atiro-os para a cadeira e eles limpam-se sozinhos", "Só lavo quando já ficam de pé sozinhas de tanta sujidade"] },
    { id: "c_me_g_17", texto: "Quando uma camisola encolhe na máquina de lavar:", opcoes: ["Choro a perda e dou ao meu cão para cama", "Finjo que é um crop-top da moda e uso", "Tento esticar a camisola com força bruta a ver se volta ao normal", "Dou aos meus irmãos mais novos disfarçadamente"] },
    { id: "c_me_g_18", texto: "Tirar fotos do 'Outfit of the Day' no espelho:", opcoes: ["Todos os dias no elevador do prédio", "Tento tirar mas sai-me o reflexo do flash na cara", "Tiro só para aprovação do grupo do WhatsApp", "Acho ridículo e sigo em frente com a minha vida"] },
    { id: "c_me_g_19", texto: "O que diz a minha mãe do meu estilo?", opcoes: ["'Vais sair à rua vestido assim?!'", "'Que lindo/a menino/a, pareces um(a) príncipe/princesa'", "'Essa roupa tem buracos de propósito?'", "'Pões esse casaco que ficas com dores de garganta'"] },
    { id: "c_me_g_20", texto: "Sobre pedir a opinião dos meus amigos para comprar roupa:", opcoes: ["Pergunto e depois faço exatamente o oposto", "Levo-os à loja para validarem a compra", "Compro sem dizer nada e apareço com aquilo vestido", "Mando 10 fotos no provador em pânico"] }
  ],
  "sub_15_1": [ // Compras Impulsivas
    { id: "c_me_c_01", texto: "Quando a Zara/Mango entra em saldos:", opcoes: ["Fico na porta às 9h da manhã para ser o/a primeiro/a", "Vou online à meia-noite e esvazio o carrinho", "Vou no fim da semana remexer na roupa que caiu ao chão", "Ignoro, acho uma confusão e só sobra roupa XS"] },
    { id: "c_me_c_02", texto: "O que sinto depois de uma grande compra impulsiva?", opcoes: ["Felicidade e adrenalina absolutas", "Culpa e prometo a mim mesmo que vou poupar a seguir", "Escondo os sacos da minha família/parceiro", "Começo a inventar 10 desculpas lógicas por que PRECISAVA daquilo"] },
    { id: "c_me_c_03", texto: "Comprar roupa nas lojas chinesas online (Shein/Temu):", opcoes: ["Mando vir 30 peças de uma vez por 50€ e seja o que Deus quiser", "Meço-me com uma fita métrica e leio as opiniões todas 3 vezes", "Acho que a qualidade é péssima, não confio", "Só encomendo gadgets manhosos para o carro/casa"] },
    { id: "c_me_c_04", texto: "Quando vejo que falta 2€ para os 'Portes Grátis':", opcoes: ["Meto uma peúgas de 5€ no carrinho para poupar os 3€ de portes", "Pago os portes indignado/a, odeio o sistema", "Passo duas horas a procurar mais coisas e gasto mais 50€", "Cancelo a encomenda por raiva"] },
    { id: "c_me_c_05", texto: "Na fila do provador (experimentar roupa):", opcoes: ["Levo as 5 peças permitidas e ainda escondo mais 2 por baixo", "Fico com tanta preguiça de despir que não provo nada, rezo e compro", "Passo lá meia hora a fazer um desfile de moda para os amigos", "Sinto que o espelho engorda sempre 5kg e saio deprimido"] },
    { id: "c_me_c_06", texto: "O que me acontece nas caixas registadoras (fila)?", opcoes: ["Acabo a comprar chicletes, pilhas e chupas que lá estão", "Fico a julgar o carrinho de compras da pessoa da frente", "Reviro as moedas todas para pagar certo e demoro horas", "Fico com suores frios com medo que o cartão não passe"] },
    { id: "c_me_c_07", texto: "Se estiver triste ou num dia mau, o meu impulso é:", opcoes: ["Comprar roupa nova online", "Ir jantar ou mandar vir muita comida no UberEats", "Ir ao supermercado comprar gelado e batatas fritas", "Não gasto nada, sofro de graça em casa"] },
    { id: "c_me_c_08", texto: "Qual a minha relação com Sapatilhas (Ténis/Sneakers)?", opcoes: ["Tenho demasiados, são a minha ruína financeira", "Tenho 1 ou 2 pares que uso até furarem o dedo grande", "Compro marcas caras e limpo as solas com escova de dentes", "Compro na feira e finjo que são de marca"] },
    { id: "c_me_c_09", texto: "Comprar maquilhagem / cremes de skincare:", opcoes: ["Gasto o ordenado na Sephora, a minha pele tem de estar perfeita", "Uso o clássico creme Nívea da lata azul para a vida toda", "Compro imenso mas chego a casa e a preguiça ganha, não uso nada", "Lavo a cara com o sabonete das mãos e tá a andar"] },
    { id: "c_me_c_10", texto: "A minha capacidade de devolver uma compra online:", opcoes: ["Tenho pânico das etiquetas e códigos dos CTT, acabo por ficar com a peça", "Devolvo sempre e sou expert na aplicação da transportadora", "Dou os restos ou as peças erradas à família", "Tento vender na Vinted para recuperar o prejuízo"] },
    { id: "c_me_c_11", texto: "Comprar roupa na Vinted/Lojas em 2ª mão:", opcoes: ["Adoro! Poupo imenso e sinto-me eco-friendly", "Odeio regatear e oferecer '2€ com portes incuídos'", "Nunca compro, tenho nojo de roupa usada", "Sou vendedor/a lá para despachar o lixo que tenho em casa"] },
    { id: "c_me_c_12", texto: "O meu carrinho de compras virtual na Zara/Asos/etc:", opcoes: ["Tem lá 500€ em peças abandonadas a ganhar pó", "Compro na hora se vir algo que adoro", "Espero que o sistema avise que 'só resta 1 peça' para entrar em pânico e comprar", "Meto as coisas lá para sonhar e depois fecho a aba para sempre"] },
    { id: "c_me_c_13", texto: "Quando uma vendedora vem perguntar 'Posso ajudar?':", opcoes: ["Fico super nervoso/a e digo 'estou só a ver, obrigado' e fujo da loja", "Faço-lhe 30 perguntas sobre os tamanhos e cores", "Finjo que estou ao telemóvel", "Digo 'não' mas a seguir dou de caras com a peça que queria e tenho vergonha de lhe pedir"] },
    { id: "c_me_c_14", texto: "Comprar presentes para os outros:", opcoes: ["Compro sempre algo inútil à pressa na véspera", "Adoro pesquisar e dou sempre a prenda perfeita", "Compro algo que também dá para mim e peço 'emprestado'", "Esqueço-me sempre e acabo a dar um vale presente ou dinheiro"] },
    { id: "c_me_c_15", texto: "Se comprar roupa que é ligeiramente apertada:", opcoes: ["Digo 'vou emagrecer para caber nisto' e nunca acontece", "Tento esticar a peça com as mãos", "Compro um tamanho acima para me sentir confortável, ninguém vai ver a etiqueta", "Respiro fundo, encolho a barriga e sofro o jantar todo"] },
    { id: "c_me_c_16", texto: "As etiquetas com os preços da roupa:", opcoes: ["Corto imediatamente com os dentes à bruta", "Deixo a etiqueta e escondo por dentro 'só para o caso de querer devolver'", "Uso a roupa no primeiro dia e esqueço-me da etiqueta pendurada nas costas", "Guardo as etiquetas de marca caras numa gaveta"] },
    { id: "c_me_c_17", texto: "Quando descubro que um/a amigo/a comprou a mesma roupa que eu:", opcoes: ["Aviso logo 'não vistas isto no sábado senão parecemos os cromos gémeos'", "Acho o máximo e combinamos ir de igual para a festa", "Fico com raiva silenciosa porque eu soube escolher primeiro", "Faço questão de dizer a toda a gente que comprei mais barato"] },
    { id: "c_me_c_18", texto: "Comprar óculos de sol nas férias:", opcoes: ["Perco os óculos caros logo no primeiro mergulho", "Compro uns fatelas de 5€ nas feirinhas todos os anos", "Sento-me em cima deles no carro no segundo dia", "Uso sempre os mesmos óculos espatifados há 5 primaveras"] },
    { id: "c_me_c_19", texto: "Como justifico uma compra inútil:", opcoes: ["'O dinheiro é para girar'", "'Trabalhei a semana toda e levei nas orelhas do chefe'", "'O meu Eu do futuro lida com a despesa'", "'Fica bem para a foto de Instagram'"] },
    { id: "c_me_c_20", texto: "A entrar numa perfumaria (ex: Sephora, Douglas):", opcoes: ["Meto amostras de perfume nos braços, pescoço e saio a cheirar a salada de fruta", "Sinto-me pobre só de pisar a carpete", "Saio de lá com as mãos cheias de riscos de maquiagem testada", "Tento roubar as amostras grátis pequeninas do balcão"] }
  ]
};
