import { PerguntaClassica } from "@/types/catalogo";

export const classico_musica_concertos: Record<string, PerguntaClassica[]> = {
  "sub_25_0": [ // Gostos Musicais
    { id: "c_mc_g_01", texto: "A minha playlist atual baseia-se em:", opcoes: ["Músicas de chorar no chuveiro (Depressão Mode)", "Hits do TikTok que enjoam ao fim de 2 dias", "Rap e Hip-hop pesado para me sentir um gangster no trânsito", "Os clássicos dos anos 80 e 90, essa sim era a boa música"] },
    { id: "c_mc_g_02", texto: "A cantar no carro sozinho/a, eu sou:", opcoes: ["O novo vocalista da banda, com agudos impossíveis", "Canto só em inglês inventado (embromation)", "Faço concertos completos com pausas para falar com o 'público'", "Não canto, oiço podcasts, sou uma pessoa séria"] },
    { id: "c_mc_g_03", texto: "Qual o meu 'Guilty Pleasure' musical (que oiço às escondidas)?", opcoes: ["Quim Barreiros, Rosinha e afins", "Músicas do Panda e Os Caricas ou Disney", "K-Pop (grupos coreanos aos saltos)", "Boybands dos anos 2000 (Backstreet Boys, D'ZRT)"] },
    { id: "c_mc_g_04", texto: "Se estiver triste, que tipo de música oiço?", opcoes: ["Música ainda mais triste para bater bem no fundo do poço", "Música de festa para afogar as mágoas a dançar", "Música de raiva (Rock pesado) para destruir coisas na cabeça", "Não oiço música, prefiro o silêncio trágico do meu quarto"] },
    { id: "c_mc_g_05", texto: "No ginásio, se os fones ficarem sem bateria:", opcoes: ["Vou-me embora, é fisicamente impossível treinar sem música", "Treino ao som das respirações estranhas dos homens a puxar ferro", "Fico a ouvir a música tecno terrível que passa nas colunas do ginásio", "Meto o telemóvel encostado ao ouvido (com som baixo) a treinar"] },
    { id: "c_mc_g_06", texto: "Qual é o meu nível de elitismo musical?", opcoes: ["Odeio pop comercial, só oiço bandas underground de 50 seguidores", "Não ligo a estilos, se a batida for boa eu danço e ouço", "Sou muito crítico/a, acho a música de hoje um lixo", "Oiço literalmente o que o rádio manda, sou bué básico/a"] },
    { id: "c_mc_g_07", texto: "O meu Spotify Wrapped no final do ano:", opcoes: ["Tenho orgulho e partilho em todas as redes sociais", "Tenho demasiada vergonha do meu top 5 para mostrar a alguém", "É estragado porque pus música de dormir / ruído de chuva o ano todo", "Eu uso o Youtube Music ou Apple Music e choro num canto"] },
    { id: "c_mc_g_08", texto: "Quando passo a música no cabo AUX (DJ do carro) dos meus amigos:", opcoes: ["Todos cantam e adoram as minhas escolhas", "Eles mandam calar a música ao fim de 30 segundos", "Ponho sempre a MESMA música de que já estão todos fartos", "Passo as músicas ao fim de 1 minuto e mudo para outra"] },
    { id: "c_mc_g_09", texto: "A minha reação à música de Natal em Novembro:", opcoes: ["Amo! Mariah Carey na veia mal acaba o Halloween!", "Irrita-me solenemente, os shoppings deviam ser multados", "Canto mentalmente, mas reclamo por fora para parecer durão/durona", "Só aceito depois do dia 1 de Dezembro, regras são regras"] },
    { id: "c_mc_g_10", texto: "Saber a letra das músicas:", opcoes: ["Sei o dicionário musical inteiro, não erro uma vírgula", "Invento 80% da letra mas canto com 100% de confiança", "Só sei o refrão e murmuro o resto", "Fico calado/a à espera que a parte que sei chegue"] },
    { id: "c_mc_g_11", texto: "Odeio quando as pessoas dizem que ouvem:", opcoes: ["'Oiço um bocadinho de tudo' (Mentira!)", "Música clássica para estudar (Armados em génios)", "Reggaeton do Brasil e deitam abaixo a música nacional", "Funk pesadão no altifalante do telemóvel no comboio"] },
    { id: "c_mc_g_12", texto: "Como lido com a música do meu ex / daquela pessoa traumática?", opcoes: ["Passo logo à frente, dá-me palpitações e suores frios", "Ouço para chorar a pensar nas memórias (masoquista)", "A música já é minha, roubei o artista na separação", "Mandei apagar da minha biblioteca do Spotify para sempre"] },
    { id: "c_mc_g_13", texto: "Em festas, a música pimba (popular portuguesa):", opcoes: ["É quando a pista de dança finalmente explode! Adoro!", "Acho super azeiteiro mas acabo a dançar o comboiozinho na mesma", "Fujo para o bar, não suporto o acordeão", "Eu sei a letra da 'Garagem da Vizinha' melhor que o Hino Nacional"] },
    { id: "c_mc_g_14", texto: "Quando me mandam uma recomendação de música longa (7 minutos):", opcoes: ["Ouço com carinho e dou feedback detalhado", "Digo 'amei!' sem sequer ter carregado no play", "Ouço só o primeiro minuto e já acho que chega", "Odeio que me enviem músicas, nunca tenho tempo"] },
    { id: "c_mc_g_15", texto: "Música nos fones enquanto ando na rua:", opcoes: ["Uso a música para me imaginar num videoclipe melancólico", "Ando ao ritmo da batida tipo desfile de moda", "Sinto que as pessoas conseguem ouvir o que eu estou a ouvir", "Uso fones desligados só para as pessoas não me falarem"] },
    { id: "c_mc_g_16", texto: "Ao trabalhar / estudar, que música ouço?", opcoes: ["Silêncio, a música distrai-me imenso", "Bandas sonoras de filmes de batalha (para dar motivação épica)", "Música cantada e acabo a fazer espetáculo em vez de estudar", "Lofi Beats, a rádio da rapariga do anime que estuda sempre"] },
    { id: "c_mc_g_17", texto: "Quando uma música bate muito no rádio (Overplayed):", opcoes: ["Canto sempre, é hit por alguma razão", "Fico com ódio de estimação e mudo de rádio instantaneamente", "Fica-me presa na cabeça e dou por mim a cantarolar a lavar os dentes", "Digo 'outra vez esta porcaria' mas sei a letra"] },
    { id: "c_mc_g_18", texto: "O que acho de concertos acústicos (só voz e violão)?", opcoes: ["Lindo e íntimo, o verdadeiro talento", "Dá-me um sono mortal, prefiro guitarras e fogo de artifício", "Depende se conheço as letras para cantarolar junto", "Acho super secante ter o público todo calado a fingir que percebe de arte"] },
    { id: "c_mc_g_19", texto: "Em qual destes programas musicais participaria se tivesse voz?", opcoes: ["The Voice, para virar as cadeiras todas com a minha emoção", "Ídolos, para o drama", "Eurovisão, para levar com zero pontos e rir muito", "Festival da Canção, para usar roupas espalhafatosas"] },
    { id: "c_mc_g_20", texto: "Se a minha vida fosse um musical:", opcoes: ["Eu cantaria os meus problemas em vez de chorar por eles", "Teria coreografias sincronizadas no supermercado", "Seria cancelado ao 2º episódio porque sou muito monótono/a", "Fazia o papel do figurante mudo lá atrás, odeio cantar em público"] }
  ],
  "sub_25_1": [ // Loucuras em Festivais
    { id: "c_mc_f_01", texto: "No parque de campismo de um festival de Verão:", opcoes: ["Sobrevivo à base de salsichas frias e pão", "Acordo às 7h da manhã a suar dentro da tenda tipo estufa", "Sou o otário que levou a tenda errada que não monta", "Fico no hotel mais próximo, recuso-me a dormir no chão sujo"] },
    { id: "c_mc_f_02", texto: "Como lido com a casa de banho nos festivais (WC portátil)?", opcoes: ["Ganho fobia e seguro as necessidades durante 3 dias", "Entro de nariz tapado e flutuo para não tocar em nada", "Acabo a ir aos arbustos no escuro para não sofrer", "Bebo tanto que já nem noto o cheiro quando lá entro"] },
    { id: "c_mc_f_03", texto: "A minha estratégia para ir para a 'Grade' (Fila da frente):", opcoes: ["Vou às 14h da tarde para o palco, mijo em garrafas e queimo ao sol", "Empurro toda a gente a dizer 'Tenho lá um amigo à frente!'", "Odeio a grade, fico cá atrás onde dá para respirar e comprar cerveja", "Tento furar, levo cotoveladas e desisto a chorar a meio"] },
    { id: "c_mc_f_04", texto: "Quando passo os meus amigos aos ombros/cavalitas:", opcoes: ["Caímos os dois para trás ao fim de 10 segundos", "Fico sem costas no dia a seguir mas vale a foto", "Eu sou a pessoa que vai sempre aos ombros dos outros", "A malta de trás insulta-me porque eu tapo a visão toda"] },
    { id: "c_mc_f_05", texto: "Perder os amigos num festival de 50 mil pessoas:", opcoes: ["Faço amizades com desconhecidos e adoto um novo grupo", "Passo o concerto a mandar SMS 'ESTOU AO PÉ DA BANDEIRA VERDE!'", "Sento-me no chão e espero que me encontrem no fim", "Eu tenho radar, eu não perco, eles é que se perdem de mim"] },
    { id: "c_mc_f_06", texto: "O dinheiro num festival:", opcoes: ["Gasto 150€ em comida e cervejas de plástico super caras", "Meto as sandes de casa escondidas nos bolsos para não gastar", "Perco os copos reutilizáveis todos os dias e perco os 2€", "Gasto mais no Merchandising da banda (t-shirts a 40€)"] },
    { id: "c_mc_f_07", texto: "Quando a banda manda fazer os 'Mosh Pits' ou 'Roda Punk':", opcoes: ["Meto-me lá no meio aos encontrões (Rambo)", "Fujo a sete pés a proteger os meus óculos e dentes", "Fico na borda a empurrar as pessoas que vêm contra mim", "Apanho uma cotovelada acidental e vou para a Cruz Vermelha"] },
    { id: "c_mc_f_08", texto: "A roupa de festival de Verão:", opcoes: ["Passo meses a comprar roupa cheia de brilhos, franjas e chapéus", "Levo a t-shirt mais velha que tenho e calções sujos", "Levo sapatilhas brancas que depois vão para o lixo cobertas de lama", "Chego lá, tiro a camisola por causa do calor e o outfit não serviu para nada"] },
    { id: "c_mc_f_09", texto: "O que acho dos concertos de artistas que eu não conheço?", opcoes: ["Fico lá na mesma a dançar e descubro música nova", "Vou para a zona da restauração comer churros ou kebabs", "Passo o tempo sentado/a na relva a falar da vida", "Reclamo o concerto todo 'quem é este cromo?'"] },
    { id: "c_mc_f_10", texto: "Qual a pior praga de um festival para mim?", opcoes: ["O pó no ar que me faz tossir terra preta nos dias seguintes", "A malta muito alta que fica sempre à minha frente no melhor concerto", "O facto de as imperial (cervejas) estarem quentes", "As filas de 40 minutos para tudo (comer, beber, casa de banho)"] },
    { id: "c_mc_f_11", texto: "No fim do concerto (na saída do recinto):", opcoes: ["Corro antes da última música para evitar a multidão trituradora", "Ando a passo de caracol durante 1 hora a cheirar o sovaco dos outros", "Fico sentado à espera que toda a gente saia para sair à vontade", "Atropelo pessoas em direção ao parque de estacionamento"] },
    { id: "c_mc_f_12", texto: "Os 'Chuveiros Comunitários' nos campismos de festivais:", opcoes: ["Tomo banho de biquíni/calções de banho e água gelada", "Uso toalhitas de bebé na tenda durante os 4 dias", "Levanto-me às 6h da manhã para ter água quente", "Lavo só o cabelo na torneira do lavatório para disfarçar"] },
    { id: "c_mc_f_13", texto: "Quando dão brindes à borla (chapéus de palha, fitas) no recinto:", opcoes: ["Vou a todas as bancas de marcas e pareço uma árvore de Natal", "Acho isso uma parolice e não pego em nada", "Só vou buscar se derem coisas úteis tipo comida ou bebida", "Obrigo os meus amigos a irem buscar por mim que tenho vergonha"] },
    { id: "c_mc_f_14", texto: "Cantar as músicas do cabeça de cartaz no recinto:", opcoes: ["Canto com os pulmões todos até perder a voz no dia 1", "Fico emocionado/a e choro a agarrar o copo de plástico", "Gravo o concerto todo no telemóvel e não aproveito o momento", "Canto super mal, os meus amigos têm de me mandar calar"] },
    { id: "c_mc_f_15", texto: "Quando começa a chover num festival de Verão ao ar livre:", opcoes: ["Visto o poncho de plástico transparente horrível", "Tento enfiar-me debaixo do toldo do bar mais próximo", "Apanho uma molha gloriosa e apanho pneumonia na semana seguinte", "Levo a minha camisola para proteger o telemóvel e a cerveja"] },
    { id: "c_mc_f_16", texto: "Como lido com a bateria do telemóvel nos festivais?", opcoes: ["Anda em 'Modo Poupança' e Avião durante 3 dias", "Pago fortunas naquelas Powerbanks dos stands", "Acaba às 19h e ando perdido do mundo o resto da noite", "Gasto a bateria toda a gravar os artistas para não ver nunca mais os vídeos"] },
    { id: "c_mc_f_17", texto: "Noite de 'Recepção ao Campista':", opcoes: ["A melhor noite de sempre, bebedeira monstra antes do festival começar", "Vou para me ambientar mas recolho à tenda cedo", "Bebo tanto que passo o 1º dia do festival agarrado ao estômago", "Não vou para poupar energias"] },
    { id: "c_mc_f_18", texto: "A minha atitude com a comida das Roulotes (Churros, Farturas, Kebabs):", opcoes: ["São o Santo Graal das 3h da manhã", "Acho super anti-higiénico mas a fome fala mais alto", "Gasto 15€ num hambúrguer cru e choro por dentro", "Só vivo a comer fatias de pizza de 3€"] },
    { id: "c_mc_f_19", texto: "Em relação aos cartazes de festivais atuais:", opcoes: ["Digo sempre 'Ah o Alive de 2012 é que foi incrível' (bota de elástico)", "Compro passe geral às cegas sem saber quem lá vai", "Só vou num dia para ver AQUELE artista específico", "Acho os bilhetes um roubo, vou para ouvir de fora do recinto"] },
    { id: "c_mc_f_20", texto: "Como chego a casa no final do festival de 3 dias?", opcoes: ["Pareço um sobrevivente de guerra, manco e sujo", "Cheio de depressão pós-festival, quero voltar para a tenda", "Passo uma hora a esfregar pó do corpo no banho de casa", "Prometo nunca mais lá voltar (mas no próximo ano compro o bilhete de novo)"] }
  ]
};
