import { PerguntaClassica } from "@/types/catalogo";

export const classico_natureza_ar_livre: Record<string, PerguntaClassica[]> = {
  "sub_18_0": [ // Praia ou Campo
    { id: "c_nal_p_01", texto: "Entre a praia e o campo, o meu coração escolhe:", opcoes: ["Praia, areia, mar e sal (até ter comichão)", "Campo, verde, silêncio e ar fresco da serra", "Cidades cosmopolitas cheias de betão e lojas", "Tanto faz, desde que tenha wi-fi e boa comida"] },
    { id: "c_nal_p_02", texto: "A minha relação com a areia da praia:", opcoes: ["Amo, estendo a toalha e fico lá horas sem me mexer", "Odeio, cola-se aos pés, à comida e ao corpo todo", "Fico sempre à beirinha da água para fugir dela", "Tento sacudir mas levo meio quilo de praia para casa na mala do carro"] },
    { id: "c_nal_p_03", texto: "Quando vou dar um mergulho no mar frio:", opcoes: ["Entro de uma vez a correr a gritar por socorro", "Vou molhando os pés centímetro a centímetro durante 20 minutos", "Olho para a água gelada e decido ficar na toalha a apanhar sol", "Sou um corajoso/a, mergulho de cabeça sem hesitar"] },
    { id: "c_nal_p_04", texto: "Fazer uma caminhada (trilho) na montanha:", opcoes: ["Adoro, conectar-me com a natureza e as árvores", "Detesto, canso-me aos primeiros 50 metros de subida", "Vou se me prometerem que há um restaurante no fim da rota", "Ajo como se fosse um alpinista profissional com equipamento todo xpto"] },
    { id: "c_nal_p_05", texto: "O sol e o protetor solar na praia:", opcoes: ["Ponho fator 50 de hora a hora, pareço um fantasma branco", "Ponho fator 10 só no primeiro dia e depois é ao deus-dará", "Uso óleo bronzeador para fritar ao sol mais rápido", "Esqueço-me sempre do protetor e fico a parecer um caranguejo"] },
    { id: "c_nal_p_06", texto: "O que acho dos insectos e bichos no campo (mosquitos, aranhas, melgas)?", opcoes: ["São os donos da casa, eu sou apenas um intruso", "Ando sempre banhado/a em repelente químico industrial", "Entro em pânico se uma formiga me tocar na perna", "Matam-me viva/o à noite, fico com o corpo todo picado"] },
    { id: "c_nal_p_07", texto: "Levar chapéu-de-sol (guarda-sol) para a praia:", opcoes: ["É obrigatório, odeio assar ao sol direto", "Tenho preguiça de o espetar na areia e fico a cozinhar", "Fico sempre na sombra natural dos outros ou do bar", "O vento arranca sempre o meu chapéu e quase mato alguém"] },
    { id: "c_nal_p_08", texto: "Fazer um piquenique no campo:", opcoes: ["Adoro a vibe de comer na toalha estendida na relva", "Apanho formigas na comida e acabo a comer no carro", "Levo metade da minha cozinha atrás para parecer chique", "Acho super fofo na teoria, mas na prática prefiro um restaurante"] },
    { id: "c_nal_p_09", texto: "Apanhar conchas na praia ou flores no campo:", opcoes: ["Ainda tenho uma coleção disso em caixas de infância", "Acho bonito mas deixo estar na natureza", "Dou pontapés nelas sem querer", "Apanho para oferecer à mãe ou namorado/a"] },
    { id: "c_nal_p_10", texto: "O som das ondas do mar à noite:", opcoes: ["É a melhor música do mundo para adormecer", "Dá-me um bocado de tágides / medo do escuro do oceano", "Não oiço nada, estou a dormir num hotel com ar condicionado", "Faz-me lembrar que tenho de ir à casa de banho"] },
    { id: "c_nal_p_11", texto: "Atividades de Verão: voleibol de praia ou raquetes (matrecos/tenis de praia)?", opcoes: ["Raquetes! O barulho 'tac tac' irrita os vizinhos de toalha", "Voleibol, dou mergulhos espetaculares na areia", "Nenhum, o meu desporto de praia é comer bolas de berlim", "Prefiro ficar a ver os outros jogar"] },
    { id: "c_nal_p_12", texto: "O vento forte na praia (a famosa nortada):", opcoes: ["Levanta a areia e esmaga-nos os olhos, fujo dali", "Fico na mesma deitado/a a levar com a lixa de areia", "Visto o casaco de malha e aguento-me à bronca", "Apanho as coisas e vou para a piscina"] },
    { id: "c_nal_p_13", texto: "Quando vejo uma fogueira de acampamento no campo:", opcoes: ["Fico a cantar músicas à volta com uma guitarra", "Fico com o cheiro a fumo entrançado no cabelo uma semana", "Tento assar marshmallows que ficam sempre carbonizados", "Mantenho-me a uma distância segura com medo de pegar fogo"] },
    { id: "c_nal_p_14", texto: "A escolha da praia: praia vigiada com gente ou praia selvagem isolada?", opcoes: ["Praia com bar, salva-vidas, toldos e muita animação", "Praia selvagem secreta onde não está ninguém", "Tanto faz, desde que o estacionamento seja perto", "Praia com ondas grandes para apanhar sustos"] },
    { id: "c_nal_p_15", texto: "Comprar a clássica bola de berlim na praia:", opcoes: ["Com ou sem creme? Compro sempre duas!", "Resisto estoicamente porque aquilo são calorias puras", "Compro, mas a gaivota rouba-ma da mão a voar", "Fico a cheirar o chocolate no ar mas não gasto dinheiro"] },
    { id: "c_nal_p_16", texto: "Sobre andar de barco ou canoa no rio/mar:", opcoes: ["Adoro a brisa e a aventura", "Fico enjoado/a logo aos primeiros segundos", "Toco na água com a mão e acho espetacular", "Tenho pavor de o barco virar e tubarões/monstros aparecerem"] },
    { id: "c_nal_p_17", texto: "O cheiro a maresia ou o cheiro a eucalipto no campo:", opcoes: ["O cheiro a maresia é o melhor cheiro do universo", "O cheiro a campo / terra molhada (petricor) revigora-me", "Dão-me espirros e alergias terríveis", "Para mim cheira a humidade e pó"] },
    { id: "c_nal_p_18", texto: "Se tiver de passar um fim de semana inteiro num monte alentejano sem rede:", opcoes: ["O paraíso na Terra, paz de espírito total", "Entro em abstinência digital ao fim de 3 horas", "Ligo o rádio do carro para ouvir as notícias", "Fico a olhar para as vacas a ver se fazem alguma coisa"] },
    { id: "c_nal_p_19", texto: "Construir castelos de areia:", opcoes: ["Faço obras de engenharia com fossos e muralhas", "Faço um monte de areia redondo e espetei uma bandeirinha", "Deixo os miúdos fazê-lo e fico a ver", "Acho uma perda de tempo, prefiro nadar"] },
    { id: "c_nal_p_20", texto: "O pôr do sol na praia vs nascer do sol no campo:", opcoes: ["Tiro 50 fotos ao pôr do sol para o Instagram", "Nunca vi o nascer do sol na vida, a essa hora estou a dormir", "O pôr do sol é cliché, prefiro o silêncio do campo", "Tanto faz, o sol é o mesmo em todo o lado"] }
  ],
  "sub_18_1": [ // Atividades Radicais
    { id: "c_nal_r_01", texto: "Saltar de paraquedas ou Bungee Jumping:", opcoes: ["Já fiz ou quero muito fazer, adoro adrenalina!", "Nem por cima do meu cadáver, amo a minha vida", "Só se me pagassem uma quantia absurda de dinheiro", "Teria um ataque cardíaco a meio da queda"] },
    { id: "c_nal_r_02", texto: "Fazer rafting ou descida de rápidos em rio:", opcoes: ["Adoro a pancadaria das águas bravas com os amigos", "Fico a rezar para o barco não virar e perder os óculos", "Fico no rio a mandar tostas aos patos", "Recuso-me a entrar em águas revoltas"] },
    { id: "c_nal_r_03", texto: "A minha experiência com escalada ou rapel:", opcoes: ["Subo paredes como se fosse o Homem-Aranha", "Fico encravado a meio, olho para baixo e choro", "Desisto logo na primeira corda porque tenho vertigens", "Acho divertido mas tenho fraqueza nos braços"] },
    { id: "c_nal_r_04", texto: "Andar de moto 4 ou fazer TT (todo-o-terreno):", opcoes: ["Gosto de sujar o carro/mota de lama até aos olhos", "Tenho medo de capotar a máquina na primeira curva", "Vou devagarinho a estorvar quem quer andar rápido", "Fico a ver os outros do pó e da bancada"] },
    { id: "c_nal_r_05", texto: "Fazer Paintball ou Laser Tag com amigos:", opcoes: ["Levo aquilo como uma guerra real, marco a descoberto", "Escondo-me atrás de um pneu e não me mexo o jogo todo", "Fico com pisadas roxas pelo corpo inteiro durante um mês", "Adoro disparar contra os meus amigos sem remorsos"] },
    { id: "c_nal_r_06", texto: "Voar de parapente ou asa-delta:", opcoes: ["O sonho supremo de voar como um pássaro", "Parece incrível, mas o meu estômago não aguentava", "Deus me livre de saltar de um penhasco com um lençol", "Só se o instrutor for um profissional com 50 anos de casa"] },
    { id: "c_nal_r_07", texto: "Mergulho com tubarões (dentro de uma jaula):", opcoes: ["Apunhalaria o ar para ir ver os tubarões de perto", "Dentro da jaula ainda aceito, de fora nem pensar", "Tubo de oxigénio e tubarões? Prefiro ver no Discovery Channel", "Se um tubarão me vir, desmaia com o meu aspeto"] },
    { id: "c_nal_r_08", texto: "Conduzir um karting numa pista profissional:", opcoes: ["Acho sempre que sou o Lewis Hamilton e esbardalho-me na curva", "Deixo toda a gente passar para não criar trânsito", "Fico com os braços completamente doridos de fazer força no volante", "Piso o travão a toda a hora, medo de bater"] },
    { id: "c_nal_r_09", texto: "Parque aquático: escorregas gigantes kamikaze:", opcoes: ["Vou sempre ao mais inclinado e assustador em primeiro", "Fico preso a meio do escorrega por falta de água e peso", "Engulo meio litro de água do parque e subo a escada a arfar", "Fico na piscina de ondas a boiar sossegado/a"] },
    { id: "c_nal_r_10", texto: "Andar de jet ski no mar:", opcoes: ["Acelero a fundo e faço curvas apertadas para mandar o pendura à água", "Vou a 20 km/h a tremer com medo das ondas", "Tento equilibrar-me mas caio sempre ao primeiro solavanco", "Adoro a velocidade, sinto-me num filme de acção"] },
    { id: "c_nal_r_11", texto: "Fazer Canyoning (saltar para cascatas e descer rios):", opcoes: ["Aventura máxima, adoro saltar para as lagoas", "Fico a olhar para o penhasco de 10 metros a pensar 'quem me mandou vir aqui?'", "Recuso-me a saltar e vou a chorar pelo trilho a pé", "Salgo mas caio de barriga e fico marcado/a"] },
    { id: "c_nal_r_12", texto: "Como reajo a uma atividade radical que correu mal (susto grande):", opcoes: ["Rio-me histericamente de nervos no fim", "Prometo a Deus nunca mais inventar aventuras", "Fico traumatizado/a e não abro a boca o resto do dia", "Vou logo ver o vídeo para rir da minha figura"] },
    { id: "c_nal_r_13", texto: "Andar de skate, patins em linha ou trotinete elétrica rápida:", opcoes: ["Faço manobras e ando sempre a inventar", "Caio com a própria sombra e esfolo os pulsos", "Tentei na adolescência, parti o pulso e nunca mais", "Prefiro andar a pé em segurança"] },
    { id: "c_nal_r_14", texto: "Fazer surf ou bodyboard:", opcoes: ["apanho umas ondas épicas (na minha cabeça)", "Apanho com a prancha na torelha e venho cuspido para a areia", "Fico na espuma a fingir que estou a surfar", "O mar engole-me sempre e perco os calções"] },
    { id: "c_nal_r_15", texto: "Explorar grutas escuras e claustrofóbicas espeleologia:", opcoes: ["Adoro o mistério do subsolo", "Fico com falta de ar só de pensar em rochas a cair em cima", "Bato com a cabeça nas estalactites todas", "Prefiro ver fotos na internet do que enfiar-me na lama"] },
    { id: "c_nal_r_16", texto: "O que acho de atividades radicais em geral:", opcoes: ["São essenciais para dar sentido à vida", "Prefiro o risco de comer um pastel de nata a mais", "Gosto de ver os outros a fazer e gravar para o TikTok", "Dão-me suores frios e palpitações"] },
    { id: "c_nal_r_17", texto: "Fazer um test-drive a alta velocidade num carro desportivo:", opcoes: ["Espeta-me o banco contra as costas, que máquina!", "Carrego no travão a meio da reta porque me assusto", "Pergunto ao vendedor se o carro traz sacos de vómito incluídos", "Ajo com indiferença mas por dentro estou a delirar"] },
    { id: "c_nal_r_18", texto: "Saltar de um penhasco para a água (coasteering):", opcoes: ["Estilo livre, dou uma pirueta no ar", "Hesito durante 10 minutos na ponta até alguém me empurrar", "Crio coragem, salto, e a água parece betão quando bato lá em baixo", "Fico a ver de longe a avisar do perigo"] },
    { id: "c_nal_r_19", texto: "Fazer baloiços gigantes nas montanhas (tipo 3anões / Columpios):", opcoes: ["Vão às alturas e sinto o coração a saltar pela boca, adoro!", "Fecho os olhos e chamo pela mãe", "Baloiço meio metro e acho que já chega de emoções fortes", "Paro a meio e exijo que me tirem dali"] },
    { id: "c_nal_r_20", texto: "O meu nível de 'coragem' em férias de aventura:", opcoes: ["Indiana Jones nas horas livres", "Indiana Jones da Wish (medo de tudo mas tento)", "Indiana Jones do sofá (só vejo os filmes)", "Indiana Jones acidentado (corro perigo a caminhar na calçada calçada)"] }
  ]
};
