import { PerguntaClassica } from "@/types/catalogo";

export const classico_passado_infancia: Record<string, PerguntaClassica[]> = {
  "sub_6_0": [ // Memórias de Escola
    { id: "c_pi_e_01", texto: "Na escola, qual era o meu lugar clássico na sala de aula?", opcoes: ["Na primeira fila, a tirar notas de tudo", "No fundo da sala a dormir ou na fofoca", "Perto da janela a olhar para a rua", "Sempre colado/a ao professor a fazer perguntas"] },
    { id: "c_pi_e_02", texto: "Qual era a minha disciplina favorita?", opcoes: ["Educação Física, só queria correr e jogar", "Matemática, adorava os números", "Português/História, era o rei/rainha das redações", "O Recreio. Conta como disciplina?"] },
    { id: "c_pi_e_03", texto: "Quando era a hora de fazer trabalhos de grupo, eu:", opcoes: ["Fazia tudo sozinho/a para garantir boa nota", "Era quem imprimia e encadernava o trabalho", "Fazia apenas a capa e punha lá o meu nome", "Dava a ideia inicial e desaparecia"] },
    { id: "c_pi_e_04", texto: "O que eu fazia na véspera de um teste importante?", opcoes: ["Estudava a noite toda a beber café/Red Bull", "Fazia cábulas hiper elaboradas", "Dormia tranquilo/a porque já tinha estudado", "Chorava a dizer que ia chumbar (e tirava grande nota)"] },
    { id: "c_pi_e_05", texto: "Qual era a minha desculpa clássica para não entregar os TPC?", opcoes: ["'Esqueci-me do caderno em casa'", "'O meu cão comeu'", "'Não percebi o que era para fazer'", "Eu entregava sempre tudo a horas!"] },
    { id: "c_pi_e_06", texto: "Na cantina da escola, eu costumava:", opcoes: ["Levar lancheira porque odiava a comida", "Comer a sopa toda e repetir o prato", "Ir para a fila furar os outros", "Sobreviver à base de pão com manteiga e sumos"] },
    { id: "c_pi_e_07", texto: "Em relação aos apontamentos das aulas:", opcoes: ["Tinha sublinhadores de 10 cores diferentes", "Pedia sempre o caderno dos outros para copiar", "Escrevia tudo num gatafunho indecifrável", "O meu caderno era só desenhos e rabiscos"] },
    { id: "c_pi_e_08", texto: "Qual foi a pior coisa que fiz na escola?", opcoes: ["Fui apanhado/a a copiar num teste", "Respondi mal a um professor e fui para a rua", "Parti um vidro/janela a jogar à bola", "Faltei para ir ao café e os meus pais descobriram"] },
    { id: "c_pi_e_09", texto: "O que sentia na aula de Educação Física?", opcoes: ["Odeio suar, fingia que estava doente", "Adorava, era o/a melhor nos desportos", "Escondia-me quando era para escolher equipas", "Corria muito mas não percebia nada de regras"] },
    { id: "c_pi_e_10", texto: "A minha relação com os professores era:", opcoes: ["Era o 'menino/a de ouro' do professor", "Estava sempre de castigo", "Passava completamente despercebido/a", "Discutia notas ao cêntimo"] },
    { id: "c_pi_e_11", texto: "Nas viagens de estudo, eu era quem:", opcoes: ["Cantava no fundo do autocarro aos berros", "Dormia com os fones a viagem toda", "Obrigava toda a gente a tirar fotos", "Trazia a mochila cheia de doces e batatas"] },
    { id: "c_pi_e_12", texto: "Como reagia quando o professor dizia 'O teste surpresa é para guardar!'?", opcoes: ["Entrava em pânico total", "Suspirava de alívio, estava safo/a", "Fazia o teste na mesma para treinar", "Tentava rasgar o teste disfarçadamente"] },
    { id: "c_pi_e_13", texto: "Qual a pior moda que segui na escola?", opcoes: ["Aquelas calças super descaídas", "Cabelo com gel espetado ou franja tapada", "Pulseiras de borracha a cobrir o braço todo", "A mochila da Eastpak no fundo do joelho"] },
    { id: "c_pi_e_14", texto: "No recreio, o meu passatempo era:", opcoes: ["Jogar à apanhada ou às escondidas", "Trocar cartas/cromos", "Falar da vida dos outros num canto", "Namorar ou mandar bilhetinhos amorosos"] },
    { id: "c_pi_e_15", texto: "Quando tinha más notas, o que eu fazia com o teste?", opcoes: ["Assinava eu pelos meus pais", "Mostrava a chorar para tentar dar pena", "Escondia no fundo da mochila durante meses", "Não ligava, os meus pais eram chill"] },
    { id: "c_pi_e_16", texto: "Quem eu era nas apresentações orais?", opcoes: ["Aquele que fala super alto e lê tudo do papel", "O que memorizava e dava show no quadro", "Ficava roxo/a e suava em bica de vergonha", "Só carregava no botão para passar o slide"] },
    { id: "c_pi_e_17", texto: "Como era o meu estojo?", opcoes: ["Cheio de canetas de gel que nunca usava", "Só uma caneta roída no fundo da mochila", "Ultra organizado, com esquadro e afia-lápis com caixa", "Cheio de mensagens e corretor branco espalhado"] },
    { id: "c_pi_e_18", texto: "Nas aulas mais secantes, eu:", opcoes: ["Mandava SMS debaixo da mesa", "Jogava ao Stop ou ao Galo no papel", "Adormecia com a cabeça nos braços", "Desenhava tatuagens nos braços com esferográfica"] },
    { id: "c_pi_e_19", texto: "O que achava das aulas de Educação Visual (EV / EVT)?", opcoes: ["Adorava, era onde relaxava e conversava", "Odeiava, sujava-me todo/a com tintas", "Esquecia-me sempre do material em casa", "Fazia obras-primas dignas de museu"] },
    { id: "c_pi_e_20", texto: "Qual é a minha melhor recordação da escola?", opcoes: ["Os toques no ombro e fugir a rir", "As festas de fim de ano", "Matar aulas com a malta do café", "Ir embora no último dia"] }
  ],
  "sub_6_1": [ // Traquinices de Criança
    { id: "c_pi_t_01", texto: "Quando eu era pequeno/a, o meu sonho era ser:", opcoes: ["Astronauta ou Médico/a", "Futebolista ou Cantor/a", "Ninja ou Super-herói", "Apenas rico/a para não fazer nada"] },
    { id: "c_pi_t_02", texto: "A maior traquinice que fiz em casa foi:", opcoes: ["Pintar as paredes com marcadores", "Cortar o próprio cabelo com a tesoura", "Partir um vaso e esconder os cacos", "Meter fogo a alguma coisa 'sem querer'"] },
    { id: "c_pi_t_03", texto: "Qual era o meu desenho animado favorito?", opcoes: ["Pokémon / Dragon Ball / Navegantes da Lua", "SpongeBob / Powerpuff Girls", "Banda da Disney (Recreio / Kim Possible)", "Não via desenhos animados, via novelas"] },
    { id: "c_pi_t_04", texto: "Como tentava escapar à hora de dormir?", opcoes: ["Dizia 'só mais 5 minutos' infinitamente", "Pedia um copo de água mil vezes", "Escondia-me debaixo da cama", "Fingia que estava doente com dores de barriga"] },
    { id: "c_pi_t_05", texto: "O que fazia quando perdia um jogo contra amigos ou irmãos?", opcoes: ["Virava o tabuleiro ou atirava o comando", "Desligava a consola e bazava amuado/a", "Aceitava bem e pedia desforra", "Começava a chorar a dizer que era batota"] },
    { id: "c_pi_t_06", texto: "O que achava do Bicho Papão ou do Escuro?", opcoes: ["Dormia com a luz do corredor acesa e a porta aberta", "Escondia o pé debaixo do lençol para não ser puxado", "Não tinha medo nenhum, era um rijo/a", "Corria do interruptor até à cama num segundo"] },
    { id: "c_pi_t_07", texto: "A minha reação a levar injeções no médico era:", opcoes: ["Fazer uma peixeirada no centro de saúde", "Só chorar depois da vacina", "Ser corajoso/a para ganhar o chupa-chups no fim", "Esconder-me atrás da cadeira do médico"] },
    { id: "c_pi_t_08", texto: "Como era o meu temperamento quando era puto/a?", opcoes: ["Um/a anjinho/a que nunca chateava", "Um/a terrorista autêntico/a, sempre aos gritos", "O/a clássico/a 'birrento/a' que se atirava para o chão no shopping", "Super tímido/a, escondia-me atrás das pernas da mãe"] },
    { id: "c_pi_t_09", texto: "O que fazia com as pastilhas elásticas engolidas?", opcoes: ["Achava que a pastilha ia ficar no estômago 7 anos", "Engolia sempre para não ter de ir ao lixo", "Colava-as debaixo das mesas", "Faziam bolas gigantes até rebentarem na cara"] },
    { id: "c_pi_t_10", texto: "O meu brinquedo favorito na infância era:", opcoes: ["Action Man, Hot Wheels ou Carros telecomandados", "Barbies, Nenuco ou Casas de bonecas", "Legos e blocos de construção", "A caixa de cartão onde vinha o brinquedo"] },
    { id: "c_pi_t_11", texto: "Quando os meus pais compravam gomas ou chocolates:", opcoes: ["Comia tudo num dia e passava mal", "Escondia debaixo da cama para ninguém me roubar", "Comia devagarinho ao longo de uma semana", "Dividia com os meus irmãos"] },
    { id: "c_pi_t_12", texto: "As brincadeiras na rua envolviam:", opcoes: ["Tocar às campainhas e fugir a sete pés", "Jogar à bola até raspar os joelhos todos", "Andar de bicicleta/patins na rua toda a tarde", "Fazer 'sopas' com terra e folhas no jardim"] },
    { id: "c_pi_t_13", texto: "A mentira mais típica que contava em criança:", opcoes: ["'Não fui eu, foi o meu irmão/cão'", "'Já lavei os dentes' (mentira)", "'A professora não mandou trabalhos'", "'Caí nas escadas' (depois de ter andado à porrada)"] },
    { id: "c_pi_t_14", texto: "No que toca a animais na infância:", opcoes: ["Pedia um cão/gato em TODOS os Natais", "Apanhava lagartixas e insetos com a mão", "Tinha pânico até de pombos", "Alimentava os gatos todos da rua"] },
    { id: "c_pi_t_15", texto: "Quando via a minha mãe a ralhar:", opcoes: ["Começava a chorar antes dela acabar a frase", "Respondia-lhe e acabava a fugir de chinelo", "Ficava calado/a a olhar para o chão", "Tirava as culpas todas de mim e atirava para outros"] },
    { id: "c_pi_t_16", texto: "O que comia às escondidas?", opcoes: ["O leite condensado da lata", "Massa crua", "Comer os cubos de Maggi / gelatina crua", "Assaltar as bolachas Maria"] },
    { id: "c_pi_t_17", texto: "A melhor coisa de estar doente em criança era:", opcoes: ["Faltar à escola e ver desenhos animados", "Comer canja e ser mimado/a", "O xarope doce", "Não tinha nada de bom, odiava ficar na cama"] },
    { id: "c_pi_t_18", texto: "Num restaurante com a família, eu era a criança que:", opcoes: ["Ficava debaixo da mesa a brincar", "Adormecia em duas cadeiras juntas", "Corria pelo restaurante todo a irritar os empregados", "Comia e ficava a jogar GameBoy/Telemóvel"] },
    { id: "c_pi_t_19", texto: "Quando ia ao dentista por ter um dente a abanar:", opcoes: ["Tirava eu em casa amarrando a uma porta", "Gritava e chorava", "Não me importava, sabia que a Fada dos Dentes ia pagar", "Engolia o dente sem querer"] },
    { id: "c_pi_t_20", texto: "A minha crença infantil mais estúpida era:", opcoes: ["Que as nuvens eram feitas de algodão doce", "Que se comesse pevides ia nascer uma árvore na barriga", "Que a Lua me estava a seguir no carro", "Que o pai natal entrava pela janela porque não havia lareira"] }
  ]
};
