import { PerguntaClassica } from "@/types/catalogo";

export const classico_personalidade: Record<string, PerguntaClassica[]> = {
  "sub_7_0": [ // Defeitos e Qualidades
    { id: "c_per_d_01", texto: "Se as coisas não saem exatamente como planeei:", opcoes: ["Entro num mini colapso nervoso e amuou", "Improviso na hora, sou chill", "A culpa é sempre dos outros, começo a reclamar", "Tento ignorar e fingir que planeei assim mesmo"] },
    { id: "c_per_d_02", texto: "Qual destes defeitos é mais a minha cara?", opcoes: ["Sou bué teimoso/a, não dou o braço a torcer", "Sou mega preguiçoso/a, deixo tudo para amanhã", "Sou dramático/a, faço filmes na minha cabeça", "Sou coscuvilheiro/a, preciso de saber as fofocas todas"] },
    { id: "c_per_d_03", texto: "A melhor qualidade que me reconhecem é:", opcoes: ["Ser o ombro amigo e dar grandes conselhos", "A minha lealdade (nunca falho)", "A capacidade de fazer rir qualquer pessoa", "Resolver os problemas todos de forma lógica"] },
    { id: "c_per_d_04", texto: "Numa discussão, qual é a minha arma secreta?", opcoes: ["Bato com a porta e aplico o tratamento do silêncio", "Ataco com argumentos hiper racionais e destruo a pessoa", "Começo a chorar para ganhar compaixão", "Relembro algo de 2012 para ter a razão"] },
    { id: "c_per_d_05", texto: "Como reajo a receber elogios sinceros?", opcoes: ["Fico super vermelho/a e mudo de assunto", "Digo 'eu sei!' (sou muito humilde)", "Desminto logo a pessoa ('achas? eu estou horrível')", "Fico genuinamente grato/a e sorrio"] },
    { id: "c_per_d_06", texto: "Sobre lidar com dinheiro, eu sou:", opcoes: ["Um/a esmifras autêntico, controlo ao cêntimo", "Compro por impulso tudo o que brilha ou é doce", "Um pai de família: gasto a pagar os jantares aos outros", "Digo sempre que estou teso mas recebi ontem"] },
    { id: "c_per_d_07", texto: "Quando não gosto de alguém:", opcoes: ["Dá logo para ver pela minha tromba e cara de nojo", "Sou falso/a e finjo que adoro a pessoa", "Corto a pessoa completamente da minha vida, ignoro", "Falo mal dela nas costas mas à frente não digo nada"] },
    { id: "c_per_d_08", texto: "Sobre a minha paciência:", opcoes: ["Tenho paciência de um santo", "O meu pavio é mais curto que uma formiga", "Sou super paciente... até deixar de o ser e rebentar", "Só não tenho paciência com quem anda devagar à minha frente"] },
    { id: "c_per_d_09", texto: "Quando me dão um presente que não gosto:", opcoes: ["Faço a pior cara de sempre (não sei disfarçar)", "Finjo um sorriso rasgado e agradeço", "Digo 'podes guardar o talão? É capaz de não me servir'", "Enfio no fundo da gaveta e nunca mais o uso"] },
    { id: "c_per_d_10", texto: "A minha atitude em relação à arrumação é:", opcoes: ["Nível TOC, não tolero uma migalha", "Desarrumado/a por fora, mas com o meu 'próprio sistema'", "Uma desgraça, vivo no meio de pilhas de coisas", "Só limpo e arrumo quando a água já me bate no pescoço"] },
    { id: "c_per_d_11", texto: "Quando tenho de tomar decisões grandes:", opcoes: ["Penso e repenso 300 vezes até dar em doido/a", "Atiro a moeda ao ar e seja o que Deus quiser", "Faço sondagens com todos os meus amigos e depois faço o oposto", "Faço listas de prós e contras hiper elaboradas"] },
    { id: "c_per_d_12", texto: "A coisa mais contraditória sobre mim:", opcoes: ["Odeio limpar, mas não consigo viver no lixo", "Sou tímido/a, mas pareço espalhafatoso/a depois de um copo", "Odeio drama, mas as fofocas são a minha vida", "Quero perder peso, mas como sempre sobremesa"] },
    { id: "c_per_d_13", texto: "Como lido com regras impostas?", opcoes: ["Sigo religiosamente, tenho medo de ser apanhado/a", "Tento sempre contorná-las de fininho", "Quebro-as só por espírito de rebeldia", "Acho que as regras são só 'sugestões' fortes"] },
    { id: "c_per_d_14", texto: "Se prometer um segredo a alguém:", opcoes: ["Guardo e esqueço que o disseram", "Luto contra a vontade de contar à minha mãe", "Aperto os lábios mas o meu cérebro grita para o partilhar", "Não sei manter segredos, espalho a palavra sem querer"] },
    { id: "c_per_d_15", texto: "O que dizem de mim quando chego a um sítio pela primeira vez?", opcoes: ["'Que gajo/a mais arrogante e com mania'", "'Parece uma pessoa espetacular e animada'", "'Não me apercebi que ele/a tinha chegado'", "'Ui, este/a nunca se cala'"] },
    { id: "c_per_d_16", texto: "Sobre a minha competitividade:", opcoes: ["Sou o terror no Monopólio, odeio perder", "Sou relaxado/a, o importante é participar", "Só sou competitivo/a no desporto", "Choro e faço batota mas digo que os outros é que fizeram"] },
    { id: "c_per_d_17", texto: "Quando as coisas correm mal na minha vida:", opcoes: ["Faço-me de vítima e pergunto 'porquê a mim?'", "Rio-me da desgraça e faço piadas (humor negro)", "Boto as culpas todas nos astros ou no universo", "Arregaço as mangas e tento consertar logo"] },
    { id: "c_per_d_18", texto: "A minha tolerância à dor física (ex: tirar sangue, tatuagens):", opcoes: ["Choro antes da agulha sequer me tocar", "Finjo que sou rijo/a mas estou a tremer por dentro", "Não me afeta nada, tenho resistência incrível", "Aperto a mão a alguém até lhes partir os ossos"] },
    { id: "c_per_d_19", texto: "Qual a minha atitude na cozinha?", opcoes: ["Gourmet: faço pratos espetaculares dignos de Insta", "Preguiça: arroz com atum é o limite", "Perigo: queimo sempre os tachos ou a comida", "Delego nos outros e ofereço-me para lavar a loiça"] },
    { id: "c_per_d_20", texto: "Como descrevo a minha memória?", opcoes: ["Lembro-me de coisas que os outros disseram há 10 anos", "Tenho a memória de um peixe dourado (3 segundos)", "Esqueço nomes mas lembro-me sempre de caras", "Só me lembro de coisas vergonhosas na hora de dormir"] }
  ],
  "sub_7_1": [ // Medos e Fobias
    { id: "c_per_m_01", texto: "Qual destes medos é o meu ponto fraco absoluto?", opcoes: ["Aranhas ou qualquer inseto com demasiadas patas", "Alturas, sinto logo vertigens", "Agulhas e ir ao médico", "O escuro (ficar sozinho/a em casa)"] },
    { id: "c_per_m_02", texto: "A ver filmes de terror, o que me assusta mais?", opcoes: ["Os 'Jumpscares' (ruídos altos de repente)", "Fantasmas e coisas paranormais", "Cenas de muito sangue e 'gore'", "Bonecos bizarros (tipo Chuckie ou Annabelle)"] },
    { id: "c_per_m_03", texto: "Qual é o meu medo mais social e irracional?", opcoes: ["Atender o telemóvel a números desconhecidos", "Falar em público para mais de 5 pessoas", "Ir sozinho/a a uma festa e não conhecer ninguém", "Ficar encravado nas portas do Metro ou Elevador"] },
    { id: "c_per_m_04", texto: "Se aparecer uma barata ou aranha voadora no quarto:", opcoes: ["Saco do chinelo e trato do assunto como um guerreiro", "Tranco a porta e deixo a casa para o bicho", "Chamo a gritar por socorro por alguém mais corajoso", "Meto o aspirador a funcionar a dois metros de distância"] },
    { id: "c_per_m_05", texto: "Tenho muito medo do oceano aberto e água profunda (Talassofobia)?", opcoes: ["Sim, imagino sempre tubarões debaixo dos meus pés", "Odeio não ter pé, entro em pânico", "Adoro mergulhar, quanto mais fundo melhor", "Gosto mas só se conseguir ver a areia cá em baixo"] },
    { id: "c_per_m_06", texto: "O medo de voar de avião afeta-me?", opcoes: ["Fico suado/a sempre que há uma mínima turbulência", "Durmo antes da descolagem, não sinto nada", "Tenho medo mas bebo um copo no aeroporto para relaxar", "Fico colado à janela a adorar as vistas"] },
    { id: "c_per_m_07", texto: "Lidar com sangue e feridas faz-me:", opcoes: ["Desmaiar ou ter que me sentar logo", "Acalmar os outros, dou para ótimo/a enfermeiro/a", "Virar a cara e não conseguir olhar", "Entro em pânico e acho que a pessoa vai morrer"] },
    { id: "c_per_m_08", texto: "Ao acordar a meio da noite no escuro para ir à casa de banho:", opcoes: ["Corro de volta para a cama antes que 'o monstro' me apanhe", "Acendo TODAS as luzes da casa", "Ando às cegas como se conhecesse a casa de cor", "Levo o telemóvel com a lanterna ligada no máximo"] },
    { id: "c_per_m_09", texto: "Qual destes medos 'modernos' sofro mais?", opcoes: ["Ficar sem bateria no telemóvel a meio da rua", "Enviar uma mensagem para a pessoa errada a falar dela", "A internet cair a meio de uma série", "Perder o telemóvel e as fotos todas"] },
    { id: "c_per_m_10", texto: "Medo de palhaços (Coulrofobia):", opcoes: ["Tenho um pavor irracional graças ao filme 'It'", "Acho que são só pessoas tristes pintadas", "Não tenho medo, mas acho desconfortável e bizarro", "Acho super engraçados, sem problema"] },
    { id: "c_per_m_11", texto: "Numa montanha-russa, eu sou:", opcoes: ["O/A que vai na primeira carruagem de mãos no ar", "O/A que grita a viagem inteira e fecha os olhos", "O/A que não vai e fica a segurar as malas cá em baixo", "O/A que vomita ou enjoa quando sai"] },
    { id: "c_per_m_12", texto: "Como lido com cães grandes a ladrar atrás de um portão?", opcoes: ["Dou um salto e fujo para a estrada", "Fico logo amigo do cão e tento fazer festas", "Não me afeta muito, é só barulho", "Começo a correr e o coração bate a 1000"] },
    { id: "c_per_m_13", texto: "Claustrofobia (medo de sítios fechados) ou Elevadores?", opcoes: ["Odeio, se puder vou pelas escadas sempre", "Fico a pensar: 'E se isto encrava agora?'", "Não lido bem com multidões ou filas apertadas", "Tranquilo, não sofro nada disso"] },
    { id: "c_per_m_14", texto: "Andar de mota/carro a altas velocidades:", opcoes: ["Sinto a adrenalina e adoro!", "Estou constantemente a travar no tapete do pendura", "Fecho os olhos e rezo um Pai Nosso", "Mando a pessoa conduzir mais devagar aos gritos"] },
    { id: "c_per_m_15", texto: "O que me dá mais arrepios só de pensar?", opcoes: ["Riscar o quadro da escola com as unhas", "Ouvir a broca do dentista", "O som de pessoas a mastigar maçãs cruas", "Tocar em algodão (ou materiais estranhos)"] },
    { id: "c_per_m_16", texto: "Medo do Futuro / Envelhecer:", opcoes: ["Entro em crise de meia-idade todos os meus anos", "Estou tranquilo, aceito as rugas e o cabelo branco", "Acho que vou ser um 'cota' espetacular", "Tenho pânico de não ter conquistado nada aos 40"] },
    { id: "c_per_m_17", texto: "Falar ao microfone num evento:", opcoes: ["Adoro a atenção, nasci para o palco", "A voz fica a tremer e falo a 200 à hora para acabar logo", "Fujo e invento dores de garganta", "Falo mas o meu coração quer sair pela boca"] },
    { id: "c_per_m_18", texto: "Qual a coisa mais estúpida de que já tive medo?", opcoes: ["Aspiradores quando era criança", "Sons estranhos da casa a 'estalar' de noite", "Ficar trancado/a numa casa de banho pública", "O ralo da banheira"] },
    { id: "c_per_m_19", texto: "Ir ver filmes de terror ao cinema:", opcoes: ["Compro sempre as pipocas para me proteger atrás do balde", "Adoro a tensão toda na sala escurecida", "Passo o filme de olhos tapados e com os ouvidos fechados", "Sou quem faz piadas a meio do filme para aliviar a tensão"] },
    { id: "c_per_m_20", texto: "O meu medo número um na vida:", opcoes: ["Ficar pobre", "Perder as pessoas que amo", "Passar vergonha em público de forma épica", "Nunca realizar os meus sonhos e ficar encravado na rotina"] }
  ]
};
