import { PerguntaClassica } from "@/types/catalogo";

export const classico_relacionamentos: Record<string, PerguntaClassica[]> = {
  "sub_2_0": [ // Amizades e Grupos
    { id: "c_rel_a_01", texto: "Qual é o meu papel principal no grupo de amigos?", opcoes: ["O paizinho/mãezinha do grupo", "O que desmarca no próprio dia", "O animador de serviço", "O que só se queixa"] },
    { id: "c_rel_a_02", texto: "Numa saída à noite em grupo, eu sou quem:", opcoes: ["Fica até acenderem as luzes", "Foge à francesa antes da meia-noite", "Está sempre na casa de banho a fazer amigos", "Fica a segurar nos casacos e malas"] },
    { id: "c_rel_a_03", texto: "Quando um amigo tem um problema, a minha abordagem é:", opcoes: ["Dar soluções hiper-lógicas (e frias)", "Dar um abraço e apenas ouvir", "Dizer logo 'eu avisei-te!'", "Vamos beber para esquecer"] },
    { id: "c_rel_a_04", texto: "Qual destas é a minha pior característica como amigo/a?", opcoes: ["Demoro 5 dias a responder no WhatsApp", "Sou inflexível e chato/a com as horas", "Dou conselhos que ninguém me pediu", "Esqueço-me de todos os aniversários"] },
    { id: "c_rel_a_05", texto: "Na organização de jantares ou férias de grupo:", opcoes: ["Sou eu que faço os Excel e reservas todas", "Só digo 'ok' e apareço na hora", "Reclamo do preço e das escolhas", "Visualizo as mensagens e nunca respondo"] },
    { id: "c_rel_a_06", texto: "Se estiver no carro com amigos, a música é:", opcoes: ["Tenho de ser eu o DJ, obrigatoriamente", "Deixo meterem o que quiserem", "Mando sempre trocar porque não gosto de nada", "Vou a cantar aos berros por cima do cantor"] },
    { id: "c_rel_a_07", texto: "No grupo do WhatsApp dos amigos, eu sou o/a:", opcoes: ["Aquele que envia 50 memes por dia", "O fantasma que só lê e nunca diz nada", "A pessoa dos áudios intermináveis", "O que só responde com figurinhas/stickers"] },
    { id: "c_rel_a_08", texto: "Como reajo quando um amigo desmarca um plano em cima da hora?", opcoes: ["Fico super ofendido/a e guardo rancor", "Fico aliviado/a, já não me apetecia ir", "Tento convencê-lo a ir de qualquer maneira", "Vou sozinho/a ou ligo a outra pessoa logo de seguida"] },
    { id: "c_rel_a_09", texto: "Quando vamos a um bar/discoteca:", opcoes: ["Sou o primeiro a ir para a pista dançar", "Fico encostado/a ao balcão a observar", "Passo a noite no telemóvel", "Vou de hora a hora à rua 'apanhar ar'"] },
    { id: "c_rel_a_10", texto: "Emprestar roupa ou coisas a amigos:", opcoes: ["Empresto tudo sem problema", "Empresto mas faço um rastreio rigoroso ao estado da peça", "Não empresto nada, tenho ciúmes das minhas coisas", "Empresto e esqueço-me para quem foi (perco as coisas)"] },
    { id: "c_rel_a_11", texto: "Qual é o meu nível de ciúme com as amizades?", opcoes: ["Zero, os meus amigos podem andar com quem quiserem", "Fico um bocado aziado/a se não me convidarem", "Sou bué ciumento/a, sou eu o/a melhor amigo/a!", "Não demonstro mas fico ofendido/a por dentro"] },
    { id: "c_rel_a_12", texto: "Como lido com discussões no meu grupo de amigos?", opcoes: ["Sou o diplomata que tenta apaziguar tudo", "Meto sempre mais lenha na fogueira (adoro drama)", "Tomo sempre o lado da pessoa com quem me dou mais", "Ignoro e afasto-me até resolverem a cena"] },
    { id: "c_rel_a_13", texto: "Nas fotos de grupo:", opcoes: ["Sou o que obriga a tirar 30 fotos até ficar bem", "Faço sempre caretas ou estrago a foto", "Sou eu que tiro a selfie porque tenho o braço comprido", "Fujo das câmaras como o Diabo da cruz"] },
    { id: "c_rel_a_14", texto: "Quando um amigo me pede ajuda numa mudança de casa:", opcoes: ["Estou lá à hora marcada a carregar os móveis todos", "Apareço no fim só para comer as pizzas", "Invento logo uma dor de costas terrível", "Ajudo mas passo o tempo todo a reclamar do peso"] },
    { id: "c_rel_a_15", texto: "O que me ofende mais numa amizade?", opcoes: ["Mentiras, mesmo as mais pequenas", "Falta de apoio num momento mau", "Quando começam a namorar e desaparecem", "Quando criticam as minhas escolhas de vida"] },
    { id: "c_rel_a_16", texto: "Como sou a guardar segredos partilhados num grupo?", opcoes: ["Um túmulo. Nem sob tortura falo.", "Tento muito, mas às vezes descai-me", "Só conto à minha pessoa de extrema confiança", "Sou uma péssima escolha, toda a gente fica a saber"] },
    { id: "c_rel_a_17", texto: "Na escolha de um presente de anos em grupo eu:", opcoes: ["Dou ideias espetaculares mas não compro nada", "Deleto em alguém, só dou o dinheiro e assino o cartão", "Sou eu que recolho o dinheiro e vou comprar", "Apareço sem ter pago e digo que esqueci"] },
    { id: "c_rel_a_18", texto: "Quantos 'melhores amigos' sinto que tenho na vida real?", opcoes: ["Nenhum a sério, dou-me bem com todos", "Apenas 1, o/a meu/minha parceiro/a no crime", "Um grupinho restrito de 3 ou 4 pessoas", "Dezenas, considero toda a gente 'melhor amigo'"] },
    { id: "c_rel_a_19", texto: "Se um amigo aparecer com um penteado ridículo eu:", opcoes: ["Digo-lhe a verdade imediatamente, doa a quem doer", "Digo 'está giro!' e critico nas costas", "Faço uma piada para disfarçar a opinião", "Não digo nada para não o magoar"] },
    { id: "c_rel_a_20", texto: "Qual é a minha tolerância a atrasos dos outros?", opcoes: ["Passados 10 minutos já estou a ligar a insultar", "Digo que não faz mal (mas julgo internamente)", "Sou pacífico, fico à espera na boa", "Normalmente sou EU quem se atrasa"] }
  ],
  "sub_2_1": [ // Vida Amorosa e Dates
    { id: "c_rel_v_01", texto: "No primeiro date, qual é para mim o cenário ideal?", opcoes: ["Um café ou copo rápido (fácil de fugir se correr mal)", "Um jantar requintado a dois", "Uma atividade fora da caixa (bowling, passear)", "Cinema (para não ter de falar muito)"] },
    { id: "c_rel_v_02", texto: "A dividir a conta num encontro:", opcoes: ["Faço questão de pagar sempre eu", "Dividimos sempre meio-a-meio", "Pago eu desta vez, pagas tu na próxima", "Faço-me sempre de desentendido/a para não pagar"] },
    { id: "c_rel_v_03", texto: "O meu maior 'Red Flag' num possível parceiro é:", opcoes: ["Tratar mal os empregados de mesa", "Falar dos/das 'ex' a toda a hora", "Estar constantemente agarrado/a ao telemóvel", "Mandar erros de português básicos por mensagem"] },
    { id: "c_rel_v_04", texto: "Qual é a minha linguagem de amor principal?", opcoes: ["Apoio físico (abraços, andar de mãos dadas)", "Receber presentes (surpresas, flores)", "Atos de serviço (fazerem coisas por mim)", "Palavras de afirmação (dizerem que me amam)"] },
    { id: "c_rel_v_05", texto: "Como lido com demonstrações de afeto em público?", opcoes: ["Adoro andar aos beijos em todo o lado", "Andar de mão dada é o meu limite máximo", "Odeio e fujo, que vergonha", "Só dou a mão se não houver conhecidos por perto"] },
    { id: "c_rel_v_06", texto: "Em relações, eu apaixono-me:", opcoes: ["Ao fim de dois dias já estou a pensar no casamento", "Demoro imenso tempo a abrir-me e a confiar", "Vou num 'vai-vém', um dia gosto, no outro não", "Apaixono-me rápido e farto-me ainda mais rápido"] },
    { id: "c_rel_v_07", texto: "Quando gosto de alguém, o meu método de engate é:", opcoes: ["Sou bué direto/a, vou lá e pergunto", "Espero sentadinho/a que a pessoa venha falar comigo", "Mando indiretas no Instagram até a pessoa perceber", "Ataco com humor e piadas secas para puxar conversa"] },
    { id: "c_rel_v_08", texto: "O que acho de partilhar a password do telemóvel com o/a parceiro/a?", opcoes: ["Sem problemas, não tenho nada a esconder", "Partilho, mas odeio que mexam", "Nem pensar, a privacidade é intocável", "Partilho a minha mas exijo a da pessoa em troca"] },
    { id: "c_rel_v_09", texto: "No que toca a dormir em casal:", opcoes: ["Gosto de dormir em conchinha o tempo todo", "Abraço só nos primeiros 5 mins, depois vou para o meu canto", "Sou daqueles que rouba os cobertores todos de noite", "Odeio dormir acompanhado, prefiro o meu espaço"] },
    { id: "c_rel_v_10", texto: "Numa relação amorosa, o meu nível de ciúme é:", opcoes: ["Zero! Relação baseada na confiança cega.", "Crio filmes na cabeça mas não digo nada", "Sou um bocado ciumento/a e assumo", "Detetive profissional do FBI, pergunto tudo"] },
    { id: "c_rel_v_11", texto: "Quanto a manter amizades com os 'ex':", opcoes: ["Falo super bem com quase todos", "Bloqueados e banidos da face da Terra", "Só falo se nos cruzarmos por acaso na rua", "Tento ser amigo mas acaba sempre mal"] },
    { id: "c_rel_v_12", texto: "Uma discussão numa relação para mim é:", opcoes: ["O fim do mundo, detesto conflitos", "Uma forma de resolver problemas e seguir em frente", "Um desporto, até adoro bater boca de vez em quando", "Viro a cara, calo-me e aplico o tratamento de silêncio"] },
    { id: "c_rel_v_13", texto: "O que acho das aplicações de encontros (Tinder, Bumble)?", opcoes: ["Adoro, são ótimas para conhecer malta", "Já usei mas aquilo é só malucos/as", "Nunca usaria, gosto de coisas orgânicas", "Tenho instaladas mas nunca falo com ninguém"] },
    { id: "c_rel_v_14", texto: "Se estiver chateado/a com o/a parceiro/a eu:", opcoes: ["Digo logo na lata qual é o problema", "Digo 'não tenho nada' com a pior cara possível", "Mando uma mensagem enorme a explicar os meus sentimentos", "Espero que a pessoa adivinhe e peça desculpa"] },
    { id: "c_rel_v_15", texto: "Como lido com a ideia de compromisso longo / casamento?", opcoes: ["O meu sonho desde que nasci!", "Assusta-me imenso, mas um dia gostava", "Acho um bocado um conceito ultrapassado", "Se tiver que acontecer acontece, não forço"] },
    { id: "c_rel_v_16", texto: "Qual a minha postura sobre presentes do Dia dos Namorados?", opcoes: ["Exijo presentes e jantares hiper românticos", "Acho super azeiteiro, por mim saltava-se", "Gosto de receber algo pequeno e com significado", "Deixo sempre a compra do presente para o próprio dia"] },
    { id: "c_rel_v_17", texto: "A conhecer os pais (sogros) da minha relação, eu:", opcoes: ["Fico incrivelmente tenso/a e nervoso/a", "Encarno o papel de genro/nora perfeito/a", "Sou super na descontra, trato-os por tu", "Evito esse encontro o máximo de meses possível"] },
    { id: "c_rel_v_18", texto: "Sobre demonstrações públicas nas redes sociais:", opcoes: ["Meto fotos do casal de 5 em 5 minutos", "Meto uma foto de vez em quando nos anos da pessoa", "Tenho a minha relação hiper em privado, nunca meto nada", "Meto indiretas quando estamos chateados"] },
    { id: "c_rel_v_19", texto: "No que toca a organizar viagens a dois:", opcoes: ["Deixo a outra pessoa tratar de tudo", "Sou eu que escolho o hotel, voo, e roteiro ao minuto", "Discutimos sempre para chegar a um consenso", "Decidimos os dois as coisas grandes e improvisamos o resto"] },
    { id: "c_rel_v_20", texto: "Um término (break-up) ideal para mim:", opcoes: ["Falar cara-a-cara, chorar e ser maduro", "Por mensagem e bloquear logo de seguida", "Ir-me afastando aos poucos até a pessoa perceber", "Inventar o clássico 'o problema não és tu, sou eu'"] }
  ]
};
