import { PerguntaClassica } from "@/types/catalogo";

export const classico_saude_bem_estar: Record<string, PerguntaClassica[]> = {
  "sub_17_0": [ // Hábitos de Sono
    { id: "c_sbe_s_01", texto: "Como descrevo a minha posição preferida para dormir?", opcoes: ["De barriga para baixo como um para-quedista", "A famosa posição fetal, bem encolhido/a", "De barriga para cima, pareço um faraó no sarcófago", "Estrela-do-mar: ocupo a cama toda e expulso o parceiro"] },
    { id: "c_sbe_s_02", texto: "O que acontece aos meus cobertores a meio da noite?", opcoes: ["Puxo-os todos para mim e faço um casulo", "Atiro-os para o chão quando tenho calores a meio da noite", "Ficam tal e qual, durmo como uma pedra sem me mexer", "Uso um como almofada entre as pernas e durmo destapado/a"] },
    { id: "c_sbe_s_03", texto: "Em relação ao bater os dentes (bruxismo) ou falar a dormir:", opcoes: ["Falo super alto e admito crimes da minha vida passada a dormir", "Ranjo os dentes tão alto que pareço um roedor de móveis", "Só me babo imenso na almofada, mas sou silencioso", "Sou um ressonador autêntico de 100 decibéis (pareço um trator)"] },
    { id: "c_sbe_s_04", texto: "A minha atitude em relação a pijamas é:", opcoes: ["Tenho um conjunto de seda/flanela combinando chiquérrimo", "Durmo com t-shirts de festivais antigas que têm buracos", "Só uso pijama no Inverno, no Verão vou quase como nasci", "Tenho calças de fato de treino e uma camisola qualquer atirada"] },
    { id: "c_sbe_s_05", texto: "Para conseguir adormecer, eu preciso OBRIGATORIAMENTE de:", opcoes: ["Silêncio absoluto e escuridão de caixão", "A televisão ou um podcast a dar baixinho", "Meias calçadas (os pés gelados são o inimigo)", "Uma perna de fora do cobertor para regular a temperatura"] },
    { id: "c_sbe_s_06", texto: "Se acordar às 3h da manhã sem sono, o que faço?", opcoes: ["Vou ao telemóvel destruir a minha retina com a luz no máximo", "Fico a pensar nas coisas vergonhosas que fiz em 2014", "Levanto-me e vou assaltar o frigorífico a meio da noite", "Fecho os olhos com força e exijo ao meu cérebro que se desligue"] },
    { id: "c_sbe_s_07", texto: "Como acordo nos dias de folga / fim de semana?", opcoes: ["O relógio biológico acorda-me estupidamente às 7h da manhã", "Durmo até doer a cabeça e a coluna (meio-dia ou mais)", "Acordo, vou comer e volto para a cama adormecer outra vez", "Meto alarme na mesma só para ter o gosto de o desligar e voltar a dormir"] },
    { id: "c_sbe_s_08", texto: "Quantas almofadas preciso na cama?", opcoes: ["Apenas uma, super fina que parece uma folha de papel", "Uma gigante e dura para me alinhar a cabeça", "Umas três ou quatro, faço um muro de almofadas", "Durmo sem almofada, sou um rijo"] },
    { id: "c_sbe_s_09", texto: "Qual a minha atitude perante a soneca (sesta) à tarde?", opcoes: ["Faço uma 'Power Nap' de 20 mins e acordo cheio/a de energia", "Durmo 3 horas e acordo a achar que é o dia seguinte", "Fico com dor de cabeça e mal humorado/a, odeio sestas", "Não consigo dormir de dia, só no escuro da noite"] },
    { id: "c_sbe_s_10", texto: "A minha reação ao som de um mosquito no quarto às 4h da manhã:", opcoes: ["Ligo a lanterna, pego num chinelo e é uma guerra até à morte", "Meto os lençóis a tapar a cabeça, o pescoço e a testa e rezo", "Ligo o repelente de tomada e espero que a ciência resolva", "Levo picadas e acordo cheio/a de alto e comichão"] },
    { id: "c_sbe_s_11", texto: "Em noites de trovoada forte eu:", opcoes: ["Durmo como um bebé, adoro o som da chuva pesada", "Fico apavorado/a e deito a mão à tomada para desligar o PC", "Meto tampões nos ouvidos", "Vou para a janela tirar vídeos para meter nos stories"] },
    { id: "c_sbe_s_12", texto: "O meu 'outfit' para viagens noturnas de avião ou autocarro longo:", opcoes: ["Levo a minha almofada de pescoço super azeiteira mas top", "Durmo com a cabeça encostada ao vidro frio e acordo babado", "Não consigo dormir em transportes e chego desfeito/a", "O encosto do banco cai sempre para trás e arranjo chatice"] },
    { id: "c_sbe_s_13", texto: "Sobre sonhos estranhos, eu sou quem:", opcoes: ["Tem sonhos super vívidos a fugir de dragões e ser devorado", "Nunca me lembro de absolutamente nenhum sonho ao acordar", "Acordo a chorar ou rir derivado a cenas mega estúpidas", "Tenho muitos pesadelos onde estou a cair no vazio e acordo a saltar"] },
    { id: "c_sbe_s_14", texto: "Beber água durante a noite:", opcoes: ["Tenho um copo na mesa de cabeceira que bebe o pó todo", "Levanto-me de madrugada só para enfiar a boca na torneira ou garrafa", "Não bebo para não ter de ir fazer xixi a meio da noite (o clássico medo do frio)", "Bebo e vou mesmo 3 vezes à casa de banho na mesma noite"] },
    { id: "c_sbe_s_15", texto: "Para me ajudar a dormir, os chás milagrosos (Camomila, Cidreira):", opcoes: ["Acredito piamente nisso, sinto logo o sono a vir", "Isso é misticismo falso, não faz nada a não ser dar vontade de urinar", "Eu bato uma taça de vinho ou cerveja, esse é o meu chá relaxante", "Só durmo se tomar algo como melatonina porque o meu cérebro não pára"] },
    { id: "c_sbe_s_16", texto: "Quando há um cão/gato a dormir em cima das pernas na cama:", opcoes: ["Contorço-me todo para não o acordar, com cãibras", "Dou um pontapé acidental no bicho a meio da noite e fico com culpa", "Expulso o animal de fininho porque ele rouba o lençol", "Eu sou o aquecedor dele, não resmungo e aceito o meu destino"] },
    { id: "c_sbe_s_17", texto: "Se esquecer de carregar o telemóvel antes de dormir:", opcoes: ["Acordo e fico num estado de ansiedade terrível por ter 2% logo de manhã", "Meto o carregador na tomada meia a dormir e de olhos fechados e rebento com o cabo", "Tenho tomada longe da cama, é a minha desgraça", "Digo 'azar' e ele que se aguente"] },
    { id: "c_sbe_s_18", texto: "Sobre camas de hotel ou casas estranhas:", opcoes: ["Durmo melhor do que em minha casa, adoro mudar", "Tiro imenso tempo a adormecer porque estranho a almofada ou o cheiro", "Levo as minhas próprias fronhas/almofadas nas viagens longas", "Fico com medo de não me acordar para as férias e meto 10 alarmes em vez de 3"] },
    { id: "c_sbe_s_19", texto: "A ouvir um colega ou parceiro a ressonar ao lado:", opcoes: ["Viro-o de lado com uma pancada nas costelas sem querer", "A estalada de língua ou o som do 'Tsc Tsc' para ver se pára", "Fico a sofrer calado e tenho fantasias violentas", "Pego na almofada e vou deitar-me no sofá da sala indignado"] },
    { id: "c_sbe_s_20", texto: "A coisa mais absurda que a preguiça já me fez na cama:", opcoes: ["Puxar as coisas com os pés do chão (meias, carregador) em vez de baixar", "Escrever mensagens com a ponta do nariz para não mexer a mão fria", "Adormecer sem lavar a cara e os dentes porque a cama sugou-me", "Deixar a luz do candeeiro acesa até às 5h da manhã porque custava muito a desligar"] }
  ],
  "sub_17_1": [ // Dietas e Alimentação
    { id: "c_sbe_d_01", texto: "A minha atitude nas Segundas-Feiras de começar a 'Dieta':", opcoes: ["Corto nos hidratos e como grelhados religiosamente (até quarta-feira)", "Chego ao fim do dia, irrito-me, e como uma tablete de Milka inteira", "Começo sempre 'na próxima semana', não estava com a cabeça certa", "A minha dieta é o jejum intermitente: só como quando tenho forme (ou seja, sempre)"] },
    { id: "c_sbe_d_02", texto: "Na leitura atenta dos rótulos e macros no supermercado:", opcoes: ["Conto as proteínas, os açúcares e as calorias (TOC das dietas)", "Só leio se é de chocolate, se tem caramelo e se traz muito dentro da caixa", "Só vejo o prazo de validade para ter certeza de que não está podre", "Olho para a informação e não percebo patavina, mas levo se a embalagem for gira"] },
    { id: "c_sbe_d_03", texto: "Substituir refeições por Batidos de Proteína (Whey) ou Shakes de Emagrecimento:", opcoes: ["Acho que todos sabem a farinha ou sabão, mas bebo num gole tapando o nariz", "Adoro as garrafinhas, dão aquele aspeto fit a ir para o escritório", "Fico com dores de barriga e muitos gases. Terrível.", "Recuso. A comida sólida mastigada é o meu sentido da vida"] },
    { id: "c_sbe_d_04", texto: "Como reajo aos famosos produtos '0% de Açúcar' e 'Light':", opcoes: ["Caio que nem um patinho na esparrela e encho o carrinho disso", "Dizem 0% de açúcar mas no fundo têm edulcorantes que fazem pior", "Acho que sabem todos a plástico molhado, prefiro não comer", "Compro-os para depois comer o dobro da dose já que 'são fit' e não engordam"] },
    { id: "c_sbe_d_05", texto: "Em que é que o 'Dia do Lixo' (Cheat Day) resulta comigo?", opcoes: ["O Cheat Day estende-se para o fim de semana todo (Cheat Weekend)", "Como 1 fatia de bolo com enorme culpa, sinto-me uma fraude", "Um balde de Nutella e rezo que amanhã não apareça na balança", "Bebo cerveja ou álcool que são calorias ocas que 'não contam'"] },
    { id: "c_sbe_d_06", texto: "Como lido com dietas da moda? (Keto, Paleo, Dukan...)", opcoes: ["Tento tudo o que envolva comer carne assada sem limite e perder peso", "Não aguento um dia sem pão ou arroz, isso é uma ditadura do terror", "Adoro ver vídeos sobre essas dietas enquanto como bolachas Maria", "Nunca tentei, sou a favor do reiki dos pratos 'um bocado de tudo não faz mal'"] },
    { id: "c_sbe_d_07", texto: "Na hora de escolher os legumes ou salada:", opcoes: ["Alface e tomate. Fim. E tem de nadar em azeite/molho.", "Brocolos, couve-flor... adoro vegetais verdes, sou super orgulhoso disso", "Escondo debaixo do arroz ou da carne e finjo que não reparei neles", "O meu único vegetal permitido pela minha mente é a batata frita (é da terra!)"] },
    { id: "c_sbe_d_08", texto: "Em jantares de aniversário quando todos pedem entrada e sobremesa:", opcoes: ["Aviso previamente toda a gente que 'estou de dieta' e peço só grelhado e recuso doçarias", "Meto a dieta em pausa logo que o couvert com manteiguinhas e queijinho chega à mesa", "Sento-me, provo de toda a gente 'só um bocadinho' e fujo à conta das culpas", "Como a sobremesa toda com os olhos e saio com dor de estômago por querer mas não comer"] },
    { id: "c_sbe_d_09", texto: "A relação mais forte que tenho com pão:", opcoes: ["Comia a todas as refeições! Pão quentinho com manteiga era só a minha perdição.", "Troquei o trigo clássico por pão escuro e sementes (estou fit)", "Não percebo o alarido, consigo muito bem viver sem isso e como tostas redondas tristes", "Só uso pão se for a tal clássica bifana ou para limpar aquele molhinho do prato de bitoque"] },
    { id: "c_sbe_d_10", texto: "A preparação de almoços antecipada (O Meal Prep dos domingos):", opcoes: ["Eu sou a lenda dos tupperwares. Frango com batata doce todos os dias", "Faço 2 dias e à quarta-feira esmago-me e mando vir sushi ou pizzas pela net", "Faço as marmitas muito bem e depois esqueço-me no frigorífico de casa 3 vezes seguidas", "Gasto o Domingo na cama... as marmitas vão para o lixo que lá sobra na cozinha dos jantares"] },
    { id: "c_sbe_d_11", texto: "Qual a pior praga alimentar se estiver a passar fome com dieta restrita?", opcoes: ["O clássico colega de trabalho a fazer inveja no escritório com um hambúrguer a pingar no ecrã do lado", "Ficar mau/humorado com o mundo e a querer matar o peão", "Ver anúncios da Telepizza na TV e ficar a babar a meio do programa", "Arranjar brigas monumentais com a minha pessoa por causa de tretas"] },
    { id: "c_sbe_d_12", texto: "O pequeno almoço e o vício nas chamadas 'papas de aveia':", opcoes: ["Como papas da aveia mas enfio lá mel, chocolate preto e manteiga de amendoim até engordar", "Como pão escuro porque não suporto a papa da aveia que tem um aspecto pastoso (sabe a papelão)", "Aveia, whey e sementes de chia! Tenho os macros estipulados", "Apenas como a panqueca super panquecástica na foto matinal para a rede social. Depois não é isto."] },
    { id: "c_sbe_d_13", texto: "No cinema, com pipocas gigantes a chamarem por ti:", opcoes: ["Como do pacote de quem se senta comigo para não ser eu o mau na foto", "Peço o XXL, o balde é a cama do meu cão, e afogo em M&Ms de seguida", "Levo gomas do super mercado às escondidas na mala ou casaco porque não aguento o preço do pipocal", "Zero trincas. Levo água e pipocas da fit com menos sal e zero gordura"] },
    { id: "c_sbe_d_14", texto: "Se estiver com problemas no 'trânsito digestivo' (o clássico inchaço ou intestinos):", opcoes: ["Meto logo uma barriga de gravida para fora das calças para respirar", "Como um Kiwi verde, uma Actívia e rezo as preces no WC trancado num pânico silencioso", "Arroto e finjo que não foi nada ao pé das visitas que se instalaram e ignoram", "Bebo só chás verdes detox e fico de rastos para todo o lado"] },
    { id: "c_sbe_d_15", texto: "Comprar 'super alimentos' saudáveis (Maca, Spirulina, Matcha, etc):", opcoes: ["Gastei 15€ nesse pacote esquisito que jurei que ia tomar e aquilo caducou a ganhar raízes e bicho", "Faço mistelas verdes da moda num shaker que ninguém me aguenta", "Sigo todos porque o pó de couve-flor em forma de pílula parece bué trendy", "Vou para o azeite da aldeia e a farinha tuga. Spirulina soa a molas de cama."] },
    { id: "c_sbe_d_16", texto: "Sair do banho e olhar ao espelho na dieta:", opcoes: ["Encolho as beiças e o pescoço todo para baixo e poso como um semi deus/deusa nos reflexos com a sombra certa", "Fico com o trauma da pancada de gordura no lombo inferior que ganhei em 2012 na praia de Quarteira", "Estou lá para ver se me espremo uma borbulha que se revelou nas banhas mas juro focar com foco!", "Ignoro o espelho com a toalha grande do Ruca ou IKEA porque doer menos do que não fazer ginásio na terça feira."] },
    { id: "c_sbe_d_17", texto: "Com os lanches entre as refeições no trabalho (meio da tarde):", opcoes: ["Bolachinhas de arroz ou milho (parece morder tabuleiros de papelão em pó) e acabo na azia total a beber o chá", "Assalto a máquina dos Kit-Kats e chocolates com as moedas que eu cravava nos mealheiros", "Um belo e belíssimo croissant de queijo que a vizinha me dá por caridade lá da bomba", "Esqueço de lanchar com o computador e os ecrãs... passo a esfomear o meu corpo e perco peso num estado caótico"] },
    { id: "c_sbe_d_18", texto: "Falar sobre os resultados do ginásio no escritório e dos músculos a crescer:", opcoes: ["'Ah, sim, hoje não tenho força para a caneta' (para ver se me dão o atestado dos bravos)", "Não quero dar show, visto-me igual para que ninguém atrofie mas posto fotos da passadeira por via das dúvidas nas stories", "Odeio de morte quem conta as lides fit quando eu estou a rebentar guloseimas nos cantos da secretaria nos dedos gordurosos.", "Puxo da camisola um milímetro como quem não quer a coisa nas passagens da malta! Olha bem para isto!"] },
    { id: "c_sbe_d_19", texto: "O que diz a Mãe no almoço da família ao Domingo da minha dieta:", opcoes: ["'Oh Tino/Tininha estás muito esgrouvinhado/a! Vai umas febras para engordar?'", "'Comes um passarinho tu? Dá licença de rapar os cantos aos tachos!' e empurra mais pernas e coxas pesadas no monte de puré", "'Isso da proteína faz muito mal ao fígado e coração! Bebe vinho!'", "Eu já fujo da casa da mãe ao Domingo por causa do cabrito no forno que estraga semanas de sacrifício da passadeira da vida!"] },
    { id: "c_sbe_d_20", texto: "A frustração brutal da Balança Digital da Farmácia / de Casa:", opcoes: ["Peso-me todos os dias às 7h00 da manhã certas DEPOIS de ir à casa de banho e SEMINU/NUA para ser verídico sem culpas do elástico das calças de ganga pesadas", "Olho para aquele traste redondo nos cantos e dou passos atrás, porque se meto um dedo aquilo marca já +5kgs a cima", "Só peso depois de semanas inteiras com grandes vitórias. Movo uma perna para baixo num truque falso a ver se a máquina reduz a numeração das massas corporais", "A Balança tem o pó e a humidade do banho... Não quero mais nada... Fui comprar uma das antigas e parti nos primeiros ensaios! Não era preciso nada de digital."] }
  ]
};
