import { PerguntaClassica } from "@/types/catalogo";

export const classico_sonhos_futuro: Record<string, PerguntaClassica[]> = {
  "sub_27_0": [ // Objetivos de Vida
    { id: "c_sf_o_01", texto: "O meu maior objetivo financeiro para o futuro é:", opcoes: ["Ficar milionário/a e não fazer nenhum", "Ter dinheiro suficiente para não olhar para os preços no supermercado", "Ganhar o Euromilhões e desaparecer", "Pagar as minhas contas e ter paz de espírito"] },
    { id: "c_sf_o_02", texto: "Como imagino a minha casa de sonho?", opcoes: ["Uma mansão gigante com piscina e cinema", "Um apartamento moderno no centro da cidade", "Uma casinha de madeira isolada no meio do mato", "Uma casa normal, mas onde a loiça se lavasse sozinha"] },
    { id: "c_sf_o_03", texto: "Se pudesse reformar-me amanhã, o que faria ao meu tempo livre?", opcoes: ["Viajava pelo mundo inteiro sem parar", "Dormia até ao meio-dia todos os dias", "Abria um negócio relaxante (ex: café de gatos)", "Ficava tão farto/a de não fazer nada que arranjava outro trabalho"] },
    { id: "c_sf_o_04", texto: "O meu objetivo a nível de saúde para daqui a 10 anos:", opcoes: ["Estar super fit, com abdominais definidos", "Conseguir subir umas escadas sem parecer que vou desmaiar", "Ter a coluna direita e sem dores ao acordar", "Aceitar o meu corpo e ser feliz a comer pão"] },
    { id: "c_sf_o_05", texto: "Se tivesse de escolher um lema de vida para o futuro:", opcoes: ["'Trabalha muito agora para descansar depois'", "'A vida são dois dias e um já passou'", "'Deixa a vida levar-me, vida leva eu'", "'O que tiver de ser, será... mas espero que seja bom'"] },
    { id: "c_sf_o_06", texto: "Em relação a ter filhos no futuro:", opcoes: ["Quero uma equipa de futebol (3 ou mais)", "Um ou dois no máximo, para não dar muito trabalho", "Prefiro ter cães e gatos, são mais baratos e não respondem mal", "Ainda não sei, mudo de ideias todos os dias"] },
    { id: "c_sf_o_07", texto: "O que preferia alcançar: Fama mundial ou Riqueza anónima?", opcoes: ["Fama! Quero ser reconhecido/a na rua e ter fãs", "Riqueza anónima. Dinheiro no bolso e ninguém me chateia", "As duas coisas, quero o pacote completo", "Nenhuma, a fama tira a paz e o dinheiro traz problemas"] },
    { id: "c_sf_o_08", texto: "Onde me vejo a morar daqui a 20 anos?", opcoes: ["No meu país, perto da família e amigos", "Num paraíso tropical (Bali, Maldivas)", "Num país frio mas super organizado (Suíça, Noruega)", "Exatamente no mesmo sofá onde estou agora"] },
    { id: "c_sf_o_09", texto: "Qual o meu maior objetivo de desenvolvimento pessoal?", opcoes: ["Aprender a dizer 'Não' sem me sentir culpado/a", "Deixar de ser tão ansioso/a com coisas pequenas", "Tornar-me uma pessoa super calma e zen", "Aprender a não deixar tudo para a última da hora (procrastinação)"] },
    { id: "c_sf_o_10", texto: "Como encaro o envelhecimento?", opcoes: ["Com pânico, já estou a comprar cremes anti-rugas", "Acho que vou ser um 'cota' muito fixe e moderno", "Não ligo, faz parte da vida", "Recuso-me a crescer, serei sempre uma criança grande"] },
    { id: "c_sf_o_11", texto: "Se eu escrevesse um livro sobre a minha vida, o título seria:", opcoes: ["'A Jornada Épica para a Riqueza'", "'Como Sobreviver a Desastres e Gafes'", "'Confusão Organizada: A Minha História'", "'Diário de uma Pessoa com Fome e Sono'"] },
    { id: "c_sf_o_12", texto: "Qual é o meu maior objetivo no amor para o futuro?", opcoes: ["Casar com uma grande festa e convidar toda a gente", "Encontrar alguém que me ature as manias todas", "Ter uma relação super independente, cada um na sua casa", "Ficar solteiro/a, ser rico/a e ter muitos animais"] },
    { id: "c_sf_o_13", texto: "Se pudesse ter uma habilidade perfeita no futuro, seria:", opcoes: ["Falar todos os idiomas do mundo", "Ser um/a mestre na cozinha e nunca queimar nada", "Ter uma memória fotográfica impecável", "Saber investir na bolsa e ficar rico/a rápido"] },
    { id: "c_sf_o_14", texto: "Qual é a minha visão sobre sustentabilidade e o planeta no futuro?", opcoes: ["Sou super eco-friendly, reciclo tudo e ando de bicicleta", "Faço o meu melhor (separo o lixo), mas sem extremismos", "Acho que já vamos tarde, a inteligência artificial vai dominar isto tudo", "Esqueço-me de levar os sacos para o supermercado e compro novos"] },
    { id: "c_sf_o_15", texto: "O que espero que digam de mim quando tiver 80 anos?", opcoes: ["'Ele/Ela teve uma vida incrível e cheia de aventuras'", "'Ainda tem bué energia e vai a festas'", "'É o/a avô/avó que dá os melhores presentes (e dinheiro)'", "'Reclama de tudo, mas tem um bom coração'"] },
    { id: "c_sf_o_16", texto: "Qual a minha ambição secreta que nunca conto a ninguém?", opcoes: ["Ser dono/a de um império gigante e mandar em todos", "Escrever um livro que vire bestseller", "Largar tudo, comprar uma autocaravana e sumir", "Participar num reality show e ganhar aquilo"] },
    { id: "c_sf_o_17", texto: "O meu objetivo de organização para os próximos anos é:", opcoes: ["Ter a casa sempre num brinco (nível Marie Kondo)", "Conseguir manter a caixa de emails a zeros", "Parar de perder as chaves e o telemóvel todos os dias", "Apenas sobreviver ao caos sem enlouquecer"] },
    { id: "c_sf_o_18", texto: "Se eu fundasse uma ONG ou instituição, seria para:", opcoes: ["Proteger e resgatar animais abandonados", "Ajudar crianças e dar-lhes acesso a educação", "Combater as alterações climáticas e limpar oceanos", "Dar café grátis e apoio psicológico a malta com sono"] },
    { id: "c_sf_o_19", texto: "Como imagino os meus fins de semana daqui a 15 anos?", opcoes: ["Com jantares chiques e provas de vinho", "A correr atrás de crianças/cães num parque", "Ainda a recuperar das noitadas (mas com mais dores de costas)", "No sofá, a ver séries em paz absoluta"] },
    { id: "c_sf_o_20", texto: "A minha visão sobre o sucesso é:", opcoes: ["Ter uma conta bancária com muitos zeros", "Ter liberdade de tempo para fazer o que quero", "Ser famoso e reconhecido na minha área", "Acordar feliz e sem ter o alarme a tocar"] }
  ],
  "sub_27_1": [ // Sonhos por Realizar
    { id: "c_sf_s_01", texto: "A viagem que está no topo absoluto da minha Bucket List (lista de sonhos):", opcoes: ["Fazer um Safari em África", "Ver a Aurora Boreal na Islândia/Noruega", "Ir a Nova Iorque no Natal", "Fazer um retiro de silêncio e ioga na Ásia"] },
    { id: "c_sf_s_02", texto: "A habilidade 'radical' que sonho aprender um dia:", opcoes: ["Tirar a licença e fazer paraquedismo sozinho/a", "Aprender a fazer surf e apanhar grandes ondas", "Conduzir um carro de Fórmula 1 numa pista real", "Nenhuma, o meu limite radical é descer escadas sem corrimão"] },
    { id: "c_sf_s_03", texto: "Qual é a língua que eu adorava acordar a saber falar perfeitamente?", opcoes: ["Japonês ou Coreano (para ver séries/animes sem legendas)", "Italiano (é super romântico e chique)", "Mandarim (para fazer negócios e dominar o mercado)", "Inglês com aquele sotaque britânico perfeito"] },
    { id: "c_sf_s_04", texto: "Se pudesse ser mestre numa arte que nunca tentei:", opcoes: ["Pintar quadros que valem milhões", "Tocar guitarra a solo num palco de estádio", "Cozinhar como um Chef Michelin", "Dança de salão (parecer no 'Dança com as Estrelas')"] },
    { id: "c_sf_o_05", texto: "O evento mundial a que eu sonho ir pelo menos uma vez na vida:", opcoes: ["O Carnaval no Rio de Janeiro", "O festival de música Coachella ou Tomorrowland", "Um jogo da final do Campeonato do Mundo (Futebol)", "A cerimónia dos Óscares em Hollywood"] },
    { id: "c_sf_o_06", texto: "Um sonho estranho/diferente que gostava de concretizar:", opcoes: ["Ser figurante num filme super famoso (tipo zumbi)", "Ter o meu nome no Guinness Book of Records por algo parvo", "Comprar uma ilha privada deserta", "Andar no Espaço (Ser turista espacial)"] },
    { id: "c_sf_o_07", texto: "Qual a celebridade viva que eu sonho conhecer e jantar?", opcoes: ["Um ator/atriz famoso/a (Brad Pitt, Zendaya...)", "Um cantor de quem sou super fã", "Um visionário/rico tipo Elon Musk ou Bill Gates", "O Gordon Ramsay para me fazer o jantar"] },
    { id: "c_sf_o_08", texto: "Um talento físico que gostava de dominar 'do nada':", opcoes: ["Fazer a espargata (ter flexibilidade extrema)", "Correr uma maratona sem me cansar", "Saber artes marciais para me defender à la Jackie Chan", "Saber nadar tão bem que pareço um peixe"] },
    { id: "c_sf_o_09", texto: "A minha compra de luxo de sonho se o dinheiro não fosse problema:", opcoes: ["Um iate gigante com tripulação", "Um carro super desportivo (Ferrari/Porsche)", "Um guarda-roupa inteiro de designers de luxo", "Um chef privado 24/7 em minha casa"] },
    { id: "c_sf_o_10", texto: "Qual a profissão que eu sonhava ter quando era criança e que ainda gostava de experimentar 1 dia?", opcoes: ["Astronauta ou Detetive do FBI", "Ator/Atriz de Hollywood", "Veterinário/a para salvar todos os bichos", "Testador de camas e colchões profissionais"] },
    { id: "c_sf_o_11", texto: "Um medo que eu sonho conseguir ultrapassar um dia:", opcoes: ["O medo de alturas (para poder fazer escalada ou saltar de pontes)", "O medo de falar em público para mil pessoas", "O medo de voar (para viajar pelo mundo inteiro sem ansiedade)", "O medo de insetos (para não ter de fugir a gritar)"] },
    { id: "c_sf_o_12", texto: "Se pudesse ser um 'Expert' numa ciência obscura, seria:", opcoes: ["Astrologia avançada e ler as cartas a toda a gente", "Arqueologia, para ir descobrir o túmulo de Cleópatra", "Criptografia, para decifrar códigos secretos do governo", "Mestre em fazer as pessoas acreditarem em mim (Lábia/Psicologia)"] },
    { id: "c_sf_o_13", texto: "Uma transformação no meu corpo que eu gostava de fazer por magia:", opcoes: ["Mudar a cor dos meus olhos consoante o humor", "Ter o cabelo sempre lavado, penteado e com grande aspeto", "Comer 5 pizzas e nunca engordar uma grama", "Não precisar de dormir para ter o dobro das horas no dia"] },
    { id: "c_sf_o_14", texto: "Um local abandonado que eu adorava explorar sem consequências:", opcoes: ["O Titanic (num submarino muito seguro, claro)", "Um castelo mal-assombrado na Escócia", "A Área 51 nos EUA", "As catacumbas secretas debaixo de Paris ou do Vaticano"] },
    { id: "c_sf_o_15", texto: "O projeto de DIY (bricolage) que sonho fazer:", opcoes: ["Comprar uma carrinha velha e transformar em autocaravana", "Construir uma casa de madeira numa árvore para mim", "Restaurar um carro clássico desde a carcaça", "Só montar um móvel do IKEA sem sobrar parafusos já era um sonho"] },
    { id: "c_sf_o_16", texto: "A minha aparição de sonho num programa de TV:", opcoes: ["Ir ao 'Preço Certo' dar um abraço ao Fernando Mendes", "Ir a um concurso de talentos e o júri chorar de emoção", "Ir a um reality show só para criar intriga e confusão", "Ir a um programa de culinária e envenenar acidentalmente o júri"] },
    { id: "c_sf_o_17", texto: "A invenção que eu queria ter criado:", opcoes: ["O Instagram ou o TikTok (e estar trilionário)", "O telemóvel (Smartphone)", "A Air Fryer (Fritadeira a Ar)", "A máquina de teletransporte"] },
    { id: "c_sf_o_18", texto: "O tipo de animal exótico que gostava de ter se fosse legal e domesticável:", opcoes: ["Um urso polar bebé que nunca crescesse", "Um tigre gigante para me proteger e eu montar", "Um macaco pequeno para andar no meu ombro", "Uma preguiça para dormir comigo a tarde toda"] },
    { id: "c_sf_o_19", texto: "O evento histórico em que eu gostava de estar presente como invisível:", opcoes: ["O afundamento do Titanic (só a ver os ricos a correr)", "A construção das Pirâmides do Egito (para ver quem fez aquilo)", "O momento em que os dinossauros foram extintos", "O concerto dos Queen no Live Aid em 1985"] },
    { id: "c_sf_o_20", texto: "Para mim, o 'Paraíso' depois da morte seria:", opcoes: ["Um buffet infinito de comida onde não se engorda", "Uma biblioteca gigante com todos os livros do universo", "Uma nuvem super fofa onde posso dormir para sempre", "Uma sala de cinema onde posso ver a vida das pessoas que deixei na Terra"] }
  ]
};
