import { PerguntaClassica } from "@/types/catalogo";

export const classico_supersticoes_crencas: Record<string, PerguntaClassica[]> = {
  "sub_20_0": [ // Astrologia e Signos
    { id: "c_sc_a_01", texto: "Qual a minha relação com a Astrologia e o meu Signo?", opcoes: ["Sei o meu Sol, Lua e Ascendente de cor", "Leio o horóscopo só a rir-me na revista", "Julgo ativamente as pessoas com base no signo delas", "Não acredito em nada disso, achas que os astros querem saber de mim?"] },
    { id: "c_sc_a_02", texto: "A culpa de eu ser uma pessoa difícil é:", opcoes: ["Claramente do meu signo (só podia ser)", "Dos meus traumas de infância", "De Mercúrio que está retrógrado outra vez", "Minha, eu assumo total responsabilidade"] },
    { id: "c_sc_a_03", texto: "O que acho de compatibilidade amorosa por signos?", opcoes: ["Se o signo não bater certo, nem vou ao primeiro date", "Acho uma piada, mas não levo a sério", "Conheço pessoas de todos os signos que são insuportáveis igual", "Só uso isso como tema de conversa para quebrar o gelo"] },
    { id: "c_sc_a_04", texto: "Quando começa a época de eclipses ou Mercúrio Retrógrado:", opcoes: ["Ponho cristais a carregar à luz da lua e protejo-me", "Culpo o mercúrio retrógrado por qualquer coisa que corra mal", "Nem sei quando isso acontece", "Acho uma superstição engraçada para partilhar memes"] },
    { id: "c_sc_a_05", texto: "Pedir a carta astral a alguém:", opcoes: ["É a primeira coisa que peço a um/a crush", "Nunca pedi isso na vida, soa a seita", "Se a pessoa alinhar, até acho divertido ver o mapa", "Nem sei o que é uma carta astral"] },
    { id: "c_sc_a_06", texto: "Qual a fama do meu signo em específico?", opcoes: ["Dizem que sou dramático/a, instável ou mandão/ona", "Dizem que sou frio/a, teimoso/a ou forreta", "Dizem que sou confuso/a, mandrião/ona ou sonhador/a", "O meu signo é pacífico, ninguém diz mal dele"] },
    { id: "c_sc_a_07", texto: "Acreditar em pedras, cristais e energias:", opcoes: ["Tenho a casa cheia de quartzo, ametistas e pedras da sorte", "Acho bonitas para decorar a estante", "Limpam energias? Só se for com lixívia", "Não ligo nenhuma, mas respeito quem gosta"] },
    { id: "c_sc_a_08", texto: "Se alguém me diz 'O teu signo não tem nada a ver contigo':", opcoes: ["Fico ofendido/a e começo a debitar as minhas características astrológicas", "Concordo, eu próprio/a acho que fui trocado na maternidade astrológica", "Dou de ombros, pois claro que não tem", "Digo que é do meu ascendente"] },
    { id: "c_sc_a_09", texto: "Ler o horóscopo na rádio ou na internet:", opcoes: ["Ouço sempre de manhã com atenção divina", "Rio-me porque diz sempre coisas genéricas tipo 'vais ter surpresas no amor'", "Só leio o dos meus amigos para ir gozar com eles", "Ignoro completamente"] },
    { id: "c_sc_a_10", texto: "O que acho das pessoas que culpam os signos por tudo?", opcoes: ["Apoio a 100%, a culpa é mesmo dos astros", "Acho piada para meme, mas na vida real é exagero", "Tenho vontade de revirar os olhos até ao céu", "Acho que é falta de assumir responsabilidade pelos atos"] },
    { id: "c_sc_a_11", texto: "Saber o signo dos meus familiares e amigos de cor:", opcoes: ["Sei de cor o de todas as pessoas com quem me dou", "Sei o do meu parceiro/a e mais nenhum", "Esqueço-me sempre e tenho de ir ao telemóvel ver", "Não faço a mínima ideia"] },
    { id: "c_sc_a_12", texto: "Fazer previsões para o novo ano (Astrologia anual):", opcoes: ["Compro o livro de previsões do ano para ver o que me espera", "Leio por curiosidade no fim de ano", "Sei que vai ser igual: trabalhar e pagar contas", "Acho puro marketing de adivinhos"] },
    { id: "c_sc_a_13", texto: "O meu ascendente no mapa astral:", opcoes: ["Salva-me de ser odiado/a pelo meu signo principal", "Nem sei bem o que isso significa na prática", "Muda a minha personalidade toda, segundo o Google", "Acho que inventaram essa palavra só para complicar"] },
    { id: "c_sc_a_14", texto: "Acreditar em vidas passadas ou reencarnação:", opcoes: ["Sim, já devo ter sido Cleópatra ou um pirata famoso", "Acho uma teoria fascinante e reconfortante", "Quando morrermos, apagamos a luz e acabou", "Tenho a certeza que fui uma preguiça numa vida passada"] },
    { id: "c_sc_a_15", texto: "Consultar tarô, cartas ou tarólogos:", opcoes: ["Já fui a consultas de tarô e assustei-me com certas verdades", "Acho um espetáculo de feira, mas divertido", "Nunca fui, tenho medo que me digam que vou ter azar", "É tudo uma vigarice para sacar dinheiro aos incautos"] },
    { id: "c_sc_a_16", texto: "Quando o horóscopo diz 'Evite tomar decisões financeiras hoje':", opcoes: ["Fico em casa sem gastar um cêntimo por precaução", "Ignoro completamente e vou às compras", "Nem sabia que o horóscopo dizia isso", "Acho útil, mais vale prevenir"] },
    { id: "c_sc_a_17", texto: "O elemento do meu signo (Fogo, Terra, Ar ou Água):", opcoes: ["Fogo/Água: sou super intenso/a e emocional", "Terra/Ar: sou prático/a e mental", "Nem sei qual é o meu elemento", "Sei o elemento mas não me rejo por isso"] },
    { id: "c_sc_a_18", texto: "Conhecer alguém novo e saber logo o signo da pessoa:", opcoes: ["Muda logo a minha forma de interagir com ela", "Guardo a info na gaveta mental para teste futuro", "Acho irrelevante, conheço a pessoa pelos atos", "Esqueço-me do signo 2 segundos depois"] },
    { id: "c_sc_a_19", texto: "O que acho dos compatibilidades de signos nos locais de trabalho:", opcoes: ["Explicaria perfeitamente porque é que o meu chefe é insuportável", "Invenção total para desculpar mau ambiente", "Até podia ser engraçado testar", "Ridículo, no trabalho só conta a competência"] },
    { id: "c_sc_a_20", texto: "Em suma, qual a importância da Astrologia na minha vida?", opcoes: ["Guia as minhas decisões diárias", "É um passatempo divertido de internet", "Quase zero, não ligo nenhuma", "Zero absoluto"] }
  ],
  "sub_20_1": [ // Sorte e Azar
    { id: "c_sc_s_01", texto: "A minha reação se um gato preto se cruzar no meu caminho:", opcoes: ["Mudo de passeio ou recuo para o azar não pegar em mim", "Acho lindo e tento fazer-lhe festas (gatos pretos são fofos)", "Penso 'olha, um gato' e sigo em frente", "Fico a pensar nisso o dia todo com medo"] },
    { id: "c_sc_s_02", texto: "Passar por debaixo de um escadote na rua:", opcoes: ["Jamais! Faço um desvio largo de 5 metros", "Passo por baixo na boa, superstições é para tótós", "Só passo se não houver mesmo alternativa", "Tenho medo que me caiga algo em cima, isso sim é azar real"] },
    { id: "c_sc_s_03", texto: "Partir um espelho em casa:", opcoes: ["Pânico! São 7 anos de azar garantidos", "Limpo os vidros com cuidado e choro pelos € do espelho", "Azar é ter de limpar os vidros todos do chão", "Nem ligo, superstição antiga de avós"] },
    { id: "c_sc_s_04", texto: "Abrir um guarda-chuva dentro de casa:", opcoes: ["Nunca o faço, traz o pior azar financeiro ao lar", "Abro para secar se estiver encharcado, sem stress", "Minha mãe dava-me com a vassoura se eu fizesse isso", "Acho que a única coisa que acontece é molhar o chão"] },
    { id: "c_sc_s_05", texto: "Colocar o pão com a 'crosta para cima' vs 'para baixo' na mesa:", opcoes: ["Para baixo dá grande azar à casa, viro sempre", "Se cair com a manteiga para o chão, choro", "Para cima ou para baixo, vai para a barriga igual", "A minha avó corrigia-me sempre se virasse o pão ao contrário"] },
    { id: "c_sc_s_06", texto: "Derramar sal na mesa de jantar:", opcoes: ["Tiro um bocadinho com os dedos e atiro por cima do ombro esquerdo", "Limpou-se com o guardanapo e acabou", "Fico com tiques nervosos à espera de uma discussão", "Acho que o sal desperdiçado é o verdadeiro azar"] },
    { id: "c_sc_s_07", texto: "Ter um trevo de quatro folhas ou olho turco (azar):", opcoes: ["Acredito que o olho turco protege contra inveja", "Acho bonitos como acessórios e pulseiras", "Guardo trevos secos nos livros", "Isso é crença popular sem lógica nenhuma"] },
    { id: "c_sc_s_08", texto: "Dizer a frase 'Até agora tem corrido tudo bem' antes de algo importante:", opcoes: ["Bato logo três vezes na madeira ('toc toc toc')", "Digo na boa, não acredito que as palavras atraiam azar", "Fico a pensar 'pronto, estraguei tudo agora'", "Penso 'azar o meu se correr mal'"] },
    { id: "c_sc_s_09", texto: "O número 13 e a Sexta-feira 13:", opcoes: ["Fico em casa escondido/a nesse dia", "Adoro a data, até acho que me traz sorte", "É um dia igual aos outros todos", "Sou indiferente, nem sei que dia é a Sexta-feira 13"] },
    { id: "c_sc_s_10", texto: "Encontrar uma moeda no chão (com a coroa para cima vs para baixo):", opcoes: ["Se estiver com a cara para cima, apanho e dá sorte!", "Apanho sempre, dinheiro é dinheiro (seja qual for o lado)", "Tenho nojo de apanhar moedas do chão da rua", "Deixo estar para dar sorte a outra pessoa"] },
    { id: "c_sc_s_11", texto: "Acreditar no 'Mau Olhado' ou inveja alheia:", opcoes: ["Sim, protejo-me sempre com figas e reza forte", "A inveja existe, mas não acredito em bruxarias", "As pessoas preocupam-se demais com a sua própria vida para terem inveja", "O meu escudo contra o mau olhado é ignorância pura"] },
    { id: "c_sc_s_12", texto: "Usar vermelho na Passagem de Ano (para o amor/sorte):", opcoes: ["Roupa interior vermelha obrigatória todos os anos", "Uso se calhar por acaso, não sigo regras", "Acho uma piada engraçada, mas visto o que me apetece", "Nem sei que cor usei no ano passado"] },
    { id: "c_sc_s_13", texto: "Deixar a carteira ou a mala no chão:", opcoes: ["'Dinheiro no chão é dinheiro a ir embora!', ponho logo em cima da mesa", "Atiro a mala para o chão da sala sem problemas", "Depende de quão sujo está o chão", "Nunca pensei que isso pudesse ser azar financeiro"] },
    { id: "c_sc_s_14", texto: "O que acho de amuletos, figas e ferraduras na porta de casa:", opcoes: ["Tenho uma ferradura virada para cima na entrada", "Acho uma decoração rústica engraçada", "Parece a casa de uma bruxa medieval", "Só acredito no meu próprio esforço para ter sorte"] },
    { id: "c_sc_s_15", texto: "Se cruzar os talheres (faca e garfo) no prato ao acabar de comer:", opcoes: ["Significa que gostei da comida / descanso, mas faço sem pensar", "Deixo de qualquer maneira, o empregado arruma", "A minha mãe dizia que cruzados dava azar à família", "Nem reparo na posição em que deixo os talheres"] },
    { id: "c_sc_s_16", texto: "O conceito de Karma ('Tudo o que fazes volta para ti'):", opcoes: ["Acredito piamente no Karma, a vida cobra tudo", "Gostava que fosse verdade, mas vejo maus a triunfar todos os dias", "O Karma sou eu quando decido vingar-me", "Acho uma bela filosofia de vida"] },
    { id: "c_sc_s_17", texto: "Se uma borboleta nocturna (traça preta gigante) entra em casa:", opcoes: ["Alguém vai falecer ou há visita de luto (crença antiga)", "Abro a janela e enxoto o bicho com uma vassoura", "Fico assustado/a com o tamanho do monstro voador", "Acho que é só um inseto perdido à luz da lâmpada"] },
    { id: "c_sc_s_18", texto: "Quando sinto um arrepio súbito sem razão:", opcoes: ["'Estão a falar de mim' (ou alguém passou pela minha tumba)", "Estou com frio, ligo o aquecedor", "Tenho febre a chegar", "Músculos a contrair, nada de paranormal"] },
    { id: "c_sc_s_19", texto: "A minha tática pessoal para atrair sorte em exames ou entrevistas:", opcoes: ["Uso a mesma peça de roupa 'da sorte' (sem lavar)", "Estudo muito (a verdadeira sorte dá trabalho)", "Levo um objeto milagroso no bolso (um boneco, moeda)", "Rezo a todos os santos e cruzo os dedos"] },
    { id: "c_sc_s_20", texto: "Em suma, considero-me uma pessoa sortuda ou azaurada?", opcoes: ["Super sortudo/a, a vida sorri-me sempre", "Azarado/a nos pequenos detalhes, sortudo/a no essencial", "A sorte constrói-se, a superstição é palha", "Nascido/a para o azar, se chover garoa caem-me pedras"] }
  ]
};
