import { PerguntaClassica } from "@/types/catalogo";

export const classico_tecnologia: Record<string, PerguntaClassica[]> = {
  "sub_9_0": [ // Vício em Redes Sociais
    { id: "c_tec_v_01", texto: "Qual é a primeira aplicação que abro quando acordo?", opcoes: ["Instagram, para ver quem viu os meus stories", "WhatsApp, a ver se alguém se lembrou de mim", "TikTok, e perco logo 30 minutos", "O email do trabalho (infelizmente)"] },
    { id: "c_tec_v_02", texto: "Qual a minha atitude a postar Stories no Instagram?", opcoes: ["Posto de tudo, desde a torrada ao pôr do sol", "Só meto coisas estéticas para parecer rico/a", "Partilho só memes e piadas secas", "Nunca meto nada, sou um fantasma digital"] },
    { id: "c_tec_v_03", texto: "Quando envio um reel/TikTok a um amigo e ele não reage:", opcoes: ["Fico genuinamente ofendido/a", "Mando mais 5 a ver se ele reage a algum", "Cobro-lhe presencialmente: 'não viste o vídeo?'", "Cago nisso, eu mando vídeos para o ar"] },
    { id: "c_tec_v_04", texto: "Como lido com a foto de perfil nas redes?", opcoes: ["Mudo todas as semanas consoante o 'mood'", "Tenho a mesma foto desde 2015", "Tiro 200 fotos, escolho uma, meto filtro e rezo", "Tenho uma foto do meu cão/gato ou paisagem"] },
    { id: "c_tec_v_05", texto: "O meu nível de 'Stalker' profissional é:", opcoes: ["FBI: descubro o NIF da pessoa em 5 minutos", "Tento cuscar mas dou um 'Like' sem querer numa foto de 2012", "Só pesquiso nomes quando me falam da pessoa", "Zero, não quero saber da vida de ninguém"] },
    { id: "c_tec_v_06", texto: "Num restaurante chique, antes de começar a comer:", opcoes: ["Obrigo toda a gente a esperar para eu tirar a foto perfeita", "Tiro uma foto rápida às escondidas", "Odeio quem tira fotos, começo logo a comer", "Posto a localização para fazer inveja"] },
    { id: "c_tec_v_07", texto: "Em relação ao LinkedIn:", opcoes: ["Sou o CEO do LinkedIn, faço posts inspiracionais semanais", "Só lá vou atualizar o currículo quando quero fugir do meu chefe", "Tenho conta mas não faço ideia de como se usa", "Acho a rede mais falsa da internet"] },
    { id: "c_tec_v_08", texto: "Quantas abas (tabs) tenho abertas no telemóvel neste momento?", opcoes: ["Só uma ou duas, super organizado", "Umas 10 a 20", "Chegou ao limite, já só aparece o símbolo do infinito", "Fecho-as todas compulsivamente a cada 5 minutos"] },
    { id: "c_tec_v_09", texto: "A usar o WhatsApp, a minha pior mania é:", opcoes: ["Ler as mensagens e responder só mentalmente", "Desativar os 'vistos azuis' para poder ignorar a malta em paz", "Estar online e não responder a ninguém", "Só mandar áudios aos gritos"] },
    { id: "c_tec_v_10", texto: "Quando a minha internet de casa vai abaixo:", opcoes: ["Ligo logo para a operadora a fazer peixeirada", "Entro em pânico e gasto os dados móveis todos", "Vou ler um livro ou fazer algo produtivo (raro)", "Fico a olhar para o router à espera do milagre"] },
    { id: "c_tec_v_11", texto: "A dar 'Unfollow' ou 'Block' a alguém:", opcoes: ["Faço-o logo na hora, não tenho cá paciência", "Faço 'Mute' para a pessoa não saber que a detesto", "Nunca dou unfollow para poder continuar a falar mal dela", "Faço e depois crio uma conta falsa para cuscar na mesma"] },
    { id: "c_tec_v_12", texto: "A minha capacidade de não pegar no telemóvel num jantar:", opcoes: ["O telemóvel fica no bolso a noite toda", "Fica em cima da mesa virado para baixo", "Passo o jantar a responder a mensagens", "Proponho o jogo do 'quem pegar no telemóvel paga a conta'"] },
    { id: "c_tec_v_13", texto: "Sobre fazer vídeos no TikTok a dançar:", opcoes: ["Já fiz e apaguei por vergonha alheia", "Faço todos os trends e sei as danças de cor", "Odeio e julgo ativamente quem faz", "Faço mas deixo só nos 'Rascunhos'"] },
    { id: "c_tec_v_14", texto: "Como lido com publicidade e influencers?", opcoes: ["Compro tudo o que me enfiam à frente com cupões", "Faço skip (passar à frente) na velocidade da luz", "Fico a julgar os produtos nos comentários", "Adoro ver 'unboxings' mesmo não tendo dinheiro para comprar"] },
    { id: "c_tec_v_15", texto: "O que me acontece quando entro no TikTok/Reels?", opcoes: ["Vejo 5 minutos e saio facilmente", "Entro num buraco negro temporal e perco 3 horas da minha vida", "Mando 20 seguidos para o mesmo amigo", "Apanho dores de cabeça com tantos vídeos"] },
    { id: "c_tec_v_16", texto: "Em relação ao grupo de família no WhatsApp:", opcoes: ["Meto lá as fotos todas dos jantares", "Tenho o grupo silenciado para sempre", "Só mando mensagens nos anos e Natal", "Sou o familiar que manda 'Bom dia' com imagens com purpurinas"] },
    { id: "c_tec_v_17", texto: "Quando uma pessoa que mal conheço me pede para seguir no Insta privado:", opcoes: ["Aceito logo, quanto mais seguidores melhor", "Deixo o pedido pendente durante 6 meses", "Rejeito sem piedade, é SÓ para amigos", "Aceito e sigo de volta por educação"] },
    { id: "c_tec_v_18", texto: "O meu algoritmo do YouTube/Insta recomenda-me maioritariamente:", opcoes: ["Vídeos de gatinhos e cães fofos", "Receitas de comida que nunca vou cozinhar", "Teorias da conspiração ou true crime", "Fofoca, dramas e barracos"] },
    { id: "c_tec_v_19", texto: "No Twitter (X), eu sou o tipo de pessoa que:", opcoes: ["Apenas leio para ver de quem estão a falar mal hoje", "Escrevo desabafos e uso aquilo como diário deprimido", "Não uso, já passei dessa fase", "Entro em discussões com pessoas anónimas"] },
    { id: "c_tec_v_20", texto: "Se as redes sociais acabassem amanhã:", opcoes: ["Enlouquecia, a minha vida não faz sentido", "Ficava chateado/a uma semanita e depois passava", "Era a melhor coisa que podia acontecer à humanidade", "Passava a mandar cartas pelo correio"] }
  ],
  "sub_9_1": [ // Gadgets e Ecrãs
    { id: "c_tec_g_01", texto: "Quando a bateria do meu telemóvel chega aos 10%:", opcoes: ["Entro em pânico e corro para um carregador", "Meto em modo de poupança e tento aguentar 5 horas", "Não me afeta, deixo morrer em paz", "Ando sempre com 3 powerbanks atrás de mim"] },
    { id: "c_tec_g_02", texto: "Qual é o estado do ecrã do meu telemóvel agora?", opcoes: ["Impecável, com película de vidro nova", "Cheio de dedadas e marcas de gordura", "Estalado num dos cantos", "Completamente destruído, faltam-lhe pedaços de vidro"] },
    { id: "c_tec_g_03", texto: "Como trato do telemóvel quando ele cai ao chão?", opcoes: ["Nem olho, deixo-o de cara virada para baixo com medo", "Apanho-o com o pé à la ninja", "Começo a chorar porque foi caríssimo", "Cai 50 vezes por dia, já estou imune"] },
    { id: "c_tec_g_04", texto: "Em relação a comprar tecnologia (Apple vs Android):", opcoes: ["Apple forever, mesmo que tenha de vender um rim", "Android sempre, Apple é só para quem quer status", "Compro o que for mais barato na Worten", "Mudo de marca todos os anos só para chatear"] },
    { id: "c_tec_g_05", texto: "A minha gaveta dos cabos lá em casa:", opcoes: ["Está super organizada, cada cabo tem etiqueta", "É um emaranhado de fios que dá para fazer pesca", "Não sei onde ponho cabos, ando sempre a roubar aos outros", "Ainda guardo carregadores de Nokias de 2004"] },
    { id: "c_tec_g_06", texto: "O que acho dos 'Smartwatches' (relógios inteligentes)?", opcoes: ["Não vivo sem ele, conto todos os passos e calorias", "Comprei um, usei uma semana e agora está na gaveta", "Acho super azeiteiro, prefiro relógios clássicos", "Só o uso para ver as mensagens sem tirar o telemóvel do bolso"] },
    { id: "c_tec_g_07", texto: "Na cama, antes de adormecer:", opcoes: ["O telemóvel cai-me na cara de sono", "Deixo-o a carregar bem longe de mim", "Fico a ver vídeos com a luz no mínimo para não encandear", "Oiço ASMR ou ruído branco (chuva) para dormir"] },
    { id: "c_tec_g_08", texto: "A minha televisão da sala:", opcoes: ["É a maior que cabia na parede, parece o cinema", "Quase nunca a ligo, vejo tudo no portátil ou tablet", "Está sempre ligada mesmo quando não estou a ver", "Só serve para jogar consola"] },
    { id: "c_tec_g_09", texto: "Qual a minha relação com a Alexa / Siri / Google Assistant?", opcoes: ["Falo com ela como se fosse humana e dou os bons dias", "Uso só para meter alarmes e timers para a massa", "Tenho pânico de ter o microfone ligado a ouvir as minhas conversas", "Passo o tempo a insultá-la quando não me percebe"] },
    { id: "c_tec_g_10", texto: "Se eu perder um fone Bluetooth (AirPod, etc):", opcoes: ["Revisto a casa toda até o encontrar a chorar", "Compro outros novos no próprio dia", "Ando 3 meses a usar só o fone que sobrou", "Por isso é que uso fones de fio, nunca se perdem"] },
    { id: "c_tec_g_11", texto: "Atualizações de software do telemóvel:", opcoes: ["Faço no primeiro segundo que aparecem", "Ignoro o aviso diário durante 8 meses", "Só atualizo quando o telemóvel encrava", "Tenho medo de atualizar e ele ficar mais lento"] },
    { id: "c_tec_g_12", texto: "O que faço quando um aparelho eletrónico deixa de funcionar?", opcoes: ["Dou-lhe duas pancadas valentes para ver se arranca", "Sigo o clássico 'Desliga e volta a ligar'", "Vou para o Youtube ver tutoriais indianos de como arranjar", "Choro e entrego na loja de reparações do shopping"] },
    { id: "c_tec_g_13", texto: "Como é a minha área de trabalho no Computador (Desktop)?", opcoes: ["Lindo e limpo, só tem a Reciclagem", "Cheio de pastas a dizer 'Nova Pasta (4)' e 'Coisas'", "O ecrã está forrado de atalhos e documentos à balda", "Tenho um fundo de ecrã 'aesthetic' e escondo os ícones"] },
    { id: "c_tec_g_14", texto: "Sobre limpar o pó a teclados e ecrãs:", opcoes: ["Tenho panos de microfibras hiper limpos", "Limpo com a manga da camisola ou cuspe", "O meu ecrã tem marcas de tosse de 2021", "Sopro e se o pó não sair, fica."] },
    { id: "c_tec_g_15", texto: "Para ler notícias, eu uso:", opcoes: ["Apps no telemóvel e notificações pop-up", "Ainda compro jornal de papel ao fim de semana", "Vejo os cabeçalhos no Twitter e não leio a notícia toda", "O que são notícias? Vivo debaixo de uma pedra"] },
    { id: "c_tec_g_16", texto: "Uso capa de proteção no telemóvel?", opcoes: ["Uso daquelas armaduras de borracha que aguentam tiros", "Uma capinha transparente super fina que depois fica amarela", "Zero capa, ando no limite do perigo", "Tenho a capa cheia de cartões multibanco e notas"] },
    { id: "c_tec_g_17", texto: "A minha relação com auscultadores em público:", opcoes: ["Ando sempre com fones, até no supermercado, para ignorar as pessoas", "Só meto quando vou no comboio/metro", "Tiro um dos fones para mostrar que estou acessível", "Esqueço-me sempre deles em casa"] },
    { id: "c_tec_g_18", texto: "O que me irrita mais num gadget?", opcoes: ["Ser lento e demorar 5 minutos a abrir uma app", "A bateria durar menos de 2 horas", "Fazer atualizações automáticas que mudam o design todo", "Pedir-me espaço na cloud constantemente"] },
    { id: "c_tec_g_19", texto: "A comprar televisão/portátil novo:", opcoes: ["Vejo 50 reviews no Youtube antes de escolher", "Vou à loja e trago o que o funcionário me impinge", "Compro o mais barato e que dê para ver Netflix", "Escolho pela cor e pelo quão fininho é"] },
    { id: "c_tec_g_20", texto: "Quando não sei alguma coisa no dia a dia:", opcoes: ["Pesquiso no Google imediatamente", "Pergunto ao ChatGPT em modo conversação", "Deixo a dúvida no ar e sigo com a minha vida", "Invento uma resposta com bué confiança"] }
  ]
};
