import { PerguntaClassica } from "@/types/catalogo";

export const classico_televisao_reality_shows: Record<string, PerguntaClassica[]> = {
  "sub_28_0": [ // Vício em Reality Shows
    { id: "c_tv_v_01", texto: "Qual seria o meu papel dentro de um Reality Show (ex: Big Brother)?", opcoes: ["O estratega manipulador que cria intrigas nas sombras", "O que faz os choradinhos todos no confessionário", "A 'planta' da casa que só come e dorme", "O protagonista barranqueiro que discute por causa da limpeza"] },
    { id: "c_tv_v_02", texto: "Se eu participasse no MasterChef:", opcoes: ["Ganhava aquilo, o meu tempero é imbatível", "Chorava na primeira vez que o chef gritasse comigo", "Tentava fazer alta gastronomia e servia algo crú", "Era expulso no primeiro dia por cortar o dedo"] },
    { id: "c_tv_v_03", texto: "No programa 'Casados à Primeira Vista' eu:", opcoes: ["Dizia o 'Sim' cego pela aventura e confiava nos especialistas", "Dizia 'Não' no altar e fugia a correr", "Passava a lua-de-mel a criticar o/a parceiro/a em off", "Aproveitava a viagem de borla e depois pedia o divórcio"] },
    { id: "c_tv_v_04", texto: "Como reajo às fofocas de Reality Shows portugueses?", opcoes: ["Vejo os extras todos e sei os nomes dos concorrentes de cor", "Finjo que não vejo, mas no fundo sei os barracos todos", "Acho um lixo televisivo e mudo de canal imediatamente", "Só vejo quando dá peixeirada a sério nas galas de Domingo"] },
    { id: "c_tv_v_05", texto: "No reality 'Survivor' (Sobreviventes numa ilha):", opcoes: ["Seria o líder tribal a construir cabanas e pescar", "Desistia ao fim de 2 horas porque tinha fome", "Fazia alianças falsas e esfaqueava todos pelas costas", "Trazia bolachas escondidas nos bolsos da roupa"] },
    { id: "c_tv_v_06", texto: "Sobre votar em concorrentes de Reality Shows:", opcoes: ["Gasto o meu próprio saldo do telemóvel a expulsar quem odeio", "Nunca votei, acho ridículo gastar dinheiro nisso", "Voto apenas com os 5 votos grátis da App", "Digo a toda a gente para votar, mas eu não gasto um tusto"] },
    { id: "c_tv_v_07", texto: "A assistir ao Hell's Kitchen (Pesadelo na Cozinha):", opcoes: ["Acho o Gordon Ramsay o maior ídolo", "Sinto ansiedade e começo a suar com os gritos dele", "Acho que a comida tem bom aspeto mesmo quando ele diz que é lixo", "Fico a pensar que eu fazia melhor que os concorrentes"] },
    { id: "c_tv_v_08", texto: "Qual a minha atitude a ver realities de encontros (Temptation Island, Too Hot to Handle)?", opcoes: ["Fico indignado/a com as traições ('Que falta de respeito!')", "Adoro a fofoca e torço pelo caos e destruição de casais", "Não percebo porque é que as pessoas são tão dramáticas", "Vejo porque os concorrentes são todos lindíssimos"] },
    { id: "c_tv_v_09", texto: "Na 'Quinta das Celebridades' ou programas com vacas e estrume:", opcoes: ["Mergulhava no lixo e lavava os porcos sem nojo", "Passava o dia a reclamar do cheiro e a vomitar", "Ficava só a cozinhar para evitar ir às limpezas pesadas", "Tentava fazer amizade com a vaca"] },
    { id: "c_tv_v_10", texto: "Se tivesse de esconder um Segredo na 'Casa dos Segredos', qual seria o nível?", opcoes: ["'Sou Herdeiro de um Rei' (muito chic)", "'Tenho pânico de pombos' (o mais estúpido possível)", "'Já tive um caso com outro concorrente'", "'Ressono de olhos abertos'"] },
    { id: "c_tv_v_11", texto: "Sobre reality shows de talentos (Ídolos / Got Talent):", opcoes: ["Choro sempre nas audições com histórias tristes", "Só vejo a fase dos cromos (os cromos que cantam mal)", "Acho que já ganha tudo por pena e não por talento", "Desligo a TV na fase das galas ao vivo, é secante"] },
    { id: "c_tv_v_12", texto: "Qual é a minha desculpa para ver programas 'Trash TV'?", opcoes: ["'É para desligar o cérebro depois de um dia de trabalho'", "'Estou só a ver ironicamente com os meus amigos'", "'Eu só vejo porque estava a dar no canal'", "Não uso desculpas, assumo com orgulho!"] },
    { id: "c_tv_v_13", texto: "No Shark Tank (Lago dos Tubarões):", opcoes: ["Teria uma ideia genial que os deixava a implorar para investir", "Bloqueava a meio do 'Pitch' e esquecia os meus próprios números", "Chorava se o João Macedo Silva dissesse que a minha ideia era lixo", "Fazia o acordo e depois roubava-lhes o dinheiro"] },
    { id: "c_tv_v_14", texto: "Se estivesse preso numa casa com pessoas desconhecidas 3 meses:", opcoes: ["Criava grandes amizades para a vida", "Tinha um esgotamento nervoso por falta de telemóvel e silêncio", "Andava à porrada com alguém na primeira semana", "Dormia 18 horas por dia para passar o tempo mais rápido"] },
    { id: "c_tv_v_15", texto: "A acompanhar a casa 24 horas no TVI Reality:", opcoes: ["Tenho a TV ligada naquilo enquanto limpo a casa/trabalho", "Só vou espreitar quando o Twitter diz que há barraco", "Acho super assustador haver câmaras na casa de banho", "Prefiro as telenovelas, os guiões são melhores"] },
    { id: "c_tv_v_16", texto: "Num reality de moda/drag (RuPaul's Drag Race / Project Runway):", opcoes: ["Servia visuais icónicos e ganhava os desafios todos", "Fazía um vestido de sacos do lixo e fita-cola que se desfazia na passadeira", "A minha maquilhagem parecia a do Joker", "Ia ser o vilão sarcástico que crítica a roupa dos outros"] },
    { id: "c_tv_v_17", texto: "Quando os concorrentes formam casais dentro da casa:", opcoes: ["Crio contas de fã-clube (Shippo-os loucamente)", "Acho sempre que é estratégia para chegarem à final", "Tenho nojo de os ver debaixo dos lençóis", "Choro quando um deles é expulso"] },
    { id: "c_tv_v_18", texto: "O que acho da Cristina Ferreira / Cláudio Ramos a apresentar galas?", opcoes: ["Adoro a energia e a gritaria, são icónicos!", "Metem-me os nervos em franja com tanto berreiro", "Só vejo para reparar nas roupas estapafúrdias", "Tiro o som da TV e vejo só as imagens"] },
    { id: "c_tv_v_19", texto: "Se houvesse um reality show da minha família/amigos (tipo Kardashians):", opcoes: ["Dava mais audiência que o da Kim Kardashian, somos uns loucos", "Durava um episódio, somos super aborrecidos a ver TV", "Dava origens a queixas na polícia de tanta ofensa", "Ficávamos ricos num instante com os nossos bordões"] },
    { id: "c_tv_v_20", texto: "Qual a minha postura perante os ex-concorrentes de reality shows?", opcoes: ["Sigo-os a todos no Instagram para ver as presenças em discotecas", "Esqueço a existência deles passados 2 meses", "Fico com inveja das parcerias e viagens grátis que ganham", "Comento 'vai trabalhar' nas fotos deles"] }
  ],
  "sub_28_1": [ // Novelas Antigas
    { id: "c_tv_n_01", texto: "Qual é a telenovela clássica que marcou a minha vida?", opcoes: ["Morangos com Açúcar (Morangomania forever!)", "Ninguém como Tu ou Inspetor Max", "Laços de Sangue (A fúria da Diana!)", "Não via novelas portuguesas, só Rebelde Way e novelas da Globo"] },
    { id: "c_tv_n_02", texto: "A minha reação à morte do Dino (Inspetor Max):", opcoes: ["Chorei baba e ranho, foi um trauma de infância", "Fiquei em choque, mas o Max é que importa", "Nunca vi Inspetor Max, vivia numa gruta", "Achei o acidente super mal feito com efeitos especiais de 1 euro"] },
    { id: "c_tv_n_03", texto: "Qual o meu nível de fanatismo por 'Morangos com Açúcar'?", opcoes: ["Tinha a coleção de argolas, cartas, cadernos e cd's todos", "Via só a série de Verão por causa da praia e do Bar do Fred", "Era a minha religião, cantava os D'zrt no banho", "Odeava os Morangos, via o 'Floribella'"] },
    { id: "c_tv_n_04", texto: "Quando a minha avó / mãe monopoliza a TV para ver a novela da noite:", opcoes: ["Sento-me a ver com elas e acabo mega investido/a na história", "Fujo para o quarto com o telemóvel para não ouvir as peixeiradas", "Faço imenso barulho para as irritar", "Pergunto 'Mas afinal quem é o pai deste gajo?' a cada 5 minutos"] },
    { id: "c_tv_n_05", texto: "O que acho dos clichés das novelas (acidentes de carro, amnésia, gémeos maus)?", opcoes: ["Amo! Quanto mais drama surreal, melhor", "Reviro os olhos, a criatividade dos argumentistas é nula", "Adoro adivinhar o cliché antes de acontecer ('Ele vai perder a memória!')", "É o que prende o público, funciona sempre"] },
    { id: "c_tv_n_06", texto: "Na Floribella, o que eu achava dos ténis da sorte dela?", opcoes: ["Um ícone de moda, usei all stars rabiscados", "A coisa mais bimba de sempre", "Achava que era assim que se enganava os príncipes ricos", "Nunca percebi a moda da Floribella"] },
    { id: "c_tv_n_07", texto: "Quando uma novela tem uma vilã icónica (tipo Nazaré, Nazaré Tedesco, Carminha):", opcoes: ["Torço por ela! As vilãs são muito mais fixes que as boazinhas", "Odeio-a de morte e grito com a televisão", "Sigo a atriz no Instagram porque acho-a brilhante", "Espero pelo último episódio só para ver a queda dela das escadas"] },
    { id: "c_tv_n_08", texto: "Novelas brasileiras (Avenida Brasil, Chocolate com Pimenta):", opcoes: ["Avenida Brasil foi a maior obra cinematográfica da humanidade", "Têm um sotaque incrível e as bofetadas soam melhor", "Eram muito longas (300 episódios), eu perdia o fio à meada", "Prefiro as portuguesas, são mais realistas"] },
    { id: "c_tv_n_09", texto: "A banda sonora (música do genérico) das novelas antigas:", opcoes: ["Ainda hoje sei a letra da música da Gabriela ou dos Morangos", "Faço skip à intro porque demora 3 minutos", "Gosto mais da música de sofrimento de quando o casal se separa", "É sempre do Tony Carreira ou do Toy, não me surpreende"] },
    { id: "c_tv_n_10", texto: "O momento 'Avenida Brasil' (A Carminha a deitar a Rita na sanita):", opcoes: ["Vibrei! A melhor cena de vingança da TV", "Fiquei em choque, aquilo foi muito violento para as 21h", "Só vi esse clipe no YouTube e achei hilariante", "Não vejo a Globo, só as novelas da SIC das ovelhas e do campo"] },
    { id: "c_tv_n_11", texto: "Quando o casal principal de uma novela demora 200 episódios a dar um beijo:", opcoes: ["Fico irritado/a e digo 'Dá-lhe um beijo logo, caramba!'", "Acho super romântico a construção da tensão", "Acabo a shippar o/a protagonista com o/a melhor amigo/a que está lá sempre", "Desisto da novela ao episódio 50 por falta de ação"] },
    { id: "c_tv_n_12", texto: "O típico cenário da 'Herdade no Alentejo' nas novelas da SIC:", opcoes: ["Dá-me logo vontade de ir beber vinho e ver cavalos", "Acho super cansativo, é sempre a mesma história das vindimas e testamentos", "Gosto porque aparece sempre o clássico núcleo cómico do café da aldeia", "Gosto mais das novelas passadas no luxo de Cascais ou Lisboa"] },
    { id: "c_tv_n_13", texto: "Quando o cão/animal da novela morre ou foge:", opcoes: ["Choro mais do que se fosse uma pessoa humana da novela", "Acho que foi uma jogada barata para ganhar audiências", "Mudo de canal, não lido bem com o sofrimento animal nem na ficção", "Não me afeta muito, sei que é um cão treinado muito bem pago"] },
    { id: "c_tv_n_14", texto: "Em relação ao 'Inspetor Max', os crimes:", opcoes: ["O Max ladrava e o Jorge resolvia tudo na última sala do armazém abandonado", "Eram sempre super óbvios, o vilão era o ator mais famoso convidado", "Metiam-me medo quando eu era criança (alguns eram sombrios)", "Via só pelas sandes do Mendes e pelas calinadas do Inspetor Sérgio"] },
    { id: "c_tv_n_15", texto: "O que acho da moda de fazerem remakes / continuações de novelas clássicas?", opcoes: ["Odeio! Deixem as lendas em paz, nunca fica tão bom", "Vou ver o primeiro episódio só para criticar", "Amei o regresso dos Morangos, deu-me nostalgia", "Sou a favor, quero ver os atores velhos com rugas"] },
    { id: "c_tv_n_16", texto: "Quando há um final trágico para a vilã (cai de um precipício, fica louca):", opcoes: ["Acho sempre que ela sobreviveu e devia haver uma temporada 2", "Adoro quando ficam num hospício a rir para as paredes", "Sinto pena, as vilãs são sempre as que carregam a novela às costas", "Preferia que ela ficasse pobre a limpar o chão à boazinha"] },
    { id: "c_tv_n_17", texto: "Numa novela, eu serei sempre o fã de:", opcoes: ["Do 'Núcleo Cómico' (a malta pobre da tasca que bebe copos)", "Do núcleo jovem (os dramas da escola e do surf)", "Dos vilões ricos e das mansões de luxo", "Do triângulo amoroso principal cheio de sofrimento"] },
    { id: "c_tv_n_18", texto: "Qual a melhor frase de vilã que já ouviste?", opcoes: ["'És uma lontra, uma labrega!' (Nazaré Tedesco)", "'Eu sou a Carminha, tu és o lixo!'", "'Eu não sou louca, eu sou visionária!'", "Eu só digo palavrões, não me lembro dessas frases poéticas"] },
    { id: "c_tv_n_19", texto: "Se a minha vida fosse um episódio de Morangos com Açúcar:", opcoes: ["Dançava Pop e formava uma banda (D'zrt/Just Girls)", "Estava sempre de castigo na sala do Diretor", "Era o/a que andava a espalhar os boatos nos cacifos", "Passava a vida no Bar a pedir sumos de laranja de 5 euros"] },
    { id: "c_tv_n_20", texto: "Qual o pior cliché de final de novela?", opcoes: ["Casamento triplo no último episódio e congela a imagem de todos a sorrir", "O vilão morre a tentar matar os bons num armazém explosivo", "A mulher pobre descobre que é herdeira da fortuna do pai secreto", "Saltam 5 anos no tempo e têm 3 filhos de repente"] }
  ]
};
