import { PerguntaClassica } from "@/types/catalogo";

export const classico_trabalho_carreira: Record<string, PerguntaClassica[]> = {
  "sub_5_0": [ // Vida no Escritório
    { id: "c_tc_v_01", texto: "A minha pontualidade de manhã para chegar ao trabalho:", opcoes: ["Chego 10 mins mais cedo e sento-me a relaxar", "Chego no minuto exato a suar", "O meu clássico 'já estou no trânsito' (estou na cama)", "Ligo a dizer que furei um pneu"] },
    { id: "c_tc_v_02", texto: "Na máquina do café do escritório, eu sou quem:", opcoes: ["Toma 5 cafés e fica a tremer", "Fica a cuscar a vida dos colegas todos", "Rouba as cápsulas/açúcar dos outros", "Não bebe café, mas vai lá para não trabalhar"] },
    { id: "c_tc_v_03", texto: "Quando recebo um email longo e complexo de um cliente chato:", opcoes: ["Leio e respondo com calma e profissionalismo", "Ignoro durante 3 dias para ele se acalmar", "Reencaminho para o colega do lado com a nota 'trata disto'", "Respondo 'Ok, obrigado' para irritar"] },
    { id: "c_tc_v_04", texto: "Em relação a reuniões que podiam ser um email:", opcoes: ["Participo e falo imenso para parecer produtivo/a", "Desligo a câmara, meto no 'mudo' e vou lavar a loiça", "Suspiro tão alto que toda a gente ouve", "Aponto tudo e faço o relatório exemplar"] },
    { id: "c_tc_v_05", texto: "O meu estado de espírito à segunda-feira de manhã:", opcoes: ["Total negação, odeio o mundo e toda a gente", "Super motivado, pronto para esmagar objetivos!", "Um zombie à procura de cafeína", "Finjo que estou bem mas choro na casa de banho"] },
    { id: "c_tc_v_06", texto: "Sobre o teletrabalho (Home Office):", opcoes: ["Trabalho de pijama e não ligo a câmara", "Produzo o triplo do que no escritório", "Passo o dia no sofá e limpo a casa nas 'pausas'", "Odeio, sinto muita falta da fofoca do escritório"] },
    { id: "c_tc_v_07", texto: "A minha organização na secretária:", opcoes: ["Impecável, não há um papel fora do sítio", "Caos puro, chávenas com bolor e canetas sem tampa", "Cheia de bonecos, post-its e coisas fofas inúteis", "Não sei, não faço ideia de onde está o agrafador"] },
    { id: "c_tc_v_08", texto: "Na pausa para almoço com colegas:", opcoes: ["Falo de trabalho o tempo TODO", "Reclamo do chefe e do salário", "Sento-me longe a ver séries no telemóvel", "Sou o/a que conta as anedotas todas"] },
    { id: "c_tc_v_09", texto: "Quando há bolo de anos no escritório:", opcoes: ["Sou o primeiro da fila para a fatia maior", "Canto os parabéns mas odeio bolo seco de pastelaria", "Faço dieta mas acabo a roubar um bocado", "Sou eu que trago o bolo para ser o/a favorito/a"] },
    { id: "c_tc_v_10", texto: "A minha relação com o/a chefe é:", opcoes: ["Aquele clássico graxista (lambe-botas)", "Cordial, mas fujo dele/a sempre que posso", "Damo-nos super bem, quase melhores amigos", "Vivemos em constante guerra fria e trocas de e-mails"] },
    { id: "c_tc_v_11", texto: "Como reajo quando a impressora encrava e fui eu a imprimir?", opcoes: ["Abro a máquina e tento resolver como um engenheiro", "Viro as costas e finjo que não foi comigo", "Chamo logo o pessoal do IT a gritar por socorro", "Bato na impressora com força"] },
    { id: "c_tc_v_12", texto: "No chat da empresa (Teams/Slack), eu costumo:", opcoes: ["Mandar GIFs para toda a gente", "Responder apenas com 'OK' e polegar para cima", "Falar no chat da equipa errada e passar vergonha", "Estar sempre com o estado 'Ausente' amarelo"] },
    { id: "c_tc_v_13", texto: "Quando pedem voluntários para fazer horas extra:", opcoes: ["Levanto a mão, preciso mesmo de dinheiro", "Escondo-me debaixo da secretária", "Invento que tenho o cão doente ou a avó a chegar", "Digo que faço amanhã (e amanhã não faço)"] },
    { id: "c_tc_v_14", texto: "No que toca a jantares de Natal da empresa:", opcoes: ["Sou a estrela da pista e apanho uma bebedeira épica", "Vou só pelo jantar de borla e saio às 22h", "Fico no canto a julgar os que dançam mal", "Sou o que faz amizade com o chefe nessa noite"] },
    { id: "c_tc_v_15", texto: "A minha password do computador do trabalho:", opcoes: ["Password123 ou a data de nascimento", "Uma sequência impenetrável que está num post-it", "Esqueço-me dela todos os meses", "Deixo o PC sempre desbloqueado, perigo iminente"] },
    { id: "c_tc_v_16", texto: "Como lido com colegas muito faladores que não me deixam trabalhar?", opcoes: ["Ponho fones (sem música) para os ignorar", "Mando calar, não tenho rodeios", "Fico a ouvir e não faço o trabalho do dia", "Respondo 'pois' a cada 5 segundos até se calarem"] },
    { id: "c_tc_v_17", texto: "Ao final do dia, quando dá a hora de saída:", opcoes: ["Arranco no milissegundo exato que dá a hora", "Fico sempre 20 minutos a mais para parecer bem", "Acabo por ficar horas a mais porque me perdi a trabalhar", "Despeço-me de toda a gente e demoro meia hora a sair"] },
    { id: "c_tc_v_18", texto: "Quando cometo um erro estúpido no trabalho:", opcoes: ["Assumo o erro e peço desculpa como um adulto", "Atiro as culpas para o estagiário invisível", "Tento resolver sozinho/a antes que alguém note", "Começo a suar e pergunto no Google como arranjar"] },
    { id: "c_tc_v_19", texto: "A minha postura nas videochamadas (Zoom):", opcoes: ["Câmara ligada, super arranjado/a da cintura para cima", "Câmara sempre desligada e de pijama na cama", "O que esquece o micro ligado enquanto mastiga bolachas", "Aquele que a internet cai sempre na sua vez de falar"] },
    { id: "c_tc_v_20", texto: "Sobre fofocas (cusquices) do escritório:", opcoes: ["Sou a agência noticiosa Lusa, sei e espalho tudo", "Ouço mas guardo para mim", "Não ligo a isso, foco-me no trabalho", "Quando chego a saber da fofoca já aconteceu há 3 meses"] }
  ],
  "sub_5_1": [ // Ambições Profissionais
    { id: "c_tc_a_01", texto: "Se eu pudesse escolher a minha carreira de sonho sem pensar em dinheiro, seria:", opcoes: ["Viajante/Avaliador de Hotéis de Luxo", "Salvar animais em vias de extinção", "Estrela rock ou ator famoso", "Qualquer coisa onde pudesse trabalhar deitado na cama"] },
    { id: "c_tc_a_02", texto: "Em relação a subir na carreira e ser líder/chefe:", opcoes: ["É o meu objetivo principal, quero mandar!", "Prefiro ser apenas colaborador e ter paz de espírito", "Tenho muito potencial mas zero paciência para aturar pessoas", "Acho que seria um chefe terrível e tirano"] },
    { id: "c_tc_a_03", texto: "O meu principal fator de motivação no trabalho é:", opcoes: ["O salário ao fim do mês a bater na conta", "O reconhecimento e palmadinhas nas costas", "Sentir que estou a fazer a diferença no mundo", "A máquina do café estar grátis"] },
    { id: "c_tc_a_04", texto: "Como lido com a ideia de criar o meu próprio negócio?", opcoes: ["Amo a ideia, ser patrão de mim mesmo!", "Gosto da ideia mas tenho pânico dos impostos e IVA", "Jamais, quero as minhas 8 horas certas e tchau", "Já tentei abrir um canal no YouTube ou fazer bolos mas falhei"] },
    { id: "c_tc_a_05", texto: "Sobre o equilíbrio entre trabalho e vida pessoal:", opcoes: ["Trabalho para viver, saio a horas certas sem stress", "Vivo para trabalhar, sou um autêntico 'workaholic'", "Qual equilíbrio? É só caos e desespero de ambos os lados", "Nem tenho vida pessoal, por isso é fácil"] },
    { id: "c_tc_a_06", texto: "Como lido com avaliações de desempenho (feedback)?", opcoes: ["Fico super nervoso/a uma semana antes", "Aceito bem e uso para melhorar", "Fico super ofendido/a e faço bico", "Discordo e argumento de volta com o chefe"] },
    { id: "c_tc_a_07", texto: "Quando penso onde estarei profissionalmente daqui a 10 anos:", opcoes: ["A liderar a minha própria empresa milionária", "Exatamente na mesma secretária, a fazer o mesmo", "Reformado nas Bahamas (a sonhar alto)", "Não sei sequer onde estarei na próxima semana"] },
    { id: "c_tc_a_08", texto: "A perspetiva de mudar de área profissional completamente:", opcoes: ["Fá-lo-ia já amanhã se não desse tanto trabalho", "Jamais, estudei anos para isto e agarro-me ao barco", "Estou sempre a mudar, sou muito inconstante", "Dá-me ataques de ansiedade só de pensar em recomeçar"] },
    { id: "c_tc_a_09", texto: "Sobre continuar a estudar ou tirar formações:", opcoes: ["Estou sempre a inscrever-me em cursos online", "Não volto a tocar num livro, já estudei que chegue", "Inscrevo-me, assisto a uma aula e desisto", "Só faço se a empresa obrigar e pagar o almoço"] },
    { id: "c_tc_a_10", texto: "Qual seria a minha atitude perante uma promoção que me obriga a viajar muito?", opcoes: ["Aceitava logo, adoro conhecer o mundo à pala da empresa!", "Recusava, gosto demasiado da minha rotina e do meu sofá", "Teria crises de ansiedade nos aeroportos", "Aceitava mas queixava-me de estar cansado todos os dias"] },
    { id: "c_tc_a_11", texto: "Como lido com a pressão e os prazos curtos (deadlines)?", opcoes: ["Trabalho incrivelmente bem sob pressão de última hora", "Entro em pânico e desata tudo a chorar", "Faço tudo muito antes do prazo para dormir tranquilo/a", "Qual prazo? Só entrego quando estiver feito."] },
    { id: "c_tc_a_12", texto: "A minha relação com os dias de folga e férias:", opcoes: ["Desligo o telemóvel e o mundo pode arder", "Vou espreitando o email 'só para garantir'", "Acabo por ter de resolver coisas do trabalho remotamente", "Fico com ansiedade porque acho que me vão despedir na ausência"] },
    { id: "c_tc_a_13", texto: "O que acho da cultura de 'vestir a camisola da empresa'?", opcoes: ["Sou o funcionário do mês, visto 10 camisolas", "Visto consoante o que me pagarem no recibo de vencimento", "Acho super tóxico, trabalho lá e pronto", "Digo que sim mas visto camisolas de outra cor por baixo"] },
    { id: "c_tc_a_14", texto: "Como reajo a uma crítica dura do meu chefe?", opcoes: ["Agradeço e reflito de forma madura", "Vou chorar para a casa de banho", "Procuro imediatamente outro emprego no LinkedIn", "Discordo mentalmente mas aceno a cabeça e sorrio"] },
    { id: "c_tc_a_15", texto: "No futuro, o que prefiro:", opcoes: ["Ter muito dinheiro e zero tempo livre", "Ter tempo livre e dinheiro contado à justa", "Ganhar o Euromilhões e não ter de escolher", "Trabalhar em part-time e viver na aldeia a plantar tomates"] },
    { id: "c_tc_a_16", texto: "Qual a minha opinião sobre trabalhar fora do meu país (emigrar)?", opcoes: ["O meu grande sonho, quero uma vida cosmopolita!", "Já lá estive / Estou lá, faz-se pelo dinheiro", "Jamais, não vivo sem a comidinha da mãe e o bom tempo", "Acho a ideia romântica mas sou cobarde demais para o fazer"] },
    { id: "c_tc_a_17", texto: "A minha perspetiva sobre a reforma (aposentação):", opcoes: ["Espero reformar-me aos 50 e ir para o Algarve", "Com as leis que aí andam, vou trabalhar até aos 85", "Não penso nisso, gasto o dinheiro todo agora", "Já estou a meter 10€ de lado todos os meses no Mealheiro"] },
    { id: "c_tc_a_18", texto: "Se eu ganhasse a lotaria amanhã, o que faria em relação ao trabalho?", opcoes: ["Entregava a carta de demissão na hora a fazer o 'gesto bonito'", "Continuava a trabalhar para me manter ocupado/a", "Comprava a empresa e despedia o chefe", "Ia de 'baixa psiquiátrica' eterna"] },
    { id: "c_tc_a_19", texto: "A minha atitude nas entrevistas de emprego:", opcoes: ["Sou hiper carismático, vendo gelo a esquimós", "Fico a gaguejar, a suar das mãos e digo coisas sem sentido", "Minto no Currículo e na entrevista rezo para que resulte", "Estudo a empresa toda na noite anterior e pareço um stalker"] },
    { id: "c_tc_a_20", texto: "A minha maior força no ambiente de trabalho é:", opcoes: ["A minha criatividade fora da caixa", "O meu foco e velocidade a despachar tarefas absurdas", "A minha capacidade de desenrascar coisas no último segundo", "Fazer um café divinal e ser o psicólogo dos meus colegas"] }
  ]
};
