import { PerguntaClassica } from "@/types/catalogo";

export const classico_viagens_ferias: Record<string, PerguntaClassica[]> = {
  "sub_4_0": [ // Destinos de Sonho
    { id: "c_vf_d_01", texto: "O meu tipo de férias ideal é:", opcoes: ["Fritar ao sol na praia tipo lagarto", "Caminhar pela montanha ou ir à neve", "Explorar cidades históricas até me doerem os pés", "Ficar na piscina do resort com tudo incluído"] },
    { id: "c_vf_d_02", texto: "Numa viagem à neve, eu sou a pessoa que:", opcoes: ["Faz snowboard ou ski como um profissional", "Passa o tempo a cair e de rabo na neve", "Fica no bar do hotel a beber chocolate quente", "Faz um boneco de neve e atira bolas a toda a gente"] },
    { id: "c_vf_d_03", texto: "Se ganhasse o Euromilhões, a minha primeira viagem seria para:", opcoes: ["Maldivas ou Bora Bora, no puro luxo", "Japão ou um destino mega exótico", "Nova Iorque, para as compras", "Alugava uma autocaravana e ia sem destino"] },
    { id: "c_vf_d_04", texto: "Qual é a minha capital europeia de eleição?", opcoes: ["Paris (eu sei que não é na Europa, reprovei a Geografia)", "Roma, adoro o romantismo", "Amesterdão, pelas 'coffee shops' e bicicletas", "Londres (eu sei que já não é UE, mas não interessa)"] },
    { id: "c_vf_d_05", texto: "Em relação a destinos exóticos (Ásia, África):", opcoes: ["Amo, adoro o choque cultural", "Tenho pânico de doenças e insetos gigantes", "Só ia se fosse para um resort de 5 estrelas", "Gosto da ideia mas a comida de rua dá-me medo"] },
    { id: "c_vf_d_06", texto: "Acampar numa tenda:", opcoes: ["É a melhor coisa do mundo, adoro ser selvagem", "Só se for 'Glamping', com cama e ar condicionado", "Odeio, as costas doem e há bichos", "Vou por causa dos amigos, mas sofro por dentro"] },
    { id: "c_vf_d_07", texto: "Férias de mochila às costas (Backpacking):", opcoes: ["Super aventureiro, o meu sonho", "Prefiro a minha mala de rodinhas, obrigado", "Dormir em hostels partilhados? Nem morta/o.", "Gosto de ver nos outros, eu gosto é de conforto"] },
    { id: "c_vf_d_08", texto: "Em relação a cruzeiros:", opcoes: ["Adorava, comida grátis 24h e não faço nada", "Acho coisa de velhos ricos", "Teria enjoos todos os dias", "Dá-me claustrofobia estar preso num barco gigante"] },
    { id: "c_vf_d_09", texto: "Numa escapadinha de fim de semana prefiro:", opcoes: ["Irrugir para o meio do Gerês ou Douro", "Fazer uma maratona de Netflix na minha própria casa", "Um city-break em Madrid ou Barcelona", "Ir para o Algarve mesmo no Inverno"] },
    { id: "c_vf_d_10", texto: "A minha relação com viagens longas de avião:", opcoes: ["Adormeço antes sequer do avião descolar", "Tenho de ver 3 filmes e andar a passear no corredor", "Tomo um calmante para aguentar o pânico", "Passo o voo todo a olhar para o mapa no ecrã a ver quanto falta"] },
    { id: "c_vf_d_11", texto: "Se pudesse visitar apenas um continente para o resto da vida, seria:", opcoes: ["Europa, tem cultura e fica perto", "Ásia, comida espetacular e barato", "Américas, desde as praias no Brasil à selva de Nova Iorque", "África, pela natureza e safaris"] },
    { id: "c_vf_d_12", texto: "Num destino de praia paradisíaco, o que faço o dia todo?", opcoes: ["Leio um livro e bebo cocktails à sombra", "Estou sempre dentro de água feito criança", "Fico vermelho/a tipo lagosta no primeiro dia", "Aborreço-me ao fim de 2 horas e quero ir ver coisas"] },
    { id: "c_vf_d_13", texto: "Viagens com tudo incluído (pulseirinha):", opcoes: ["É o Paraíso. Acordo e vou para o bar.", "É fixe dois dias, depois começa a chatear ficar preso no hotel", "Tento dar prejuízo ao hotel comendo até rebentar", "Odeio, acho super básico e nada cultural"] },
    { id: "c_vf_d_14", texto: "Se viajasse no tempo para umas férias históricas, ia para:", opcoes: ["O Egipto antigo", "A época Medieval para andar de espada", "Os anos 80, para a discoteca", "Fico em 2024, que há internet e antibióticos"] },
    { id: "c_vf_d_15", texto: "Qual a minha opinião sobre destinos turísticos lotados de gente (ex: Veneza, Torre Eiffel)?", opcoes: ["Tiro as fotos na mesma, faz parte", "Irritam-me profundamente e empurro os turistas", "Prefiro ir na época baixa no Inverno", "Adoro ir para os sítios menos conhecidos ('hidden gems')"] },
    { id: "c_vf_d_16", texto: "Num Safari em África, eu seria a pessoa que:", opcoes: ["Passa o tempo todo com binóculos hiper focado/a", "Tem pânico que um leão ataque o jipe", "Tira 5000 fotos mas todas desfocadas", "Fica chateado/a porque está calor e não há wi-fi"] },
    { id: "c_vf_d_17", texto: "Viagens pelo próprio país (Portugal):", opcoes: ["Conheço o país quase de norte a sul", "Conheço melhor lá fora do que Portugal", "Vou sempre para os mesmos 2 sítios (Algarve ou neve)", "Faço roadtrips espontâneas pelas terrinhas"] },
    { id: "c_vf_d_18", texto: "Quando penso nos EUA, o que quero ver primeiro?", opcoes: ["Nova Iorque e arranha-céus", "As estradas gigantes da Rota 66 de descapotável", "Disneylândia e Parques de diversões", "Os fast-foods para comer hambúrgueres épicos"] },
    { id: "c_vf_d_19", texto: "Um destino romântico para mim seria:", opcoes: ["Paris ou Veneza, bem azeiteiro mas clássico", "Uma cabana isolada na montanha com lareira", "Maldivas num bungalow sobre a água", "Ficar no sofá de casa com pão de alho e Netflix"] },
    { id: "c_vf_d_20", texto: "Viagens gastronómicas (ir a um país só pela comida):", opcoes: ["Sim! Itália, lá vou eu comer 5kg de massa", "Gosto mas tem de haver cultura pelo meio", "Teria dores de barriga constantes", "Só vou se houver restaurantes de bife e batatas fritas"] }
  ],
  "sub_4_1": [ // Peripécias de Viagem
    { id: "c_vf_p_01", texto: "Quando estou a fazer a mala para ir de férias:", opcoes: ["Faço-a uma semana antes com lista militar", "Atiro 15 camisas para lá 3 horas antes do voo", "Levo roupa a mais para 5 anos de viagem", "Esqueço-me sempre das cuecas ou da escova de dentes"] },
    { id: "c_vf_p_02", texto: "Qual o meu nível de stress antes de um voo?", opcoes: ["Zero, vou a dormir para o aeroporto", "Chego 4 horas antes com medo de perder o avião", "Confiro o passaporte a cada 30 segundos", "Corro pelo aeroporto porque vou sempre atrasado/a"] },
    { id: "c_vf_p_03", texto: "Quando chego ao aeroporto:", opcoes: ["Vou direto ao Duty Free gastar dinheiro", "Sento-me logo na porta de embarque no chão", "Bebo uma mini ou café bué caro para celebrar", "Fico ansioso com o peso da mala de cabine"] },
    { id: "c_vf_p_04", texto: "Como lido com o roteiro da viagem?", opcoes: ["Tenho um Excel com tudo planeado minuto a minuto", "Decido o que fazer no próprio dia quando acordo", "Sigo o que os meus amigos disserem", "Vou só ao que vi no TikTok e no Instagram"] },
    { id: "c_vf_p_05", texto: "Se me perder numa cidade desconhecida:", opcoes: ["Olho para o Google Maps em pânico", "Pergunto aos locais (mesmo que com gestos)", "Acho incrível, 'faz parte da aventura!'", "Começo a culpar os meus amigos por andarmos perdidos"] },
    { id: "c_vf_p_06", texto: "Com a comida local (estranha e picante), eu:", opcoes: ["Provo tudo, até insetos se for preciso", "Fico-me pelo McDonald's para não arriscar", "Como, mas passo os dias seguintes agarrado/a à sanita", "Tiro foto, digo que é horrível e como pão"] },
    { id: "c_vf_p_07", texto: "Para tirar fotos nas férias, eu sou:", opcoes: ["O/A fotógrafo/a de serviço que saca grandes poses aos outros", "Tiro uma foto a uma parede e está feito", "Obrigo os outros a tirar-me 50 fotos e reclamo que estou feio/a", "Só tiro selfies porque não confio em ninguém"] },
    { id: "c_vf_p_08", texto: "Na hora de comprar lembranças / souvenirs:", opcoes: ["Compro ímanes de frigorífico para a família toda", "Não compro nada, é tudo lixo para ganhar pó", "Compro artesanato inútil que depois não cabe na mala", "Esqueço-me e compro no Duty Free à última da hora"] },
    { id: "c_vf_p_09", texto: "Com o orçamento da viagem:", opcoes: ["Controlo cada cêntimo que gasto", "Estouro o dinheiro todo nos primeiros 3 dias", "Vou à maluca e pago as dívidas quando voltar", "Faço os meus amigos pagarem e depois dou MBWay (ou não)"] },
    { id: "c_vf_p_10", texto: "Sobre alugar carro no estrangeiro:", opcoes: ["Conduzo em qualquer país como o Vin Diesel", "Tenho pânico de riscar o carro e pagar balúrdios", "Fico a gritar com o GPS porque não percebo as rotundas", "Recuso-me a conduzir, só ando de Uber/Metro"] },
    { id: "c_vf_p_11", texto: "Quando não entendo a língua local:", opcoes: ["Meto o Google Tradutor e mostro o ecrã", "Falo português cada vez mais alto a achar que eles percebem", "Faço mimica e gestos tipo Mímica", "Sorrio, digo 'Yes' e fujo"] },
    { id: "c_vf_p_12", texto: "A usar o mapa ou GPS no telemóvel:", opcoes: ["Sou o navegador perfeito", "Mando a malta para a esquerda quando o mapa dizia direita", "Ando 3 kms na direção errada e não digo nada para não passar vergonha", "Gasto a bateria toda nos primeiros 10 minutos de viagem"] },
    { id: "c_vf_p_13", texto: "Em relação à cultura de regatear os preços em mercados:", opcoes: ["Adoro, negoceio até comprar por 1 cêntimo", "Tenho muita vergonha, pago o primeiro valor absurdo que dizem", "Tento regatear mas os vendedores passam-me sempre a perna", "Acho mal, pago e calo-me"] },
    { id: "c_vf_p_14", texto: "O que faço sempre que chego a um quarto de hotel novo?", opcoes: ["Verifico a limpeza e a pressão da água do chuveiro", "Atiro a mala para o chão e atiro-me para a cama", "Roubo logo as miniaturas do champô e do gel de banho", "Procuro o botão do Wi-fi para ligar ao telemóvel"] },
    { id: "c_vf_p_15", texto: "A arrumar a mala no fim das férias:", opcoes: ["Dobro a roupa limpa da roupa suja perfeitamente", "Sento-me em cima da mala para conseguir fechar o fecho", "Tento enfiar 5kg a mais e rezo para não pesar no aeroporto", "Deixo coisas para trás porque já não cabe lá nada"] },
    { id: "c_vf_p_16", texto: "Ao acordar durante as férias:", opcoes: ["Levanto-me às 7h para 'aproveitar o dia'", "Acordo às 11h todo roto da caminhada de ontem", "Obrigo os meus amigos a levantarem-se e sou insuportável", "Perco o pequeno-almoço do hotel por preguiça"] },
    { id: "c_vf_p_17", texto: "Qual a probabilidade de eu perder o passaporte/carteira?", opcoes: ["Altíssima, ando sempre a apalpar os bolsos em pânico", "Zero, uso aquela bolsinha de cinto hiper segura (e azeiteira)", "Guardo tão bem guardado que depois não encontro", "Os meus amigos é que guardam as minhas coisas"] },
    { id: "c_vf_p_18", texto: "Se chover todos os dias durante as férias:", opcoes: ["Fico super deprimido e amuado", "Compro um impermeável e ando à chuva, é a vida!", "Fico no hotel a beber e a jogar cartas", "Vou para os museus todos até ficar farto de arte"] },
    { id: "c_vf_p_19", texto: "Ao visitar museus e monumentos:", opcoes: ["Leio todas as placas informativas até ao fim", "Passo por tudo a correr em 5 minutos para ir beber café", "Tiro uma foto na entrada para provar que estive lá e saio", "Sento-me nos bancos a descansar os pés"] },
    { id: "c_vf_p_20", texto: "A voltar para casa e para a rotina:", opcoes: ["Começo a chorar no avião a pensar no trabalho", "Chego e vou logo planear a próxima viagem", "Sinto um alívio gigante de voltar para a minha sanita", "Preciso de 3 dias de férias para recuperar das férias"] }
  ]
};
