import { PerguntaClassica } from "@/types/catalogo";

export const classico_vida_pessoal: Record<string, PerguntaClassica[]> = {
  "sub_0_0": [ // Rotinas Diárias
    { id: "c_vp_r_01", texto: "Quantos alarmes meto de manhã para conseguir acordar?", opcoes: ["Só um e acordo logo", "Dois, por segurança", "Uns cinco, a cada 5 minutos", "Não uso, acordo naturalmente"] },
    { id: "c_vp_r_02", texto: "Qual é o meu estilo no banho?", opcoes: ["5 min à militar", "15 min a cantar", "30 min a dar um concerto ao vivo", "Fico até a água ficar fria"] },
    { id: "c_vp_r_03", texto: "O que é sagrado no meu pequeno-almoço?", opcoes: ["Uma torrada e um galão", "Flocos ou panquecas fit", "Só um café a correr", "Não como nada de manhã"] },
    { id: "c_vp_r_04", texto: "Ao combinar saídas, como é a minha pontualidade?", opcoes: ["Sempre atrasado/a", "Chego 5 min antes", "Exatamente à hora marcada", "Chego a horas mas esqueço-me sempre de algo"] },
    { id: "c_vp_r_05", texto: "Qual é a primeira coisa que faço no telemóvel ao acordar?", opcoes: ["Abrir o Instagram/TikTok", "Ver mensagens no WhatsApp", "Ver os emails", "Desligar o alarme e chorar um bocado"] },
    { id: "c_vp_r_06", texto: "Como escolho a roupa de manhã?", opcoes: ["Deixo tudo escolhido na véspera", "A primeira coisa que me aparece à frente", "Demoro uma hora a decidir", "Tenho um 'uniforme' e ando sempre igual"] },
    { id: "c_vp_r_07", texto: "O que faço quando vou nos transportes/no trânsito?", opcoes: ["Oiço podcasts", "Música aos altos berros", "Vou a dormir a viagem toda", "Vou a reclamar mentalmente com toda a gente"] },
    { id: "c_vp_r_08", texto: "A primeira coisa que faço quando chego a casa do trabalho/aulas é:", opcoes: ["Vestir o pijama ou roupa de andar por casa imediatamente", "Deitar-me no sofá a olhar para o vazio", "Assaltar o frigorífico", "Ir treinar"] },
    { id: "c_vp_r_09", texto: "Qual é a minha rotina de lavar os dentes?", opcoes: ["No mínimo 3x ao dia", "Só de manhã e antes de ir dormir", "Quando me lembro", "Lavo no banho para poupar tempo"] },
    { id: "c_vp_r_10", texto: "O que costumo fazer imediatamente antes de adormecer?", opcoes: ["Scroll infinito no TikTok/Instagram", "Ler um livro", "Fazer listas para o dia seguinte", "Fecho os olhos e apago em 3 segundos"] },
    { id: "c_vp_r_11", texto: "Como é o meu fim de semana ideal?", opcoes: ["Sofá, manta e Netflix", "Sair para beber copos até de madrugada", "Ir dar um passeio na natureza", "Limpar a casa e fazer as lides todas"] },
    { id: "c_vp_r_12", texto: "Como é que me organizo durante a semana?", opcoes: ["Tenho uma agenda super detalhada", "Post-its e notas espalhadas por todo o lado", "Fica tudo na cabeça (e esqueço-me de metade)", "Que organização?"] },
    { id: "c_vp_r_13", texto: "Qual é a minha regra em relação a fazer a cama?", opcoes: ["Faço todos os dias impecavelmente", "Puxo só o edredão para disfarçar", "Fica exatamente como acordei", "Só faço a cama quando vem cá alguém a casa"] },
    { id: "c_vp_r_14", texto: "Lavar a loiça: qual é o meu método?", opcoes: ["Lavo logo mal acabo de comer", "Acumulo até não haver mais pratos limpos", "Metade na máquina, metade na bancada", "Fica a 'demolhar' durante 3 dias"] },
    { id: "c_vp_r_15", texto: "Como faço compras no supermercado?", opcoes: ["Levo uma lista e cumpro à risca", "Vou com fome e trago tudo o que me apetece", "Vou só comprar pão e trago 50€ em doces", "Mando vir online porque detesto ir lá"] },
    { id: "c_vp_r_16", texto: "Na pausa de almoço do trabalho/escola eu normalmente:", opcoes: ["Levo a minha marmita saudável preparada em casa", "Levo os restos do jantar de ontem", "Vou sempre comer fora com o pessoal", "Como uma sandes da máquina de venda automática"] },
    { id: "c_vp_r_17", texto: "O meu relatório semanal de Tempo de Ecrã no telemóvel deve ser de:", opcoes: ["Menos de 2 horas diárias", "Umas 4 a 5 horas", "Mais de 8 horas (socorro)", "Recuso-me a ver, vivo em negação"] },
    { id: "c_vp_r_18", texto: "O meu consumo de água durante o dia:", opcoes: ["Ando sempre com a minha garrafa de 2 litros atrás", "Só bebo à hora das refeições", "Esqueço-me de beber água o dia inteiro", "Substituo os dois litros de água por dois litros de café"] },
    { id: "c_vp_r_19", texto: "O estado normal do meu quarto é:", opcoes: ["Minimalista e arrumadinho", "Tenho a clássica 'Cadeira da Roupa' cheia", "Caos organizado, eu sei onde está tudo", "Zona de guerra total"] },
    { id: "c_vp_r_20", texto: "O que costumo fazer aos Domingos à tarde?", opcoes: ["Meal prep e organizar a roupa da semana", "Sofrer de depressão pré-segunda-feira", "Ir a um lanche ajantarado incrível", "Dormir a sesta até não saber em que ano estou"] }
  ],
  "sub_0_1": [ // Hábitos e Manias
    { id: "c_vp_h_01", texto: "Uma mania muito minha a comer:", opcoes: ["Separar os diferentes tipos de comida no prato", "Comer à velocidade da luz como se me fossem roubar", "Cheirar a comida antes de provar", "Deixar sempre a melhor parte para a última dentada"] },
    { id: "c_vp_h_02", texto: "Quando estou muito nervoso/a ou ansioso/a, o que faço?", opcoes: ["Roo as unhas até ao sabugo", "Abano a perna compulsivamente", "Falo muito e muito rápido", "Começo a comer doces"] },
    { id: "c_vp_h_03", texto: "Para conseguir adormecer preciso sempre de:", opcoes: ["Dormir com um pé de fora dos lençóis", "Estar completamente tapado (até a cabeça)", "Estar abraçado/a a uma almofada extra", "Só consigo dormir de barriga para baixo"] },
    { id: "c_vp_h_04", texto: "Qual é o meu maior tique enquanto estou a falar?", opcoes: ["Usar a palavra 'tipo' em todas as frases", "Mexer muito as mãos", "Tocar no cabelo ou na cara constantemente", "Começar a falar cada vez mais alto sem reparar"] },
    { id: "c_vp_h_05", texto: "A minha pior mania quando vejo um filme em casa acompanhado/a:", opcoes: ["Comento e pergunto tudo o que está a acontecer", "Pego no telemóvel a meio e perco a atenção", "Adormeço passados 20 minutos", "Faço imenso barulho a mastigar pipocas/batatas"] },
    { id: "c_vp_h_06", texto: "A responder a mensagens no WhatsApp eu sou:", opcoes: ["A pessoa que responde no próprio segundo", "Aquela que vê, não responde, e passados 3 dias diz 'ah desculpa não vi'", "A que só manda áudios de 5 minutos como se fossem podcasts", "A pessoa que responde apenas com um emoji ou 'ahahaha'"] },
    { id: "c_vp_h_07", texto: "Como me comporto a andar no supermercado?", opcoes: ["Tenho de andar por todos os corredores, mesmo os que não preciso", "Vou a correr direto ao que quero como num contrarrelógio", "Paro para ler os rótulos e as calorias de tudo", "Sou atraído pelas promoções e levo sempre algo inútil"] },
    { id: "c_vp_h_08", texto: "Qual é a minha mania com o volume da televisão ou do rádio do carro?", opcoes: ["Tem que estar num número par", "Tem que terminar em 0 ou 5 (ex: 15, 20)", "Tem que estar o mais alto possível, senão não oiço", "Sou caótico, ponho no 17 ou no 23 e vivo bem com isso"] },
    { id: "c_vp_h_09", texto: "Como organizo as aplicações no meu telemóvel?", opcoes: ["Esteticamente, ordenadas por cores", "Por pastas super organizadas (Trabalho, Lazer, etc.)", "Ordem alfabética para não me perder", "Um caos espalhado por 10 páginas em que nunca encontro nada"] },
    { id: "c_vp_h_10", texto: "Qual é o meu pior traço em relação à pontualidade?", opcoes: ["Chegar 15 min mais cedo e ficar às secas à espera", "Ficar no carro a fazer tempo para não ser o primeiro a chegar", "Dizer 'estou a chegar em 5 min' mas ainda nem saí de casa", "Ficar ofendido se for eu o último a chegar e já estiverem a comer"] },
    { id: "c_vp_h_11", texto: "Qual é a minha reação automática quando me apanham e dão um susto?", opcoes: ["Gritar um palavrão imediatamente", "Dar um salto gigante seguido de um grito fininho", "A minha alma abandona o corpo, mas por fora fico paralisado", "Gasto os 5 minutos seguintes a tentar dar um estalo à pessoa"] },
    { id: "c_vp_h_12", texto: "Qual destas é a minha maior 'pequena' mania de higiene?", opcoes: ["Não consigo usar as casas de banho públicas, prefiro rebentar", "Lavo as mãos 20 vezes por dia", "Passo álcool-gel no telemóvel quase todos os dias", "Uso 5 toalhas diferentes a seguir ao banho"] },
    { id: "c_vp_h_13", texto: "A tomar comprimidos ou medicamentos eu sou:", opcoes: ["O clássico: deito um litro de água na boca e engulo de olhos fechados", "O super-herói: engulo a seco sem água nenhuma", "O difícil: tenho de partir em bocados senão engasgo-me", "A criança: faço uma fita terrível para não tomar"] },
    { id: "c_vp_h_14", texto: "O meu maior vício quando tomo banho:", opcoes: ["Tomar com a água a escaldar ao ponto de derreter a pele", "Acabar sempre com um jato de água gelada", "Aproveito para tomar as melhores decisões da minha vida lá dentro", "Ensaboar o corpo de cima a baixo na mesma ordem, sempre"] },
    { id: "c_vp_h_15", texto: "Quando alguém me conta uma 'fofoca' ou segredo:", opcoes: ["Guardo religiosamente e levo o segredo para o túmulo", "Conto apenas e exclusivamente ao meu/minha melhor amigo/a", "Conto a toda a gente mas com a condição de 'não contes a ninguém'", "Esqueço-me do que me contaram no próprio dia à tarde"] },
    { id: "c_vp_h_16", texto: "Em dias de muito frio em casa, qual é a minha mania?", opcoes: ["Vestir 3 camadas de roupa, casaco e duas meias calçadas", "Ligar o aquecedor no máximo e andar de t-shirt em casa", "Fazer um chá e não sair de debaixo da manta no sofá", "Ignorar e dizer sempre 'isto não é frio nenhum, no Alentejo é pior'"] },
    { id: "c_vp_h_17", texto: "A minha relação com ouvir música:", opcoes: ["Oiço a mesma música repetida em loop até a odiar", "Tenho que ouvir os álbuns seguidos do início ao fim", "Tenho uma playlist hiper específica para cada estado de espírito", "Ligo a rádio ou oiço a playlist top 50, não ligo muito a descobrir bandas novas"] },
    { id: "c_vp_h_18", texto: "Quando me cruzo na rua com alguém de quem me esqueci o nome:", opcoes: ["Finjo demência e chamo a pessoa de 'amigo/a', 'chefe' ou 'mestre'", "Pergunto diretamente o nome sem problemas", "Espero que essa pessoa pergunte o meu e tento adivinhar pelo contexto", "Finjo que recebi uma chamada para não ter de falar"] },
    { id: "c_vp_h_19", texto: "O meu sistema de senhas (passwords) é:", opcoes: ["Uso literalmente a mesma password para absolutamente tudo", "Tenho 20 senhas complexas e apontadas num bloco de notas na gaveta", "Tenho um gestor de palavras-passe no telemóvel hiper seguro", "Não faço ideia, faço sempre 'Esqueci-me da palavra-passe' em todas as compras"] },
    { id: "c_vp_h_20", texto: "Quando entro num pequeno debate ou discussão inútil com amigos:", opcoes: ["Tenho sempre de ter a última palavra, nem que não tenha razão", "Faço muitas vezes de 'advogado do diabo' só para picar o pessoal", "Desisto logo a meio e dou-lhes razão porque não me apetece discutir", "Levanto a voz muito rápido e irrito-me logo a sério"] }
  ]
};